-- legal_search_mock labor_dispute_2026 — init.sql
-- A synthesized labordispute (labor dispute) research corpus for a English text benchmark:
--   • 6 courts/arbitrationEnglish text across Shanghai/Beijing
--   • 2 statutes: Labor Contract Law + Labor Law, with their key articles (English text simplified, public-domain style)
--   • 18 anonymized labor-dispute judgments (unlawful termination/overtime pay/double wage for no written contract/economic compensation/English text/non-compete ...)
--   • citation links from cases → statute articles (and a few case→case references)
--   • seeded user usr_li_wei with 2 saved cases + notes (preparing a laborarbitration/litigation)
-- All party names anonymized (English text/English text). All text original/synthesized.
-- Reference date: 2026-05-20 (task-level only; the server has no clock).

BEGIN;

-- ── Courts / arbitrationEnglish text ─────────────────────────────────────────────
INSERT INTO courts (court_id, name, level, region) VALUES
  ('court_sh_pudong',   'ShanghaiEnglish textPeople''s Court',       'English textcourt',   'ShanghaiEnglish text'),
  ('court_sh_minhang',  'ShanghaiEnglish textPeople''s Court',         'English textcourt',   'ShanghaiEnglish text'),
  ('court_sh_no1',      'ShanghaiEnglish textPeople''s Court',       'English textcourt',   'ShanghaiEnglish text'),
  ('court_sh_high',     'ShanghaiEnglish textPeople''s Court',           'English textcourt',   'ShanghaiEnglish text'),
  ('court_bj_chaoyang', 'BeijingEnglish textPeople''s Court',         'English textcourt',   'BeijingEnglish text'),
  ('arb_sh_pudong',     'ShanghaiEnglish textlaborEnglish textdisputearbitrationEnglish text', 'arbitrationEnglish text', 'ShanghaiEnglish text');

-- ── Statutes ───────────────────────────────────────────────────────
INSERT INTO statutes (statute_id, name, short_name, issuer, effective_date, status, summary) VALUES
  ('stat_lcl',  'English textLabor Contract Law', 'Labor Contract Law', 'English text', '2008-01-01', 'in force',
    'English textlaborEnglish text、English text、English text、English text，English textlaborEnglish text，English textlaborEnglish textsalary、unlawful terminationEnglish text、English textcompensationEnglish text。'),
  ('stat_ll',   'English textLabor Law', 'Labor Law', 'English text', '1995-01-01', 'in force',
    'adjustmentlaborEnglish textbaselegal，English text、English text、salary、English textlabordisputeEnglish textbaseEnglish text。');

-- ── Statute articles (English text) ─────────────────────────────────────────
-- Labor Contract Law key articles
INSERT INTO statute_articles (article_id, statute_id, article_no, seq, heading, text) VALUES
  ('art_lcl_010', 'stat_lcl', 'English text',     10, 'English textlaborEnglish text',
    'English textlaborEnglish text，English textlaborEnglish text。English textlaborEnglish text，English textlaborEnglish text，English textlaborEnglish text。'),
  ('art_lcl_036', 'stat_lcl', 'English text', 36, 'English text',
    'English textlaborEnglish text，English textlaborEnglish text。'),
  ('art_lcl_038', 'stat_lcl', 'English text', 38, 'laborEnglish text',
    'English textlaborEnglish textprovidelaborEnglish textlaborEnglish text、English textlaborEnglish text、English text，laborEnglish textlaborEnglish text。'),
  ('art_lcl_039', 'stat_lcl', 'English text', 39, 'English text（English text）',
    'laborEnglish text、English text、English text，English textlaborEnglish text。'),
  ('art_lcl_040', 'stat_lcl', 'English text',   40, 'English text',
    'English text，English textnoticelaborEnglish textlaborEnglish textsalaryEnglish text，English textlaborEnglish text：laborEnglish text；English text；English text。'),
  ('art_lcl_046', 'stat_lcl', 'English text', 46, 'English textcompensation',
    'English text，English textlaborEnglish textcompensation：English text；English text；English text、English text；laborEnglish text。'),
  ('art_lcl_047', 'stat_lcl', 'English text', 47, 'English textcompensationEnglish text',
    'English textcompensationEnglish textlaborEnglish text，English textsalaryEnglish textlaborEnglish text。English text，English text；English text，English textlaborEnglish textsalaryEnglish textcompensation。'),
  ('art_lcl_048', 'stat_lcl', 'English text', 48, 'unlawful terminationEnglish text',
    'English textlaborEnglish text，laborEnglish textlaborEnglish text，English text；laborEnglish textlaborEnglish text，English text。'),
  ('art_lcl_082', 'stat_lcl', 'English text', 82, 'English textsalary',
    'English textlaborEnglish textlaborEnglish text，English textlaborEnglish textsalary。'),
  ('art_lcl_087', 'stat_lcl', 'English text', 87, 'unlawful terminationEnglish text',
    'English textlaborEnglish text，English textcompensationEnglish textlaborEnglish text。');

-- Labor Law key articles
INSERT INTO statute_articles (article_id, statute_id, article_no, seq, heading, text) VALUES
  ('art_ll_036', 'stat_ll', 'English text', 36, 'English text',
    'English textlaborEnglish text、English textweeklyEnglish text。'),
  ('art_ll_041', 'stat_ll', 'English text', 41, 'English text',
    'English text，English textlaborEnglish text，English text；English text，English text。'),
  ('art_ll_044', 'stat_ll', 'English text', 44, 'overtime pay',
    'English textlaborEnglish text，English textsalaryEnglish text；English text，English text；English text，English text。'),
  ('art_ll_050', 'stat_ll', 'English text', 50, 'salaryEnglish text',
    'salaryEnglish textlaborEnglish text，English textlaborEnglish textsalary。');

-- ── Cases (anonymized judgments) ────────────────────────────────────
INSERT INTO cases (case_id, case_number, title, court_id, case_type, cause, judgment_date, parties, summary, facts, reasoning, holding, ruling, outcome, keywords) VALUES
  ('case_001', '(2025)English text0115English text12001English text', 'English textcompanyunlawful terminationlaborEnglish text', 'court_sh_pudong', 'labordispute', 'unlawful terminationlaborEnglish text', '2025-11-18',
    'English text：English text（English text）；English text：English textcompany',
    'companyEnglish text"English textadjustment"English textlaborEnglish text，English textprovideEnglish textbasis，courtEnglish textunlawful termination，rulingEnglish text。',
    'English text2019English text3English textcompanyEnglish text，English textsalary25000English text。2025English text6English textcompanyEnglish textadjustmentEnglish textnoticeEnglish textlaborEnglish text，English textnotice，English textnoticeEnglish text。English textunlawful termination，English text2NEnglish text。',
    'English textbasisEnglish text，English text，English textnoticeEnglish textsalaryEnglish text，English text，English textunlawful termination，English text、English textcompensationEnglish text。',
    'English text"English textadjustment"English textlaborEnglish text，English text，English textunlawful termination，English text。',
    'English text、English textrulingEnglish textunlawful terminationlaborEnglish text325000English text（25000English text×6.5English text×2）；English text、English textlitigationpleaseEnglish text。',
    'English text', 'unlawful termination,English text,2N,English textadjustment,English text'),

  ('case_002', '(2025)English text0112English text08842English text', 'English textdiningcompanyovertime payEnglish text', 'court_sh_minhang', 'labordispute', 'overtime pay', '2025-09-22',
    'English text：English text（English text）；English text：English textdiningcompany',
    'English text，companyEnglish textovertime pay，courtbasisEnglish textrecordrulingEnglish textovertime pay。',
    'English text2022English text，English textmonthly salary9000English text，English text。English textrecordEnglish text2024English text52English text，companyEnglish textovertime pay。',
    'basisLabor LawEnglish text，English text，English textovertime pay。English textprovideEnglish textovertime payEnglish text，English text。',
    'English textlaborEnglish text，English textsalaryEnglish textovertime pay；English textprovideEnglish text，English text。',
    'English text、English text2024English textovertime payEnglish text43034English text；English text、English text。',
    'English text', 'overtime pay,English text,English textsalary,English text,English text'),

  ('case_003', '(2025)English text0115English text09931English text', 'English textcompanydouble wage for no written contractEnglish text', 'court_sh_pudong', 'labordispute', 'English textlaborEnglish text', '2025-08-30',
    'English text：English text（English text）；English text：English textcompany',
    'companyEnglish textlaborEnglish text，courtrulingEnglish textsalaryshortfall。',
    'English text2024English text9English text1English text，English textlaborEnglish text。English text2025English text5English textdeparture，English textsalary12000English text。English text2024English text10English text1English textdepartureEnglish textsalary。',
    'basisLabor Contract LawEnglish text、English text，English textlaborEnglish text，English textsalary。English textsalaryEnglish textarbitrationlimitation periodEnglish text，English textlimitation period。',
    'English textlaborEnglish textlaborEnglish text，English textsalary，English text。',
    'English text、English text2024English text10English text1English text2025English text5English textlaborEnglish textsalaryshortfallEnglish text96000English text；English text、English textpleaseEnglish text。',
    'English text', 'English textlaborEnglish text,English textsalary,English text,arbitrationlimitation period,English text'),

  ('case_004', '(2025)English text0112English text07765English text', 'English textcompanyeconomic compensationEnglish text', 'court_sh_minhang', 'labordispute', 'English textcompensation', '2025-07-15',
    'English text：English text（English text）；English text：English textcompany',
    'companyEnglish text，English textlaborEnglish textcompensation，courtEnglish text。',
    'English text2017English text，English textsalary8000English text。English text2023English text。2025English text3English textnoticeEnglish textlaborEnglish text，English textcompensation。',
    'basisLabor Contract LawEnglish text，English textlaborEnglish text，laborEnglish textlaborEnglish text；basisEnglish text、English text，English textcompensation，English text。',
    'English text，laborEnglish textlaborEnglish text，English textbasisEnglish textcompensation（N），English text。',
    'English text、English texteconomic compensationEnglish text64000English text（8000English text×8English text）；English text、English text。',
    'English text', 'English textcompensation,N,English text,English text,English text'),

  ('case_005', '(2025)English text01English text04421English text', 'English textcompanyEnglish textunlawful terminationlaborEnglish text', 'court_sh_no1', 'labordispute', 'unlawful terminationlaborEnglish text', '2025-10-09',
    'English text：English textcompany；English text：English text（English text）',
    'companyEnglish text"English text"English text，English text，English textunlawful termination，English text。',
    'English text2020English text，English textsalary18000English text。2025English textcompanyEnglish text"English text"English text。companyEnglish text《English text》English text。English textunlawful termination，companyEnglish text。',
    'basisLabor Contract LawEnglish text，English text。English textlaborEnglish text，English textbasis，English textunlawful termination，English text。',
    'English text"English text"English textlaborEnglish text，English textbasisEnglish textlaborEnglish text，English textbasis。',
    'English text、English text，English text（English textunlawful terminationEnglish text180000English text）；English text、English text。',
    'English text', 'unlawful termination,English text,English text,English text,English text,English text'),

  ('case_006', '(2025)English text0115English text10210English text', 'English textcompanyovertime payEnglish textsalaryEnglish text', 'court_sh_pudong', 'labordispute', 'overtime pay', '2025-06-28',
    'English text：English text（English text）；English text：English textcompany',
    'English text，courtrulingEnglish textovertime payEnglish textsalary。',
    'English text2021English text，English textsalary20000English text，English text。English text2023-2024English textpassedEnglish textrecordEnglish texttotalEnglish text260English text，English text。',
    'basisLabor LawEnglish text，English textovertime pay；English text，English textsalaryEnglish textsalaryEnglish text。English textrecordEnglish textfactsEnglish text。',
    'English textrecordEnglish textfactsEnglish text，English textovertime pay；English text，English textsalaryEnglish text。',
    'English text、English textovertime payEnglish text43103English text；English text、English textsalaryEnglish text22069English text；English text、English textpleaseEnglish text。',
    'English text', 'overtime pay,English text,English text,English text,English text'),

  ('case_007', '(2025)English text0105English text15580English text', 'English textcompanyunlawful termination（pregnancy）English text', 'court_bj_chaoyang', 'labordispute', 'unlawful terminationlaborEnglish text', '2025-12-03',
    'English text：English text（English text）；English text：English textcompany',
    'companyEnglish textpregnancyEnglish text"English text"English textlaborEnglish text，English text，courtEnglish textunlawful terminationEnglish textrulingEnglish text。',
    'English text2022English text，English textsalary15000English text。2025English textpregnancyEnglish text，companyEnglish text"English text"English text。companyEnglish textprovideEnglish textadjustmentEnglish textpositionEnglish text。',
    'basisLabor Contract LawEnglish text，English text；English textpregnancyEnglish text，English text。English text，English text，English textlaborEnglish text。',
    'English textpregnancy、English text、English text，English textbasisEnglish textlaborEnglish text；laborEnglish text，English text。',
    'English text、confirmEnglish textlaborEnglish text；English text、English textlaborEnglish text，English textsalary。',
    'English text', 'unlawful termination,pregnancy,English text,English text,English text'),

  ('case_008', '(2025)English text0112English text06012English text', 'English textcompanyEnglish textsalaryEnglish text', 'court_sh_minhang', 'labordispute', 'English textlaborEnglish text', '2025-05-19',
    'English text：English text（English text）；English text：English textcompany',
    'companyEnglish textsalary，English textsalaryEnglish textcompensation，courtEnglish textsalaryEnglish text。',
    'English text2023English text，English textsalary7500English text。English text2025English text1English textsalary。English textlaborEnglish textsalaryEnglish textcompensation。',
    'basisLabor LawEnglish textLabor Contract LawEnglish text，English textsalaryEnglish text，English text，laborEnglish textcompensation。English textfactsEnglish text。',
    'English textlaborEnglish text，English text，laborEnglish textlaborEnglish textcompensation。',
    'English text、English textsalaryEnglish text22500English text；English text、English texteconomic compensationEnglish text15000English text。',
    'English text', 'English textsalary,English text,English text,English textcompensation,English text'),

  ('case_009', '(2025)English text0115English text11876English text', 'English textcompanynon-competecompensationEnglish text', 'court_sh_pudong', 'labordispute', 'non-compete', '2025-10-27',
    'English text：English text（English text）；English text：English textcompany',
    'English textnon-competeEnglish textcompanyEnglish textcompensation，English textcompensationEnglish text，courtrulingEnglish textnon-competeEnglish textcompensation。',
    'English text2021English textR&DEnglish text，English textsalary30000English text，departureEnglish textnon-competeEnglish text。departureEnglish textnon-competeEnglish text，English textanycompensation。',
    'non-competeEnglish textcompensation；English textcompensationEnglish text，English textlaborEnglish textdepartureEnglish textsalaryEnglish text，English textsalaryEnglish text。',
    'English textnon-competeEnglish textcompensationEnglish text，laborEnglish textdepartureEnglish textsalaryEnglish textcompensation。',
    'English text、English textnon-competeeconomic compensationEnglish text108000English text（30000English text×30%×12English text）；English text、English textpleaseEnglish text。',
    'English text', 'non-compete,compensationEnglish text,R&DEnglish text,English text,departure'),

  ('case_010', '(2025)English text0112English text05533English text', 'English textcompanyEnglish text', 'court_sh_minhang', 'labordispute', 'unlawful terminationlaborEnglish text', '2025-04-11',
    'English text：English text（English text）；English text：English textcompany',
    'companyEnglish text"English text"English text，English textbasis，courtEnglish textunlawful termination。',
    'English text2025English text1English text，English text。English textcompanyEnglish text"English text"English text，English text，English textanyEnglish textrecord。',
    'basisLabor Contract LawEnglish text，English text，English textlaborEnglish text。English text，English textunlawful termination。',
    'English textlaborEnglish text，English textlaborEnglish text。',
    'English text、English textunlawful terminationEnglish text6000English text；English text、English text。',
    'English text', 'unlawful termination,English text,English text,English text,English text'),

  ('case_011', '(2024)English text0115English text21344English text', 'English textcompanydouble wage for no written contractEnglish text', 'court_sh_pudong', 'labordispute', 'English textlaborEnglish text', '2024-12-20',
    'English text：English text（English text）；English text：English textcompany',
    'companyEnglish text，courtrulingEnglish textsalaryshortfall。',
    'English text2023English text6English text，English textsalary14000English text，English text2024English text6English textdepartureEnglish textlaborEnglish text。English textsalary。',
    'basisLabor Contract LawEnglish text，English textlaborEnglish textsalaryEnglish text，English text。',
    'English textlaborEnglish textsalaryEnglish text，English textstartEnglish text。',
    'English text、English textlaborEnglish textsalaryshortfallEnglish text154000English text；English text、English textpleaseEnglish text。',
    'English text', 'English textlaborEnglish text,English textsalary,English text,English text,English text'),

  ('case_012', '(2025)English text0112English text06890English text', 'English textcompanyeconomic compensationEnglish text', 'court_sh_minhang', 'labordispute', 'English textcompensation', '2025-06-05',
    'English text：English text（English text）；English text：English textcompany',
    'English textcompensationEnglish textdispute，courtEnglish textdepartureEnglish textsalaryEnglish text。',
    'English text2018English text，English textmonthly salary16000English text，English text。2025English text，companyEnglish textbasesalaryEnglish textcompensation。English text。',
    'basisLabor Contract LawEnglish text，English textcompensationEnglish textsalaryEnglish textlaborEnglish textlaborEnglish textsalary，English text、English text。',
    'English textcompensationEnglish textsalaryEnglish textlaborEnglish textsalary，English text、English text，English textbasesalary。',
    'English text、English texteconomic compensationshortfallEnglish text28000English text；English text、English text。',
    'English text', 'English textcompensation,English text,English textsalary,English text,English text'),

  ('case_013', '(2025)English text0115English text10044English text', 'English textcompanyovertime payEnglish text（English text）', 'court_sh_pudong', 'labordispute', 'overtime pay', '2025-09-08',
    'English text：English text（English text）；English text：English textcompany',
    'companyEnglish texttotalEnglish text，courtEnglish textrulingovertime pay。',
    'English text2022English text，English textsalary13000English text。companyEnglish texttotalEnglish textovertime pay，English textprovideEnglish text。',
    'English texttotalEnglish textlaborEnglish text。English text，English textovertime pay。',
    'English texttotalEnglish textlaborEnglish text，English textovertime pay。',
    'English text、English textovertime payEnglish text31494English text；English text、English textpleaseEnglish text。',
    'English text', 'overtime pay,English text,English text,English text,English text'),

  ('case_014', '(2025)English text0105English text12233English text', 'English textcompanyunlawful termination（"English text"）English text', 'court_bj_chaoyang', 'labordispute', 'unlawful terminationlaborEnglish text', '2025-08-14',
    'English text：English text（English text）；English text：English textcompany',
    'companyEnglish text"English text"English textlaborEnglish text，courtEnglish text，English textunlawful termination。',
    'English text2020English textengineer，English textsalary28000English text。2025English textcompanyEnglish text。companyEnglish text，English text。',
    '"English text"English text。English text，English text，English textunlawful termination。',
    'English text"English text"English textlaborEnglish text，English text，English textunlawful termination，English text。',
    'English text、English textunlawful terminationEnglish text280000English text；English text、English text。',
    'English text', 'unlawful termination,English text,English text,English text,engineer'),

  ('case_015', '(2025)English text0112English text07120English text', 'English textcompanyEnglish textsalaryEnglish text', 'court_sh_minhang', 'labordispute', 'English textlaborEnglish text', '2025-07-02',
    'English text：English text（English text）；English text：English textcompany',
    'English textcompanyEnglish textsalary，courtrulingEnglish textsalaryEnglish textsalary。',
    'English text2020English text，English textsalary6500English text。2024English text，English textcompanyEnglish textsalary。',
    'English text，English textsalaryEnglish text，English text。',
    'English text，English textsalaryEnglish textsalary，English text。',
    'English text、English textsalaryEnglish text39000English text；English text、English text。',
    'English text', 'English text,English text,salary,English textsalaryEnglish text,English text'),

  ('case_016', '(2025)English text0115English text09015English text', 'English textcompanyunlawful terminationEnglish text', 'court_sh_pudong', 'labordispute', 'unlawful terminationlaborEnglish text', '2025-05-26',
    'English text：English text（English text）；English text：English textcompany',
    'companyEnglish text"English text"English text，courtEnglish textunlawful termination。',
    'English text2016English textengineer，English textsalary32000English text。2025English textcompanyEnglish textadjustmentEnglish text"English text"English text，English textlaborEnglish text。',
    'basisLabor Contract LawEnglish text，English text，English textlaborEnglish text。English text，English textunlawful termination。',
    'English text"English text"English textlaborEnglish text，English textlaborEnglish textlaborEnglish text，English textunlawful termination。',
    'English text、English textunlawful terminationEnglish text608000English text（32000English text×9.5English text×2）；English text、English textpleaseEnglish text。',
    'English text', 'unlawful termination,English text,English text,English text,English textengineer'),

  ('case_017', '(2024)English text0115English text19922English text', 'English textcompanyunlawful terminationEnglish text（English text）', 'court_sh_pudong', 'labordispute', 'unlawful terminationlaborEnglish text', '2024-11-30',
    'English text：English text（English text）；English text：English textcompany',
    'companyEnglish textlaborEnglish text，courtEnglish text。',
    'English text2015English textengineer，English textlaborEnglish text，English textsalary22000English text。2024English textcompanyEnglish text，English text，English textlaborEnglish textplan。',
    'basisLabor Contract LawEnglish text，English textlaborEnglish textlaborEnglish text，English textlaborEnglish text。English text，English textunlawful termination。',
    'English textlaborEnglish textlaborEnglish text，English text，English textunlawful termination。',
    'English text、English textunlawful terminationEnglish text418000English text；English text、English text。',
    'English text', 'unlawful termination,English text,English text,English text,English text'),

  ('case_018', '(2025)English text01English text05012English text', 'English textcompanyEnglish textnon-competeEnglish text', 'court_sh_no1', 'labordispute', 'non-compete', '2025-11-05',
    'English text：English textcompany；English text：English text（English text）',
    'companyEnglish textnon-competeEnglish text，English text。',
    'English text2019English textengineer，departureEnglish textnon-competeEnglish text180English text。companyEnglish text。English text。companyEnglish text。',
    'non-competeEnglish text，laborEnglish textpleaseEnglish text。English textcompensationEnglish text、English text，English text。',
    'non-competeEnglish text，People''s CourtEnglish textpleaseEnglish text。',
    'English text、English text，English text（English textnon-competeEnglish text360000English text）；English text、English text。',
    'English text', 'non-compete,English text,English text,English textengineer,English text');

-- ── Citations (case → statute article / case) ──────────────────────
INSERT INTO citations (citation_id, case_id, target_type, target_id, label) VALUES
  ('cit_seed_0001', 'case_001', 'article', 'art_lcl_040', 'English textbasisEnglish text'),
  ('cit_seed_0002', 'case_001', 'article', 'art_lcl_048', 'unlawful termination'),
  ('cit_seed_0003', 'case_001', 'article', 'art_lcl_087', 'English textbasis'),
  ('cit_seed_0004', 'case_002', 'article', 'art_ll_044',  'overtime paybasis'),
  ('cit_seed_0005', 'case_003', 'article', 'art_lcl_010', 'English text'),
  ('cit_seed_0006', 'case_003', 'article', 'art_lcl_082', 'English textsalarybasis'),
  ('cit_seed_0007', 'case_004', 'article', 'art_lcl_038', 'English text'),
  ('cit_seed_0008', 'case_004', 'article', 'art_lcl_046', 'English textcompensationEnglish text'),
  ('cit_seed_0009', 'case_004', 'article', 'art_lcl_047', 'English textcompensationEnglish text'),
  ('cit_seed_0010', 'case_005', 'article', 'art_lcl_039', 'English text'),
  ('cit_seed_0011', 'case_005', 'article', 'art_lcl_087', 'English textbasis'),
  ('cit_seed_0012', 'case_006', 'article', 'art_ll_044',  'overtime paybasis'),
  ('cit_seed_0013', 'case_007', 'article', 'art_lcl_040', 'English text'),
  ('cit_seed_0014', 'case_007', 'article', 'art_lcl_048', 'English text'),
  ('cit_seed_0015', 'case_008', 'article', 'art_ll_050',  'salaryEnglish text'),
  ('cit_seed_0016', 'case_008', 'article', 'art_lcl_038', 'English text'),
  ('cit_seed_0017', 'case_010', 'article', 'art_lcl_039', 'English text'),
  ('cit_seed_0018', 'case_011', 'article', 'art_lcl_082', 'English textsalarybasis'),
  ('cit_seed_0019', 'case_012', 'article', 'art_lcl_047', 'English textcompensationEnglish text'),
  ('cit_seed_0020', 'case_013', 'article', 'art_ll_036',  'English text'),
  ('cit_seed_0021', 'case_013', 'article', 'art_ll_044',  'overtime paybasis'),
  ('cit_seed_0022', 'case_014', 'article', 'art_lcl_040', 'English text'),
  ('cit_seed_0023', 'case_014', 'article', 'art_lcl_087', 'English textbasis'),
  ('cit_seed_0024', 'case_016', 'article', 'art_lcl_040', 'English text'),
  ('cit_seed_0025', 'case_016', 'article', 'art_lcl_087', 'English textbasis'),
  ('cit_seed_0026', 'case_017', 'article', 'art_lcl_087', 'English textbasis'),
  ('cit_seed_0027', 'case_005', 'case',    'case_001',    'English textunlawful terminationEnglish text'),
  ('cit_seed_0028', 'case_014', 'case',    'case_001',    'English textunlawful terminationEnglish text'),
  ('cit_seed_0029', 'case_016', 'case',    'case_017',    'English text');

-- ── Seeded user library: usr_li_wei (preparing laborarbitration/litigation) ────────
-- Li Wei was dismissed via "English textadjustment" and is researching precedent.
INSERT INTO saved_cases (saved_id, user_id, case_id, note, saved_at) VALUES
  ('saved_seed_001', 'usr_li_wei', 'case_001',
    'English text：companyEnglish text"English textadjustment"English text，English text30English textnotice。English text2NEnglish text，English textbasis。', '2026-05-12T09:15:00Z'),
  ('saved_seed_002', 'usr_li_wei', 'case_016',
    'English text：companyEnglish text"English text"English text——English textreasoningEnglish text，courtEnglish textunlawful termination。', '2026-05-14T20:40:00Z');

-- ══ Distractor courts (dis_*) ══
INSERT INTO courts (court_id, name, level, region) VALUES
  ('dis_court_sh_xuhui', 'ShanghaiEnglish textPeople''s Court', 'English textcourt', 'ShanghaiEnglish text'),
  ('dis_court_sh_jingan', 'ShanghaiEnglish textPeople''s Court', 'English textcourt', 'ShanghaiEnglish text'),
  ('dis_court_bj_haidian', 'BeijingEnglish textPeople''s Court', 'English textcourt', 'BeijingEnglish text'),
  ('dis_arb_bj_chaoyang', 'BeijingEnglish textlaborEnglish textdisputearbitrationEnglish text', 'arbitrationEnglish text', 'BeijingEnglish text');

-- ══ Distractor cases (dis_*) — realistic older labor disputes, never displace seed cases ══
INSERT INTO cases (case_id, case_number, title, court_id, case_type, cause, judgment_date, parties, summary, facts, reasoning, holding, ruling, outcome, keywords) VALUES
  ('dis_case_001', '(2023)English text9000English text20000English text', 'English textcompanyovertime payEnglish text', 'dis_court_sh_xuhui', 'labordispute', 'overtime pay', '2023-12-15',
    'English text：English text（English text）；English text：English textcompany',
    'English textcompanyEnglish textovertime pay，courtEnglish textrulingEnglish text。',
    'English text2021English text，English textsalary6000English text。English textcompanyEnglish textovertime pay，courtEnglish textrulingEnglish text。relatedEnglish text。',
    'basisLabor Contract LawEnglish textLabor LawrelatedEnglish text，English textovertime payEnglish textlegalEnglish text，English textfactsEnglish text，legalEnglish text。',
    'English textovertime payEnglish text，English text。',
    'English text、English textrelatedEnglish text12000English text；English text、English text。',
    'English text', 'overtime pay,English text,English text,English text'),

  ('dis_case_002', '(2023)English text9001English text20037English text', 'English textcompanyEnglish textcompensationEnglish text', 'dis_court_sh_jingan', 'labordispute', 'English textcompensation', '2023-11-22',
    'English text：English text（English text）；English text：English textcompany',
    'companyEnglish textlaborEnglish text，courtrulingEnglish textcompensation。',
    'English text2020English text，English textsalary6350English text。companyEnglish textlaborEnglish text，courtrulingEnglish textcompensation。relatedEnglish text。',
    'basisLabor Contract LawEnglish textLabor LawrelatedEnglish text，English textcompensationEnglish textlegalEnglish text，English textfactsEnglish text，legalEnglish text。',
    'English textcompensationEnglish text，English text。',
    'English text、English textrelatedEnglish text19050English text；English text、English text。',
    'English text', 'English textcompensation,N,English text,English text'),

  ('dis_case_003', '(2023)English text9002English text20074English text', 'English textcompanyEnglish textlaborEnglish text', 'dis_court_bj_haidian', 'labordispute', 'English textlaborEnglish text', '2023-10-01',
    'English text：English text（English text）；English text：English textcompany',
    'English text，courtrulingEnglish textsalaryshortfall。',
    'English text2019English textengineer，English textsalary6700English text。English text，courtrulingEnglish textsalaryshortfall。relatedEnglish text。',
    'basisLabor Contract LawEnglish textLabor LawrelatedEnglish text，English textlaborEnglish textlegalEnglish text，English textfactsEnglish text，legalEnglish text。',
    'English textlaborEnglish text，English text。',
    'English text、English textrelatedEnglish text26800English text；English text、English text。',
    'English text', 'English textlaborEnglish text,English textsalary,English text'),

  ('dis_case_004', '(2023)English text9003English text20111English text', 'English textcompanyEnglish textlaborEnglish text', 'dis_arb_bj_chaoyang', 'labordispute', 'English textlaborEnglish text', '2023-09-08',
    'English text：English text（English text）；English text：English textcompany',
    'companyEnglish textsalary，English text，courtEnglish text。',
    'English text2018English text，English textsalary7050English text。companyEnglish textsalary，English text，courtEnglish text。relatedEnglish text。',
    'basisLabor Contract LawEnglish textLabor LawrelatedEnglish text，English textlaborEnglish textlegalEnglish text，English textfactsEnglish text，legalEnglish text。',
    'English textlaborEnglish text，English text。',
    'English text、English textrelatedEnglish text35250English text；English text、English text。',
    'English text', 'English textsalary,English text,English text'),

  ('dis_case_005', '(2023)English text9004English text20148English text', 'English textcompanynon-competeEnglish text', 'court_sh_pudong', 'labordispute', 'non-compete', '2023-08-15',
    'English text：English text（English text）；English text：English textcompany',
    'English textnon-competeEnglish textcompensation，English textcompensationEnglish text，courtEnglish text。',
    'English text2017English text，English textsalary7400English text。English textnon-competeEnglish textcompensation，English textcompensationEnglish text，courtEnglish text。relatedEnglish text。',
    'basisLabor Contract LawEnglish textLabor LawrelatedEnglish text，English textnon-competeEnglish textlegalEnglish text，English textfactsEnglish text，legalEnglish text。',
    'English textnon-competeEnglish text，English text。',
    'English text、English textrelatedEnglish text44400English text；English text、English text。',
    'English text', 'non-compete,compensationEnglish text,departure'),

  ('dis_case_006', '(2023)English text9005English text20185English text', 'English textcompanyunlawful terminationlaborEnglish text', 'court_sh_minhang', 'labordispute', 'unlawful terminationlaborEnglish text', '2023-07-22',
    'English text：English text（English text）；English text：English textcompany',
    'companyEnglish text，courtEnglish textunlawful terminationEnglish text。',
    'English text2016English text，English textsalary7750English text。companyEnglish text，courtEnglish textunlawful terminationEnglish text。relatedEnglish text。',
    'basisLabor Contract LawEnglish textLabor LawrelatedEnglish text，English textunlawful terminationlaborEnglish textlegalEnglish text，English textfactsEnglish text，legalEnglish text。',
    'English textunlawful terminationlaborEnglish text，English text。',
    'English text、English textrelatedEnglish text54250English text；English text、English text。',
    'English text', 'unlawful termination,English text,English text'),

  ('dis_case_007', '(2023)English text9006English text20222English text', 'English textdiningcompanyEnglish text', 'court_bj_chaoyang', 'labordispute', 'English text', '2023-06-01',
    'English text：English text（English text）；English text：English textdiningcompany',
    'English text，courtrulingEnglish textsalary。',
    'English text2015English text，English textsalary8100English text。English text，courtrulingEnglish textsalary。relatedEnglish text。',
    'basisLabor Contract LawEnglish textLabor LawrelatedEnglish text，English textlegalEnglish text，English textfactsEnglish text，legalEnglish text。',
    'English text，English text。',
    'English text、English textrelatedEnglish text64800English text；English text、English text。',
    'English text', 'English text,English textsalary,English text'),

  ('dis_case_008', '(2023)English text9007English text20259English text', 'English textcompanyEnglish text', 'dis_court_sh_xuhui', 'labordispute', 'English text', '2023-05-08',
    'English text：English text（English text）；English text：English textcompany',
    'companyEnglish text，English textcompensation。',
    'English text2014English textassistant，English textsalary8450English text。companyEnglish text，English textcompensation。relatedEnglish text。',
    'basisLabor Contract LawEnglish textLabor LawrelatedEnglish text，English textlegalEnglish text，English textfactsEnglish text，legalEnglish text。',
    'English text，English text。',
    'English text、English textrelatedEnglish text76050English text；English text、English text。',
    'English text', 'English text,English text,English text,English text'),

  ('dis_case_009', '(2023)English text9008English text20296English text', 'English textcompanyEnglish text', 'dis_court_sh_jingan', 'labordispute', 'English text', '2023-04-15',
    'English text：English text（English text）；English text：English textcompany',
    'English textcompanyEnglish textsalary，courtrulingEnglish text。',
    'English text2013English textdataEnglish text，English textsalary8800English text。English textcompanyEnglish textsalary，courtrulingEnglish text。relatedEnglish text。',
    'basisLabor Contract LawEnglish textLabor LawrelatedEnglish text，English textlegalEnglish text，English textfactsEnglish text，legalEnglish text。',
    'English text，English text。',
    'English text、English textrelatedEnglish text88000English text；English text、English text。',
    'English text', 'English text,English text,salary'),

  ('dis_case_010', '(2023)English text9009English text20333English text', 'English textcompanylaborarbitrationEnglish text', 'dis_court_bj_haidian', 'laborarbitration', 'laborarbitration', '2023-03-22',
    'English text：English text（English text）；English text：English textcompany',
    'English textarbitrationEnglish text，companyEnglish textcompensation。',
    'English text2021English text，English textsalary9150English text。English textarbitrationEnglish text，companyEnglish textcompensation。relatedEnglish text。',
    'basisLabor Contract LawEnglish textLabor LawrelatedEnglish text，English textlaborarbitrationEnglish textlegalEnglish text，English textfactsEnglish text，legalEnglish text。',
    'English textlaborarbitrationEnglish text，English text。',
    'English text、English textrelatedEnglish text18300English text；English text、English text。',
    'English text', 'laborarbitration,English text,English textcompensation'),

  ('dis_case_011', '(2023)English text9010English text20370English text', 'English textcompanyovertime payEnglish text', 'dis_arb_bj_chaoyang', 'labordispute', 'overtime pay', '2023-02-01',
    'English text：English text（English text）；English text：English textcompany',
    'English textcompanyEnglish textovertime pay，courtEnglish textrulingEnglish text。',
    'English text2020English text，English textsalary9500English text。English textcompanyEnglish textovertime pay，courtEnglish textrulingEnglish text。relatedEnglish text。',
    'basisLabor Contract LawEnglish textLabor LawrelatedEnglish text，English textovertime payEnglish textlegalEnglish text，English textfactsEnglish text，legalEnglish text。',
    'English textovertime payEnglish text，English text。',
    'English text、English textrelatedEnglish text28500English text；English text、English text。',
    'English text', 'overtime pay,English text,English text,English text'),

  ('dis_case_012', '(2023)English text9011English text20407English text', 'English textcompanyEnglish textcompensationEnglish text', 'court_sh_pudong', 'labordispute', 'English textcompensation', '2023-01-08',
    'English text：English text（English text）；English text：English textcompany',
    'companyEnglish textlaborEnglish text，courtrulingEnglish textcompensation。',
    'English text2019English textUIEnglish text，English textsalary9850English text。companyEnglish textlaborEnglish text，courtrulingEnglish textcompensation。relatedEnglish text。',
    'basisLabor Contract LawEnglish textLabor LawrelatedEnglish text，English textcompensationEnglish textlegalEnglish text，English textfactsEnglish text，legalEnglish text。',
    'English textcompensationEnglish text，English text。',
    'English text、English textrelatedEnglish text39400English text；English text、English text。',
    'English text', 'English textcompensation,N,English text,English text'),

  ('dis_case_013', '(2022)English text9012English text20444English text', 'English textcompanyEnglish textlaborEnglish text', 'court_sh_minhang', 'labordispute', 'English textlaborEnglish text', '2022-12-15',
    'English text：English text（English text）；English text：English textcompany',
    'English text，courtrulingEnglish textsalaryshortfall。',
    'English text2017English textengineer，English textsalary10200English text。English text，courtrulingEnglish textsalaryshortfall。relatedEnglish text。',
    'basisLabor Contract LawEnglish textLabor LawrelatedEnglish text，English textlaborEnglish textlegalEnglish text，English textfactsEnglish text，legalEnglish text。',
    'English textlaborEnglish text，English text。',
    'English text、English textrelatedEnglish text51000English text；English text、English text。',
    'English text', 'English textlaborEnglish text,English textsalary,English text'),

  ('dis_case_014', '(2022)English text9013English text20481English text', 'English textcompanyEnglish textlaborEnglish text', 'court_bj_chaoyang', 'labordispute', 'English textlaborEnglish text', '2022-11-22',
    'English text：English text（English text）；English text：English textcompany',
    'companyEnglish textsalary，English text，courtEnglish text。',
    'English text2016English text，English textsalary10550English text。companyEnglish textsalary，English text，courtEnglish text。relatedEnglish text。',
    'basisLabor Contract LawEnglish textLabor LawrelatedEnglish text，English textlaborEnglish textlegalEnglish text，English textfactsEnglish text，legalEnglish text。',
    'English textlaborEnglish text，English text。',
    'English text、English textrelatedEnglish text63300English text；English text、English text。',
    'English text', 'English textsalary,English text,English text'),

  ('dis_case_015', '(2022)English text9014English text20518English text', 'English textcompanynon-competeEnglish text', 'dis_court_sh_xuhui', 'labordispute', 'non-compete', '2022-10-01',
    'English text：English text（English text）；English text：English textcompany',
    'English textnon-competeEnglish textcompensation，English textcompensationEnglish text，courtEnglish text。',
    'English text2015English text，English textsalary10900English text。English textnon-competeEnglish textcompensation，English textcompensationEnglish text，courtEnglish text。relatedEnglish text。',
    'basisLabor Contract LawEnglish textLabor LawrelatedEnglish text，English textnon-competeEnglish textlegalEnglish text，English textfactsEnglish text，legalEnglish text。',
    'English textnon-competeEnglish text，English text。',
    'English text、English textrelatedEnglish text76300English text；English text、English text。',
    'English text', 'non-compete,compensationEnglish text,departure'),

  ('dis_case_016', '(2022)English text9015English text20555English text', 'English textcompanyunlawful terminationlaborEnglish text', 'dis_court_sh_jingan', 'labordispute', 'unlawful terminationlaborEnglish text', '2022-09-08',
    'English text：English text（English text）；English text：English textcompany',
    'companyEnglish text，courtEnglish textunlawful terminationEnglish text。',
    'English text2014English text，English textsalary11250English text。companyEnglish text，courtEnglish textunlawful terminationEnglish text。relatedEnglish text。',
    'basisLabor Contract LawEnglish textLabor LawrelatedEnglish text，English textunlawful terminationlaborEnglish textlegalEnglish text，English textfactsEnglish text，legalEnglish text。',
    'English textunlawful terminationlaborEnglish text，English text。',
    'English text、English textrelatedEnglish text90000English text；English text、English text。',
    'English text', 'unlawful termination,English text,English text'),

  ('dis_case_017', '(2022)English text9016English text20592English text', 'English textdiningcompanyEnglish text', 'dis_court_bj_haidian', 'labordispute', 'English text', '2022-08-15',
    'English text：English text（English text）；English text：English textdiningcompany',
    'English text，courtrulingEnglish textsalary。',
    'English text2013English text，English textsalary11600English text。English text，courtrulingEnglish textsalary。relatedEnglish text。',
    'basisLabor Contract LawEnglish textLabor LawrelatedEnglish text，English textlegalEnglish text，English textfactsEnglish text，legalEnglish text。',
    'English text，English text。',
    'English text、English textrelatedEnglish text104400English text；English text、English text。',
    'English text', 'English text,English textsalary,English text'),

  ('dis_case_018', '(2022)English text9017English text20629English text', 'English textcompanyEnglish text', 'dis_arb_bj_chaoyang', 'labordispute', 'English text', '2022-07-22',
    'English text：English text（English text）；English text：English textcompany',
    'companyEnglish text，English textcompensation。',
    'English text2012English textengineer，English textsalary11950English text。companyEnglish text，English textcompensation。relatedEnglish text。',
    'basisLabor Contract LawEnglish textLabor LawrelatedEnglish text，English textlegalEnglish text，English textfactsEnglish text，legalEnglish text。',
    'English text，English text。',
    'English text、English textrelatedEnglish text119500English text；English text、English text。',
    'English text', 'English text,English text,English text,English text'),

  ('dis_case_019', '(2022)English text9018English text20666English text', 'English textcompanyEnglish text', 'court_sh_pudong', 'labordispute', 'English text', '2022-06-01',
    'English text：English text（English text）；English text：English textcompany',
    'English textcompanyEnglish textsalary，courtrulingEnglish text。',
    'English text2020English text，English textsalary12300English text。English textcompanyEnglish textsalary，courtrulingEnglish text。relatedEnglish text。',
    'basisLabor Contract LawEnglish textLabor LawrelatedEnglish text，English textlegalEnglish text，English textfactsEnglish text，legalEnglish text。',
    'English text，English text。',
    'English text、English textrelatedEnglish text24600English text；English text、English text。',
    'English text', 'English text,English text,salary'),

  ('dis_case_020', '(2022)English text9019English text20703English text', 'English textcompanylaborarbitrationEnglish text', 'court_sh_minhang', 'laborarbitration', 'laborarbitration', '2022-05-08',
    'English text：English text（English text）；English text：English textcompany',
    'English textarbitrationEnglish text，companyEnglish textcompensation。',
    'English text2019English text，English textsalary12650English text。English textarbitrationEnglish text，companyEnglish textcompensation。relatedEnglish text。',
    'basisLabor Contract LawEnglish textLabor LawrelatedEnglish text，English textlaborarbitrationEnglish textlegalEnglish text，English textfactsEnglish text，legalEnglish text。',
    'English textlaborarbitrationEnglish text，English text。',
    'English text、English textrelatedEnglish text37950English text；English text、English text。',
    'English text', 'laborarbitration,English text,English textcompensation'),

  ('dis_case_021', '(2022)English text9020English text20740English text', 'English textcompanyovertime payEnglish text', 'court_bj_chaoyang', 'labordispute', 'overtime pay', '2022-04-15',
    'English text：English text（English text）；English text：English textcompany',
    'English textcompanyEnglish textovertime pay，courtEnglish textrulingEnglish text。',
    'English text2018English text，English textsalary13000English text。English textcompanyEnglish textovertime pay，courtEnglish textrulingEnglish text。relatedEnglish text。',
    'basisLabor Contract LawEnglish textLabor LawrelatedEnglish text，English textovertime payEnglish textlegalEnglish text，English textfactsEnglish text，legalEnglish text。',
    'English textovertime payEnglish text，English text。',
    'English text、English textrelatedEnglish text52000English text；English text、English text。',
    'English text', 'overtime pay,English text,English text,English text'),

  ('dis_case_022', '(2022)English text9021English text20777English text', 'English textcompanyEnglish textcompensationEnglish text', 'dis_court_sh_xuhui', 'labordispute', 'English textcompensation', '2022-03-22',
    'English text：English text（English text）；English text：English textcompany',
    'companyEnglish textlaborEnglish text，courtrulingEnglish textcompensation。',
    'English text2017English text，English textsalary13350English text。companyEnglish textlaborEnglish text，courtrulingEnglish textcompensation。relatedEnglish text。',
    'basisLabor Contract LawEnglish textLabor LawrelatedEnglish text，English textcompensationEnglish textlegalEnglish text，English textfactsEnglish text，legalEnglish text。',
    'English textcompensationEnglish text，English text。',
    'English text、English textrelatedEnglish text66750English text；English text、English text。',
    'English text', 'English textcompensation,N,English text,English text'),

  ('dis_case_023', '(2022)English text9022English text20814English text', 'English textcompanyEnglish textlaborEnglish text', 'dis_court_sh_jingan', 'labordispute', 'English textlaborEnglish text', '2022-02-01',
    'English text：English text（English text）；English text：English textcompany',
    'English text，courtrulingEnglish textsalaryshortfall。',
    'English text2016English textassistant，English textsalary13700English text。English text，courtrulingEnglish textsalaryshortfall。relatedEnglish text。',
    'basisLabor Contract LawEnglish textLabor LawrelatedEnglish text，English textlaborEnglish textlegalEnglish text，English textfactsEnglish text，legalEnglish text。',
    'English textlaborEnglish text，English text。',
    'English text、English textrelatedEnglish text82200English text；English text、English text。',
    'English text', 'English textlaborEnglish text,English textsalary,English text'),

  ('dis_case_024', '(2022)English text9023English text20851English text', 'English textcompanyEnglish textlaborEnglish text', 'dis_court_bj_haidian', 'labordispute', 'English textlaborEnglish text', '2022-01-08',
    'English text：English text（English text）；English text：English textcompany',
    'companyEnglish textsalary，English text，courtEnglish text。',
    'English text2015English textdataEnglish text，English textsalary14050English text。companyEnglish textsalary，English text，courtEnglish text。relatedEnglish text。',
    'basisLabor Contract LawEnglish textLabor LawrelatedEnglish text，English textlaborEnglish textlegalEnglish text，English textfactsEnglish text，legalEnglish text。',
    'English textlaborEnglish text，English text。',
    'English text、English textrelatedEnglish text98350English text；English text、English text。',
    'English text', 'English textsalary,English text,English text'),

  ('dis_case_025', '(2021)English text9024English text20888English text', 'English textcompanynon-competeEnglish text', 'dis_arb_bj_chaoyang', 'labordispute', 'non-compete', '2021-12-15',
    'English text：English text（English text）；English text：English textcompany',
    'English textnon-competeEnglish textcompensation，English textcompensationEnglish text，courtEnglish text。',
    'English text2013English text，English textsalary14400English text。English textnon-competeEnglish textcompensation，English textcompensationEnglish text，courtEnglish text。relatedEnglish text。',
    'basisLabor Contract LawEnglish textLabor LawrelatedEnglish text，English textnon-competeEnglish textlegalEnglish text，English textfactsEnglish text，legalEnglish text。',
    'English textnon-competeEnglish text，English text。',
    'English text、English textrelatedEnglish text115200English text；English text、English text。',
    'English text', 'non-compete,compensationEnglish text,departure'),

  ('dis_case_026', '(2021)English text9025English text20925English text', 'English textcompanyunlawful terminationlaborEnglish text', 'court_sh_pudong', 'labordispute', 'unlawful terminationlaborEnglish text', '2021-11-22',
    'English text：English text（English text）；English text：English textcompany',
    'companyEnglish text，courtEnglish textunlawful terminationEnglish text。',
    'English text2012English text，English textsalary14750English text。companyEnglish text，courtEnglish textunlawful terminationEnglish text。relatedEnglish text。',
    'basisLabor Contract LawEnglish textLabor LawrelatedEnglish text，English textunlawful terminationlaborEnglish textlegalEnglish text，English textfactsEnglish text，legalEnglish text。',
    'English textunlawful terminationlaborEnglish text，English text。',
    'English text、English textrelatedEnglish text132750English text；English text、English text。',
    'English text', 'unlawful termination,English text,English text'),

  ('dis_case_027', '(2021)English text9026English text20962English text', 'English textdiningcompanyEnglish text', 'court_sh_minhang', 'labordispute', 'English text', '2021-10-01',
    'English text：English text（English text）；English text：English textdiningcompany',
    'English text，courtrulingEnglish textsalary。',
    'English text2011English textUIEnglish text，English textsalary15100English text。English text，courtrulingEnglish textsalary。relatedEnglish text。',
    'basisLabor Contract LawEnglish textLabor LawrelatedEnglish text，English textlegalEnglish text，English textfactsEnglish text，legalEnglish text。',
    'English text，English text。',
    'English text、English textrelatedEnglish text151000English text；English text、English text。',
    'English text', 'English text,English textsalary,English text'),

  ('dis_case_028', '(2021)English text9027English text20999English text', 'English textcompanyEnglish text', 'court_bj_chaoyang', 'labordispute', 'English text', '2021-09-08',
    'English text：English text（English text）；English text：English textcompany',
    'companyEnglish text，English textcompensation。',
    'English text2019English textengineer，English textsalary15450English text。companyEnglish text，English textcompensation。relatedEnglish text。',
    'basisLabor Contract LawEnglish textLabor LawrelatedEnglish text，English textlegalEnglish text，English textfactsEnglish text，legalEnglish text。',
    'English text，English text。',
    'English text、English textrelatedEnglish text30900English text；English text、English text。',
    'English text', 'English text,English text,English text,English text'),

  ('dis_case_029', '(2021)English text9028English text21036English text', 'English textcompanyEnglish text', 'dis_court_sh_xuhui', 'labordispute', 'English text', '2021-08-15',
    'English text：English text（English text）；English text：English textcompany',
    'English textcompanyEnglish textsalary，courtrulingEnglish text。',
    'English text2018English text，English textsalary15800English text。English textcompanyEnglish textsalary，courtrulingEnglish text。relatedEnglish text。',
    'basisLabor Contract LawEnglish textLabor LawrelatedEnglish text，English textlegalEnglish text，English textfactsEnglish text，legalEnglish text。',
    'English text，English text。',
    'English text、English textrelatedEnglish text47400English text；English text、English text。',
    'English text', 'English text,English text,salary'),

  ('dis_case_030', '(2021)English text9029English text21073English text', 'English textcompanylaborarbitrationEnglish text', 'dis_court_sh_jingan', 'laborarbitration', 'laborarbitration', '2021-07-22',
    'English text：English text（English text）；English text：English textcompany',
    'English textarbitrationEnglish text，companyEnglish textcompensation。',
    'English text2017English text，English textsalary16150English text。English textarbitrationEnglish text，companyEnglish textcompensation。relatedEnglish text。',
    'basisLabor Contract LawEnglish textLabor LawrelatedEnglish text，English textlaborarbitrationEnglish textlegalEnglish text，English textfactsEnglish text，legalEnglish text。',
    'English textlaborarbitrationEnglish text，English text。',
    'English text、English textrelatedEnglish text64600English text；English text、English text。',
    'English text', 'laborarbitration,English text,English textcompensation'),

  ('dis_case_031', '(2021)English text9030English text21110English text', 'English textcompanyovertime payEnglish text', 'dis_court_bj_haidian', 'labordispute', 'overtime pay', '2021-06-01',
    'English text：English text（English text）；English text：English textcompany',
    'English textcompanyEnglish textovertime pay，courtEnglish textrulingEnglish text。',
    'English text2016English text，English textsalary16500English text。English textcompanyEnglish textovertime pay，courtEnglish textrulingEnglish text。relatedEnglish text。',
    'basisLabor Contract LawEnglish textLabor LawrelatedEnglish text，English textovertime payEnglish textlegalEnglish text，English textfactsEnglish text，legalEnglish text。',
    'English textovertime payEnglish text，English text。',
    'English text、English textrelatedEnglish text82500English text；English text、English text。',
    'English text', 'overtime pay,English text,English text,English text'),

  ('dis_case_032', '(2021)English text9031English text21147English text', 'English textcompanyEnglish textcompensationEnglish text', 'dis_arb_bj_chaoyang', 'labordispute', 'English textcompensation', '2021-05-08',
    'English text：English text（English text）；English text：English textcompany',
    'companyEnglish textlaborEnglish text，courtrulingEnglish textcompensation。',
    'English text2015English text，English textsalary16850English text。companyEnglish textlaborEnglish text，courtrulingEnglish textcompensation。relatedEnglish text。',
    'basisLabor Contract LawEnglish textLabor LawrelatedEnglish text，English textcompensationEnglish textlegalEnglish text，English textfactsEnglish text，legalEnglish text。',
    'English textcompensationEnglish text，English text。',
    'English text、English textrelatedEnglish text101100English text；English text、English text。',
    'English text', 'English textcompensation,N,English text,English text'),

  ('dis_case_033', '(2021)English text9032English text21184English text', 'English textcompanyEnglish textlaborEnglish text', 'court_sh_pudong', 'labordispute', 'English textlaborEnglish text', '2021-04-15',
    'English text：English text（English text）；English text：English textcompany',
    'English text，courtrulingEnglish textsalaryshortfall。',
    'English text2014English textengineer，English textsalary17200English text。English text，courtrulingEnglish textsalaryshortfall。relatedEnglish text。',
    'basisLabor Contract LawEnglish textLabor LawrelatedEnglish text，English textlaborEnglish textlegalEnglish text，English textfactsEnglish text，legalEnglish text。',
    'English textlaborEnglish text，English text。',
    'English text、English textrelatedEnglish text120400English text；English text、English text。',
    'English text', 'English textlaborEnglish text,English textsalary,English text'),

  ('dis_case_034', '(2021)English text9033English text21221English text', 'English textcompanyEnglish textlaborEnglish text', 'court_sh_minhang', 'labordispute', 'English textlaborEnglish text', '2021-03-22',
    'English text：English text（English text）；English text：English textcompany',
    'companyEnglish textsalary，English text，courtEnglish text。',
    'English text2013English text，English textsalary17550English text。companyEnglish textsalary，English text，courtEnglish text。relatedEnglish text。',
    'basisLabor Contract LawEnglish textLabor LawrelatedEnglish text，English textlaborEnglish textlegalEnglish text，English textfactsEnglish text，legalEnglish text。',
    'English textlaborEnglish text，English text。',
    'English text、English textrelatedEnglish text140400English text；English text、English text。',
    'English text', 'English textsalary,English text,English text'),

  ('dis_case_035', '(2021)English text9034English text21258English text', 'English textcompanynon-competeEnglish text', 'court_bj_chaoyang', 'labordispute', 'non-compete', '2021-02-01',
    'English text：English text（English text）；English text：English textcompany',
    'English textnon-competeEnglish textcompensation，English textcompensationEnglish text，courtEnglish text。',
    'English text2012English text，English textsalary17900English text。English textnon-competeEnglish textcompensation，English textcompensationEnglish text，courtEnglish text。relatedEnglish text。',
    'basisLabor Contract LawEnglish textLabor LawrelatedEnglish text，English textnon-competeEnglish textlegalEnglish text，English textfactsEnglish text，legalEnglish text。',
    'English textnon-competeEnglish text，English text。',
    'English text、English textrelatedEnglish text161100English text；English text、English text。',
    'English text', 'non-compete,compensationEnglish text,departure'),

  ('dis_case_036', '(2021)English text9035English text21295English text', 'English textcompanyunlawful terminationlaborEnglish text', 'dis_court_sh_xuhui', 'labordispute', 'unlawful terminationlaborEnglish text', '2021-01-08',
    'English text：English text（English text）；English text：English textcompany',
    'companyEnglish text，courtEnglish textunlawful terminationEnglish text。',
    'English text2011English text，English textsalary18250English text。companyEnglish text，courtEnglish textunlawful terminationEnglish text。relatedEnglish text。',
    'basisLabor Contract LawEnglish textLabor LawrelatedEnglish text，English textunlawful terminationlaborEnglish textlegalEnglish text，English textfactsEnglish text，legalEnglish text。',
    'English textunlawful terminationlaborEnglish text，English text。',
    'English text、English textrelatedEnglish text182500English text；English text、English text。',
    'English text', 'unlawful termination,English text,English text'),

  ('dis_case_037', '(2020)English text9036English text21332English text', 'English textdiningcompanyEnglish text', 'dis_court_sh_jingan', 'labordispute', 'English text', '2020-12-15',
    'English text：English text（English text）；English text：English textdiningcompany',
    'English text，courtrulingEnglish textsalary。',
    'English text2018English text，English textsalary18600English text。English text，courtrulingEnglish textsalary。relatedEnglish text。',
    'basisLabor Contract LawEnglish textLabor LawrelatedEnglish text，English textlegalEnglish text，English textfactsEnglish text，legalEnglish text。',
    'English text，English text。',
    'English text、English textrelatedEnglish text37200English text；English text、English text。',
    'English text', 'English text,English textsalary,English text'),

  ('dis_case_038', '(2020)English text9037English text21369English text', 'English textcompanyEnglish text', 'dis_court_bj_haidian', 'labordispute', 'English text', '2020-11-22',
    'English text：English text（English text）；English text：English textcompany',
    'companyEnglish text，English textcompensation。',
    'English text2017English textassistant，English textsalary18950English text。companyEnglish text，English textcompensation。relatedEnglish text。',
    'basisLabor Contract LawEnglish textLabor LawrelatedEnglish text，English textlegalEnglish text，English textfactsEnglish text，legalEnglish text。',
    'English text，English text。',
    'English text、English textrelatedEnglish text56850English text；English text、English text。',
    'English text', 'English text,English text,English text,English text'),

  ('dis_case_039', '(2020)English text9038English text21406English text', 'English textcompanyEnglish text', 'dis_arb_bj_chaoyang', 'labordispute', 'English text', '2020-10-01',
    'English text：English text（English text）；English text：English textcompany',
    'English textcompanyEnglish textsalary，courtrulingEnglish text。',
    'English text2016English textdataEnglish text，English textsalary19300English text。English textcompanyEnglish textsalary，courtrulingEnglish text。relatedEnglish text。',
    'basisLabor Contract LawEnglish textLabor LawrelatedEnglish text，English textlegalEnglish text，English textfactsEnglish text，legalEnglish text。',
    'English text，English text。',
    'English text、English textrelatedEnglish text77200English text；English text、English text。',
    'English text', 'English text,English text,salary'),

  ('dis_case_040', '(2020)English text9039English text21443English text', 'English textcompanylaborarbitrationEnglish text', 'court_sh_pudong', 'laborarbitration', 'laborarbitration', '2020-09-08',
    'English text：English text（English text）；English text：English textcompany',
    'English textarbitrationEnglish text，companyEnglish textcompensation。',
    'English text2015English text，English textsalary19650English text。English textarbitrationEnglish text，companyEnglish textcompensation。relatedEnglish text。',
    'basisLabor Contract LawEnglish textLabor LawrelatedEnglish text，English textlaborarbitrationEnglish textlegalEnglish text，English textfactsEnglish text，legalEnglish text。',
    'English textlaborarbitrationEnglish text，English text。',
    'English text、English textrelatedEnglish text98250English text；English text、English text。',
    'English text', 'laborarbitration,English text,English textcompensation'),

  ('dis_case_041', '(2020)English text9040English text21480English text', 'English textcompanyovertime payEnglish text', 'court_sh_minhang', 'labordispute', 'overtime pay', '2020-08-15',
    'English text：English text（English text）；English text：English textcompany',
    'English textcompanyEnglish textovertime pay，courtEnglish textrulingEnglish text。',
    'English text2014English text，English textsalary20000English text。English textcompanyEnglish textovertime pay，courtEnglish textrulingEnglish text。relatedEnglish text。',
    'basisLabor Contract LawEnglish textLabor LawrelatedEnglish text，English textovertime payEnglish textlegalEnglish text，English textfactsEnglish text，legalEnglish text。',
    'English textovertime payEnglish text，English text。',
    'English text、English textrelatedEnglish text120000English text；English text、English text。',
    'English text', 'overtime pay,English text,English text,English text'),

  ('dis_case_042', '(2020)English text9041English text21517English text', 'English textcompanyEnglish textcompensationEnglish text', 'court_bj_chaoyang', 'labordispute', 'English textcompensation', '2020-07-22',
    'English text：English text（English text）；English text：English textcompany',
    'companyEnglish textlaborEnglish text，courtrulingEnglish textcompensation。',
    'English text2013English textUIEnglish text，English textsalary20350English text。companyEnglish textlaborEnglish text，courtrulingEnglish textcompensation。relatedEnglish text。',
    'basisLabor Contract LawEnglish textLabor LawrelatedEnglish text，English textcompensationEnglish textlegalEnglish text，English textfactsEnglish text，legalEnglish text。',
    'English textcompensationEnglish text，English text。',
    'English text、English textrelatedEnglish text142450English text；English text、English text。',
    'English text', 'English textcompensation,N,English text,English text'),

  ('dis_case_043', '(2020)English text9042English text21554English text', 'English textcompanyEnglish textlaborEnglish text', 'dis_court_sh_xuhui', 'labordispute', 'English textlaborEnglish text', '2020-06-01',
    'English text：English text（English text）；English text：English textcompany',
    'English text，courtrulingEnglish textsalaryshortfall。',
    'English text2012English textengineer，English textsalary20700English text。English text，courtrulingEnglish textsalaryshortfall。relatedEnglish text。',
    'basisLabor Contract LawEnglish textLabor LawrelatedEnglish text，English textlaborEnglish textlegalEnglish text，English textfactsEnglish text，legalEnglish text。',
    'English textlaborEnglish text，English text。',
    'English text、English textrelatedEnglish text165600English text；English text、English text。',
    'English text', 'English textlaborEnglish text,English textsalary,English text'),

  ('dis_case_044', '(2020)English text9043English text21591English text', 'English textcompanyEnglish textlaborEnglish text', 'dis_court_sh_jingan', 'labordispute', 'English textlaborEnglish text', '2020-05-08',
    'English text：English text（English text）；English text：English textcompany',
    'companyEnglish textsalary，English text，courtEnglish text。',
    'English text2011English text，English textsalary21050English text。companyEnglish textsalary，English text，courtEnglish text。relatedEnglish text。',
    'basisLabor Contract LawEnglish textLabor LawrelatedEnglish text，English textlaborEnglish textlegalEnglish text，English textfactsEnglish text，legalEnglish text。',
    'English textlaborEnglish text，English text。',
    'English text、English textrelatedEnglish text189450English text；English text、English text。',
    'English text', 'English textsalary,English text,English text'),

  ('dis_case_045', '(2020)English text9044English text21628English text', 'English textcompanynon-competeEnglish text', 'dis_court_bj_haidian', 'labordispute', 'non-compete', '2020-04-15',
    'English text：English text（English text）；English text：English textcompany',
    'English textnon-competeEnglish textcompensation，English textcompensationEnglish text，courtEnglish text。',
    'English text2010English text，English textsalary21400English text。English textnon-competeEnglish textcompensation，English textcompensationEnglish text，courtEnglish text。relatedEnglish text。',
    'basisLabor Contract LawEnglish textLabor LawrelatedEnglish text，English textnon-competeEnglish textlegalEnglish text，English textfactsEnglish text，legalEnglish text。',
    'English textnon-competeEnglish text，English text。',
    'English text、English textrelatedEnglish text214000English text；English text、English text。',
    'English text', 'non-compete,compensationEnglish text,departure'),

  ('dis_case_046', '(2020)English text9045English text21665English text', 'English textcompanyunlawful terminationlaborEnglish text', 'dis_arb_bj_chaoyang', 'labordispute', 'unlawful terminationlaborEnglish text', '2020-03-22',
    'English text：English text（English text）；English text：English textcompany',
    'companyEnglish text，courtEnglish textunlawful terminationEnglish text。',
    'English text2018English text，English textsalary21750English text。companyEnglish text，courtEnglish textunlawful terminationEnglish text。relatedEnglish text。',
    'basisLabor Contract LawEnglish textLabor LawrelatedEnglish text，English textunlawful terminationlaborEnglish textlegalEnglish text，English textfactsEnglish text，legalEnglish text。',
    'English textunlawful terminationlaborEnglish text，English text。',
    'English text、English textrelatedEnglish text43500English text；English text、English text。',
    'English text', 'unlawful termination,English text,English text'),

  ('dis_case_047', '(2020)English text9046English text21702English text', 'English textdiningcompanyEnglish text', 'court_sh_pudong', 'labordispute', 'English text', '2020-02-01',
    'English text：English text（English text）；English text：English textdiningcompany',
    'English text，courtrulingEnglish textsalary。',
    'English text2017English text，English textsalary22100English text。English text，courtrulingEnglish textsalary。relatedEnglish text。',
    'basisLabor Contract LawEnglish textLabor LawrelatedEnglish text，English textlegalEnglish text，English textfactsEnglish text，legalEnglish text。',
    'English text，English text。',
    'English text、English textrelatedEnglish text66300English text；English text、English text。',
    'English text', 'English text,English textsalary,English text'),

  ('dis_case_048', '(2020)English text9047English text21739English text', 'English textcompanyEnglish text', 'court_sh_minhang', 'labordispute', 'English text', '2020-01-08',
    'English text：English text（English text）；English text：English textcompany',
    'companyEnglish text，English textcompensation。',
    'English text2016English textengineer，English textsalary22450English text。companyEnglish text，English textcompensation。relatedEnglish text。',
    'basisLabor Contract LawEnglish textLabor LawrelatedEnglish text，English textlegalEnglish text，English textfactsEnglish text，legalEnglish text。',
    'English text，English text。',
    'English text、English textrelatedEnglish text89800English text；English text、English text。',
    'English text', 'English text,English text,English text,English text'),

  ('dis_case_049', '(2019)English text9048English text21776English text', 'English textcompanyEnglish text', 'court_bj_chaoyang', 'labordispute', 'English text', '2019-12-15',
    'English text：English text（English text）；English text：English textcompany',
    'English textcompanyEnglish textsalary，courtrulingEnglish text。',
    'English text2014English text，English textsalary22800English text。English textcompanyEnglish textsalary，courtrulingEnglish text。relatedEnglish text。',
    'basisLabor Contract LawEnglish textLabor LawrelatedEnglish text，English textlegalEnglish text，English textfactsEnglish text，legalEnglish text。',
    'English text，English text。',
    'English text、English textrelatedEnglish text114000English text；English text、English text。',
    'English text', 'English text,English text,salary'),

  ('dis_case_050', '(2019)English text9049English text21813English text', 'English textcompanylaborarbitrationEnglish text', 'dis_court_sh_xuhui', 'laborarbitration', 'laborarbitration', '2019-11-22',
    'English text：English text（English text）；English text：English textcompany',
    'English textarbitrationEnglish text，companyEnglish textcompensation。',
    'English text2013English text，English textsalary23150English text。English textarbitrationEnglish text，companyEnglish textcompensation。relatedEnglish text。',
    'basisLabor Contract LawEnglish textLabor LawrelatedEnglish text，English textlaborarbitrationEnglish textlegalEnglish text，English textfactsEnglish text，legalEnglish text。',
    'English textlaborarbitrationEnglish text，English text。',
    'English text、English textrelatedEnglish text138900English text；English text、English text。',
    'English text', 'laborarbitration,English text,English textcompensation'),

  ('dis_case_051', '(2019)English text9050English text21850English text', 'English textcompanyovertime payEnglish text', 'dis_court_sh_jingan', 'labordispute', 'overtime pay', '2019-10-01',
    'English text：English text（English text）；English text：English textcompany',
    'English textcompanyEnglish textovertime pay，courtEnglish textrulingEnglish text。',
    'English text2012English text，English textsalary23500English text。English textcompanyEnglish textovertime pay，courtEnglish textrulingEnglish text。relatedEnglish text。',
    'basisLabor Contract LawEnglish textLabor LawrelatedEnglish text，English textovertime payEnglish textlegalEnglish text，English textfactsEnglish text，legalEnglish text。',
    'English textovertime payEnglish text，English text。',
    'English text、English textrelatedEnglish text164500English text；English text、English text。',
    'English text', 'overtime pay,English text,English text,English text'),

  ('dis_case_052', '(2019)English text9051English text21887English text', 'English textcompanyEnglish textcompensationEnglish text', 'dis_court_bj_haidian', 'labordispute', 'English textcompensation', '2019-09-08',
    'English text：English text（English text）；English text：English textcompany',
    'companyEnglish textlaborEnglish text，courtrulingEnglish textcompensation。',
    'English text2011English text，English textsalary23850English text。companyEnglish textlaborEnglish text，courtrulingEnglish textcompensation。relatedEnglish text。',
    'basisLabor Contract LawEnglish textLabor LawrelatedEnglish text，English textcompensationEnglish textlegalEnglish text，English textfactsEnglish text，legalEnglish text。',
    'English textcompensationEnglish text，English text。',
    'English text、English textrelatedEnglish text190800English text；English text、English text。',
    'English text', 'English textcompensation,N,English text,English text'),

  ('dis_case_053', '(2019)English text9052English text21924English text', 'English textcompanyEnglish textlaborEnglish text', 'dis_arb_bj_chaoyang', 'labordispute', 'English textlaborEnglish text', '2019-08-15',
    'English text：English text（English text）；English text：English textcompany',
    'English text，courtrulingEnglish textsalaryshortfall。',
    'English text2010English textassistant，English textsalary24200English text。English text，courtrulingEnglish textsalaryshortfall。relatedEnglish text。',
    'basisLabor Contract LawEnglish textLabor LawrelatedEnglish text，English textlaborEnglish textlegalEnglish text，English textfactsEnglish text，legalEnglish text。',
    'English textlaborEnglish text，English text。',
    'English text、English textrelatedEnglish text217800English text；English text、English text。',
    'English text', 'English textlaborEnglish text,English textsalary,English text'),

  ('dis_case_054', '(2019)English text9053English text21961English text', 'English textcompanyEnglish textlaborEnglish text', 'court_sh_pudong', 'labordispute', 'English textlaborEnglish text', '2019-07-22',
    'English text：English text（English text）；English text：English textcompany',
    'companyEnglish textsalary，English text，courtEnglish text。',
    'English text2009English textdataEnglish text，English textsalary24550English text。companyEnglish textsalary，English text，courtEnglish text。relatedEnglish text。',
    'basisLabor Contract LawEnglish textLabor LawrelatedEnglish text，English textlaborEnglish textlegalEnglish text，English textfactsEnglish text，legalEnglish text。',
    'English textlaborEnglish text，English text。',
    'English text、English textrelatedEnglish text245500English text；English text、English text。',
    'English text', 'English textsalary,English text,English text'),

  ('dis_case_055', '(2019)English text9054English text21998English text', 'English textcompanynon-competeEnglish text', 'court_sh_minhang', 'labordispute', 'non-compete', '2019-06-01',
    'English text：English text（English text）；English text：English textcompany',
    'English textnon-competeEnglish textcompensation，English textcompensationEnglish text，courtEnglish text。',
    'English text2017English text，English textsalary24900English text。English textnon-competeEnglish textcompensation，English textcompensationEnglish text，courtEnglish text。relatedEnglish text。',
    'basisLabor Contract LawEnglish textLabor LawrelatedEnglish text，English textnon-competeEnglish textlegalEnglish text，English textfactsEnglish text，legalEnglish text。',
    'English textnon-competeEnglish text，English text。',
    'English text、English textrelatedEnglish text49800English text；English text、English text。',
    'English text', 'non-compete,compensationEnglish text,departure');

-- ══ Distractor citations (dis_*) ══
INSERT INTO citations (citation_id, case_id, target_type, target_id, label) VALUES
  ('dis_cit_0001', 'dis_case_001', 'article', 'art_lcl_040', 'English text'),
  ('dis_cit_0002', 'dis_case_001', 'article', 'art_lcl_048', 'English text'),
  ('dis_cit_0003', 'dis_case_002', 'article', 'art_lcl_046', 'English text'),
  ('dis_cit_0004', 'dis_case_003', 'article', 'art_lcl_047', 'English text'),
  ('dis_cit_0005', 'dis_case_003', 'article', 'art_lcl_087', 'English text'),
  ('dis_cit_0006', 'dis_case_004', 'article', 'art_lcl_048', 'English text'),
  ('dis_cit_0007', 'dis_case_005', 'article', 'art_lcl_082', 'English text'),
  ('dis_cit_0008', 'dis_case_005', 'article', 'art_lcl_039', 'English text'),
  ('dis_cit_0009', 'dis_case_006', 'article', 'art_lcl_087', 'English text'),
  ('dis_cit_0010', 'dis_case_007', 'article', 'art_lcl_038', 'English text'),
  ('dis_cit_0011', 'dis_case_007', 'article', 'art_ll_050', 'English text'),
  ('dis_cit_0012', 'dis_case_008', 'article', 'art_lcl_039', 'English text'),
  ('dis_cit_0013', 'dis_case_009', 'article', 'art_ll_044', 'English text'),
  ('dis_cit_0014', 'dis_case_009', 'article', 'art_lcl_010', 'English text'),
  ('dis_cit_0015', 'dis_case_010', 'article', 'art_ll_050', 'English text'),
  ('dis_cit_0016', 'dis_case_011', 'article', 'art_ll_036', 'English text'),
  ('dis_cit_0017', 'dis_case_011', 'article', 'art_lcl_046', 'English text'),
  ('dis_cit_0018', 'dis_case_012', 'article', 'art_lcl_010', 'English text'),
  ('dis_cit_0019', 'dis_case_013', 'article', 'art_lcl_040', 'English text'),
  ('dis_cit_0020', 'dis_case_013', 'article', 'art_lcl_048', 'English text'),
  ('dis_cit_0021', 'dis_case_014', 'article', 'art_lcl_046', 'English text'),
  ('dis_cit_0022', 'dis_case_015', 'article', 'art_lcl_047', 'English text'),
  ('dis_cit_0023', 'dis_case_015', 'article', 'art_lcl_087', 'English text'),
  ('dis_cit_0024', 'dis_case_016', 'article', 'art_lcl_048', 'English text'),
  ('dis_cit_0025', 'dis_case_017', 'article', 'art_lcl_082', 'English text'),
  ('dis_cit_0026', 'dis_case_017', 'article', 'art_lcl_039', 'English text'),
  ('dis_cit_0027', 'dis_case_018', 'article', 'art_lcl_087', 'English text'),
  ('dis_cit_0028', 'dis_case_019', 'article', 'art_lcl_038', 'English text'),
  ('dis_cit_0029', 'dis_case_019', 'article', 'art_ll_050', 'English text'),
  ('dis_cit_0030', 'dis_case_020', 'article', 'art_lcl_039', 'English text'),
  ('dis_cit_0031', 'dis_case_021', 'article', 'art_ll_044', 'English text'),
  ('dis_cit_0032', 'dis_case_021', 'article', 'art_lcl_010', 'English text'),
  ('dis_cit_0033', 'dis_case_022', 'article', 'art_ll_050', 'English text'),
  ('dis_cit_0034', 'dis_case_023', 'article', 'art_ll_036', 'English text'),
  ('dis_cit_0035', 'dis_case_023', 'article', 'art_lcl_046', 'English text'),
  ('dis_cit_0036', 'dis_case_024', 'article', 'art_lcl_010', 'English text'),
  ('dis_cit_0037', 'dis_case_025', 'article', 'art_lcl_040', 'English text'),
  ('dis_cit_0038', 'dis_case_025', 'article', 'art_lcl_048', 'English text'),
  ('dis_cit_0039', 'dis_case_026', 'article', 'art_lcl_046', 'English text'),
  ('dis_cit_0040', 'dis_case_027', 'article', 'art_lcl_047', 'English text'),
  ('dis_cit_0041', 'dis_case_027', 'article', 'art_lcl_087', 'English text'),
  ('dis_cit_0042', 'dis_case_028', 'article', 'art_lcl_048', 'English text'),
  ('dis_cit_0043', 'dis_case_029', 'article', 'art_lcl_082', 'English text'),
  ('dis_cit_0044', 'dis_case_029', 'article', 'art_lcl_039', 'English text'),
  ('dis_cit_0045', 'dis_case_030', 'article', 'art_lcl_087', 'English text'),
  ('dis_cit_0046', 'dis_case_031', 'article', 'art_lcl_038', 'English text'),
  ('dis_cit_0047', 'dis_case_031', 'article', 'art_ll_050', 'English text'),
  ('dis_cit_0048', 'dis_case_032', 'article', 'art_lcl_039', 'English text'),
  ('dis_cit_0049', 'dis_case_033', 'article', 'art_ll_044', 'English text'),
  ('dis_cit_0050', 'dis_case_033', 'article', 'art_lcl_010', 'English text'),
  ('dis_cit_0051', 'dis_case_034', 'article', 'art_ll_050', 'English text'),
  ('dis_cit_0052', 'dis_case_035', 'article', 'art_ll_036', 'English text'),
  ('dis_cit_0053', 'dis_case_035', 'article', 'art_lcl_046', 'English text'),
  ('dis_cit_0054', 'dis_case_036', 'article', 'art_lcl_010', 'English text'),
  ('dis_cit_0055', 'dis_case_037', 'article', 'art_lcl_040', 'English text'),
  ('dis_cit_0056', 'dis_case_037', 'article', 'art_lcl_048', 'English text'),
  ('dis_cit_0057', 'dis_case_038', 'article', 'art_lcl_046', 'English text'),
  ('dis_cit_0058', 'dis_case_039', 'article', 'art_lcl_047', 'English text'),
  ('dis_cit_0059', 'dis_case_039', 'article', 'art_lcl_087', 'English text'),
  ('dis_cit_0060', 'dis_case_040', 'article', 'art_lcl_048', 'English text'),
  ('dis_cit_0061', 'dis_case_041', 'article', 'art_lcl_082', 'English text'),
  ('dis_cit_0062', 'dis_case_041', 'article', 'art_lcl_039', 'English text'),
  ('dis_cit_0063', 'dis_case_042', 'article', 'art_lcl_087', 'English text'),
  ('dis_cit_0064', 'dis_case_043', 'article', 'art_lcl_038', 'English text'),
  ('dis_cit_0065', 'dis_case_043', 'article', 'art_ll_050', 'English text'),
  ('dis_cit_0066', 'dis_case_044', 'article', 'art_lcl_039', 'English text'),
  ('dis_cit_0067', 'dis_case_045', 'article', 'art_ll_044', 'English text'),
  ('dis_cit_0068', 'dis_case_045', 'article', 'art_lcl_010', 'English text'),
  ('dis_cit_0069', 'dis_case_046', 'article', 'art_ll_050', 'English text'),
  ('dis_cit_0070', 'dis_case_047', 'article', 'art_ll_036', 'English text'),
  ('dis_cit_0071', 'dis_case_047', 'article', 'art_lcl_046', 'English text'),
  ('dis_cit_0072', 'dis_case_048', 'article', 'art_lcl_010', 'English text'),
  ('dis_cit_0073', 'dis_case_049', 'article', 'art_lcl_040', 'English text'),
  ('dis_cit_0074', 'dis_case_049', 'article', 'art_lcl_048', 'English text'),
  ('dis_cit_0075', 'dis_case_050', 'article', 'art_lcl_046', 'English text'),
  ('dis_cit_0076', 'dis_case_051', 'article', 'art_lcl_047', 'English text'),
  ('dis_cit_0077', 'dis_case_051', 'article', 'art_lcl_087', 'English text'),
  ('dis_cit_0078', 'dis_case_052', 'article', 'art_lcl_048', 'English text'),
  ('dis_cit_0079', 'dis_case_053', 'article', 'art_lcl_082', 'English text'),
  ('dis_cit_0080', 'dis_case_053', 'article', 'art_lcl_039', 'English text'),
  ('dis_cit_0081', 'dis_case_054', 'article', 'art_lcl_087', 'English text'),
  ('dis_cit_0082', 'dis_case_055', 'article', 'art_lcl_038', 'English text'),
  ('dis_cit_0083', 'dis_case_055', 'article', 'art_ll_050', 'English text');

-- ── Counters (seed so newly-issued IDs don''t collide with seed IDs) ──
INSERT INTO _counters (key, value) VALUES
  ('saved_seq', 2),
  ('citation_seq', 29);

COMMIT;
