PRAGMA foreign_keys = ON;
BEGIN TRANSACTION;

INSERT INTO "users" ("user_id", "name", "avatar_url", "email", "type") VALUES ('user_li_cheng', 'Li Cheng', NULL, 'li.cheng.family@example.cn', 'person');
INSERT INTO "users" ("user_id", "name", "avatar_url", "email", "type") VALUES ('bot_family_rv', 'Family Workspace Assistant', NULL, 'assistant-bot@example.cn', 'bot');

INSERT INTO "workspaces" ("workspace_id", "name", "owner_user_id") VALUES ('pa7hnrh5ae', 'Li Cheng Family Travel', 'user_li_cheng');

INSERT INTO "pages" ("page_id", "parent_type", "parent_id", "title", "archived", "created_time", "last_edited_time", "properties_json", "icon", "cover") VALUES ('pa2ngmdk3x', 'workspace', 'pa7hnrh5ae', '2025 familyfamily travel detail', 0, '2025-01-02T09:00:00Z', '2026-01-03T11:30:00Z', '{"summary":"family travel detail、health、family travel detailfamilytimefamily travel detail。","status":"closed","tags":["family","annual"]}', 'home', NULL);
INSERT INTO "pages" ("page_id", "parent_type", "parent_id", "title", "archived", "created_time", "last_edited_time", "properties_json", "icon", "cover") VALUES ('par6rnemzx', 'workspace', 'pa7hnrh5ae', 'kindergartenpickupfamily travel detail', 0, '2025-02-03T09:00:00Z', '2026-02-06T11:30:00Z', '{"summary":"pickupfamily travel detail；do not storeIdentityfamily travel detail。","status":"active","owner":"Li Cheng"}', 'calendar', NULL);
INSERT INTO "pages" ("page_id", "parent_type", "parent_id", "title", "archived", "created_time", "last_edited_time", "properties_json", "icon", "cover") VALUES ('pazctvimvx', 'workspace', 'pa7hnrh5ae', 'family travel detailreview', 1, '2025-03-04T09:00:00Z', '2026-03-09T11:30:00Z', '{"summary":"family travel detailcancelledfamily travel detail，childsleeping bagfamily travel detail。","status":"archived","trip":"Chongming"}', 'car', NULL);
INSERT INTO "pages" ("page_id", "parent_type", "parent_id", "title", "archived", "created_time", "last_edited_time", "properties_json", "icon", "cover") VALUES ('pacvf7lu5x', 'workspace', 'pa7hnrh5ae', 'familyvehiclefamily travel detailrecord', 0, '2025-04-05T09:00:00Z', '2026-04-12T11:30:00Z', '{"summary":"tiresfamily travel detailbrakesInspectfamily travel detail，family travel detailanchor pointsstatusfamily travel detail。","status":"current"}', 'paw', NULL);
INSERT INTO "pages" ("page_id", "parent_type", "parent_id", "title", "archived", "created_time", "last_edited_time", "properties_json", "icon", "cover") VALUES ('pab23pyyux', 'workspace', 'pa7hnrh5ae', 'pet carefamily travel detail', 0, '2025-05-06T09:00:00Z', '2026-05-15T11:30:00Z', '{"summary":"family travel detail、family travel detail。","status":"draft"}', 'wallet', NULL);
INSERT INTO "pages" ("page_id", "parent_type", "parent_id", "title", "archived", "created_time", "last_edited_time", "properties_json", "icon", "cover") VALUES ('payq3abcax', 'workspace', 'pa7hnrh5ae', 'family travel detailfamilybudgetfamily travel detail', 0, '2025-06-07T09:00:00Z', '2026-06-18T11:30:00Z', '{"summary":"family travel detail、family travel detail、insurancefamily travel detailreservefamily travel detail。","status":"active"}', 'book', NULL);
INSERT INTO "pages" ("page_id", "parent_type", "parent_id", "title", "archived", "created_time", "last_edited_time", "properties_json", "icon", "cover") VALUES ('padd2gyo4i', 'workspace', 'pa7hnrh5ae', 'childoutdoorgearfamily travel detail', 0, '2025-07-08T09:00:00Z', '2026-07-21T11:30:00Z', '{"summary":"family travel detail、sleeping bag、family travel detail。","status":"current"}', 'home', NULL);
INSERT INTO "pages" ("page_id", "parent_type", "parent_id", "title", "archived", "created_time", "last_edited_time", "properties_json", "icon", "cover") VALUES ('pactoteujt', 'workspace', 'pa7hnrh5ae', 'family travel detail', 0, '2025-08-09T09:00:00Z', '2026-08-24T11:30:00Z', '{"summary":"family travel detail、family travel detail。","status":"reference"}', 'calendar', NULL);
INSERT INTO "pages" ("page_id", "parent_type", "parent_id", "title", "archived", "created_time", "last_edited_time", "properties_json", "icon", "cover") VALUES ('pavdtl2eny', 'workspace', 'pa7hnrh5ae', 'family travel detailemergency contact', 0, '2025-09-10T09:00:00Z', '2026-01-27T11:30:00Z', '{"summary":"family travel detail、family travel detail。","status":"active"}', 'car', NULL);
INSERT INTO "pages" ("page_id", "parent_type", "parent_id", "title", "archived", "created_time", "last_edited_time", "properties_json", "icon", "cover") VALUES ('pawtv7gqtx', 'workspace', 'pa7hnrh5ae', 'family travel detailsummary', 0, '2025-10-11T09:00:00Z', '2026-02-05T11:30:00Z', '{"summary":"family travel detailrecordfamily travel detail，do not storepassportfamily travel detail。","status":"restricted"}', 'paw', NULL);
INSERT INTO "pages" ("page_id", "parent_type", "parent_id", "title", "archived", "created_time", "last_edited_time", "properties_json", "icon", "cover") VALUES ('pahd2kzjfj', 'workspace', 'pa7hnrh5ae', 'family travel detailchildfamily travel detail', 0, '2025-11-12T09:00:00Z', '2026-03-08T11:30:00Z', '{"summary":"family travel detail、family travel detail、family travel detail。","status":"reference"}', 'wallet', NULL);
INSERT INTO "pages" ("page_id", "parent_type", "parent_id", "title", "archived", "created_time", "last_edited_time", "properties_json", "icon", "cover") VALUES ('paysksxbjt', 'workspace', 'pa7hnrh5ae', 'family travel detail', 0, '2025-12-13T09:00:00Z', '2026-04-11T11:30:00Z', '{"summary":"family travel detail、family travel detail。","status":"reference"}', 'book', NULL);
INSERT INTO "pages" ("page_id", "parent_type", "parent_id", "title", "archived", "created_time", "last_edited_time", "properties_json", "icon", "cover") VALUES ('paicihj2jf', 'workspace', 'pa7hnrh5ae', 'familyfamily travel detailinsurancefamily travel detail', 0, '2025-01-14T09:00:00Z', '2026-05-14T11:30:00Z', '{"summary":"family travel detail、cancelled、family travel detail、family travel detail。","status":"reference"}', 'home', NULL);
INSERT INTO "pages" ("page_id", "parent_type", "parent_id", "title", "archived", "created_time", "last_edited_time", "properties_json", "icon", "cover") VALUES ('pag2uc4ltm', 'workspace', 'pa7hnrh5ae', 'right-hand drivingfamily travel detail', 0, '2025-02-15T09:00:00Z', '2026-06-17T11:30:00Z', '{"summary":"family travel detail、family travel detail。","status":"learning"}', 'calendar', NULL);
INSERT INTO "pages" ("page_id", "parent_type", "parent_id", "title", "archived", "created_time", "last_edited_time", "properties_json", "icon", "cover") VALUES ('palx35ltre', 'workspace', 'pa7hnrh5ae', 'childfamily travel detailrestraintfamily travel detailrecord', 0, '2025-03-16T09:00:00Z', '2026-07-20T11:30:00Z', '{"summary":"family travel detailheight and weightfamily travel detail，family travel detailreview。","status":"current"}', 'car', NULL);
INSERT INTO "pages" ("page_id", "parent_type", "parent_id", "title", "archived", "created_time", "last_edited_time", "properties_json", "icon", "cover") VALUES ('pap4xjrsfx', 'workspace', 'pa7hnrh5ae', 'Septemberwork handoverfamily travel detail', 0, '2025-04-17T09:00:00Z', '2026-08-23T11:30:00Z', '{"summary":"family travel detail，family travel detail。","status":"draft"}', 'paw', NULL);
INSERT INTO "pages" ("page_id", "parent_type", "parent_id", "title", "archived", "created_time", "last_edited_time", "properties_json", "icon", "cover") VALUES ('paimdlkwen', 'workspace', 'pa7hnrh5ae', 'familyfamily travel detail', 0, '2025-05-18T09:00:00Z', '2026-01-26T11:30:00Z', '{"summary":"family travel detail、childfamily travel detail；family travel detail。","status":"current"}', 'wallet', NULL);
INSERT INTO "pages" ("page_id", "parent_type", "parent_id", "title", "archived", "created_time", "last_edited_time", "properties_json", "icon", "cover") VALUES ('pagvihr2mw', 'workspace', 'pa7hnrh5ae', 'airportfamily travel detailcompare', 0, '2025-06-19T09:00:00Z', '2026-02-04T11:30:00Z', '{"summary":"family travel detail、family travel detailpickupfamily travel detailtimefamily travel detail。","status":"reference"}', 'book', NULL);
INSERT INTO "pages" ("page_id", "parent_type", "parent_id", "title", "archived", "created_time", "last_edited_time", "properties_json", "icon", "cover") VALUES ('pa6ffdudjx', 'workspace', 'pa7hnrh5ae', 'family travel detail', 0, '2025-07-20T09:00:00Z', '2026-03-07T11:30:00Z', '{"summary":"family travel detail、family travel detail、family travel detailreturn to kindergarten。","status":"template"}', 'home', NULL);
INSERT INTO "pages" ("page_id", "parent_type", "parent_id", "title", "archived", "created_time", "last_edited_time", "properties_json", "icon", "cover") VALUES ('pa4zctbusi', 'workspace', 'pa7hnrh5ae', 'familyfamily travel detail 2026-08', 0, '2025-08-21T09:00:00Z', '2026-04-10T11:30:00Z', '{"summary":"family travel detailleave、family travel detailbudgetfamily travel detail，family travel detail。","status":"open"}', 'calendar', NULL);

INSERT INTO "counters" ("key", "value") VALUES ('page_seq', 500);
INSERT INTO "counters" ("key", "value") VALUES ('block_seq', 500);

COMMIT;
