PRAGMA foreign_keys = ON;
BEGIN TRANSACTION;

INSERT INTO "users" ("user_id", "name", "avatar_url", "email", "type") VALUES ('user_li_cheng', 'Li Cheng', NULL, 'li.cheng.family@example.cn', 'person');
INSERT INTO "users" ("user_id", "name", "avatar_url", "email", "type") VALUES ('bot_family_rv', 'Family Workspace Assistant', NULL, 'assistant-bot@example.cn', 'bot');

INSERT INTO "workspaces" ("workspace_id", "name", "owner_user_id") VALUES ('pa7hnrh5ae', 'Li Cheng Family Travel', 'user_li_cheng');

INSERT INTO "pages" ("page_id", "parent_type", "parent_id", "title", "archived", "created_time", "last_edited_time", "properties_json", "icon", "cover") VALUES ('pa2ngmdk3x', 'workspace', 'pa7hnrh5ae', '2025 family annual goals', 0, '2025-01-02T09:00:00Z', '2026-01-03T11:30:00Z', '{"summary":"Annual review of education, health, savings, and family time.","status":"closed","tags":["family","annual"]}', 'home', NULL);
INSERT INTO "pages" ("page_id", "parent_type", "parent_id", "title", "archived", "created_time", "last_edited_time", "properties_json", "icon", "cover") VALUES ('par6rnemzx', 'workspace', 'pa7hnrh5ae', 'Kindergarten pickup contacts', 0, '2025-02-03T09:00:00Z', '2026-02-06T11:30:00Z', '{"summary":"Pickup authorisation names and relationships; identity document numbers are not stored.","status":"active","owner":"Li Cheng"}', 'calendar', NULL);
INSERT INTO "pages" ("page_id", "parent_type", "parent_id", "title", "archived", "created_time", "last_edited_time", "properties_json", "icon", "cover") VALUES ('pazctvimvx', 'workspace', 'pa7hnrh5ae', 'Chongming camping retrospective', 1, '2025-03-04T09:00:00Z', '2026-03-09T11:30:00Z', '{"summary":"The rain cancellation process went smoothly; the child sleeping bag was not warm enough.","status":"archived","trip":"Chongming"}', 'car', NULL);
INSERT INTO "pages" ("page_id", "parent_type", "parent_id", "title", "archived", "created_time", "last_edited_time", "properties_json", "icon", "cover") VALUES ('pacvf7lu5x', 'workspace', 'pa7hnrh5ae', 'Family vehicle service record', 0, '2025-04-05T09:00:00Z', '2026-04-12T11:30:00Z', '{"summary":"Tyre and brake checks are complete and the rear anchor points are in normal condition.","status":"current"}', 'paw', NULL);
INSERT INTO "pages" ("page_id", "parent_type", "parent_id", "title", "archived", "created_time", "last_edited_time", "properties_json", "icon", "cover") VALUES ('pab23pyyux', 'workspace', 'pa7hnrh5ae', 'Pet care handover', 0, '2025-05-06T09:00:00Z', '2026-05-15T11:30:00Z', '{"summary":"Feeding, activity, and the emergency vet contact details.","status":"draft"}', 'wallet', NULL);
INSERT INTO "pages" ("page_id", "parent_type", "parent_id", "title", "archived", "created_time", "last_edited_time", "properties_json", "icon", "cover") VALUES ('payq3abcax', 'workspace', 'pa7hnrh5ae', 'Second-half family budget categories', 0, '2025-06-07T09:00:00Z', '2026-06-18T11:30:00Z', '{"summary":"Education, travel, insurance, and the reserve are tracked separately.","status":"active"}', 'book', NULL);
INSERT INTO "pages" ("page_id", "parent_type", "parent_id", "title", "archived", "created_time", "last_edited_time", "properties_json", "icon", "cover") VALUES ('padd2gyo4i', 'workspace', 'pa7hnrh5ae', 'Child outdoor gear sizes', 0, '2025-07-08T09:00:00Z', '2026-07-21T11:30:00Z', '{"summary":"Current sizes and replacement months for the raincoat, sleeping bag, and hiking shoes.","status":"current"}', 'home', NULL);
INSERT INTO "pages" ("page_id", "parent_type", "parent_id", "title", "archived", "created_time", "last_edited_time", "properties_json", "icon", "cover") VALUES ('pactoteujt', 'workspace', 'pa7hnrh5ae', 'Weekend short trip notes', 0, '2025-08-09T09:00:00Z', '2026-08-24T11:30:00Z', '{"summary":"Transport and rest experience from Suzhou, Hangzhou, and Chongming.","status":"reference"}', 'calendar', NULL);
INSERT INTO "pages" ("page_id", "parent_type", "parent_id", "title", "archived", "created_time", "last_edited_time", "properties_json", "icon", "cover") VALUES ('pavdtl2eny', 'workspace', 'pa7hnrh5ae', 'Home emergency contacts', 0, '2025-09-10T09:00:00Z', '2026-01-27T11:30:00Z', '{"summary":"Ordinary contact details for the property office, relatives, and the vet clinic.","status":"active"}', 'car', NULL);
INSERT INTO "pages" ("page_id", "parent_type", "parent_id", "title", "archived", "created_time", "last_edited_time", "properties_json", "icon", "cover") VALUES ('pawtv7gqtx', 'workspace', 'pa7hnrh5ae', 'Document validity summary', 0, '2025-10-11T09:00:00Z', '2026-02-05T11:30:00Z', '{"summary":"Only expiry months are recorded; passport or document numbers are not stored.","status":"restricted"}', 'paw', NULL);
INSERT INTO "pages" ("page_id", "parent_type", "parent_id", "title", "archived", "created_time", "last_edited_time", "properties_json", "icon", "cover") VALUES ('pahd2kzjfj', 'workspace', 'pa7hnrh5ae', 'Long-haul flight child item checklist', 0, '2025-11-12T09:00:00Z', '2026-03-08T11:30:00Z', '{"summary":"Ear pressure relief, spare clothes, snacks, and a comfort toy.","status":"reference"}', 'wallet', NULL);
INSERT INTO "pages" ("page_id", "parent_type", "parent_id", "title", "archived", "created_time", "last_edited_time", "properties_json", "icon", "cover") VALUES ('paysksxbjt', 'workspace', 'pa7hnrh5ae', 'New Zealand self-drive sharing notes', 0, '2025-12-13T09:00:00Z', '2026-04-11T11:30:00Z', '{"summary":"A colleague mentioned driving on the left, rural fuel stops, and mountain road weather.","status":"reference"}', 'book', NULL);
INSERT INTO "pages" ("page_id", "parent_type", "parent_id", "title", "archived", "created_time", "last_edited_time", "properties_json", "icon", "cover") VALUES ('paicihj2jf', 'workspace', 'pa7hnrh5ae', 'Family travel insurance terminology', 0, '2025-01-14T09:00:00Z', '2026-05-14T11:30:00Z', '{"summary":"Common definitions for medical, cancellation, interruption, excess, and assistance.","status":"reference"}', 'home', NULL);
INSERT INTO "pages" ("page_id", "parent_type", "parent_id", "title", "archived", "created_time", "last_edited_time", "properties_json", "icon", "cover") VALUES ('pag2uc4ltm', 'workspace', 'pa7hnrh5ae', 'Right-hand-drive course notes', 0, '2025-02-15T09:00:00Z', '2026-06-17T11:30:00Z', '{"summary":"Mirror positions, roundabout direction, and lane-centring practice.","status":"learning"}', 'calendar', NULL);
INSERT INTO "pages" ("page_id", "parent_type", "parent_id", "title", "archived", "created_time", "last_edited_time", "properties_json", "icon", "cover") VALUES ('palx35ltre', 'workspace', 'pa7hnrh5ae', 'Child restraint growth record', 0, '2025-03-16T09:00:00Z', '2026-07-20T11:30:00Z', '{"summary":"Shoulder straps are adjusted by height and weight and the installation is checked by a professional.","status":"current"}', 'car', NULL);
INSERT INTO "pages" ("page_id", "parent_type", "parent_id", "title", "archived", "created_time", "last_edited_time", "properties_json", "icon", "cover") VALUES ('pap4xjrsfx', 'workspace', 'pa7hnrh5ae', 'September work handover draft', 0, '2025-04-17T09:00:00Z', '2026-08-23T11:30:00Z', '{"summary":"List the project deputy and the emergency escalation contact; the roster is not published yet.","status":"draft"}', 'paw', NULL);
INSERT INTO "pages" ("page_id", "parent_type", "parent_id", "title", "archived", "created_time", "last_edited_time", "properties_json", "icon", "cover") VALUES ('paimdlkwen', 'workspace', 'pa7hnrh5ae', 'Family medicine storage', 0, '2025-05-18T09:00:00Z', '2026-01-26T11:30:00Z', '{"summary":"Sorted into adult, child, and topical; prescriptions stay in the medical system.","status":"current"}', 'wallet', NULL);
INSERT INTO "pages" ("page_id", "parent_type", "parent_id", "title", "archived", "created_time", "last_edited_time", "properties_json", "icon", "cover") VALUES ('pagvihr2mw', 'workspace', 'pa7hnrh5ae', 'Airport transport options comparison', 0, '2025-06-19T09:00:00Z', '2026-02-04T11:30:00Z', '{"summary":"Time and luggage capacity for metro, taxi, and pickup by family or friends.","status":"reference"}', 'book', NULL);
INSERT INTO "pages" ("page_id", "parent_type", "parent_id", "title", "archived", "created_time", "last_edited_time", "properties_json", "icon", "cover") VALUES ('pa6ffdudjx', 'workspace', 'pa7hnrh5ae', 'Post-return recovery checklist', 0, '2025-07-20T09:00:00Z', '2026-03-07T11:30:00Z', '{"summary":"Laundry, jet-lag recovery, pet collection, and the school return.","status":"template"}', 'home', NULL);
INSERT INTO "pages" ("page_id", "parent_type", "parent_id", "title", "archived", "created_time", "last_edited_time", "properties_json", "icon", "cover") VALUES ('pa4zctbusi', 'workspace', 'pa7hnrh5ae', 'Family meeting minutes 2026-08', 0, '2025-08-21T09:00:00Z', '2026-04-10T11:30:00Z', '{"summary":"Discussed leave, the boarding waitlist, and the budget buffer; no travel order has been placed yet.","status":"open"}', 'calendar', NULL);

INSERT INTO "counters" ("key", "value") VALUES ('page_seq', 500);
INSERT INTO "counters" ("key", "value") VALUES ('block_seq', 500);

COMMIT;
