INSERT INTO official_accounts (account_id, name, category, description) VALUES ('acct_gmat_official_003', 'GMAT Focus Official', 'exam', 'Official GMAT notices');
INSERT INTO official_accounts (account_id, name, category, description) VALUES ('acct_mba_r2_monitor_003', 'MBA Round 2 Portal Updates', 'application', 'Official MBA requirement notices');
INSERT INTO official_account_subscriptions (user_id, account_id, subscribed_at) VALUES ('user_lin_che', 'acct_gmat_official_003', '2026-09-01T08:00:00+08:00');
INSERT INTO subscriptions (subscription_id, user_id, source, type, target, condition_json, status, created_at, updated_at) VALUES ('sub_gmat_policy_003', 'user_lin_che', 'official_exam', 'policy_update', 'GMAT Focus rules and seats', '{"window":"2026Q3"}', 'active', '2026-09-01T08:00:00+08:00', '2026-09-01T08:00:00+08:00');
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_gmat_rules_003', 'user_lin_che', 'official_exam', 'policy', 'sub_gmat_policy_003', 'GMAT Focus 2026 Q3 rules published', 'Rules cover identity, payment receipt, official score availability, and score sending after official release.', '{"source_object":"notif_gmat_rules_003"}', '2026-09-01T10:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_mba_projects_003', 'user_lin_che', 'application_portal', 'requirements', 'sub_gmat_policy_003', 'MBA Round 2 project requirements opened', 'Five target projects have deadline, timezone, code and official score policy records.', '{"source_object":"notif_mba_projects_003"}', '2026-09-01T10:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_001', 'user_lin_che', 'application_portal', 'policy', 'sub_gmat_policy_003', 'Background exam preparation update 001', 'Background notification 001 for search and filtering noise.', '{"index":1,"noise":true}', '2026-08-02T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_002', 'user_lin_che', 'prep_vendor', 'event', 'sub_gmat_policy_003', 'Background exam preparation update 002', 'Background notification 002 for search and filtering noise.', '{"index":2,"noise":true}', '2026-08-03T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_003', 'user_lin_che', 'calendar_digest', 'digest', 'sub_gmat_policy_003', 'Background exam preparation update 003', 'Background notification 003 for search and filtering noise.', '{"index":3,"noise":true}', '2026-08-04T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_004', 'user_lin_che', 'official_exam', 'newsletter', 'sub_gmat_policy_003', 'Background exam preparation update 004', 'Background notification 004 for search and filtering noise.', '{"index":4,"noise":true}', '2026-08-05T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_005', 'user_lin_che', 'application_portal', 'policy', 'sub_gmat_policy_003', 'Background exam preparation update 005', 'Background notification 005 for search and filtering noise.', '{"index":5,"noise":true}', '2026-08-06T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_006', 'user_lin_che', 'prep_vendor', 'event', 'sub_gmat_policy_003', 'Background exam preparation update 006', 'Background notification 006 for search and filtering noise.', '{"index":6,"noise":true}', '2026-08-07T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_007', 'user_lin_che', 'calendar_digest', 'digest', 'sub_gmat_policy_003', 'Background exam preparation update 007', 'Background notification 007 for search and filtering noise.', '{"index":7,"noise":true}', '2026-08-08T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_008', 'user_lin_che', 'official_exam', 'newsletter', 'sub_gmat_policy_003', 'Background exam preparation update 008', 'Background notification 008 for search and filtering noise.', '{"index":8,"noise":true}', '2026-08-09T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_009', 'user_lin_che', 'application_portal', 'policy', 'sub_gmat_policy_003', 'Background exam preparation update 009', 'Background notification 009 for search and filtering noise.', '{"index":9,"noise":true}', '2026-08-10T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_010', 'user_lin_che', 'prep_vendor', 'event', 'sub_gmat_policy_003', 'Background exam preparation update 010', 'Background notification 010 for search and filtering noise.', '{"index":10,"noise":true}', '2026-08-11T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_011', 'user_lin_che', 'calendar_digest', 'digest', 'sub_gmat_policy_003', 'Background exam preparation update 011', 'Background notification 011 for search and filtering noise.', '{"index":11,"noise":true}', '2026-08-12T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_012', 'user_lin_che', 'official_exam', 'newsletter', 'sub_gmat_policy_003', 'Background exam preparation update 012', 'Background notification 012 for search and filtering noise.', '{"index":12,"noise":true}', '2026-08-13T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_013', 'user_lin_che', 'application_portal', 'policy', 'sub_gmat_policy_003', 'Background exam preparation update 013', 'Background notification 013 for search and filtering noise.', '{"index":13,"noise":true}', '2026-08-14T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_014', 'user_lin_che', 'prep_vendor', 'event', 'sub_gmat_policy_003', 'Background exam preparation update 014', 'Background notification 014 for search and filtering noise.', '{"index":14,"noise":true}', '2026-08-15T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_015', 'user_lin_che', 'calendar_digest', 'digest', 'sub_gmat_policy_003', 'Background exam preparation update 015', 'Background notification 015 for search and filtering noise.', '{"index":15,"noise":true}', '2026-08-16T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_016', 'user_lin_che', 'official_exam', 'newsletter', 'sub_gmat_policy_003', 'Background exam preparation update 016', 'Background notification 016 for search and filtering noise.', '{"index":16,"noise":true}', '2026-08-17T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_017', 'user_lin_che', 'application_portal', 'policy', 'sub_gmat_policy_003', 'Background exam preparation update 017', 'Background notification 017 for search and filtering noise.', '{"index":17,"noise":true}', '2026-08-18T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_018', 'user_lin_che', 'prep_vendor', 'event', 'sub_gmat_policy_003', 'Background exam preparation update 018', 'Background notification 018 for search and filtering noise.', '{"index":18,"noise":true}', '2026-08-19T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_019', 'user_lin_che', 'calendar_digest', 'digest', 'sub_gmat_policy_003', 'Background exam preparation update 019', 'Background notification 019 for search and filtering noise.', '{"index":19,"noise":true}', '2026-08-20T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_020', 'user_lin_che', 'official_exam', 'newsletter', 'sub_gmat_policy_003', 'Background exam preparation update 020', 'Background notification 020 for search and filtering noise.', '{"index":20,"noise":true}', '2026-08-21T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_021', 'user_lin_che', 'application_portal', 'policy', 'sub_gmat_policy_003', 'Background exam preparation update 021', 'Background notification 021 for search and filtering noise.', '{"index":21,"noise":true}', '2026-08-22T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_022', 'user_lin_che', 'prep_vendor', 'event', 'sub_gmat_policy_003', 'Background exam preparation update 022', 'Background notification 022 for search and filtering noise.', '{"index":22,"noise":true}', '2026-08-23T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_023', 'user_lin_che', 'calendar_digest', 'digest', 'sub_gmat_policy_003', 'Background exam preparation update 023', 'Background notification 023 for search and filtering noise.', '{"index":23,"noise":true}', '2026-08-24T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_024', 'user_lin_che', 'official_exam', 'newsletter', 'sub_gmat_policy_003', 'Background exam preparation update 024', 'Background notification 024 for search and filtering noise.', '{"index":24,"noise":true}', '2026-08-25T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_025', 'user_lin_che', 'application_portal', 'policy', 'sub_gmat_policy_003', 'Background exam preparation update 025', 'Background notification 025 for search and filtering noise.', '{"index":25,"noise":true}', '2026-08-26T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_026', 'user_lin_che', 'prep_vendor', 'event', 'sub_gmat_policy_003', 'Background exam preparation update 026', 'Background notification 026 for search and filtering noise.', '{"index":26,"noise":true}', '2026-08-27T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_027', 'user_lin_che', 'calendar_digest', 'digest', 'sub_gmat_policy_003', 'Background exam preparation update 027', 'Background notification 027 for search and filtering noise.', '{"index":27,"noise":true}', '2026-08-28T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_028', 'user_lin_che', 'official_exam', 'newsletter', 'sub_gmat_policy_003', 'Background exam preparation update 028', 'Background notification 028 for search and filtering noise.', '{"index":28,"noise":true}', '2026-08-01T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_029', 'user_lin_che', 'application_portal', 'policy', 'sub_gmat_policy_003', 'Background exam preparation update 029', 'Background notification 029 for search and filtering noise.', '{"index":29,"noise":true}', '2026-08-02T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_030', 'user_lin_che', 'prep_vendor', 'event', 'sub_gmat_policy_003', 'Background exam preparation update 030', 'Background notification 030 for search and filtering noise.', '{"index":30,"noise":true}', '2026-08-03T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_031', 'user_lin_che', 'calendar_digest', 'digest', 'sub_gmat_policy_003', 'Background exam preparation update 031', 'Background notification 031 for search and filtering noise.', '{"index":31,"noise":true}', '2026-08-04T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_032', 'user_lin_che', 'official_exam', 'newsletter', 'sub_gmat_policy_003', 'Background exam preparation update 032', 'Background notification 032 for search and filtering noise.', '{"index":32,"noise":true}', '2026-08-05T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_033', 'user_lin_che', 'application_portal', 'policy', 'sub_gmat_policy_003', 'Background exam preparation update 033', 'Background notification 033 for search and filtering noise.', '{"index":33,"noise":true}', '2026-08-06T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_034', 'user_lin_che', 'prep_vendor', 'event', 'sub_gmat_policy_003', 'Background exam preparation update 034', 'Background notification 034 for search and filtering noise.', '{"index":34,"noise":true}', '2026-08-07T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_035', 'user_lin_che', 'calendar_digest', 'digest', 'sub_gmat_policy_003', 'Background exam preparation update 035', 'Background notification 035 for search and filtering noise.', '{"index":35,"noise":true}', '2026-08-08T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_036', 'user_lin_che', 'official_exam', 'newsletter', 'sub_gmat_policy_003', 'Background exam preparation update 036', 'Background notification 036 for search and filtering noise.', '{"index":36,"noise":true}', '2026-08-09T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_037', 'user_lin_che', 'application_portal', 'policy', 'sub_gmat_policy_003', 'Background exam preparation update 037', 'Background notification 037 for search and filtering noise.', '{"index":37,"noise":true}', '2026-08-10T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_038', 'user_lin_che', 'prep_vendor', 'event', 'sub_gmat_policy_003', 'Background exam preparation update 038', 'Background notification 038 for search and filtering noise.', '{"index":38,"noise":true}', '2026-08-11T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_039', 'user_lin_che', 'calendar_digest', 'digest', 'sub_gmat_policy_003', 'Background exam preparation update 039', 'Background notification 039 for search and filtering noise.', '{"index":39,"noise":true}', '2026-08-12T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_040', 'user_lin_che', 'official_exam', 'newsletter', 'sub_gmat_policy_003', 'Background exam preparation update 040', 'Background notification 040 for search and filtering noise.', '{"index":40,"noise":true}', '2026-08-13T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_041', 'user_lin_che', 'application_portal', 'policy', 'sub_gmat_policy_003', 'Background exam preparation update 041', 'Background notification 041 for search and filtering noise.', '{"index":41,"noise":true}', '2026-08-14T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_042', 'user_lin_che', 'prep_vendor', 'event', 'sub_gmat_policy_003', 'Background exam preparation update 042', 'Background notification 042 for search and filtering noise.', '{"index":42,"noise":true}', '2026-08-15T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_043', 'user_lin_che', 'calendar_digest', 'digest', 'sub_gmat_policy_003', 'Background exam preparation update 043', 'Background notification 043 for search and filtering noise.', '{"index":43,"noise":true}', '2026-08-16T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_044', 'user_lin_che', 'official_exam', 'newsletter', 'sub_gmat_policy_003', 'Background exam preparation update 044', 'Background notification 044 for search and filtering noise.', '{"index":44,"noise":true}', '2026-08-17T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_045', 'user_lin_che', 'application_portal', 'policy', 'sub_gmat_policy_003', 'Background exam preparation update 045', 'Background notification 045 for search and filtering noise.', '{"index":45,"noise":true}', '2026-08-18T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_046', 'user_lin_che', 'prep_vendor', 'event', 'sub_gmat_policy_003', 'Background exam preparation update 046', 'Background notification 046 for search and filtering noise.', '{"index":46,"noise":true}', '2026-08-19T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_047', 'user_lin_che', 'calendar_digest', 'digest', 'sub_gmat_policy_003', 'Background exam preparation update 047', 'Background notification 047 for search and filtering noise.', '{"index":47,"noise":true}', '2026-08-20T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_048', 'user_lin_che', 'official_exam', 'newsletter', 'sub_gmat_policy_003', 'Background exam preparation update 048', 'Background notification 048 for search and filtering noise.', '{"index":48,"noise":true}', '2026-08-21T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_049', 'user_lin_che', 'application_portal', 'policy', 'sub_gmat_policy_003', 'Background exam preparation update 049', 'Background notification 049 for search and filtering noise.', '{"index":49,"noise":true}', '2026-08-22T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_050', 'user_lin_che', 'prep_vendor', 'event', 'sub_gmat_policy_003', 'Background exam preparation update 050', 'Background notification 050 for search and filtering noise.', '{"index":50,"noise":true}', '2026-08-23T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_051', 'user_lin_che', 'calendar_digest', 'digest', 'sub_gmat_policy_003', 'Background exam preparation update 051', 'Background notification 051 for search and filtering noise.', '{"index":51,"noise":true}', '2026-08-24T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_052', 'user_lin_che', 'official_exam', 'newsletter', 'sub_gmat_policy_003', 'Background exam preparation update 052', 'Background notification 052 for search and filtering noise.', '{"index":52,"noise":true}', '2026-08-25T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_053', 'user_lin_che', 'application_portal', 'policy', 'sub_gmat_policy_003', 'Background exam preparation update 053', 'Background notification 053 for search and filtering noise.', '{"index":53,"noise":true}', '2026-08-26T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_054', 'user_lin_che', 'prep_vendor', 'event', 'sub_gmat_policy_003', 'Background exam preparation update 054', 'Background notification 054 for search and filtering noise.', '{"index":54,"noise":true}', '2026-08-27T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_055', 'user_lin_che', 'calendar_digest', 'digest', 'sub_gmat_policy_003', 'Background exam preparation update 055', 'Background notification 055 for search and filtering noise.', '{"index":55,"noise":true}', '2026-08-28T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_056', 'user_lin_che', 'official_exam', 'newsletter', 'sub_gmat_policy_003', 'Background exam preparation update 056', 'Background notification 056 for search and filtering noise.', '{"index":56,"noise":true}', '2026-08-01T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_057', 'user_lin_che', 'application_portal', 'policy', 'sub_gmat_policy_003', 'Background exam preparation update 057', 'Background notification 057 for search and filtering noise.', '{"index":57,"noise":true}', '2026-08-02T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_058', 'user_lin_che', 'prep_vendor', 'event', 'sub_gmat_policy_003', 'Background exam preparation update 058', 'Background notification 058 for search and filtering noise.', '{"index":58,"noise":true}', '2026-08-03T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_059', 'user_lin_che', 'calendar_digest', 'digest', 'sub_gmat_policy_003', 'Background exam preparation update 059', 'Background notification 059 for search and filtering noise.', '{"index":59,"noise":true}', '2026-08-04T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_060', 'user_lin_che', 'official_exam', 'newsletter', 'sub_gmat_policy_003', 'Background exam preparation update 060', 'Background notification 060 for search and filtering noise.', '{"index":60,"noise":true}', '2026-08-05T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_061', 'user_lin_che', 'application_portal', 'policy', 'sub_gmat_policy_003', 'Background exam preparation update 061', 'Background notification 061 for search and filtering noise.', '{"index":61,"noise":true}', '2026-08-06T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_062', 'user_lin_che', 'prep_vendor', 'event', 'sub_gmat_policy_003', 'Background exam preparation update 062', 'Background notification 062 for search and filtering noise.', '{"index":62,"noise":true}', '2026-08-07T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_063', 'user_lin_che', 'calendar_digest', 'digest', 'sub_gmat_policy_003', 'Background exam preparation update 063', 'Background notification 063 for search and filtering noise.', '{"index":63,"noise":true}', '2026-08-08T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_064', 'user_lin_che', 'official_exam', 'newsletter', 'sub_gmat_policy_003', 'Background exam preparation update 064', 'Background notification 064 for search and filtering noise.', '{"index":64,"noise":true}', '2026-08-09T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_065', 'user_lin_che', 'application_portal', 'policy', 'sub_gmat_policy_003', 'Background exam preparation update 065', 'Background notification 065 for search and filtering noise.', '{"index":65,"noise":true}', '2026-08-10T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_066', 'user_lin_che', 'prep_vendor', 'event', 'sub_gmat_policy_003', 'Background exam preparation update 066', 'Background notification 066 for search and filtering noise.', '{"index":66,"noise":true}', '2026-08-11T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_067', 'user_lin_che', 'calendar_digest', 'digest', 'sub_gmat_policy_003', 'Background exam preparation update 067', 'Background notification 067 for search and filtering noise.', '{"index":67,"noise":true}', '2026-08-12T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_068', 'user_lin_che', 'official_exam', 'newsletter', 'sub_gmat_policy_003', 'Background exam preparation update 068', 'Background notification 068 for search and filtering noise.', '{"index":68,"noise":true}', '2026-08-13T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_069', 'user_lin_che', 'application_portal', 'policy', 'sub_gmat_policy_003', 'Background exam preparation update 069', 'Background notification 069 for search and filtering noise.', '{"index":69,"noise":true}', '2026-08-14T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_070', 'user_lin_che', 'prep_vendor', 'event', 'sub_gmat_policy_003', 'Background exam preparation update 070', 'Background notification 070 for search and filtering noise.', '{"index":70,"noise":true}', '2026-08-15T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_071', 'user_lin_che', 'calendar_digest', 'digest', 'sub_gmat_policy_003', 'Background exam preparation update 071', 'Background notification 071 for search and filtering noise.', '{"index":71,"noise":true}', '2026-08-16T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_072', 'user_lin_che', 'official_exam', 'newsletter', 'sub_gmat_policy_003', 'Background exam preparation update 072', 'Background notification 072 for search and filtering noise.', '{"index":72,"noise":true}', '2026-08-17T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_073', 'user_lin_che', 'application_portal', 'policy', 'sub_gmat_policy_003', 'Background exam preparation update 073', 'Background notification 073 for search and filtering noise.', '{"index":73,"noise":true}', '2026-08-18T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_074', 'user_lin_che', 'prep_vendor', 'event', 'sub_gmat_policy_003', 'Background exam preparation update 074', 'Background notification 074 for search and filtering noise.', '{"index":74,"noise":true}', '2026-08-19T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_075', 'user_lin_che', 'calendar_digest', 'digest', 'sub_gmat_policy_003', 'Background exam preparation update 075', 'Background notification 075 for search and filtering noise.', '{"index":75,"noise":true}', '2026-08-20T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_076', 'user_lin_che', 'official_exam', 'newsletter', 'sub_gmat_policy_003', 'Background exam preparation update 076', 'Background notification 076 for search and filtering noise.', '{"index":76,"noise":true}', '2026-08-21T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_077', 'user_lin_che', 'application_portal', 'policy', 'sub_gmat_policy_003', 'Background exam preparation update 077', 'Background notification 077 for search and filtering noise.', '{"index":77,"noise":true}', '2026-08-22T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_078', 'user_lin_che', 'prep_vendor', 'event', 'sub_gmat_policy_003', 'Background exam preparation update 078', 'Background notification 078 for search and filtering noise.', '{"index":78,"noise":true}', '2026-08-23T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_079', 'user_lin_che', 'calendar_digest', 'digest', 'sub_gmat_policy_003', 'Background exam preparation update 079', 'Background notification 079 for search and filtering noise.', '{"index":79,"noise":true}', '2026-08-24T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_080', 'user_lin_che', 'official_exam', 'newsletter', 'sub_gmat_policy_003', 'Background exam preparation update 080', 'Background notification 080 for search and filtering noise.', '{"index":80,"noise":true}', '2026-08-25T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_081', 'user_lin_che', 'application_portal', 'policy', 'sub_gmat_policy_003', 'Background exam preparation update 081', 'Background notification 081 for search and filtering noise.', '{"index":81,"noise":true}', '2026-08-26T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_082', 'user_lin_che', 'prep_vendor', 'event', 'sub_gmat_policy_003', 'Background exam preparation update 082', 'Background notification 082 for search and filtering noise.', '{"index":82,"noise":true}', '2026-08-27T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_083', 'user_lin_che', 'calendar_digest', 'digest', 'sub_gmat_policy_003', 'Background exam preparation update 083', 'Background notification 083 for search and filtering noise.', '{"index":83,"noise":true}', '2026-08-28T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_084', 'user_lin_che', 'official_exam', 'newsletter', 'sub_gmat_policy_003', 'Background exam preparation update 084', 'Background notification 084 for search and filtering noise.', '{"index":84,"noise":true}', '2026-08-01T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_085', 'user_lin_che', 'application_portal', 'policy', 'sub_gmat_policy_003', 'Background exam preparation update 085', 'Background notification 085 for search and filtering noise.', '{"index":85,"noise":true}', '2026-08-02T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_086', 'user_lin_che', 'prep_vendor', 'event', 'sub_gmat_policy_003', 'Background exam preparation update 086', 'Background notification 086 for search and filtering noise.', '{"index":86,"noise":true}', '2026-08-03T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_087', 'user_lin_che', 'calendar_digest', 'digest', 'sub_gmat_policy_003', 'Background exam preparation update 087', 'Background notification 087 for search and filtering noise.', '{"index":87,"noise":true}', '2026-08-04T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_088', 'user_lin_che', 'official_exam', 'newsletter', 'sub_gmat_policy_003', 'Background exam preparation update 088', 'Background notification 088 for search and filtering noise.', '{"index":88,"noise":true}', '2026-08-05T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_089', 'user_lin_che', 'application_portal', 'policy', 'sub_gmat_policy_003', 'Background exam preparation update 089', 'Background notification 089 for search and filtering noise.', '{"index":89,"noise":true}', '2026-08-06T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_090', 'user_lin_che', 'prep_vendor', 'event', 'sub_gmat_policy_003', 'Background exam preparation update 090', 'Background notification 090 for search and filtering noise.', '{"index":90,"noise":true}', '2026-08-07T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_091', 'user_lin_che', 'calendar_digest', 'digest', 'sub_gmat_policy_003', 'Background exam preparation update 091', 'Background notification 091 for search and filtering noise.', '{"index":91,"noise":true}', '2026-08-08T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_092', 'user_lin_che', 'official_exam', 'newsletter', 'sub_gmat_policy_003', 'Background exam preparation update 092', 'Background notification 092 for search and filtering noise.', '{"index":92,"noise":true}', '2026-08-09T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_093', 'user_lin_che', 'application_portal', 'policy', 'sub_gmat_policy_003', 'Background exam preparation update 093', 'Background notification 093 for search and filtering noise.', '{"index":93,"noise":true}', '2026-08-10T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_094', 'user_lin_che', 'prep_vendor', 'event', 'sub_gmat_policy_003', 'Background exam preparation update 094', 'Background notification 094 for search and filtering noise.', '{"index":94,"noise":true}', '2026-08-11T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_095', 'user_lin_che', 'calendar_digest', 'digest', 'sub_gmat_policy_003', 'Background exam preparation update 095', 'Background notification 095 for search and filtering noise.', '{"index":95,"noise":true}', '2026-08-12T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_096', 'user_lin_che', 'official_exam', 'newsletter', 'sub_gmat_policy_003', 'Background exam preparation update 096', 'Background notification 096 for search and filtering noise.', '{"index":96,"noise":true}', '2026-08-13T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_097', 'user_lin_che', 'application_portal', 'policy', 'sub_gmat_policy_003', 'Background exam preparation update 097', 'Background notification 097 for search and filtering noise.', '{"index":97,"noise":true}', '2026-08-14T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_098', 'user_lin_che', 'prep_vendor', 'event', 'sub_gmat_policy_003', 'Background exam preparation update 098', 'Background notification 098 for search and filtering noise.', '{"index":98,"noise":true}', '2026-08-15T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_099', 'user_lin_che', 'calendar_digest', 'digest', 'sub_gmat_policy_003', 'Background exam preparation update 099', 'Background notification 099 for search and filtering noise.', '{"index":99,"noise":true}', '2026-08-16T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_100', 'user_lin_che', 'official_exam', 'newsletter', 'sub_gmat_policy_003', 'Background exam preparation update 100', 'Background notification 100 for search and filtering noise.', '{"index":100,"noise":true}', '2026-08-17T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_101', 'user_lin_che', 'application_portal', 'policy', 'sub_gmat_policy_003', 'Background exam preparation update 101', 'Background notification 101 for search and filtering noise.', '{"index":101,"noise":true}', '2026-08-18T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_102', 'user_lin_che', 'prep_vendor', 'event', 'sub_gmat_policy_003', 'Background exam preparation update 102', 'Background notification 102 for search and filtering noise.', '{"index":102,"noise":true}', '2026-08-19T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_103', 'user_lin_che', 'calendar_digest', 'digest', 'sub_gmat_policy_003', 'Background exam preparation update 103', 'Background notification 103 for search and filtering noise.', '{"index":103,"noise":true}', '2026-08-20T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_104', 'user_lin_che', 'official_exam', 'newsletter', 'sub_gmat_policy_003', 'Background exam preparation update 104', 'Background notification 104 for search and filtering noise.', '{"index":104,"noise":true}', '2026-08-21T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_105', 'user_lin_che', 'application_portal', 'policy', 'sub_gmat_policy_003', 'Background exam preparation update 105', 'Background notification 105 for search and filtering noise.', '{"index":105,"noise":true}', '2026-08-22T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_106', 'user_lin_che', 'prep_vendor', 'event', 'sub_gmat_policy_003', 'Background exam preparation update 106', 'Background notification 106 for search and filtering noise.', '{"index":106,"noise":true}', '2026-08-23T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_107', 'user_lin_che', 'calendar_digest', 'digest', 'sub_gmat_policy_003', 'Background exam preparation update 107', 'Background notification 107 for search and filtering noise.', '{"index":107,"noise":true}', '2026-08-24T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_108', 'user_lin_che', 'official_exam', 'newsletter', 'sub_gmat_policy_003', 'Background exam preparation update 108', 'Background notification 108 for search and filtering noise.', '{"index":108,"noise":true}', '2026-08-25T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_109', 'user_lin_che', 'application_portal', 'policy', 'sub_gmat_policy_003', 'Background exam preparation update 109', 'Background notification 109 for search and filtering noise.', '{"index":109,"noise":true}', '2026-08-26T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_110', 'user_lin_che', 'prep_vendor', 'event', 'sub_gmat_policy_003', 'Background exam preparation update 110', 'Background notification 110 for search and filtering noise.', '{"index":110,"noise":true}', '2026-08-27T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_111', 'user_lin_che', 'calendar_digest', 'digest', 'sub_gmat_policy_003', 'Background exam preparation update 111', 'Background notification 111 for search and filtering noise.', '{"index":111,"noise":true}', '2026-08-28T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_112', 'user_lin_che', 'official_exam', 'newsletter', 'sub_gmat_policy_003', 'Background exam preparation update 112', 'Background notification 112 for search and filtering noise.', '{"index":112,"noise":true}', '2026-08-01T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_113', 'user_lin_che', 'application_portal', 'policy', 'sub_gmat_policy_003', 'Background exam preparation update 113', 'Background notification 113 for search and filtering noise.', '{"index":113,"noise":true}', '2026-08-02T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_114', 'user_lin_che', 'prep_vendor', 'event', 'sub_gmat_policy_003', 'Background exam preparation update 114', 'Background notification 114 for search and filtering noise.', '{"index":114,"noise":true}', '2026-08-03T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_115', 'user_lin_che', 'calendar_digest', 'digest', 'sub_gmat_policy_003', 'Background exam preparation update 115', 'Background notification 115 for search and filtering noise.', '{"index":115,"noise":true}', '2026-08-04T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_116', 'user_lin_che', 'official_exam', 'newsletter', 'sub_gmat_policy_003', 'Background exam preparation update 116', 'Background notification 116 for search and filtering noise.', '{"index":116,"noise":true}', '2026-08-05T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_117', 'user_lin_che', 'application_portal', 'policy', 'sub_gmat_policy_003', 'Background exam preparation update 117', 'Background notification 117 for search and filtering noise.', '{"index":117,"noise":true}', '2026-08-06T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_118', 'user_lin_che', 'prep_vendor', 'event', 'sub_gmat_policy_003', 'Background exam preparation update 118', 'Background notification 118 for search and filtering noise.', '{"index":118,"noise":true}', '2026-08-07T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_119', 'user_lin_che', 'calendar_digest', 'digest', 'sub_gmat_policy_003', 'Background exam preparation update 119', 'Background notification 119 for search and filtering noise.', '{"index":119,"noise":true}', '2026-08-08T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_120', 'user_lin_che', 'official_exam', 'newsletter', 'sub_gmat_policy_003', 'Background exam preparation update 120', 'Background notification 120 for search and filtering noise.', '{"index":120,"noise":true}', '2026-08-09T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_121', 'user_lin_che', 'application_portal', 'policy', 'sub_gmat_policy_003', 'Background exam preparation update 121', 'Background notification 121 for search and filtering noise.', '{"index":121,"noise":true}', '2026-08-10T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_122', 'user_lin_che', 'prep_vendor', 'event', 'sub_gmat_policy_003', 'Background exam preparation update 122', 'Background notification 122 for search and filtering noise.', '{"index":122,"noise":true}', '2026-08-11T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_123', 'user_lin_che', 'calendar_digest', 'digest', 'sub_gmat_policy_003', 'Background exam preparation update 123', 'Background notification 123 for search and filtering noise.', '{"index":123,"noise":true}', '2026-08-12T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_124', 'user_lin_che', 'official_exam', 'newsletter', 'sub_gmat_policy_003', 'Background exam preparation update 124', 'Background notification 124 for search and filtering noise.', '{"index":124,"noise":true}', '2026-08-13T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_125', 'user_lin_che', 'application_portal', 'policy', 'sub_gmat_policy_003', 'Background exam preparation update 125', 'Background notification 125 for search and filtering noise.', '{"index":125,"noise":true}', '2026-08-14T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_126', 'user_lin_che', 'prep_vendor', 'event', 'sub_gmat_policy_003', 'Background exam preparation update 126', 'Background notification 126 for search and filtering noise.', '{"index":126,"noise":true}', '2026-08-15T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_127', 'user_lin_che', 'calendar_digest', 'digest', 'sub_gmat_policy_003', 'Background exam preparation update 127', 'Background notification 127 for search and filtering noise.', '{"index":127,"noise":true}', '2026-08-16T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_128', 'user_lin_che', 'official_exam', 'newsletter', 'sub_gmat_policy_003', 'Background exam preparation update 128', 'Background notification 128 for search and filtering noise.', '{"index":128,"noise":true}', '2026-08-17T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_129', 'user_lin_che', 'application_portal', 'policy', 'sub_gmat_policy_003', 'Background exam preparation update 129', 'Background notification 129 for search and filtering noise.', '{"index":129,"noise":true}', '2026-08-18T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_130', 'user_lin_che', 'prep_vendor', 'event', 'sub_gmat_policy_003', 'Background exam preparation update 130', 'Background notification 130 for search and filtering noise.', '{"index":130,"noise":true}', '2026-08-19T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_131', 'user_lin_che', 'calendar_digest', 'digest', 'sub_gmat_policy_003', 'Background exam preparation update 131', 'Background notification 131 for search and filtering noise.', '{"index":131,"noise":true}', '2026-08-20T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_132', 'user_lin_che', 'official_exam', 'newsletter', 'sub_gmat_policy_003', 'Background exam preparation update 132', 'Background notification 132 for search and filtering noise.', '{"index":132,"noise":true}', '2026-08-21T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_133', 'user_lin_che', 'application_portal', 'policy', 'sub_gmat_policy_003', 'Background exam preparation update 133', 'Background notification 133 for search and filtering noise.', '{"index":133,"noise":true}', '2026-08-22T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_134', 'user_lin_che', 'prep_vendor', 'event', 'sub_gmat_policy_003', 'Background exam preparation update 134', 'Background notification 134 for search and filtering noise.', '{"index":134,"noise":true}', '2026-08-23T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_135', 'user_lin_che', 'calendar_digest', 'digest', 'sub_gmat_policy_003', 'Background exam preparation update 135', 'Background notification 135 for search and filtering noise.', '{"index":135,"noise":true}', '2026-08-24T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_136', 'user_lin_che', 'official_exam', 'newsletter', 'sub_gmat_policy_003', 'Background exam preparation update 136', 'Background notification 136 for search and filtering noise.', '{"index":136,"noise":true}', '2026-08-25T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_137', 'user_lin_che', 'application_portal', 'policy', 'sub_gmat_policy_003', 'Background exam preparation update 137', 'Background notification 137 for search and filtering noise.', '{"index":137,"noise":true}', '2026-08-26T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_138', 'user_lin_che', 'prep_vendor', 'event', 'sub_gmat_policy_003', 'Background exam preparation update 138', 'Background notification 138 for search and filtering noise.', '{"index":138,"noise":true}', '2026-08-27T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_139', 'user_lin_che', 'calendar_digest', 'digest', 'sub_gmat_policy_003', 'Background exam preparation update 139', 'Background notification 139 for search and filtering noise.', '{"index":139,"noise":true}', '2026-08-28T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_140', 'user_lin_che', 'official_exam', 'newsletter', 'sub_gmat_policy_003', 'Background exam preparation update 140', 'Background notification 140 for search and filtering noise.', '{"index":140,"noise":true}', '2026-08-01T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_141', 'user_lin_che', 'application_portal', 'policy', 'sub_gmat_policy_003', 'Background exam preparation update 141', 'Background notification 141 for search and filtering noise.', '{"index":141,"noise":true}', '2026-08-02T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_142', 'user_lin_che', 'prep_vendor', 'event', 'sub_gmat_policy_003', 'Background exam preparation update 142', 'Background notification 142 for search and filtering noise.', '{"index":142,"noise":true}', '2026-08-03T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_143', 'user_lin_che', 'calendar_digest', 'digest', 'sub_gmat_policy_003', 'Background exam preparation update 143', 'Background notification 143 for search and filtering noise.', '{"index":143,"noise":true}', '2026-08-04T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_144', 'user_lin_che', 'official_exam', 'newsletter', 'sub_gmat_policy_003', 'Background exam preparation update 144', 'Background notification 144 for search and filtering noise.', '{"index":144,"noise":true}', '2026-08-05T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_145', 'user_lin_che', 'application_portal', 'policy', 'sub_gmat_policy_003', 'Background exam preparation update 145', 'Background notification 145 for search and filtering noise.', '{"index":145,"noise":true}', '2026-08-06T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_146', 'user_lin_che', 'prep_vendor', 'event', 'sub_gmat_policy_003', 'Background exam preparation update 146', 'Background notification 146 for search and filtering noise.', '{"index":146,"noise":true}', '2026-08-07T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_147', 'user_lin_che', 'calendar_digest', 'digest', 'sub_gmat_policy_003', 'Background exam preparation update 147', 'Background notification 147 for search and filtering noise.', '{"index":147,"noise":true}', '2026-08-08T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_148', 'user_lin_che', 'official_exam', 'newsletter', 'sub_gmat_policy_003', 'Background exam preparation update 148', 'Background notification 148 for search and filtering noise.', '{"index":148,"noise":true}', '2026-08-09T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_149', 'user_lin_che', 'application_portal', 'policy', 'sub_gmat_policy_003', 'Background exam preparation update 149', 'Background notification 149 for search and filtering noise.', '{"index":149,"noise":true}', '2026-08-10T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_150', 'user_lin_che', 'prep_vendor', 'event', 'sub_gmat_policy_003', 'Background exam preparation update 150', 'Background notification 150 for search and filtering noise.', '{"index":150,"noise":true}', '2026-08-11T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_151', 'user_lin_che', 'calendar_digest', 'digest', 'sub_gmat_policy_003', 'Background exam preparation update 151', 'Background notification 151 for search and filtering noise.', '{"index":151,"noise":true}', '2026-08-12T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_152', 'user_lin_che', 'official_exam', 'newsletter', 'sub_gmat_policy_003', 'Background exam preparation update 152', 'Background notification 152 for search and filtering noise.', '{"index":152,"noise":true}', '2026-08-13T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_153', 'user_lin_che', 'application_portal', 'policy', 'sub_gmat_policy_003', 'Background exam preparation update 153', 'Background notification 153 for search and filtering noise.', '{"index":153,"noise":true}', '2026-08-14T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_154', 'user_lin_che', 'prep_vendor', 'event', 'sub_gmat_policy_003', 'Background exam preparation update 154', 'Background notification 154 for search and filtering noise.', '{"index":154,"noise":true}', '2026-08-15T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_155', 'user_lin_che', 'calendar_digest', 'digest', 'sub_gmat_policy_003', 'Background exam preparation update 155', 'Background notification 155 for search and filtering noise.', '{"index":155,"noise":true}', '2026-08-16T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_156', 'user_lin_che', 'official_exam', 'newsletter', 'sub_gmat_policy_003', 'Background exam preparation update 156', 'Background notification 156 for search and filtering noise.', '{"index":156,"noise":true}', '2026-08-17T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_157', 'user_lin_che', 'application_portal', 'policy', 'sub_gmat_policy_003', 'Background exam preparation update 157', 'Background notification 157 for search and filtering noise.', '{"index":157,"noise":true}', '2026-08-18T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_158', 'user_lin_che', 'prep_vendor', 'event', 'sub_gmat_policy_003', 'Background exam preparation update 158', 'Background notification 158 for search and filtering noise.', '{"index":158,"noise":true}', '2026-08-19T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_159', 'user_lin_che', 'calendar_digest', 'digest', 'sub_gmat_policy_003', 'Background exam preparation update 159', 'Background notification 159 for search and filtering noise.', '{"index":159,"noise":true}', '2026-08-20T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_160', 'user_lin_che', 'official_exam', 'newsletter', 'sub_gmat_policy_003', 'Background exam preparation update 160', 'Background notification 160 for search and filtering noise.', '{"index":160,"noise":true}', '2026-08-21T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_161', 'user_lin_che', 'application_portal', 'policy', 'sub_gmat_policy_003', 'Background exam preparation update 161', 'Background notification 161 for search and filtering noise.', '{"index":161,"noise":true}', '2026-08-22T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_162', 'user_lin_che', 'prep_vendor', 'event', 'sub_gmat_policy_003', 'Background exam preparation update 162', 'Background notification 162 for search and filtering noise.', '{"index":162,"noise":true}', '2026-08-23T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_163', 'user_lin_che', 'calendar_digest', 'digest', 'sub_gmat_policy_003', 'Background exam preparation update 163', 'Background notification 163 for search and filtering noise.', '{"index":163,"noise":true}', '2026-08-24T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_164', 'user_lin_che', 'official_exam', 'newsletter', 'sub_gmat_policy_003', 'Background exam preparation update 164', 'Background notification 164 for search and filtering noise.', '{"index":164,"noise":true}', '2026-08-25T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_165', 'user_lin_che', 'application_portal', 'policy', 'sub_gmat_policy_003', 'Background exam preparation update 165', 'Background notification 165 for search and filtering noise.', '{"index":165,"noise":true}', '2026-08-26T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_166', 'user_lin_che', 'prep_vendor', 'event', 'sub_gmat_policy_003', 'Background exam preparation update 166', 'Background notification 166 for search and filtering noise.', '{"index":166,"noise":true}', '2026-08-27T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_167', 'user_lin_che', 'calendar_digest', 'digest', 'sub_gmat_policy_003', 'Background exam preparation update 167', 'Background notification 167 for search and filtering noise.', '{"index":167,"noise":true}', '2026-08-28T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_168', 'user_lin_che', 'official_exam', 'newsletter', 'sub_gmat_policy_003', 'Background exam preparation update 168', 'Background notification 168 for search and filtering noise.', '{"index":168,"noise":true}', '2026-08-01T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_169', 'user_lin_che', 'application_portal', 'policy', 'sub_gmat_policy_003', 'Background exam preparation update 169', 'Background notification 169 for search and filtering noise.', '{"index":169,"noise":true}', '2026-08-02T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_170', 'user_lin_che', 'prep_vendor', 'event', 'sub_gmat_policy_003', 'Background exam preparation update 170', 'Background notification 170 for search and filtering noise.', '{"index":170,"noise":true}', '2026-08-03T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_171', 'user_lin_che', 'calendar_digest', 'digest', 'sub_gmat_policy_003', 'Background exam preparation update 171', 'Background notification 171 for search and filtering noise.', '{"index":171,"noise":true}', '2026-08-04T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_172', 'user_lin_che', 'official_exam', 'newsletter', 'sub_gmat_policy_003', 'Background exam preparation update 172', 'Background notification 172 for search and filtering noise.', '{"index":172,"noise":true}', '2026-08-05T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_173', 'user_lin_che', 'application_portal', 'policy', 'sub_gmat_policy_003', 'Background exam preparation update 173', 'Background notification 173 for search and filtering noise.', '{"index":173,"noise":true}', '2026-08-06T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_174', 'user_lin_che', 'prep_vendor', 'event', 'sub_gmat_policy_003', 'Background exam preparation update 174', 'Background notification 174 for search and filtering noise.', '{"index":174,"noise":true}', '2026-08-07T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_175', 'user_lin_che', 'calendar_digest', 'digest', 'sub_gmat_policy_003', 'Background exam preparation update 175', 'Background notification 175 for search and filtering noise.', '{"index":175,"noise":true}', '2026-08-08T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_176', 'user_lin_che', 'official_exam', 'newsletter', 'sub_gmat_policy_003', 'Background exam preparation update 176', 'Background notification 176 for search and filtering noise.', '{"index":176,"noise":true}', '2026-08-09T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_177', 'user_lin_che', 'application_portal', 'policy', 'sub_gmat_policy_003', 'Background exam preparation update 177', 'Background notification 177 for search and filtering noise.', '{"index":177,"noise":true}', '2026-08-10T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_178', 'user_lin_che', 'prep_vendor', 'event', 'sub_gmat_policy_003', 'Background exam preparation update 178', 'Background notification 178 for search and filtering noise.', '{"index":178,"noise":true}', '2026-08-11T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_179', 'user_lin_che', 'calendar_digest', 'digest', 'sub_gmat_policy_003', 'Background exam preparation update 179', 'Background notification 179 for search and filtering noise.', '{"index":179,"noise":true}', '2026-08-12T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_180', 'user_lin_che', 'official_exam', 'newsletter', 'sub_gmat_policy_003', 'Background exam preparation update 180', 'Background notification 180 for search and filtering noise.', '{"index":180,"noise":true}', '2026-08-13T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_181', 'user_lin_che', 'application_portal', 'policy', 'sub_gmat_policy_003', 'Background exam preparation update 181', 'Background notification 181 for search and filtering noise.', '{"index":181,"noise":true}', '2026-08-14T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_182', 'user_lin_che', 'prep_vendor', 'event', 'sub_gmat_policy_003', 'Background exam preparation update 182', 'Background notification 182 for search and filtering noise.', '{"index":182,"noise":true}', '2026-08-15T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_183', 'user_lin_che', 'calendar_digest', 'digest', 'sub_gmat_policy_003', 'Background exam preparation update 183', 'Background notification 183 for search and filtering noise.', '{"index":183,"noise":true}', '2026-08-16T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_184', 'user_lin_che', 'official_exam', 'newsletter', 'sub_gmat_policy_003', 'Background exam preparation update 184', 'Background notification 184 for search and filtering noise.', '{"index":184,"noise":true}', '2026-08-17T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_185', 'user_lin_che', 'application_portal', 'policy', 'sub_gmat_policy_003', 'Background exam preparation update 185', 'Background notification 185 for search and filtering noise.', '{"index":185,"noise":true}', '2026-08-18T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_186', 'user_lin_che', 'prep_vendor', 'event', 'sub_gmat_policy_003', 'Background exam preparation update 186', 'Background notification 186 for search and filtering noise.', '{"index":186,"noise":true}', '2026-08-19T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_187', 'user_lin_che', 'calendar_digest', 'digest', 'sub_gmat_policy_003', 'Background exam preparation update 187', 'Background notification 187 for search and filtering noise.', '{"index":187,"noise":true}', '2026-08-20T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_188', 'user_lin_che', 'official_exam', 'newsletter', 'sub_gmat_policy_003', 'Background exam preparation update 188', 'Background notification 188 for search and filtering noise.', '{"index":188,"noise":true}', '2026-08-21T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_189', 'user_lin_che', 'application_portal', 'policy', 'sub_gmat_policy_003', 'Background exam preparation update 189', 'Background notification 189 for search and filtering noise.', '{"index":189,"noise":true}', '2026-08-22T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_190', 'user_lin_che', 'prep_vendor', 'event', 'sub_gmat_policy_003', 'Background exam preparation update 190', 'Background notification 190 for search and filtering noise.', '{"index":190,"noise":true}', '2026-08-23T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_191', 'user_lin_che', 'calendar_digest', 'digest', 'sub_gmat_policy_003', 'Background exam preparation update 191', 'Background notification 191 for search and filtering noise.', '{"index":191,"noise":true}', '2026-08-24T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_192', 'user_lin_che', 'official_exam', 'newsletter', 'sub_gmat_policy_003', 'Background exam preparation update 192', 'Background notification 192 for search and filtering noise.', '{"index":192,"noise":true}', '2026-08-25T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_193', 'user_lin_che', 'application_portal', 'policy', 'sub_gmat_policy_003', 'Background exam preparation update 193', 'Background notification 193 for search and filtering noise.', '{"index":193,"noise":true}', '2026-08-26T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_194', 'user_lin_che', 'prep_vendor', 'event', 'sub_gmat_policy_003', 'Background exam preparation update 194', 'Background notification 194 for search and filtering noise.', '{"index":194,"noise":true}', '2026-08-27T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_195', 'user_lin_che', 'calendar_digest', 'digest', 'sub_gmat_policy_003', 'Background exam preparation update 195', 'Background notification 195 for search and filtering noise.', '{"index":195,"noise":true}', '2026-08-28T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_196', 'user_lin_che', 'official_exam', 'newsletter', 'sub_gmat_policy_003', 'Background exam preparation update 196', 'Background notification 196 for search and filtering noise.', '{"index":196,"noise":true}', '2026-08-01T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_197', 'user_lin_che', 'application_portal', 'policy', 'sub_gmat_policy_003', 'Background exam preparation update 197', 'Background notification 197 for search and filtering noise.', '{"index":197,"noise":true}', '2026-08-02T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_198', 'user_lin_che', 'prep_vendor', 'event', 'sub_gmat_policy_003', 'Background exam preparation update 198', 'Background notification 198 for search and filtering noise.', '{"index":198,"noise":true}', '2026-08-03T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_199', 'user_lin_che', 'calendar_digest', 'digest', 'sub_gmat_policy_003', 'Background exam preparation update 199', 'Background notification 199 for search and filtering noise.', '{"index":199,"noise":true}', '2026-08-04T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_200', 'user_lin_che', 'official_exam', 'newsletter', 'sub_gmat_policy_003', 'Background exam preparation update 200', 'Background notification 200 for search and filtering noise.', '{"index":200,"noise":true}', '2026-08-05T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_201', 'user_lin_che', 'application_portal', 'policy', 'sub_gmat_policy_003', 'Background exam preparation update 201', 'Background notification 201 for search and filtering noise.', '{"index":201,"noise":true}', '2026-08-06T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_202', 'user_lin_che', 'prep_vendor', 'event', 'sub_gmat_policy_003', 'Background exam preparation update 202', 'Background notification 202 for search and filtering noise.', '{"index":202,"noise":true}', '2026-08-07T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_203', 'user_lin_che', 'calendar_digest', 'digest', 'sub_gmat_policy_003', 'Background exam preparation update 203', 'Background notification 203 for search and filtering noise.', '{"index":203,"noise":true}', '2026-08-08T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_204', 'user_lin_che', 'official_exam', 'newsletter', 'sub_gmat_policy_003', 'Background exam preparation update 204', 'Background notification 204 for search and filtering noise.', '{"index":204,"noise":true}', '2026-08-09T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_205', 'user_lin_che', 'application_portal', 'policy', 'sub_gmat_policy_003', 'Background exam preparation update 205', 'Background notification 205 for search and filtering noise.', '{"index":205,"noise":true}', '2026-08-10T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_206', 'user_lin_che', 'prep_vendor', 'event', 'sub_gmat_policy_003', 'Background exam preparation update 206', 'Background notification 206 for search and filtering noise.', '{"index":206,"noise":true}', '2026-08-11T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_207', 'user_lin_che', 'calendar_digest', 'digest', 'sub_gmat_policy_003', 'Background exam preparation update 207', 'Background notification 207 for search and filtering noise.', '{"index":207,"noise":true}', '2026-08-12T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_208', 'user_lin_che', 'official_exam', 'newsletter', 'sub_gmat_policy_003', 'Background exam preparation update 208', 'Background notification 208 for search and filtering noise.', '{"index":208,"noise":true}', '2026-08-13T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_209', 'user_lin_che', 'application_portal', 'policy', 'sub_gmat_policy_003', 'Background exam preparation update 209', 'Background notification 209 for search and filtering noise.', '{"index":209,"noise":true}', '2026-08-14T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_210', 'user_lin_che', 'prep_vendor', 'event', 'sub_gmat_policy_003', 'Background exam preparation update 210', 'Background notification 210 for search and filtering noise.', '{"index":210,"noise":true}', '2026-08-15T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_211', 'user_lin_che', 'calendar_digest', 'digest', 'sub_gmat_policy_003', 'Background exam preparation update 211', 'Background notification 211 for search and filtering noise.', '{"index":211,"noise":true}', '2026-08-16T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_212', 'user_lin_che', 'official_exam', 'newsletter', 'sub_gmat_policy_003', 'Background exam preparation update 212', 'Background notification 212 for search and filtering noise.', '{"index":212,"noise":true}', '2026-08-17T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_213', 'user_lin_che', 'application_portal', 'policy', 'sub_gmat_policy_003', 'Background exam preparation update 213', 'Background notification 213 for search and filtering noise.', '{"index":213,"noise":true}', '2026-08-18T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_214', 'user_lin_che', 'prep_vendor', 'event', 'sub_gmat_policy_003', 'Background exam preparation update 214', 'Background notification 214 for search and filtering noise.', '{"index":214,"noise":true}', '2026-08-19T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_215', 'user_lin_che', 'calendar_digest', 'digest', 'sub_gmat_policy_003', 'Background exam preparation update 215', 'Background notification 215 for search and filtering noise.', '{"index":215,"noise":true}', '2026-08-20T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_216', 'user_lin_che', 'official_exam', 'newsletter', 'sub_gmat_policy_003', 'Background exam preparation update 216', 'Background notification 216 for search and filtering noise.', '{"index":216,"noise":true}', '2026-08-21T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_217', 'user_lin_che', 'application_portal', 'policy', 'sub_gmat_policy_003', 'Background exam preparation update 217', 'Background notification 217 for search and filtering noise.', '{"index":217,"noise":true}', '2026-08-22T09:00:00+08:00', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('notif_background_examprep_218', 'user_lin_che', 'prep_vendor', 'event', 'sub_gmat_policy_003', 'Background exam preparation update 218', 'Background notification 218 for search and filtering noise.', '{"index":218,"noise":true}', '2026-08-23T09:00:00+08:00', 0);
INSERT INTO _counters (key, value) VALUES ('notification_seq', 9000);
INSERT INTO _counters (key, value) VALUES ('subscription_seq', 9000);

-- Handbook v1.14 remediation: make every feed item a distinct, scoped notification.
WITH facts AS (
  SELECT rowid AS rid,
    CASE rowid % 17
      WHEN 0 THEN 'officialEnglish text' WHEN 1 THEN 'English textaccountEnglish textreminder' WHEN 2 THEN 'English text'
      WHEN 3 THEN 'English textpleaseportalEnglish text' WHEN 4 THEN 'English textreportcancheckview' WHEN 5 THEN 'English text'
      WHEN 6 THEN 'clientEnglish textlocationupdate' WHEN 7 THEN 'English texttimechange' WHEN 8 THEN 'studydayEnglish text'
      WHEN 9 THEN 'English textnotification' WHEN 10 THEN 'English textnewEnglish text' WHEN 11 THEN 'English textbudgetEnglish text'
      WHEN 12 THEN 'countEnglish textupdate' WHEN 13 THEN 'English text' WHEN 14 THEN 'English textcheckreminder'
      WHEN 15 THEN 'programEnglish text' ELSE 'English text' END AS event_fact,
    CASE rowid % 19
      WHEN 0 THEN 'noneEnglish text' WHEN 1 THEN 'onlyEnglish text' WHEN 2 THEN 'andEnglish textstatusnoneEnglish text'
      WHEN 3 THEN 'canatEnglish texttimeEnglish text' WHEN 4 THEN 'notEnglish textplease' WHEN 5 THEN 'English textfirstcheckEnglish textrecord'
      WHEN 6 THEN 'retainEnglish text' WHEN 7 THEN 'notEnglish textpayment' WHEN 8 THEN 'English texthasEnglish textdayEnglish text'
      WHEN 9 THEN 'notEnglish textscoreEnglish text' WHEN 10 THEN 'English textaccount' WHEN 11 THEN 'needEnglish texttime zone'
      WHEN 12 THEN 'English textnotcanexternal sharing' WHEN 13 THEN 'historicalversionEnglish textcanEnglish text' WHEN 14 THEN 'statusmayEnglish textafterupdate'
      WHEN 15 THEN 'notneedEnglish text' WHEN 16 THEN 'onlyrecordrisk，notEnglish text' WHEN 17 THEN 'English textaftercanEnglish textread'
      ELSE 'useofficialsubsequentnotificationas authority' END AS scope_fact
  FROM notifications WHERE notification_id LIKE 'notif_background_examprep_%'
)
UPDATE notifications
SET title = (SELECT event_fact FROM facts WHERE facts.rid=notifications.rowid),
    body = CASE rowid % 5
      WHEN 0 THEN (SELECT event_fact || '；' || scope_fact || '。' FROM facts WHERE facts.rid=notifications.rowid)
      WHEN 1 THEN (SELECT 'English textupdate：' || event_fact || '。English textdescription：' || scope_fact || '。' FROM facts WHERE facts.rid=notifications.rowid)
      WHEN 2 THEN (SELECT scope_fact || '；English textitemrecordEnglish text' || event_fact || '。' FROM facts WHERE facts.rid=notifications.rowid)
      WHEN 3 THEN (SELECT 'English text' || event_fact || '，English textas' || scope_fact || '。' FROM facts WHERE facts.rid=notifications.rowid)
      ELSE (SELECT event_fact || 'alreadyenteredEnglish textinEnglish text。' || scope_fact || '。' FROM facts WHERE facts.rid=notifications.rowid)
    END,
    notification_id = replace(notification_id, 'notif_background_examprep_', 'notif_context_examprep_')
WHERE notification_id LIKE 'notif_background_examprep_%';

UPDATE notifications
SET payload_json = json_object('record_kind','context_update','actionable',0,'source',source)
WHERE notification_id LIKE 'notif_context_examprep_%';
