PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
DELETE FROM "saved_cases";
DELETE FROM "citations";
DELETE FROM "statute_articles";
DELETE FROM "cases";
DELETE FROM "statutes";
DELETE FROM "courts";
INSERT INTO "courts" ("court_id","name","level","region") VALUES ('court_sh_minhang','Shanghaitranslated source textMinhangtranslated source text','translated source text','Shanghai');
INSERT INTO "statutes" ("statute_id","name","short_name","issuer","effective_date","status","summary") VALUES ('stat_rent_safety','translated source textleasesafetytranslated source text','leasesafetytranslated source text','translated source text','2025-01-01','translated source text','rentaltranslated source textshouldtranslated source textsafety、translated source textandproperty managementtranslated source text。');
INSERT INTO "cases" ("case_id","case_number","title","court_id","case_type","cause","judgment_date","parties","summary","facts","reasoning","holding","ruling","outcome","keywords") VALUES ('case_hj_leak','(2024)translated source text0112translated source text4312translated source text','translated source textwater seepagetranslated source text','court_sh_minhang','translated source text','translated source textleasetranslated source text','2024-11-18','translated source text、translated source text','before rentalalreadyfoundwater seepage，translated source text。','rentaltranslated source textnotcompletedwater-retention testacceptance inspection。','translated source textrecordandtranslated source textshouldtranslated source textcompletedtranslated source text。','translated source textdefertranslated source text。','translated source textcompletedtranslated source text。','translated source text','water seepage,translated source text,translated source text');
INSERT INTO "cases" ("case_id","case_number","title","court_id","case_type","cause","judgment_date","parties","summary","facts","reasoning","holding","ruling","outcome","keywords") VALUES ('case_hj_air','(2025)translated source text0112translated source text1886translated source text','renovationtranslated source textmove-intranslated source text','court_sh_minhang','translated source text','translated source textleasetranslated source text','2025-05-09','translated source text、translated source text','translated source textrenovationtranslated source textnottranslated source texttestingtranslated source textmove-in。','translated source textreporttranslated source text。','translated source text，translated source textlaboratoryreport。','translated source text daytranslated source text。','translated source text daytranslated source text。','translated source text','air-quality testing,move-intranslated source text,translated source text');
INSERT INTO "cases" ("case_id","case_number","title","court_id","case_type","cause","judgment_date","parties","summary","facts","reasoning","holding","ruling","outcome","keywords") VALUES ('case_hj_private_pay','(2023)translated source text0112translated source text9021translated source text','renovationtranslated source text','court_sh_minhang','translated source text','translated source textrenovationtranslated source text','2023-12-21','translated source text、translated source text','translated source textpersonal accounttranslated source textlatertranslated source text。','translated source textistranslated source text。','translated source textauthorization、translated source textandtranslated source text。','translated source textauthorizationtranslated source text。','translated source textauthorizationtranslated source textpleasetranslated source text。','translated source text','translated source text,authorization,translated source text');
INSERT INTO "cases" ("case_id","case_number","title","court_id","case_type","cause","judgment_date","parties","summary","facts","reasoning","holding","ruling","outcome","keywords") VALUES ('case_hj_property_hours','(2024)translated source text0112translated source text771translated source text','property managementtranslated source text','court_sh_minhang','translated source text','translated source text','2024-03-14','translated source text、translated source text','renovationtranslated source text。','property managementnoticeandtranslated source text daytranslated source text。','translated source textnottranslated source text。','translated source text。','translated source text。','translated source text','translated source text,property managementnotice,translated source text');
INSERT INTO "statute_articles" ("article_id","statute_id","article_no","seq","heading","text") VALUES ('art_air_quality','stat_rent_safety','translated source text1translated source text',1,'translated source text','translated source textrenovationtranslated source textbefore rentalshouldtranslated source texttestingtranslated source text，formaldehyde、TVOC translated source textshouldtranslated source text，translated source textusenottranslated source textscreenshottranslated source textreport。');
INSERT INTO "statute_articles" ("article_id","statute_id","article_no","seq","heading","text") VALUES ('art_electrical_safety','stat_rent_safety','translated source text2translated source text',2,'translated source textsafety','before rentalfoundtranslated source text、residual-current protectiontranslated source text，shouldtranslated source text。');
INSERT INTO "statute_articles" ("article_id","statute_id","article_no","seq","heading","text") VALUES ('art_property_hours','stat_rent_safety','translated source text3translated source text',3,'property managementconstruction hours','translated source textshouldtranslated source textproperty managementtranslated source textandnoisy worktranslated source text。');
INSERT INTO "statute_articles" ("article_id","statute_id","article_no","seq","heading","text") VALUES ('art_lease_promise','stat_rent_safety','translated source text4translated source text',4,'move-intranslated source text','rentaltranslated source textnottranslated source textmove-intranslated source text。');
COMMIT;
PRAGMA foreign_keys=ON;

BEGIN TRANSACTION;
INSERT INTO courts(court_id,name,level,region) VALUES
('court_sh_changning','Shanghaitranslated source textChangningtranslated source text','translated source text','Shanghai'),
('court_sh_xuhui','Shanghaitranslated source text','translated source text','Shanghai'),
('court_sh_pudong','Shanghaitranslated source text','translated source text','Shanghai'),
('court_sh_first','Shanghaitranslated source text','translated source text','Shanghai'),
('court_sh_second','Shanghaitranslated source text','translated source text','Shanghai'),
('court_sh_arbitration','Shanghaitranslated source text','translated source text','Shanghai');
INSERT INTO statutes(statute_id,name,short_name,issuer,effective_date,status,summary) VALUES
('stat_civil_lease','translated source textleasetranslated source text','leasetranslated source text','translated source text','2021-01-01','translated source text','translated source textleasetranslated source text、translated source textandtranslated source text。'),
('stat_sh_rental','Shanghaitranslated source textleasetranslated source text','Shanghaileasetranslated source text','Shanghaitranslated source text','2022-02-01','translated source text','translated source textleasetranslated source text、translated source textandtranslated source text。'),
('stat_property_service','translated source textproperty managementtranslated source text','property managementtranslated source text','Shanghaitranslated source text','2024-01-01','translated source text','translated source textrenovationtranslated source text、translated source textandtranslated source text。'),
('stat_indoor_air','translated source text','translated source text','translated source text','2023-07-01','translated source text','translated source texttestingandreporttranslated source text。'),
('stat_electrical_code','translated source textsafetytranslated source text','translated source text','translated source text','2023-03-01','translated source text','translated source text、translated source textandtranslated source text。'),
('stat_fire_home','translated source textsafetytranslated source text','translated source text','translated source text','2022-11-01','translated source text','translated source text、translated source textandtranslated source text daytranslated source text。'),
('stat_deposit_receipt','translated source textrenovationtranslated source text','renovationtranslated source text','translated source textlaboratory','2024-05-01','translated source text','descriptiontranslated source text、translated source text、translated source textandacceptance inspectiontranslated source text。'),
('stat_noise_construction','translated source textrenovationtranslated source text','renovationtranslated source text','translated source textproperty managementtranslated source text','2023-09-01','translated source text','translated source textrenovationtranslated source textandtranslated source text。'),
('stat_appliance_delivery','translated source text','appliancestranslated source text','translated source text','2024-06-01','translated source text','translated source text、translated source text、translated source textandtranslated source textareatranslated source textrecord。'),
('stat_personal_info_lease','translated source textleasetranslated source text','leasetranslated source text','translated source text','2025-02-01','translated source text','translated source text、translated source textandtranslated source text。');
INSERT INTO statute_articles(article_id,statute_id,article_no,seq,heading,text) VALUES
('art_civil_delivery','stat_civil_lease','translated source text',1,'leasetranslated source text','rentaltranslated source textleasetranslated source text，translated source textleasetranslated source text。'),
('art_civil_repair','stat_civil_lease','translated source text',2,'translated source text','leasetranslated source textandtranslated source text，translated source textrecordtranslated source text。'),
('art_sh_listing','stat_sh_rental','translated source text',1,'translated source text','translated source text、translated source textandtranslated source text。'),
('art_sh_record','stat_sh_rental','translated source text',2,'leasetranslated source text','leasetranslated source text、translated source textandtranslated source text。'),
('art_property_filing','stat_property_service','translated source text',1,'renovationtranslated source text','property managementtranslated source text、translated source text、translated source textandshouldtranslated source text。'),
('art_property_elevator','stat_property_service','translated source text',2,'translated source text','translated source text，property managementrecordtranslated source textandtranslated source text。'),
('art_air_report','stat_indoor_air','translated source text',1,'testingreport','reporttranslated source text、 daytranslated source text、translated source text、translated source textlaboratoryandtranslated source text。'),
('art_air_sampling','stat_indoor_air','translated source text',2,'translated source text','translated source text、translated source textandtranslated source textrenovationtranslated source textrecord。'),
('art_electric_rcd','stat_electrical_code','translated source text',1,'translated source text','translated source textandtranslated source text。'),
('art_electric_label','stat_electrical_code','translated source text',2,'translated source text','translated source textsaidtranslated source textshould。'),
('art_fire_exit','stat_fire_home','translated source text',1,'translated source text','translated source text，translated source textareatranslated source text。'),
('art_fire_gas','stat_fire_home','translated source text',2,'translated source textsafety','translated source text、translated source textandtranslated source text daytranslated source textrecord。'),
('art_payment_entity','stat_deposit_receipt','translated source text',1,'translated source text','translated source textauthorizationtranslated source textshould。'),
('art_payment_acceptance','stat_deposit_receipt','translated source text',2,'translated source text','translated source text、acceptance inspectionrecord、translated source textandtranslated source text。'),
('art_noise_hours','stat_noise_construction','translated source text',1,'translated source text','property managementtranslated source textrecordtranslated source textrenovationtranslated source text。'),
('art_noise_notice','stat_noise_construction','translated source text',2,'translated source textnotice','translated source textnoisy worktranslated source text daytranslated source textandtranslated source textpassedproperty managementtranslated source text。'),
('art_appliance_check','stat_appliance_delivery','translated source text',1,'translated source text','translated source textrecordtranslated source text、translated source text、translated source textandtranslated source textquantity。'),
('art_appliance_old','stat_appliance_delivery','translated source text',2,'translated source textareatranslated source text','translated source textappliancestranslated source text、quantityandtranslated source text。'),
('art_privacy_minimum','stat_personal_info_lease','translated source text',1,'translated source text','leasetranslated source textcompletedtranslated source textshouldtranslated source text。'),
('art_privacy_storage','stat_personal_info_lease','translated source text',2,'translated source text','translated source text、translated source textandtranslated source text。');
INSERT INTO cases(case_id,case_number,title,court_id,case_type,cause,judgment_date,parties,summary,facts,reasoning,holding,ruling,outcome,keywords) VALUES
('case_hj_deposit_inventory','(2025)translated source text0105translated source text1842translated source text','translated source textlisttranslated source text','court_sh_changning','translated source text','translated source textleasetranslated source text','2025-04-16','translated source text、translated source text','translated source textandtranslated source text。','translated source textlisttranslated source text，translated source text。','translated source textnormaltranslated source text、translated source textandtranslated source textrecordtranslated source text。','translated source text，translated source textrecordtranslated source text。','translated source text。','translated source text','translated source text,translated source textlist,normaltranslated source text'),
('case_hj_window_repair','(2024)translated source text0104translated source text6390translated source text','translated source text','court_sh_xuhui','translated source text','translated source text','2024-09-05','translated source text、translated source textproperty managementtranslated source text','translated source text。','property managementtranslated source textrecordnottranslated source text，translated source text。','translated source textandtranslated source text。','translated source text。','translated source text。','translated source text','translated source text,translated source textrecord,property managementtranslated source text'),
('case_hj_elevator_damage','(2023)translated source text0115translated source text12041translated source text','translated source text','court_sh_pudong','translated source text','translated source text','2023-11-22','translated source textproperty managementtranslated source text、translated source text','appliancestranslated source text。','property managementtranslated source text，translated source textnottranslated source text。','translated source textandtranslated source textshouldtranslated source text。','translated source text，property managementtranslated source text。','translated source text。','translated source text','translated source text,translated source text,translated source text'),
('case_hj_invoice_scope','(2025)translated source text01translated source text2286translated source text','renovationtranslated source text','court_sh_first','translated source text','translated source textrenovationtranslated source text','2025-06-12','translated source text、translated source text','translated source textandtranslated source text，translated source textsaidtranslated source text。','translated source text、translated source textandtranslated source textrecordtranslated source text。','translated source textusetranslated source textandtranslated source textacceptance inspectionrecordtranslated source text。','translated source textnottranslated source textshouldtranslated source text。','translated source text。','translated source text','translated source text,translated source text,translated source text'),
('case_hj_report_signature','(2024)translated source text02translated source text5139translated source text','testingreporttranslated source text','court_sh_second','translated source text','translated source text','2024-10-18','translated source text、translated source texttestinglaboratory','translated source textreporttranslated source text。','reporttranslated source textlaboratorytranslated source text，translated source textshould。','translated source textnottranslated source text。','testinglaboratorytranslated source text。','translated source text。','translated source text','testingreport,translated source text,translated source text'),
('case_hj_storage_damage','(2024)translated source text0112translated source text5840translated source text','translated source text','court_sh_minhang','translated source text','translated source text','2024-08-27','translated source text、translated source text','translated source text。','translated source text，translated source textrecordtranslated source text。','translated source textnottranslated source text。','translated source text。','translated source text。','translated source text','translated source text,translated source text,translated source text'),
('case_hj_firedoor_block','(2023)translated source text0112translated source text3127translated source text','translated source text','court_sh_minhang','translated source text','translated source text','2023-07-14','translated source text、translated source text','translated source textandtranslated source text。','property managementnotice、translated source textandtranslated source textrecordtranslated source text。','translated source text。','translated source text。','translated source textandtranslated source text。','translated source text','translated source text,translated source text,translated source text'),
('case_hj_noise_schedule','(2025)translated source text0105translated source text4502translated source text','renovationtranslated source text','court_sh_changning','translated source text','translated source text','2025-07-03','translated source text、translated source text','translated source textproperty managementtranslated source text。','translated source text、translated source textandtranslated source textshould daytranslated source text。','translated source textnormalrenovationtranslated source text。','translated source textandtranslated source text。','translated source text。','translated source text','renovationtranslated source text,translated source text,translated source text'),
('case_hj_appliance_model','(2024)translated source text0112translated source text9108translated source text','appliancestranslated source textlisttranslated source text','court_sh_minhang','translated source text','translated source text','2024-12-09','translated source text、translated source textappliancestranslated source text','arrivaltranslated source text。','translated source text、translated source textandtranslated source text。','translated source text。','translated source text。','translated source text。','translated source text','translated source text,translated source text,translated source text'),
('case_hj_personal_info','(2025)translated source text0115translated source text7255translated source text','leasetranslated source text','court_sh_pudong','translated source text','translated source text','2025-09-18','translated source text、translated source text','translated source textnottranslated source text。','translated source text daytranslated source text。','translated source textleasetranslated source text。','translated source text、translated source text。','translated source text。','translated source text','translated source text,leasetranslated source text,translated source text'),
('case_hj_payment_authority','(2024)translated source text1847translated source text','renovationtranslated source text','court_sh_arbitration','translated source text','translated source textrenovationtranslated source text','2024-06-28','translated source text、translated source textrenovationtranslated source text','translated source textpersonal accounttranslated source textadditionaltranslated source text。','translated source textauthorizationlisttranslated source textpersonal account。','translated source textusetranslated source textandtranslated source textauthorizationtranslated source text。','personal accounttranslated source textalreadytranslated source text。','translated source text，translated source textpleasetranslated source text。','translated source text','personal account,translated source text,authorization'),
('case_hj_ready_date','(2025)translated source text01translated source text6031translated source text','rentaltranslated source text daytranslated source textcompletedtranslated source text','court_sh_first','translated source text','translated source textleasetranslated source text','2025-11-07','translated source text、translated source text','translated source text day，translated source text daytranslated source textnotcompleted。','translated source text daytranslated source text。','translated source text daytranslated source text。','translated source text daytranslated source text。','translated source textcompletedtranslated source text daytranslated source text。','translated source text','translated source text daytranslated source text,translated source text,translated source text');
INSERT INTO citations(citation_id,case_id,target_type,target_id,label) VALUES
('cite_deposit_civil','case_hj_deposit_inventory','article','art_civil_delivery','translated source text'),
('cite_window_property','case_hj_window_repair','article','art_property_filing','translated source textrecord'),
('cite_elevator_rule','case_hj_elevator_damage','article','art_property_elevator','translated source textrecord'),
('cite_invoice_payment','case_hj_invoice_scope','article','art_payment_acceptance','translated source text'),
('cite_report_air','case_hj_report_signature','article','art_air_report','reporttranslated source text'),
('cite_storage_case','case_hj_storage_damage','case','case_hj_leak','translated source text'),
('cite_fire_exit','case_hj_firedoor_block','article','art_fire_exit','translated source text'),
('cite_noise_hours','case_hj_noise_schedule','article','art_noise_hours','translated source text'),
('cite_appliance_check','case_hj_appliance_model','article','art_appliance_check','translated source text'),
('cite_privacy_min','case_hj_personal_info','article','art_privacy_minimum','translated source text'),
('cite_payment_entity','case_hj_payment_authority','article','art_payment_entity','translated source text'),
('cite_ready_civil','case_hj_ready_date','article','art_civil_repair','translated source text');
COMMIT;

BEGIN TRANSACTION;
INSERT INTO statutes(statute_id,name,short_name,issuer,effective_date,status,summary) VALUES
('stat_rental_fire_device','Shanghaitranslated source textrentaltranslated source text','rentaltranslated source text','Shanghaitranslated source text','2024-01-01','translated source text','translated source text、translated source textandbefore rentaltranslated source textrecordtranslated source text。'),
('stat_appliance_delivery_check','translated source textacceptance inspectiontranslated source text','appliancesacceptance inspectiontranslated source text','translated source text','2023-03-15','translated source text','translated source text、translated source text、translated source textandtranslated source textverifytranslated source text。');
INSERT INTO statute_articles(article_id,statute_id,article_no,seq,heading,text) VALUES
('art_rental_smoke_record','stat_rental_fire_device','translated source text',1,'translated source textrecord','before rentaltranslated source textrecordtranslated source text、translated source textandtranslated source text daytranslated source text。'),
('art_appliance_model_check','stat_appliance_delivery_check','translated source text',1,'translated source textverify','translated source textverifytranslated source text、translated source text、translated source textlistandtranslated source text。');
INSERT INTO cases(case_id,case_number,title,court_id,case_type,cause,judgment_date,parties,summary,facts,reasoning,holding,ruling,outcome,keywords) VALUES
('case_hj_smoke_alarm_duty','(2025)translated source text0112translated source text6034translated source text','rentaltranslated source text','court_sh_minhang','translated source text','translated source textleasetranslated source text','2025-08-19','translated source text、translated source text','tenantmove-intranslated source textfoundtranslated source text。','translated source text，translated source text daytranslated source textandtranslated source text。','translated source textbefore rentalsafetytranslated source textistranslated source text。','translated source texttenanttranslated source text。','translated source texttestingtranslated source text。','translated source text','translated source text,before rentaltranslated source text,translated source textrecord'),
('case_hj_install_floor_damage','(2024)translated source text0104translated source text7811translated source text','translated source textwater seepagetranslated source text','court_sh_xuhui','translated source text','translated source text','2024-11-26','translated source text、translated source textappliancestranslated source text','translated source textnottranslated source text，translated source text。','translated source textandtranslated source textrecord，translated source textacceptance inspectiontranslated source textnottranslated source text。','translated source text、translated source textandtranslated source text。','translated source textandtranslated source text。','translated source text。','translated source text','translated source text,translated source text,acceptance inspectiontranslated source text');
INSERT INTO citations(citation_id,case_id,target_type,target_id,label) VALUES
('cit_hj_smoke_record','case_hj_smoke_alarm_duty','article','art_rental_smoke_record','before rentaltranslated source textrecord'),
('cit_hj_appliance_model','case_hj_install_floor_damage','article','art_appliance_model_check','appliancestranslated source textverify');
COMMIT;
