-- Curated Stage-0 seed for campus_ai_infra_offer_deadline_tradeoff / job_board.

BEGIN;

INSERT INTO companies (company_id, name, industry, size, stage, city, intro, rating) VALUES
  ('comp_starridge', 'StarRidge AI', 'AI Infra', '500-1000 people', 'Round B', 'Shanghai', 'Focus on large-model inference services, model gateways, and heterogeneous computing power scheduling.', 4.3),
  ('comp_matrixcloud', 'MatrixCloud', 'Cloud computing', '1000-5000 people', 'Round C', 'Shanghai', 'Delivers a privatized inference platform for financial and manufacturing customers.', 3.8),
  ('comp_bytelattice', 'ByteLattice', 'Infrastructure software', '1000-5000 people', 'Round D', 'Beijing', 'Develop LLM runtime kernels, compilers, and high-performance operators.', 4.5),
  ('comp_qingyan', 'Qingyan Compute', 'AI Infra', '500-1000 people', 'Round B', 'Beijing', 'Build inference runtimes and heterogeneous computing platforms.', 4.0),
  ('comp_orbitserve', 'OrbitServe', 'Cloud computing', '200-500 people', 'Round A', 'Beijing', 'Provide multi-tenant model services and capacity management products.', 4.1),
  ('comp_pinevector', 'PineVector', 'Database', '500-1000 people', 'Round C', 'Shanghai', 'Develop vector retrieval, hybrid search, and data infrastructure.', 4.2),
  ('comp_siliconriver', 'SiliconRiver', 'Chip', '1000-5000 people', 'Strategic financing', 'Shanghai', 'Develop an AI accelerator software stack and compiler toolchain.', 4.0),
  ('comp_northstar', 'NorthStar Cloud', 'Cloud computing', 'More than 5000 people', 'Listed', 'Beijing', 'Operate a public cloud GPU platform and distributed training services.', 4.1),
  ('comp_lanternai', 'Lantern AI', 'Enterprise software', '200-500 people', 'Round B', 'Shanghai', 'Provides model deployment, observability, and evaluation tools for enterprises.', 3.9),
  ('comp_heliosdata', 'Helios Data', 'Data platform', '500-1000 people', 'Round C', 'Beijing', 'Provide real-time data platforms and feature services.', 4.0),
  ('comp_moonshotops', 'Moonshot Ops', 'Developer tools', '50-200 people', 'Round A', 'Shanghai', 'Develop GPU performance observability and cost analysis tools.', 4.4),
  ('comp_redwood', 'Redwood Robotics', 'Robot', '500-1000 people', 'Round B', 'Beijing', 'Build an on-device inference system for a robot multimodal model.', 4.1),
  ('comp_cloudharbor', 'CloudHarbor', 'Cloud security', '1000-5000 people', 'Round D', 'Shanghai', 'Provide cloud-native security, zero trust, and runtime protection.', 3.9),
  ('comp_frostbyte', 'FrostByte Games', 'Games', '1000-5000 people', 'Listed', 'Shanghai', 'Operate large-scale online games and real-time recommendation systems.', 4.0),
  ('comp_cobalt', 'Cobalt Search', 'Search', '200-500 people', 'Round B', 'Beijing', 'Develop search ranking, semantic retrieval, and content understanding services.', 4.2),
  ('comp_auroraedge', 'Aurora Edge', 'Edge computing', '200-500 people', 'Round B', 'Shanghai', 'Provides edge inference platforms for retail and industrial sites.', 3.7),
  ('comp_keystone', 'Keystone Systems', 'Infrastructure software', '500-1000 people', 'Round C', 'Beijing', 'Develop high-performance networking, storage, and container runtimes.', 4.3),
  ('comp_inkstone', 'Inkstone AI', 'Content technology', '200-500 people', 'Round A', 'Shanghai', 'Provides generative content tools for creators.', 3.8),
  ('comp_bluefin', 'Bluefin Finance Tech', 'Fintech', '1000-5000 people', 'Listed', 'Beijing', 'Build payment risk control and online feature platforms.', 3.9),
  ('comp_vermilion', 'Vermilion Auto', 'Smart cars', 'More than 5000 people', 'Listed', 'Shanghai', 'Develop onboard computing platforms and data closed loops.', 4.0);

INSERT INTO jobs (job_id, company_id, title, city, category, salary_min_minor, salary_max_minor, salary_months, experience, education, jd, requirements, tags, status, posted_at) VALUES
  ('job_starridge_infer_001', 'comp_starridge', 'LLM Inference Optimization Engineer', 'Shanghai', 'ai_infra', 3100000, 3600000, 14, 'fresh_grad', 'master', 'Responsible for dynamic batching, KV cache management, and GPU utilization optimization for online inference services.', 'Familiar with C++, Python, CUDA profiling, vLLM or TensorRT-LLM, and able to explain the sources of end-to-end latency.', 'AI Infra,LLM inference,CUDA,vLLM', 'open', '2026-05-03'),
  ('job_matrixcloud_platform_001', 'comp_matrixcloud', 'Inference Platform Engineer', 'Shanghai', 'software_engineering', 3500000, 3800000, 13, 'fresh_grad', 'master', 'Build an enterprise inference platform and undertake private deployment delivery for financial clients, with a potentially long on-site customer support cycle.', 'Familiar with distributed systems, Kubernetes, and model serving; able to accept 12 to 18 consecutive months of client-site work.', 'AI Infra,onsite,platform', 'open', '2026-05-04'),
  ('job_bytelattice_kernel_001', 'comp_bytelattice', 'LLM Runtime Kernel Engineer', 'Beijing', 'ai_infra', 3800000, 4200000, 13, 'fresh_grad', 'master', 'Optimize attention operators, KV cache layouts, the scheduler, and multi-GPU communication paths.', 'Has CUDA/C++ performance analysis experience and can use Nsight to locate kernel and memory bottlenecks.', 'LLM runtime,kernel,CUDA', 'open', '2026-05-05'),
  ('job_qingyan_runtime_001', 'comp_qingyan', 'Runtime Systems Engineer', 'Beijing', 'ai_infra', 2800000, 3200000, 15, 'fresh_grad', 'master', 'Responsible for inference runtime stability, model loading pipelines, and service capacity governance.', 'Familiar with Linux, Python/C++, and online services; compensation includes separately valued stock options.', 'runtime systems,LLM,options', 'open', '2026-05-06'),
  ('job_orbit_scheduler_001', 'comp_orbitserve', 'GPU Scheduler Engineer', 'Beijing', 'ai_infra', 2800000, 3400000, 14, 'fresh_grad', 'master', 'Design multi-tenant GPU queues, preemption strategies, and capacity waterline control to reduce fragmentation and queueing delay.', 'Be proficient in scheduling algorithms, Kubernetes device plugins, and observability, and be able to analyze resource fairness.', 'GPU,scheduler,Kubernetes', 'open', '2026-05-07'),
  ('job_orbit_gateway_002', 'comp_orbitserve', 'Model Gateway Backend Engineer', 'Beijing', 'ai_infra', 2600000, 3200000, 14, 'fresh_grad', 'master', 'Develop routing, rate limiting, circuit breaking, and tenant quota capabilities for the model gateway.', 'Familiar with Go or Rust, microservice governance, and high-concurrency network programming.', 'gateway,backend,serving', 'open', '2026-05-08'),
  ('job_pinevector_engine_001', 'comp_pinevector', 'Vector Search Engine Engineer', 'Shanghai', 'software_engineering', 2900000, 3500000, 14, 'fresh_grad', 'master', 'Optimize vector index building, hot and cold data layouts, and hybrid retrieval execution plans.', 'Familiar with database kernels, ANN algorithms, C++, and performance benchmark design.', 'vector search,database,C++', 'open', '2026-05-09'),
  ('job_pinevector_platform_002', 'comp_pinevector', 'Retrieval Platform Engineer', 'Shanghai', 'software_engineering', 2500000, 3100000, 14, 'fresh_grad', 'master', 'Build a search service platform, index publishing workflows, and query quality monitoring.', 'Familiar with Python/Go, distributed storage, and online fault localization.', 'retrieval,platform,SRE', 'open', '2026-05-10'),
  ('job_silicon_compiler_001', 'comp_siliconriver', 'AI Compiler Engineer', 'Shanghai', 'software_engineering', 3000000, 3800000, 15, 'fresh_grad', 'master', 'Develop graph optimization, operator fusion, and code generation for self-developed accelerators.', 'Familiar with MLIR/LLVM, compiler principles, and deep learning computation graphs.', 'compiler,MLIR,accelerator', 'open', '2026-05-11'),
  ('job_silicon_runtime_002', 'comp_siliconriver', 'Accelerator Runtime Engineer', 'Shanghai', 'ai_infra', 3000000, 3700000, 15, 'fresh_grad', 'master', 'Maintain device runtimes, memory allocators, and asynchronous execution queues.', 'Familiar with C/C++, driver interfaces, concurrent programming, and performance tuning.', 'runtime,accelerator,memory', 'open', '2026-05-03'),
  ('job_northstar_training_001', 'comp_northstar', 'Distributed Training Engineer', 'Beijing', 'software_engineering', 3000000, 3900000, 16, 'fresh_grad', 'master', 'Optimize parallel strategies, communication topology, and fault recovery for large-scale training.', 'Familiar with PyTorch distributed, NCCL, and cluster networking; the role focuses on training rather than inference.', 'training,NCCL,distributed', 'open', '2026-05-04'),
  ('job_northstar_inference_002', 'comp_northstar', 'Cloud Inference Service Engineer', 'Beijing', 'ai_infra', 2900000, 3700000, 16, 'fresh_grad', 'master', 'Build cloud model deployment, elastic scaling, and version canary capabilities.', 'Familiar with container platforms, service mesh, and model inference frameworks.', 'cloud,inference,Kubernetes', 'open', '2026-05-05'),
  ('job_lantern_observe_001', 'comp_lanternai', 'LLM Observability Engineer', 'Shanghai', 'ai_infra', 2600000, 3300000, 14, 'fresh_grad', 'master', 'Establish request tracing, token-level metrics, and cost attribution systems.', 'Familiar with OpenTelemetry, time-series databases, and online service performance diagnosis.', 'observability,LLM,metrics', 'open', '2026-05-06'),
  ('job_lantern_eval_002', 'comp_lanternai', 'Model Evaluation Platform Engineer', 'Shanghai', 'software_engineering', 2500000, 3200000, 14, 'fresh_grad', 'master', 'Develop model evaluation pipelines, data version management, and result analysis services.', 'Familiar with Python, data engineering, and experimentation platforms; the direction is adjacent to inference optimization but not centered on CUDA.', 'evaluation,platform,data', 'open', '2026-05-07'),
  ('job_helios_stream_001', 'comp_heliosdata', 'Streaming Systems Engineer', 'Beijing', 'software_engineering', 2700000, 3400000, 14, 'fresh_grad', 'master', 'Optimize the state backend, checkpointing, and latency stability of the real-time computing engine.', 'Familiar with Flink or similar stream processing systems, Java/C++, and distributed consistency.', 'streaming,distributed,state', 'open', '2026-05-08'),
  ('job_helios_feature_002', 'comp_heliosdata', 'Feature Store Backend Engineer', 'Beijing', 'software_engineering', 2500000, 3100000, 14, 'fresh_grad', 'master', 'Build online feature reading, data backfill, and consistency verification services.', 'Familiar with KV storage, cache strategies, and data quality governance.', 'feature store,backend,data', 'open', '2026-05-09'),
  ('job_moonshot_profiler_001', 'comp_moonshotops', 'GPU Performance Tooling Engineer', 'Shanghai', 'ai_infra', 3000000, 3600000, 14, 'fresh_grad', 'master', 'Develop GPU trace collection, kernel timeline analysis, and performance regression platforms.', 'Familiar with CUDA, Nsight data formats, C++, and visualization backends.', 'profiling,GPU,developer tools', 'open', '2026-05-10'),
  ('job_moonshot_cost_002', 'comp_moonshotops', 'AI Cost Analytics Engineer', 'Shanghai', 'software_engineering', 2400000, 3000000, 14, 'fresh_grad', 'master', 'Build model service cost allocation, capacity forecasting, and budget alerts.', 'Familiar with SQL, Python, metrics systems, and cloud resource billing.', 'cost,analytics,capacity', 'open', '2026-05-11'),
  ('job_redwood_edge_001', 'comp_redwood', 'Edge Inference Engineer', 'Beijing', 'ai_infra', 2700000, 3400000, 14, 'fresh_grad', 'master', 'Optimize model quantization, operator deployment, and real-time inference latency on robots.', 'Familiar with C++, ONNX/TensorRT, and heterogeneous hardware on the device side.', 'edge,inference,robotics', 'open', '2026-05-03'),
  ('job_redwood_multimodal_002', 'comp_redwood', 'Multimodal Serving Engineer', 'Beijing', 'ai_infra', 2800000, 3500000, 14, 'fresh_grad', 'master', 'Build vision-language model services, media preprocessing, and request orchestration.', 'Familiar with multimodal models, Python services, and GPU memory management.', 'multimodal,serving,GPU', 'open', '2026-05-04'),
  ('job_cloudharbor_runtime_001', 'comp_cloudharbor', 'Container Runtime Security Engineer', 'Shanghai', 'ai_infra', 2600000, 3300000, 14, 'fresh_grad', 'master', 'Develop container runtime detection, policy enforcement, and security event collection.', 'Familiar with Linux namespace, eBPF, and container security; not a model inference role.', 'security,eBPF,runtime', 'open', '2026-05-05'),
  ('job_cloudharbor_platform_002', 'comp_cloudharbor', 'Cloud Security Platform Engineer', 'Shanghai', 'software_engineering', 2400000, 3100000, 14, 'fresh_grad', 'master', 'Build asset discovery, risk strategy, and security operations platforms.', 'Familiar with Go, message queues, and cloud-native infrastructure.', 'cloud security,platform,Go', 'open', '2026-05-06'),
  ('job_frostbyte_reco_001', 'comp_frostbyte', 'Recommendation Infrastructure Engineer', 'Shanghai', 'software_engineering', 2700000, 3500000, 15, 'fresh_grad', 'master', 'Maintain online features, retrieval services, and recommendation model deployment pipelines.', 'Familiar with high-concurrency services, caching, and machine learning engineering.', 'recommendation,infrastructure,ML', 'open', '2026-05-07'),
  ('job_frostbyte_engine_002', 'comp_frostbyte', 'Game Server Performance Engineer', 'Shanghai', 'software_engineering', 2600000, 3400000, 15, 'fresh_grad', 'master', 'Optimize frame synchronization, network latency, and resource usage for game servers.', 'Familiar with C++ network programming and performance analysis; the direction does not belong to LLM Infra.', 'game server,C++,performance', 'open', '2026-05-08'),
  ('job_cobalt_ranking_001', 'comp_cobalt', 'Search Ranking Engineer', 'Beijing', 'software_engineering', 2800000, 3600000, 14, 'fresh_grad', 'master', 'Develop search ranking models, feature engineering, and online inference pipelines.', 'Familiar with machine learning, feature systems, and A/B testing.', 'ranking,search,ML', 'open', '2026-05-09'),
  ('job_cobalt_query_002', 'comp_cobalt', 'Query Understanding Engineer', 'Beijing', 'software_engineering', 2700000, 3500000, 14, 'fresh_grad', 'master', 'Build query rewriting, intent recognition, and semantic retrieval services.', 'Familiar with NLP, retrieval algorithms, and Python/C++.', 'NLP,query,retrieval', 'open', '2026-05-10'),
  ('job_aurora_deploy_001', 'comp_auroraedge', 'Edge Deployment Engineer', 'Shanghai', 'software_engineering', 2500000, 3100000, 13, 'fresh_grad', 'master', 'Responsible for software release, monitoring, and remote troubleshooting of store and factory edge nodes.', 'Requires about one week of on-site customer support per month; familiar with Linux and automated operations and maintenance.', 'edge,deployment,travel', 'open', '2026-05-11'),
  ('job_aurora_runtime_002', 'comp_auroraedge', 'Edge Runtime Engineer', 'Shanghai', 'ai_infra', 2700000, 3300000, 13, 'fresh_grad', 'master', 'Develop model runtimes for edge devices, plugin mechanisms, and offline fault tolerance.', 'Familiar with C++, embedded Linux, and model format conversion.', 'edge,runtime,C++', 'open', '2026-05-03'),
  ('job_keystone_network_001', 'comp_keystone', 'High Performance Network Engineer', 'Beijing', 'software_engineering', 3000000, 3800000, 14, 'fresh_grad', 'master', 'Optimize RPC, zero-copy transmission, and multi-machine communication libraries.', 'Familiar with RDMA, DPDK, C++, and network performance measurement.', 'network,RDMA,C++', 'open', '2026-05-04'),
  ('job_keystone_container_002', 'comp_keystone', 'Container Runtime Engineer', 'Beijing', 'ai_infra', 2800000, 3500000, 14, 'fresh_grad', 'master', 'Maintain container lifecycle, image distribution, and resource isolation.', 'Familiar with the Linux kernel, containerd, and Go.', 'container,runtime,Go', 'open', '2026-05-05'),
  ('job_inkstone_generation_001', 'comp_inkstone', 'Generative AI Backend Engineer', 'Shanghai', 'software_engineering', 2400000, 3000000, 14, 'fresh_grad', 'master', 'Develop task orchestration and quota systems for text-to-image and copy generation products.', 'Familiar with Python, queue systems, and third-party model APIs; the core model is provided by an external vendor.', 'AIGC,backend,orchestration', 'open', '2026-05-06'),
  ('job_inkstone_moderation_002', 'comp_inkstone', 'Content Safety Platform Engineer', 'Shanghai', 'software_engineering', 2400000, 3000000, 14, 'fresh_grad', 'master', 'Build content moderation rules, model invocation, and appeal workflows.', 'Familiar with policy platforms, data analysis, and service stability.', 'content safety,platform,workflow', 'open', '2026-05-07'),
  ('job_bluefin_feature_001', 'comp_bluefin', 'Risk Feature Platform Engineer', 'Beijing', 'software_engineering', 2800000, 3500000, 16, 'fresh_grad', 'master', 'Build low-latency risk-control feature computation and online storage.', 'Familiar with stream processing, KV storage, and high-availability architecture.', 'fintech,feature,low latency', 'open', '2026-05-08'),
  ('job_bluefin_payment_002', 'comp_bluefin', 'Payment Backend Engineer', 'Beijing', 'software_engineering', 2600000, 3300000, 16, 'fresh_grad', 'master', 'Develop payment routing, reconciliation, and exception recovery services.', 'Familiar with Java/Go, database transactions, and fund security.', 'payment,backend,reconciliation', 'open', '2026-05-09'),
  ('job_vermilion_vehicle_001', 'comp_vermilion', 'Vehicle Compute Platform Engineer', 'Shanghai', 'software_engineering', 2900000, 3700000, 15, 'fresh_grad', 'master', 'Build in-vehicle task scheduling, resource isolation, and software upgrade platforms.', 'Familiar with C++, Linux, and real-time systems; the work location includes phased test-site support.', 'automotive,platform,C++', 'open', '2026-05-10'),
  ('job_vermilion_data_002', 'comp_vermilion', 'Autonomous Driving Data Platform Engineer', 'Shanghai', 'software_engineering', 2700000, 3500000, 15, 'fresh_grad', 'master', 'Develop a data collection, upload, cleaning, and training sample management platform.', 'Familiar with big data systems, object storage, and data governance.', 'autonomous,data,platform', 'open', '2026-05-11'),
  ('job_starridge_gateway_002', 'comp_starridge', 'Inference Gateway Engineer', 'Shanghai', 'ai_infra', 2900000, 3400000, 14, 'fresh_grad', 'master', 'Develop model routing, request merging, streaming output, and fault isolation.', 'Familiar with Go/C++, HTTP/gRPC, and service governance; inference framework experience is preferred.', 'gateway,streaming,LLM', 'open', '2026-05-03'),
  ('job_starridge_sre_003', 'comp_starridge', 'AI Platform SRE', 'Shanghai', 'ai_infra', 2700000, 3300000, 14, 'fresh_grad', 'master', 'Ensure the stability of the GPU cluster, model services, and release system.', 'Familiar with Kubernetes, Prometheus, failure drills, and capacity planning.', 'SRE,GPU,Kubernetes', 'open', '2026-05-04'),
  ('job_matrixcloud_solution_002', 'comp_matrixcloud', 'AI Platform Solution Engineer', 'Shanghai', 'software_engineering', 3000000, 3600000, 13, 'fresh_grad', 'master', 'Designs model platform solutions for bank clients and participates in on-site acceptance.', 'Requires frequent business trips and customer communication; familiar with private cloud, networking, and security integration.', 'solution,onsite,private cloud', 'open', '2026-05-05'),
  ('job_matrixcloud_backend_003', 'comp_matrixcloud', 'Inference Control Plane Engineer', 'Shanghai', 'software_engineering', 2900000, 3500000, 13, 'fresh_grad', 'master', 'Develop a control plane for model versions, resource orchestration, and deployment approvals.', 'Familiar with Go, Kubernetes controllers, and distributed state management.', 'control plane,Kubernetes,Go', 'open', '2026-05-06'),
  ('job_bytelattice_compiler_002', 'comp_bytelattice', 'LLM Compiler Engineer', 'Beijing', 'ai_infra', 3600000, 4200000, 13, 'fresh_grad', 'master', 'Optimize computation graph partitioning, operator fusion, and hardware backend code generation.', 'Familiar with MLIR/LLVM, CUDA, and model architecture.', 'compiler,LLVM,LLM', 'open', '2026-05-07'),
  ('job_bytelattice_serving_003', 'comp_bytelattice', 'Serving Systems Engineer', 'Beijing', 'ai_infra', 3400000, 4000000, 13, 'fresh_grad', 'master', 'Develop continuous batching, request scheduling, and multi-model serving frameworks.', 'Familiar with C++/Python, concurrency control, and GPU memory management.', 'serving,batching,GPU', 'open', '2026-05-08'),
  ('job_qingyan_platform_002', 'comp_qingyan', 'AI Infrastructure Engineer', 'Beijing', 'software_engineering', 2700000, 3200000, 15, 'fresh_grad', 'master', 'Maintain shared cluster resources, images, and release pipelines for both training and inference.', 'Familiar with Kubernetes, Linux, and infrastructure automation; options and cash are explained separately.', 'AI Infra,platform,options', 'open', '2026-05-09'),
  ('job_qingyan_kernel_003', 'comp_qingyan', 'Inference Kernel Engineer', 'Beijing', 'software_engineering', 3000000, 3500000, 15, 'fresh_grad', 'master', 'Optimize attention, quantization, and sampling-related GPU kernels.', 'Familiar with CUDA, Triton, or C++ template programming.', 'kernel,Triton,CUDA', 'open', '2026-05-10'),
  ('job_orbit_capacity_003', 'comp_orbitserve', 'Capacity Planning Engineer', 'Beijing', 'ai_infra', 2500000, 3100000, 14, 'fresh_grad', 'master', 'Establish mechanisms for inference traffic forecasting, GPU utilization modeling, and scaling reviews.', 'Familiar with statistical modeling, SQL, and cloud resource management.', 'capacity,forecasting,GPU', 'open', '2026-05-11'),
  ('job_pinevector_storage_003', 'comp_pinevector', 'Storage Engine Engineer', 'Shanghai', 'software_engineering', 2900000, 3600000, 14, 'fresh_grad', 'master', 'Develop WAL, compression, compaction, and hot-cold tiered storage.', 'Familiar with C++, LSM-trees, and system performance analysis.', 'storage,LSM,C++', 'open', '2026-05-03'),
  ('job_silicon_validation_003', 'comp_siliconriver', 'Accelerator Software Validation Engineer', 'Shanghai', 'software_engineering', 2500000, 3100000, 15, 'fresh_grad', 'master', 'Design correctness, performance, and stability tests for the runtime and operator library.', 'Familiar with Python/C++, automated testing, and performance baselines.', 'validation,accelerator,testing', 'open', '2026-05-04'),
  ('job_northstar_cluster_003', 'comp_northstar', 'GPU Cluster Platform Engineer', 'Beijing', 'ai_infra', 2900000, 3600000, 16, 'fresh_grad', 'master', 'Build a GPU node operations and maintenance, fault isolation, and resource quota platform.', 'Familiar with Kubernetes, Linux, networking, and large-scale cluster operations.', 'cluster,GPU,platform', 'open', '2026-05-05'),
  ('job_lantern_release_003', 'comp_lanternai', 'Model Release Platform Engineer', 'Shanghai', 'software_engineering', 2500000, 3100000, 14, 'fresh_grad', 'master', 'Develop workflows for model artifacts, approval, canary releases, and rollbacks.', 'Familiar with CI/CD, object storage, and service release.', 'release,model ops,CI/CD', 'open', '2026-05-06'),
  ('job_moonshot_trace_003', 'comp_moonshotops', 'Distributed Trace Backend Engineer', 'Shanghai', 'software_engineering', 2600000, 3300000, 14, 'fresh_grad', 'master', 'Develop a high-throughput trace ingestion, sampling, and query backend.', 'Familiar with columnar storage, message queues, and observability protocols.', 'trace,backend,observability', 'open', '2026-05-07'),
  ('job_keystone_storage_003', 'comp_keystone', 'Distributed Storage Engineer', 'Beijing', 'software_engineering', 2900000, 3700000, 14, 'fresh_grad', 'master', 'Optimize object storage metadata, replication protocols, and fault recovery.', 'Familiar with C++/Go, distributed consistency, and disk performance.', 'storage,distributed,systems', 'open', '2026-05-08');

INSERT INTO resumes (resume_id, user_id, name, headline, years_exp, education, skills, summary, updated_at) VALUES
  ('resume_lin_aiinfra', 'usr_lin_che', 'Lin Che', 'Master’s degree in computer science | LLM inference optimization', 0, 'master', 'vLLM performance evaluation,KV cache compression,CUDA profiling,Python,C++', 'It has been confirmed that the experience includes only vLLM performance evaluation, KV cache compression, and CUDA profiling; no unverified projects will be added.', '2026-05-12T08:00:00Z');

INSERT INTO saved_jobs (user_id, job_id, saved_at) VALUES
  ('usr_lin_che', 'job_starridge_infer_001', '2026-05-08T09:00:00Z'),
  ('usr_lin_che', 'job_matrixcloud_platform_001', '2026-05-09T09:00:00Z'),
  ('usr_lin_che', 'job_bytelattice_kernel_001', '2026-05-10T09:00:00Z'),
  ('usr_lin_che', 'job_qingyan_runtime_001', '2026-05-11T09:00:00Z'),
  ('usr_lin_che', 'job_orbit_scheduler_001', '2026-05-12T09:00:00Z'),
  ('usr_lin_che', 'job_orbit_gateway_002', '2026-05-08T09:00:00Z'),
  ('usr_lin_che', 'job_pinevector_engine_001', '2026-05-09T09:00:00Z'),
  ('usr_lin_che', 'job_pinevector_platform_002', '2026-05-10T09:00:00Z'),
  ('usr_lin_che', 'job_silicon_compiler_001', '2026-05-11T09:00:00Z'),
  ('usr_lin_che', 'job_silicon_runtime_002', '2026-05-12T09:00:00Z');

INSERT INTO applications (application_id, user_id, job_id, resume_id, cover_letter, status, applied_at, updated_at) VALUES
  ('app_starridge_001', 'usr_lin_che', 'job_starridge_infer_001', 'resume_lin_aiinfra', 'The technical interview has been completed, waiting for HR follow-up.', 'interview', '2026-05-04T10:00:00Z', '2026-05-08T10:00:00Z'),
  ('app_matrixcloud_001', 'usr_lin_che', 'job_matrixcloud_platform_001', 'resume_lin_aiinfra', 'The platform role process is ongoing, and the work format is pending written confirmation.', 'interview', '2026-05-05T10:00:00Z', '2026-05-09T10:00:00Z'),
  ('app_bytelattice_001', 'usr_lin_che', 'job_bytelattice_kernel_001', 'resume_lin_aiinfra', 'Senior student referral, no written offer yet.', 'submitted', '2026-05-06T10:00:00Z', '2026-05-10T10:00:00Z'),
  ('app_qingyan_001', 'usr_lin_che', 'job_qingyan_runtime_001', 'resume_lin_aiinfra', 'When screening positions, compensation and HC should follow the official written materials.', 'submitted', '2026-05-07T10:00:00Z', '2026-05-11T10:00:00Z'),
  ('app_orbit_2025', 'usr_lin_che', 'job_orbit_scheduler_001', 'resume_lin_aiinfra', '2025 autumn recruitment historical applications, direction aligned but the process has ended.', 'rejected', '2025-10-08T10:00:00Z', '2025-10-12T10:00:00Z'),
  ('app_pinevector_2025', 'usr_lin_che', 'job_pinevector_engine_001', 'resume_lin_aiinfra', 'Historical applications only completed resume review.', 'viewed', '2025-10-09T10:00:00Z', '2025-10-10T10:00:00Z'),
  ('app_siliconriver_2025', 'usr_lin_che', 'job_silicon_compiler_001', 'resume_lin_aiinfra', 'The compiler role ended because the coursework background was not an exact match.', 'rejected', '2025-10-10T10:00:00Z', '2025-10-16T10:00:00Z'),
  ('app_northstar_2025', 'usr_lin_che', 'job_northstar_inference_002', 'resume_lin_aiinfra', 'Historical applications are kept for position comparison.', 'viewed', '2025-10-11T10:00:00Z', '2025-10-12T10:00:00Z');

INSERT INTO chats (chat_id, user_id, job_id, company_id, recruiter_name, created_at, last_at) VALUES
  ('chat_starridge_001', 'usr_lin_che', 'job_starridge_infer_001', 'comp_starridge', 'Chen HR', '2026-05-07T09:00:00Z', '2026-05-12T09:00:00Z'),
  ('chat_matrixcloud_001', 'usr_lin_che', 'job_matrixcloud_platform_001', 'comp_matrixcloud', 'Luo Recruiting', '2026-05-08T09:00:00Z', '2026-05-12T09:00:00Z'),
  ('chat_bytelattice_001', 'usr_lin_che', 'job_bytelattice_kernel_001', 'comp_bytelattice', 'Senior Brother Wang', '2026-05-09T09:00:00Z', '2026-05-12T09:00:00Z'),
  ('chat_qingyan_001', 'usr_lin_che', 'job_qingyan_runtime_001', 'comp_qingyan', 'Weekly HR', '2026-05-10T09:00:00Z', '2026-05-12T09:00:00Z'),
  ('chat_orbit_001', 'usr_lin_che', 'job_orbit_scheduler_001', 'comp_orbitserve', 'Meng recruitment', '2026-05-11T09:00:00Z', '2026-05-12T09:00:00Z'),
  ('chat_pinevector_001', 'usr_lin_che', 'job_pinevector_engine_001', 'comp_pinevector', 'Xu Recruiting', '2026-05-12T09:00:00Z', '2026-05-12T09:00:00Z');

INSERT INTO chat_messages (message_id, chat_id, sender, body, sent_at) VALUES
  ('msg_starridge_001', 'chat_starridge_001', 'recruiter', 'The StarRidge technical interview feedback was positive, and HR will later synchronize the rhythm of the written offer.', '2026-05-07T09:30:00Z'),
  ('msg_matrixcloud_001', 'chat_matrixcloud_001', 'recruiter', 'The MatrixCloud platform role includes financial customer delivery, so the work pattern needs to be checked against the formal terms.', '2026-05-08T09:30:00Z'),
  ('msg_bytelattice_001', 'chat_bytelattice_001', 'recruiter', 'The ByteLattice runtime kernel position is currently being screened for internal referral.', '2026-05-09T09:30:00Z'),
  ('msg_qingyan_001', 'chat_qingyan_001', 'recruiter', 'The Qingyan Runtime Systems role is still open, and the salary structure shall be based on the written version.', '2026-05-10T09:30:00Z'),
  ('msg_orbit_001', 'chat_orbit_001', 'recruiter', 'The OrbitServe scheduling role is opening an online technical exchange this week; you can first learn about the team.', '2026-05-11T09:30:00Z'),
  ('msg_pinevector_001', 'chat_pinevector_001', 'recruiter', 'The PineVector search engine role leans toward database kernels and requires a C++ project description.', '2026-05-12T09:30:00Z');

INSERT INTO job_alerts (alert_id, user_id, query_json, created_at, active) VALUES
  ('alert_aiinfra_001', 'usr_lin_che', '{"keyword": "LLM inference", "city": ["Beijing", "Shanghai"]}', '2026-05-12T09:00:00Z', 1),
  ('alert_cuda_001', 'usr_lin_che', '{"keyword": "CUDA runtime", "city": ["Beijing", "Shanghai"]}', '2026-05-12T09:05:00Z', 1);

INSERT INTO companies (company_id, name, industry, size, stage, city, intro, rating) VALUES
  ('comp_embermesh', 'EmberMesh Networks', 'Network infrastructure', '200-500 people', 'Round B', 'Beijing', 'Develop data center network controllers, traffic observability, and edge gateways.', 4.1),
  ('comp_harborledger', 'HarborLedger Data', 'Financial data services', '500-1000 people', 'Round C', 'Shenzhen', 'Builds data governance, auditing, and batch-processing platforms for banks and insurance institutions.', 3.7),
  ('comp_maplearchive', 'MapleArchive Systems', 'Storage software', '50-200 people', 'Round A', 'Hangzhou', 'Develop archival storage, backup verification, and object lifecycle management products.', 4.2);

INSERT INTO jobs (job_id, company_id, title, city, category, salary_min_minor, salary_max_minor, salary_months, experience, education, jd, requirements, tags, status, posted_at) VALUES
  ('job_embermesh_dataplane', 'comp_embermesh', 'High-performance Data Plane Engineer', 'Beijing', 'software_engineering', 3200000, 3900000, 14, '3-5', 'bachelor', 'Optimize the user-space network stack, packet processing pipeline, and NUMA resource allocation; the role is for engineers with work experience.', 'At least three years of C/C++ network development experience, familiar with DPDK, eBPF, and performance counters.', 'network,DPDK,eBPF,experienced', 'open', '2026-02-18'),
  ('job_embermesh_observability', 'comp_embermesh', 'Network Observability Intern', 'Beijing', 'intern', 800000, 1200000, 12, 'intern', 'bachelor', 'Develop traffic sampling, topology visualization, and alert data cleaning scripts; the internship period is no less than four months.', 'On-site four days a week, familiar with Python, SQL, and basic network protocols.', 'intern,observability,network', 'open', '2026-03-22'),
  ('job_embermesh_field', 'comp_embermesh', 'Edge Gateway Support Engineer', 'Chengdu', 'customer_success', 2100000, 2700000, 13, '1-3', 'bachelor', 'Support retail store gateway deployment, remote diagnostics, and version upgrades, covering customers in Southwest China.', 'Able to handle about one week of business trips per month, familiar with Linux network troubleshooting.', 'edge,support,travel', 'closed', '2025-11-09'),
  ('job_harborledger_governance', 'comp_harborledger', 'Data Governance Engineer', 'Shenzhen', 'data_engineering', 2400000, 3100000, 14, '1-3', 'master', 'Build metadata catalogs, field lineage, and data quality rules to serve bank compliance reports.', 'Experience in data warehouse or governance projects, familiar with Spark, SQL, and permission models.', 'governance,metadata,Spark', 'open', '2026-01-16'),
  ('job_harborledger_delivery', 'comp_harborledger', 'Banking Platform Delivery Engineer', 'Shenzhen', 'solution_engineering', 2600000, 3300000, 13, 'fresh_grad', 'bachelor', 'Participate in on-site client environment checks, batch-processing platform deployment, and go-live acceptance; in the first year, mainly serve South China clients.', 'Accept continuous on-site assignment and nighttime change windows, and have a foundation in Java, Linux, and databases.', 'banking,delivery,onsite', 'open', '2026-04-03'),
  ('job_harborledger_audit', 'comp_harborledger', 'Audit Data Analyst', 'Shanghai', 'data_analysis', 1900000, 2400000, 13, 'fresh_grad', 'bachelor', 'Check batch job logs, abnormal transactions, and reporting standards; the role leans toward business audit analysis.', 'Familiar with Excel, SQL, and basic financial terminology; system development experience is not required.', 'audit,SQL,reporting', 'closed', '2025-12-11'),
  ('job_maplearchive_validation', 'comp_maplearchive', 'Storage Validation Intern', 'Hangzhou', 'quality_assurance', 700000, 1000000, 12, 'intern', 'bachelor', 'Construct power outage recovery, media damage, and capacity watermark scenarios, and archive the product test results.', 'Able to intern continuously for five months, understands file systems, and can write Python test scripts.', 'storage,testing,intern', 'open', '2026-03-07'),
  ('job_maplearchive_build', 'comp_maplearchive', 'Build and Release Engineer', 'Hangzhou', 'devops', 2200000, 2800000, 14, '1-3', 'bachelor', 'Maintain cross-platform builds, artifact signing, and offline upgrade package release workflows.', 'More than one year of CI/CD experience, familiar with CMake, containers, and software supply chain tools.', 'build,release,CI/CD', 'open', '2026-04-26'),
  ('job_maplearchive_support', 'comp_maplearchive', 'Archive Migration Consultant', 'Beijing', 'solution_engineering', 2500000, 3000000, 12, '5-10', 'bachelor', 'Plan the historical data migration between the tape library and object storage, and take responsibility for capacity assessment and downtime window design.', 'More than five years of enterprise storage experience, able to serve government and enterprise clients long term.', 'archive,migration,consulting', 'closed', '2025-10-28');

INSERT INTO saved_jobs (user_id, job_id, saved_at) VALUES
  ('usr_lin_che', 'job_embermesh_observability', '2026-03-24T12:18:00Z'),
  ('usr_lin_che', 'job_harborledger_delivery', '2026-04-05T08:42:00Z'),
  ('usr_lin_che', 'job_maplearchive_validation', '2026-03-09T05:27:00Z'),
  ('usr_lin_che', 'job_maplearchive_build', '2026-04-29T11:06:00Z');

INSERT INTO job_alerts (alert_id, user_id, query_json, created_at, active) VALUES
  ('alert_storage_intern_history', 'usr_lin_che', '{"keyword": "storage validation", "city": ["Hangzhou"], "experience": "intern"}', '2026-03-01T06:30:00Z', 0),
  ('alert_network_observe_history', 'usr_lin_che', '{"keyword": "network observability", "city": ["Beijing"], "education": "bachelor"}', '2026-02-25T09:15:00Z', 0),
  ('alert_build_release_history', 'usr_lin_che', '{"keyword": "build release", "city": ["Shanghai", "Hangzhou"], "experience": "1-3"}', '2026-04-12T04:48:00Z', 1),
  ('alert_data_governance_history', 'usr_lin_che', '{"keyword": "data governance", "city": ["Shenzhen"], "education": "master"}', '2026-01-20T13:22:00Z', 0);

COMMIT;
