-- visa_and_advisory environment for a four-person East Asia travel workspace.
-- Records combine relevant options with historical and near-match business context.
-- Later scenario incidents are released only by event mutations, not by this initial state.

PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;

-- advisories: 3 rows
INSERT INTO "advisories" ("country_code", "level", "text", "updated_at") VALUES ('JP', 1, 'Japanoverallsafetysituationgood，pleasenote      regulations。', '2026-01-01T00:00:00Z');
INSERT INTO "advisories" ("country_code", "level", "text", "updated_at") VALUES ('KR', 1, 'South Koreaoverallsafetysituationgood，please  Seoul  crowded      。', '2026-01-01T00:00:00Z');
INSERT INTO "advisories" ("country_code", "level", "text", "updated_at") VALUES ('CN', 1, '    overallsafety  。', '2026-01-01T00:00:00Z');

-- advisory_subscriptions: 4 rows
INSERT INTO "advisory_subscriptions" ("sub_id", "country_code", "sink", "created_at") VALUES ('SUB-JP-240218-I5PDHO', 'JP', 'email:luo.qi@example.com', '2024-02-18T12:20:00Z');
INSERT INTO "advisory_subscriptions" ("sub_id", "country_code", "sink", "created_at") VALUES ('SUB-KR-240629-SPM6FA', 'KR', 'push:device-kr-71c', '2024-06-29T02:45:00Z');
INSERT INTO "advisory_subscriptions" ("sub_id", "country_code", "sink", "created_at") VALUES ('east_sub_cn_ops_mail', 'CN', 'email:ops.reader@example.com', '2025-01-09T09:30:00Z');
INSERT INTO "advisory_subscriptions" ("sub_id", "country_code", "sink", "created_at") VALUES ('SUB-JP-250817-OVOO2H', 'JP', 'push:device-jp-28a', '2025-08-17T06:12:00Z');

-- application_documents: 8 rows
INSERT INTO "application_documents" ("doc_id", "application_id", "kind", "ref", "uploaded_at") VALUES ('east_doc_luo_passport', 'VA-JP-240304-BPJ4X6L', 'passport', 'vault://east-casefiles/luo/passport-redacted.pdf', '2024-03-04T02:25:00Z');
INSERT INTO "application_documents" ("doc_id", "application_id", "kind", "ref", "uploaded_at") VALUES ('east_doc_luo_employment', 'VA-JP-240304-BPJ4X6L', 'employment_proof', 'vault://east-casefiles/luo/employer-letter.pdf', '2024-03-05T06:10:00Z');
INSERT INTO "application_documents" ("doc_id", "application_id", "kind", "ref", "uploaded_at") VALUES ('east_doc_qin_bank', 'VA-KR-240711-DWUTFXR', 'financial_proof', 'vault://east-casefiles/qin/bank-partial.pdf', '2024-07-11T05:22:00Z');
INSERT INTO "application_documents" ("doc_id", "application_id", "kind", "ref", "uploaded_at") VALUES ('east_doc_fan_invite', 'VA-JP-250118-KIXJPQG', 'invitation_letter', 'vault://east-casefiles/fan/mori-invite.pdf', '2025-01-18T03:12:00Z');
INSERT INTO "application_documents" ("doc_id", "application_id", "kind", "ref", "uploaded_at") VALUES ('east_doc_ma_invite', 'VA-KR-250402-4EIDCYF', 'invitation_letter', 'vault://east-casefiles/ma/hanul-invite.pdf', '2025-04-02T01:48:00Z');
INSERT INTO "application_documents" ("doc_id", "application_id", "kind", "ref", "uploaded_at") VALUES ('east_doc_ma_employer', 'VA-KR-250402-4EIDCYF', 'employment_letter', 'vault://east-casefiles/ma/employer-letter.pdf', '2025-04-03T08:15:00Z');
INSERT INTO "application_documents" ("doc_id", "application_id", "kind", "ref", "uploaded_at") VALUES ('east_doc_xu_kinship', 'VA-JP-250908-LV4FNOM', 'kinship_proof', 'vault://east-casefiles/xu/kinship-record.pdf', '2025-09-08T04:32:00Z');
INSERT INTO "application_documents" ("doc_id", "application_id", "kind", "ref", "uploaded_at") VALUES ('east_doc_xu_host', 'VA-JP-250908-LV4FNOM', 'resident_record', 'vault://east-casefiles/xu/host-residence.pdf', '2025-09-10T07:05:00Z');

-- entry_requirements: 4 rows
INSERT INTO "entry_requirements" ("origin_nationality", "destination", "purpose", "visa_required", "allowed_stay_days", "passport_validity_months", "docs_needed_json", "notes", "updated_at") VALUES ('CN', 'JP', 'tourism', 1, 15, 0, '["passport","visa","bank_statement","hotel_reservation","return_ticket"]', 'No universal six-month passport-validity rule applies; the passport must remain valid through the intended stay in Japan.', '2026-01-01T00:00:00Z');
INSERT INTO "entry_requirements" ("origin_nationality", "destination", "purpose", "visa_required", "allowed_stay_days", "passport_validity_months", "docs_needed_json", "notes", "updated_at") VALUES ('CN', 'JP', 'business', 1, 90, 6, '["passport","visa","invitation_letter","business_registration"]', 'businessvisa， provide   please 。', '2026-01-01T00:00:00Z');
INSERT INTO "entry_requirements" ("origin_nationality", "destination", "purpose", "visa_required", "allowed_stay_days", "passport_validity_months", "docs_needed_json", "notes", "updated_at") VALUES ('CN', 'KR', 'tourism', 1, 30, 6, '["passport","visa","bank_statement","hotel_reservation","return_ticket"]', 'A visa application is required for Chinese tourists; the passport should have at least six months of validity at the application checkpoint.', '2026-01-01T00:00:00Z');
INSERT INTO "entry_requirements" ("origin_nationality", "destination", "purpose", "visa_required", "allowed_stay_days", "passport_validity_months", "docs_needed_json", "notes", "updated_at") VALUES ('CN', 'KR', 'business', 1, 90, 6, '["passport","visa","invitation_letter"]', 'businessvisa， provide   please 。', '2026-01-01T00:00:00Z');

-- notifications: 3 rows
INSERT INTO "notifications" ("id", "created_at", "channel", "payload_json") VALUES ('east_notif_jp_2024', '2024-10-03T04:10:00Z', 'email', '{"country_code":"JP","topic":"office_closure_calendar","delivery":"sent"}');
INSERT INTO "notifications" ("id", "created_at", "channel", "payload_json") VALUES ('east_notif_kr_2025', '2025-03-14T07:35:00Z', 'push', '{"country_code":"KR","topic":"visa_center_hours","delivery":"opened"}');
INSERT INTO "notifications" ("id", "created_at", "channel", "payload_json") VALUES ('east_notif_cn_2025', '2025-12-02T12:00:00Z', 'email', '{"country_code":"CN","topic":"document_storage_notice","delivery":"sent"}');

-- visa_applications: 5 rows
INSERT INTO "visa_applications" ("application_id", "user_id", "product_id", "status", "applicant_json", "answers_json", "decision_day", "decision_note", "evisa_doc_ref", "history_json", "created_at", "updated_at") VALUES ('VA-JP-240304-BPJ4X6L', 'usr_luo_qi', 'vp_jp_single_cn', 'approved', '{"full_name":"Luo Qi","passport_last4":"3170"}', '{"stay_days":8,"city":"Osaka","funding":"self"}', 6, 'Employment letter was accepted after employer callback.', 'EVI-VWUENZHHDRR4J', '[{"at":"2024-03-04T02:20:00Z","status":"submitted","detail":"Osaka tourism packet accepted at the counter"},{"at":"2024-03-07T05:45:00Z","status":"reviewing","detail":"Employer telephone verification completed"},{"at":"2024-03-10T08:30:00Z","status":"approved","detail":"Single-entry visa issued"}]', '2024-03-04T02:20:00Z', '2024-03-10T08:30:00Z');
INSERT INTO "visa_applications" ("application_id", "user_id", "product_id", "status", "applicant_json", "answers_json", "decision_day", "decision_note", "evisa_doc_ref", "history_json", "created_at", "updated_at") VALUES ('VA-KR-240711-DWUTFXR', 'usr_qin_mo', 'vp_kr_single_cn', 'rejected', '{"full_name":"Qin Mo","passport_last4":"8452"}', '{"stay_days":5,"city":"Busan","funding":"self"}', 5, 'The submitted bank statement did not cover the requested period.', NULL, '[{"at":"2024-07-11T05:15:00Z","status":"submitted","detail":"Busan itinerary and bank file received"},{"at":"2024-07-16T06:40:00Z","status":"rejected","detail":"Statement period did not meet review window"}]', '2024-07-11T05:15:00Z', '2024-07-16T06:40:00Z');
INSERT INTO "visa_applications" ("application_id", "user_id", "product_id", "status", "applicant_json", "answers_json", "decision_day", "decision_note", "evisa_doc_ref", "history_json", "created_at", "updated_at") VALUES ('VA-JP-250118-KIXJPQG', 'usr_fan_yi', 'vp_jp_business_cn', 'withdrawn', '{"full_name":"Fan Yi","passport_last4":"2094"}', '{"host":"Mori Systems","city":"Nagoya"}', NULL, 'The conference moved online before submission to the consulate.', NULL, '[{"at":"2025-01-18T03:05:00Z","status":"draft","detail":"Nagoya conference documents assembled"},{"at":"2025-01-22T09:10:00Z","status":"withdrawn","detail":"Applicant withdrew after event moved online"}]', '2025-01-18T03:05:00Z', '2025-01-22T09:10:00Z');
INSERT INTO "visa_applications" ("application_id", "user_id", "product_id", "status", "applicant_json", "answers_json", "decision_day", "decision_note", "evisa_doc_ref", "history_json", "created_at", "updated_at") VALUES ('VA-KR-250402-4EIDCYF', 'usr_ma_lin', 'vp_kr_business_cn', 'approved', '{"full_name":"Ma Lin","passport_last4":"6618"}', '{"host":"Hanul Media","city":"Seoul"}', 7, 'Host registration and invitation dates were consistent.', 'EVI-2TGCO3RU7WS5X', '[{"at":"2025-04-02T01:40:00Z","status":"submitted","detail":"Seoul media invitation lodged"},{"at":"2025-04-05T04:20:00Z","status":"reviewing","detail":"Host business registration checked"},{"at":"2025-04-09T07:05:00Z","status":"approved","detail":"Business visitor visa granted"}]', '2025-04-02T01:40:00Z', '2025-04-09T07:05:00Z');
INSERT INTO "visa_applications" ("application_id", "user_id", "product_id", "status", "applicant_json", "answers_json", "decision_day", "decision_note", "evisa_doc_ref", "history_json", "created_at", "updated_at") VALUES ('VA-JP-250908-LV4FNOM', 'usr_xu_ning', 'vp_jp_family_cn', 'approved', '{"full_name":"Xu Ning","passport_last4":"5027"}', '{"host_city":"Saitama","relationship":"sibling"}', 8, 'Kinship records matched the host residence certificate.', 'EVI-YCBMREOFR3DLF', '[{"at":"2025-09-08T04:25:00Z","status":"submitted","detail":"Saitama sibling visit packet delivered"},{"at":"2025-09-12T02:15:00Z","status":"reviewing","detail":"Residence certificate matched host record"},{"at":"2025-09-16T02:50:00Z","status":"approved","detail":"Family visit visa released"}]', '2025-09-08T04:25:00Z', '2025-09-16T02:50:00Z');

-- visa_products: 6 rows
INSERT INTO "visa_products" ("product_id", "destination", "nationality", "name", "processing_time_days", "fee_amount", "fee_currency", "delivery", "form_schema_json") VALUES ('vp_jp_single_cn', 'JP', 'CN', 'Japan single-entry tourism document review', 7, 680, 'CNY', 'consulate_submission', '{"fields":["Passport biodata page","Recent portrait photo","Daily travel outline","Employment or study proof"]}');
INSERT INTO "visa_products" ("product_id", "destination", "nationality", "name", "processing_time_days", "fee_amount", "fee_currency", "delivery", "form_schema_json") VALUES ('vp_jp_business_cn', 'JP', 'CN', 'Japan short-stay business filing service', 8, 920, 'CNY', 'consulate_submission', '{"fields":["Valid passport","Japanese company invitation","Applicant employer letter","Meeting schedule"]}');
INSERT INTO "visa_products" ("product_id", "destination", "nationality", "name", "processing_time_days", "fee_amount", "fee_currency", "delivery", "form_schema_json") VALUES ('vp_jp_family_cn', 'JP', 'CN', 'Japan family-visit application support', 9, 760, 'CNY', 'consulate_submission', '{"fields":["Passport identity page","Kinship certificate","Host resident record","Visit explanation"]}');
INSERT INTO "visa_products" ("product_id", "destination", "nationality", "name", "processing_time_days", "fee_amount", "fee_currency", "delivery", "form_schema_json") VALUES ('vp_kr_single_cn', 'KR', 'CN', 'Korea single-entry tourism application service', 6, 590, 'CNY', 'visa_center', '{"fields":["Passport and prior visas","Color photo","Personal bank statements","Hotel and transport plan"]}');
INSERT INTO "visa_products" ("product_id", "destination", "nationality", "name", "processing_time_days", "fee_amount", "fee_currency", "delivery", "form_schema_json") VALUES ('vp_kr_business_cn', 'KR', 'CN', 'Korea business visitor document package', 7, 840, 'CNY', 'visa_center', '{"fields":["Passport copy","Korean host invitation","Company registration extract","Employment confirmation"]}');
INSERT INTO "visa_products" ("product_id", "destination", "nationality", "name", "processing_time_days", "fee_amount", "fee_currency", "delivery", "form_schema_json") VALUES ('vp_kr_family_cn', 'KR', 'CN', 'Korea family-visit document review', 8, 720, 'CNY', 'visa_center', '{"fields":["Passport details","Relationship evidence","Host identity document","Accommodation statement"]}');

COMMIT;
PRAGMA foreign_keys=ON;
