-- Generated listing_platform seed for camping_trip_procure_30d
BEGIN;
INSERT INTO agents (agent_id, name, agency, phone, rating, deals_count, service_area) VALUES ('agt_camp_1', 'camping business detailplatformofficialcamping business detail', 'platformcamping business detail', '4009000088', 4.8, 15230, 'nationwide SF Express collect inspection');
INSERT INTO listings (listing_id, category, title, city, district, community, price_minor, area_sqm, rooms, metro, attrs_json, description, photos_json, agent_id, owner_user_id, status, listed_at) VALUES ('lst_camp_0001', 'secondhand', 'same modelfolding table-and-chair set discountcamping business detail', 'Kunming', 'Panlong District', 'online', 96000, NULL, NULL, 'near a metro station', '{"price_protect": true, "new_price_minor": 96000}', 'Discounts, price protection, and member rebates for the folding set; verify accounting and crediting.', '["camping business detail", "camping business detail", "camping business detail"]', NULL, 'usr_ye_chen', 'active', '2026-06-15T09:00:00+08:00');
INSERT INTO listings (listing_id, category, title, city, district, community, price_minor, area_sqm, rooms, metro, attrs_json, description, photos_json, agent_id, owner_user_id, status, listed_at) VALUES ('lst_camp_0002', 'secondhand', 'same modelfolding table-and-chair set camping business detail', 'Kunming', 'online', 'urban area', 96000, NULL, NULL, 'near a metro station', '{}', 'current price after reduction。', '["camping business detail"]', 'agt_camp_1', NULL, 'active', '2026-06-15T10:00:00+08:00');
INSERT INTO listings (listing_id, category, title, city, district, community, price_minor, area_sqm, rooms, metro, attrs_json, description, photos_json, agent_id, owner_user_id, status, listed_at) VALUES ('lst_camp_0003', 'secondhand', 'same modelfolding table-and-chair set camping business detail', 'Kunming', 'online', 'urban area', 115200, NULL, NULL, 'near a metro station', '{}', 'your purchase price。', '["camping business detail"]', 'agt_camp_1', NULL, 'active', '2026-06-15T10:00:00+08:00');
INSERT INTO market_stats (stat_id, area, city, category, avg_price_minor, unit, sample_size, period) VALUES ('stat_camp_1', 'camping business detail', 'Kunming', 'secondhand', 96000, 'total', 80, '2026-06');
INSERT INTO market_stats (stat_id, area, city, category, avg_price_minor, unit, sample_size, period) VALUES ('stat_camp_2', 'camping business detail', 'Kunming', 'secondhand', 115200, 'total', 80, '2026-06');
INSERT INTO _counters (key,value) VALUES ('listing_seq',3),('viewing_seq',0),('contact_seq',0),('subscription_seq',0),('saved_seq',0);
COMMIT;
