-- Generated listing_platform seed for camera_resale_30d
BEGIN;
INSERT INTO agents (agent_id, name, agency, phone, rating, deals_count, service_area) VALUES ('agt_rscam_1', 'Secondhand Platform Official Inspection', 'Platform Escrow Service', '4009000088', 4.8, 15230, 'Nationwide SF Express collect-on-delivery inspection');
INSERT INTO listings (listing_id, category, title, city, district, community, price_minor, area_sqm, rooms, metro, attrs_json, description, photos_json, agent_id, owner_user_id, status, listed_at) VALUES ('lst_rscam_0001', 'secondhand', 'Sonar A7M3 Full-Frame Mirrorless Body | First-Hand Personal Ownership', 'Guangzhou City', 'Haizhu District', 'Kecun', 800000, NULL, NULL, 'Line 3·Kecun Station', '{"condition_grade":"Good","shutter_count":18420,"serial_no":"SNR-A7M3-3521","verification_code":"VRF-RSCAM-3521G","original_invoice":true,"platform_fee_minor":20000,"escrow_required":true}', 'Purchased at the end of 2025, with all functions testing normally; slight marks from a quick-release tripod plate on the bottom, with no impact marks on the screen or mount. Includes the original battery, charger, body cap, and original invoice. Platform-escrowed orders only.', '["Front of body and serial number","Signs of use on bottom","Screen powered on","Mount and sensor","Shutter count screenshot","Redacted page of original invoice"]', 'agt_rscam_1', 'usr_zhan_peng', 'active', '2026-06-15T09:00:00+08:00');
INSERT INTO listings (listing_id, category, title, city, district, community, price_minor, area_sqm, rooms, metro, attrs_json, description, photos_json, agent_id, owner_user_id, status, listed_at) VALUES ('lst_rscam_0002', 'secondhand', 'Same-City A7M3 Body | High Shutter Count, No Invoice', 'Guangzhou City', 'Baiyun District', 'Sanyuanli', 715000, NULL, NULL, 'Line 2·Sanyuanli Station', '{"condition_grade":"Fair","shutter_count":61200,"original_invoice":false,"escrow_required":true}', 'The body functions normally, but the grip leather is lifting; the seller cannot provide the original invoice. The price includes one third-party battery.', '["Front of body","Grip leather","Shutter count"]', 'agt_rscam_1', NULL, 'active', '2026-06-12T10:00:00+08:00');
INSERT INTO listings (listing_id, category, title, city, district, community, price_minor, area_sqm, rooms, metro, attrs_json, description, photos_json, agent_id, owner_user_id, status, listed_at) VALUES ('lst_rscam_0003', 'secondhand', 'A7M3 Low-Shutter-Count Kit | Original Battery and Packaging Included', 'Guangzhou City', 'Tianhe District', 'Gangding', 835000, NULL, NULL, 'Line 3·Gangding Station', '{"condition_grade":"Excellent","shutter_count":9600,"original_invoice":true,"escrow_required":true}', 'Low-shutter-count personal camera; the packaging and body numbers match. No obvious edge wear exposing the underlying material. Supports shipment after platform inspection.', '["Six sides of body","Shutter count","Box label number"]', 'agt_rscam_1', NULL, 'active', '2026-06-11T10:00:00+08:00');
INSERT INTO market_stats (stat_id, area, city, category, avg_price_minor, unit, sample_size, period) VALUES ('stat_rscam_1', 'Guangzhou A7M3 Fair Condition', 'Guangzhou City', 'secondhand', 724000, 'total', 60, '2026-06');
INSERT INTO market_stats (stat_id, area, city, category, avg_price_minor, unit, sample_size, period) VALUES ('stat_rscam_2', 'Guangzhou A7M3 Good Condition with Invoice', 'Guangzhou City', 'secondhand', 806000, 'total', 60, '2026-06');
INSERT INTO contacts (contact_id,user_id,listing_id,agent_id,message,created_at) VALUES ('contact_rscam_initial','usr_zhan_peng','lst_rscam_0001','agt_rscam_1','The buyer asks about the shutter count, marks on the bottom, and whether the original invoice can be verified in the platform order.','2026-06-15T09:42:00+08:00');
INSERT INTO _counters (key,value) VALUES ('listing_seq',3),('viewing_seq',0),('contact_seq',1),('subscription_seq',0),('saved_seq',0);
COMMIT;

-- Curated Guangzhou secondhand search space: comparable but non-target bodies, lenses and studio accessories.
BEGIN;
INSERT INTO listings (listing_id,category,title,city,district,community,price_minor,area_sqm,rooms,metro,attrs_json,description,photos_json,agent_id,owner_user_id,status,listed_at) VALUES
('lst_camera_a6400_body','secondhand','APS-C Mirrorless Body, Approximately 20,000 Shutter Count','Guangzhou City','Tianhe District','Tiyu West','386000',NULL,NULL,'Line 3·Tiyu Xilu Station','{"condition":"85% new","shutter_count":21840}','Slight edge wear on the body, with no obvious dust spots on the sensor. Includes the original battery and charger.','["Front of body","Wear on bottom","Shutter screenshot"]',NULL,NULL,'active','2026-05-18T10:20:00+08:00'),
('lst_camera_xt30_body','secondhand','Retro Mirrorless Body, Silver-and-Black Colorway','Guangzhou City','Yuexiu District','Dongshankou','468000',NULL,NULL,'Line 1·Dongshankou Station','{"condition":"90% new","shutter_count":12600}','The dials have normal resistance, the screen protector is still installed, and the camera has never been repaired. The box and body numbers match.','["Silver-and-black body","Dials","Box label"]',NULL,NULL,'active','2026-05-22T16:05:00+08:00'),
('lst_camera_35mm_lens','secondhand','35mm F1.8 Autofocus Lens','Guangzhou City','Haizhu District','Jiangnan West','156000',NULL,NULL,'Line 2·Jiangnan Xilu Station','{"condition":"88% new","mount":"E"}','The glass is clear and fungus-free, the lens hood has scuff marks, and focusing is quiet. Includes front and rear caps.','["Front element","Rear element","Lens hood"]',NULL,NULL,'active','2026-05-26T09:18:00+08:00'),
('lst_camera_85mm_lens','secondhand','85mm F1.8 Portrait Lens','Guangzhou City','Panyu District','Wanbo','238000',NULL,NULL,'Line 7·Nancun Wanbo Station','{"condition":"92% new","mount":"E"}','No impact marks on the lens barrel, clean aperture blades, and the minimum-focus-distance test is normal.','["Lens barrel","Lens glass","Test sample"]',NULL,NULL,'active','2026-05-30T14:42:00+08:00'),
('lst_camera_flash','secondhand','Round-Head On-Camera Flash with Wireless Trigger','Guangzhou City','Baiyun District','Sanyuanli','92000',NULL,NULL,'Line 2·Sanyuanli Station','{"condition":"80% new","ttl":true}','The flash head rotates smoothly, the battery compartment has no leakage, and the trigger range is stable indoors.','["Flash head","Battery compartment","Wireless trigger"]',NULL,NULL,'active','2026-06-02T19:26:00+08:00'),
('lst_camera_tripod','secondhand','Carbon-Fiber Travel Tripod, Reverse-Folding Design','Guangzhou City','Liwan District','Chen Clan Academy','128000',NULL,NULL,'Line 1·Chen Clan Academy Station','{"condition":"85% new","max_load_kg":8}','The leg locks work normally, the center column shows signs of use, and a short center column and tripod bag are included.','["Deployed","Leg locks","Center column"]',NULL,NULL,'active','2026-06-05T11:10:00+08:00'),
('lst_camera_monitor','secondhand','Five-Inch On-Camera Monitor','Guangzhou City','Tianhe District','Gangding','116000',NULL,NULL,'Line 3·Gangding Station','{"condition":"90% new","input":"HDMI"}','The screen has no dead pixels, false color and peaking work normally, and a sun hood is included.','["Powered-on display","Ports","Sun hood"]',NULL,NULL,'active','2026-05-14T15:33:00+08:00'),
('lst_camera_recorder','secondhand','Dual-Track Portable Recorder','Guangzhou City','Haizhu District','Kecun','78000',NULL,NULL,'Line 3·Kecun Station','{"condition":"82% new","tracks":2}','The knobs and XLR ports work normally. There are scratches on the side of the body. Memory card not included.','["Front","Ports","Scratches"]',NULL,NULL,'active','2026-05-20T08:47:00+08:00'),
('lst_camera_led_panel','secondhand','Bi-Color LED Light Panels, Two-Light Kit','Guangzhou City','Huangpu District','Science City','142000',NULL,NULL,'Line 6·Xiangang Station','{"condition":"88% new","lights":2}','Both lights have matching brightness, the diffusion panels are intact, and one knob on one light stand has been replaced.','["Both lights powered on","Diffusion panels","Light-stand knob"]',NULL,NULL,'active','2026-05-24T18:12:00+08:00'),
('lst_camera_gimbal','secondhand','Three-Axis Mirrorless Gimbal, Standard Kit','Guangzhou City','Panyu District','University Town','165000',NULL,NULL,'Line 4·University Town North Station','{"condition":"86% new","payload_kg":2.6}','The three-axis motors make no abnormal noise, the quick-release plate is included, and there is slight wear on the bottom of the handle.','["Folded","Quick-release plate","Bottom of handle"]',NULL,NULL,'active','2026-05-28T12:55:00+08:00'),
('lst_camera_sd_cards','secondhand','High-Speed 128GB SD Cards, Two-Pack','Guangzhou City','Yuexiu District','Beijing Road','62000',NULL,NULL,'Line 6·Beijing Road Station','{"condition":"Normal health","capacity_gb":256}','Both cards have completed full-disk write tests. Photos of the serial numbers are available. Sold only as a set.','["Two cards","Speed-test screenshot","Serial numbers"]',NULL,NULL,'active','2026-06-01T21:08:00+08:00'),
('lst_camera_backpack','secondhand','20L Black Camera Backpack','Guangzhou City','Haizhu District','Pazhou','68000',NULL,NULL,'Line 8·Pazhou Station','{"condition":"90% new","capacity_l":20}','All padded dividers are included, the back-mesh fabric has no damage, and the rain cover is unused.','["Front","Interior","Rain cover"]',NULL,NULL,'active','2026-05-12T10:36:00+08:00'),
('lst_camera_light_meter','secondhand','Handheld Incident Light Meter','Guangzhou City','Liwan District','Shamian','108000',NULL,NULL,'Line 6·Cultural Park Station','{"condition":"85% new","battery":"AA"}','The lumisphere has no yellowing. Compared with the studio reference meter, the error is less than one-third of a stop.','["Meter body","Lumisphere","Comparison reading"]',NULL,NULL,'active','2026-05-16T17:24:00+08:00'),
('lst_camera_color_chart','secondhand','Portable Mini Color Chart','Guangzhou City','Tianhe District','Zhujiang New Town','36000',NULL,NULL,'Line 5·Zhujiang New Town Station','{"condition":"Lightly used","panels":24}','There are no fingerprints on the color patches, the case hinge works normally, and the production batch is shown on the back.','["Color patches","Case","Batch"]',NULL,NULL,'active','2026-05-21T13:02:00+08:00'),
('lst_camera_battery_set','secondhand','Three Mirrorless Batteries with Dual Charger','Guangzhou City','Baiyun District','Jiahewanggang','54000',NULL,NULL,'Line 2·Jiahewanggang Station','{"condition":"Different cycle counts","batteries":3}','The three batteries have different runtimes. The seller provides individual health screenshots and a dual-charger test.','["Three batteries","Health","Dual charger"]',NULL,NULL,'active','2026-05-25T09:44:00+08:00'),
('lst_camera_filter_kit','secondhand','67mm ND and CPL Filter Set','Guangzhou City','Huangpu District','Yuzhu','47000',NULL,NULL,'Line 5·Yuzhu Station','{"condition":"90% new","diameter_mm":67}','The filters have no obvious scratches, the ND adjustment ring turns smoothly, and a storage pouch is included.','["Filter set","Filter surfaces","Storage pouch"]',NULL,NULL,'active','2026-05-31T15:16:00+08:00'),
('lst_camera_macro_rail','secondhand','Four-Way Macro Focusing Rail with Head','Guangzhou City','Panyu District','Shiqiao','58000',NULL,NULL,'Line 3·Shiqiao Station','{"condition":"88% new","travel_mm":100}','The gear drive has no obvious backlash, and the quick-release clamp is compatible with the Arca standard.','["Rail overall","Gear","Clamp"]',NULL,NULL,'active','2026-06-04T18:30:00+08:00'),
('lst_camera_dry_cabinet','secondhand','50L Electronic Dry Cabinet','Guangzhou City','Haizhu District','Chigang','72000',NULL,NULL,'Line 8·Chigang Station','{"condition":"85% new","capacity_l":50}','The humidity display differs from the independent meter by approximately 3%. The door seal is intact. Pickup only.','["Cabinet","Humidity display","Door seal"]',NULL,NULL,'active','2026-06-07T10:48:00+08:00'),
('lst_camera_printer','secondhand','A3+ Photo Printer','Guangzhou City','Tianhe District','Yuancun','286000',NULL,NULL,'Line 5·Yuancun Station','{"condition":"80% new","nozzles":"test_ok"}','The nozzle check is complete, the maintenance tank is 42% full, and the ink batches vary. Test page included.','["Printer","Nozzle test","Ink status"]',NULL,NULL,'active','2026-06-09T14:06:00+08:00'),
('lst_camera_slider','secondhand','80cm Manual Camera Slider','Guangzhou City','Foshan City','Qiandeng Lake','88000',NULL,NULL,'Guangfo Line·Qiandeng Lake Station','{"condition":"87% new","length_cm":80}','The slider moves smoothly, the feet at both ends are adjustable, and there is one shallow mark on the rail.','["Full length","Slider","Shallow mark on rail"]',NULL,NULL,'active','2026-06-11T16:40:00+08:00');
INSERT INTO saved_listings (user_id,listing_id,saved_at) VALUES
('usr_zhan_peng','lst_camera_a6400_body','2026-05-18T10:28:00+08:00'),('usr_zhan_peng','lst_camera_xt30_body','2026-05-22T16:13:00+08:00'),('usr_zhan_peng','lst_camera_35mm_lens','2026-05-26T09:26:00+08:00'),('usr_zhan_peng','lst_camera_85mm_lens','2026-05-30T14:50:00+08:00'),
('usr_zhan_peng','lst_camera_flash','2026-06-02T19:34:00+08:00'),('usr_zhan_peng','lst_camera_tripod','2026-06-05T11:18:00+08:00'),('usr_zhan_peng','lst_camera_monitor','2026-05-14T15:41:00+08:00'),('usr_zhan_peng','lst_camera_recorder','2026-05-20T08:55:00+08:00'),
('usr_zhan_peng','lst_camera_led_panel','2026-05-24T18:20:00+08:00'),('usr_zhan_peng','lst_camera_gimbal','2026-05-28T13:03:00+08:00'),('usr_zhan_peng','lst_camera_sd_cards','2026-06-01T21:16:00+08:00'),('usr_zhan_peng','lst_camera_backpack','2026-05-12T10:44:00+08:00'),
('usr_zhan_peng','lst_camera_light_meter','2026-05-16T17:32:00+08:00'),('usr_zhan_peng','lst_camera_color_chart','2026-05-21T13:10:00+08:00'),('usr_zhan_peng','lst_camera_battery_set','2026-05-25T09:52:00+08:00'),('usr_zhan_peng','lst_camera_filter_kit','2026-05-31T15:24:00+08:00'),
('usr_zhan_peng','lst_camera_macro_rail','2026-06-04T18:38:00+08:00'),('usr_zhan_peng','lst_camera_dry_cabinet','2026-06-07T10:56:00+08:00'),('usr_zhan_peng','lst_camera_printer','2026-06-09T14:14:00+08:00'),('usr_zhan_peng','lst_camera_slider','2026-06-11T16:48:00+08:00');
INSERT INTO contacts (contact_id,user_id,listing_id,agent_id,message,created_at) VALUES
('contact_camera_a6400','usr_zhan_peng','lst_camera_a6400_body',NULL,'Please provide the date of the most recent sensor cleaning and the complete shutter-count page.','2026-05-18T10:35:00+08:00'),
('contact_camera_xt30','usr_zhan_peng','lst_camera_xt30_body',NULL,'Does the serial number on the box match the body, and do the dials ever skip settings?','2026-05-22T16:20:00+08:00'),
('contact_camera_35mm','usr_zhan_peng','lst_camera_35mm_lens',NULL,'Could you take a video of the rear element under strong light and the minimum-focus-distance test?','2026-05-26T09:33:00+08:00'),
('contact_camera_85mm','usr_zhan_peng','lst_camera_85mm_lens',NULL,'Please confirm the blade movement when the aperture is fully open and the condition of the mount screws.','2026-05-30T14:57:00+08:00'),
('contact_camera_flash','usr_zhan_peng','lst_camera_flash',NULL,'Is recycling stable through ten consecutive flashes, and what is the firmware version of the wireless trigger?','2026-06-02T19:41:00+08:00'),
('contact_camera_tripod','usr_zhan_peng','lst_camera_tripod',NULL,'Does the lowest leg section slip, and what is the packed length after folding the legs back?','2026-06-05T11:25:00+08:00'),
('contact_camera_monitor','usr_zhan_peng','lst_camera_monitor',NULL,'Does the monitor support custom LUTs, and is the HDMI port loose?','2026-05-14T15:48:00+08:00'),
('contact_camera_recorder','usr_zhan_peng','lst_camera_recorder',NULL,'Can both channels of phantom power be enabled simultaneously, and is the knob noise floor noticeable?','2026-05-20T09:02:00+08:00'),
('contact_camera_led','usr_zhan_peng','lst_camera_led_panel',NULL,'How much does the color temperature differ between the two lights at 5600K, and what is the maximum height of the light stand?','2026-05-24T18:27:00+08:00'),
('contact_camera_gimbal','usr_zhan_peng','lst_camera_gimbal',NULL,'Has the gimbal been unlinked from its account, and what are the specifications of the quick-release plate screws?','2026-05-28T13:10:00+08:00'),
('contact_camera_cards','usr_zhan_peng','lst_camera_sd_cards',NULL,'Please send the complete write-test results and a close-up of the serial numbers on the backs of the cards.','2026-06-01T21:23:00+08:00'),
('contact_camera_bag','usr_zhan_peng','lst_camera_backpack',NULL,'Does the back-mesh fabric have sweat stains, and is the rain-cover pouch sewn inside the bag?','2026-05-12T10:51:00+08:00'),
('contact_camera_meter','usr_zhan_peng','lst_camera_light_meter',NULL,'Can you provide the light source and readings used for the comparison with the reference meter?','2026-05-16T17:39:00+08:00'),
('contact_camera_chart','usr_zhan_peng','lst_camera_color_chart',NULL,'What year was the color chart produced, and was it exposed to strong light for a long time?','2026-05-21T13:17:00+08:00'),
('contact_camera_battery','usr_zhan_peng','lst_camera_battery_set',NULL,'Please label the cycle count of each of the three batteries separately. What is the power per slot on the dual charger?','2026-05-25T09:59:00+08:00'),
('contact_camera_filter','usr_zhan_peng','lst_camera_filter_kit',NULL,'Does the maximum ND setting produce obvious color casts, and does the CPL filter frame ever stick?','2026-05-31T15:31:00+08:00'),
('contact_camera_macro','usr_zhan_peng','lst_camera_macro_rail',NULL,'Are the rail markings clear, and approximately how many millimeters of backlash does it have when driven in reverse?','2026-06-04T18:45:00+08:00'),
('contact_camera_cabinet','usr_zhan_peng','lst_camera_dry_cabinet',NULL,'How long does it take to stabilize at 45% humidity, and has the dehumidifying element ever been replaced?','2026-06-07T11:03:00+08:00'),
('contact_camera_printer','usr_zhan_peng','lst_camera_printer',NULL,'Please provide the original nozzle-check image and the current remaining ink levels for each color.','2026-06-09T14:21:00+08:00'),
('contact_camera_slider','usr_zhan_peng','lst_camera_slider',NULL,'Does the slider resistance change between the two ends, and what are the thread specifications of the feet?','2026-06-11T16:55:00+08:00');
INSERT INTO market_stats (stat_id,area,city,category,avg_price_minor,unit,sample_size,period) VALUES
('stat_camera_body_apsc','Guangzhou APS-C Body','Guangzhou City','secondhand',418000,'total',84,'2026-05'),('stat_camera_body_retro','Guangzhou Retro Mirrorless','Guangzhou City','secondhand',492000,'total',53,'2026-05'),
('stat_camera_lens_wide','Guangzhou 35mm Prime','Guangzhou City','secondhand',168000,'total',71,'2026-05'),('stat_camera_lens_portrait','Guangzhou 85mm Prime','Guangzhou City','secondhand',246000,'total',66,'2026-05'),
('stat_camera_flash_ttl','Guangzhou TTL Flash','Guangzhou City','secondhand',98000,'total',49,'2026-06'),('stat_camera_tripod_carbon','Guangzhou Carbon-Fiber Travel Tripod','Guangzhou City','secondhand',136000,'total',42,'2026-06'),
('stat_camera_monitor_five','Guangzhou Five-Inch Monitor','Guangzhou City','secondhand',121000,'total',38,'2026-05'),('stat_camera_audio_dual','Guangzhou Dual-Track Recorder','Guangzhou City','secondhand',82000,'total',44,'2026-05'),
('stat_camera_led_pair','Guangzhou Two-Light Lighting Kit','Guangzhou City','secondhand',149000,'total',35,'2026-05'),('stat_camera_gimbal_mirrorless','Guangzhou Mirrorless Gimbal','Guangzhou City','secondhand',172000,'total',59,'2026-05'),
('stat_camera_card_v90','Guangzhou High-Speed Memory Card','Guangzhou City','secondhand',66000,'total',92,'2026-06'),('stat_camera_bag_twenty','Guangzhou 20L Camera Bag','Guangzhou City','secondhand',72000,'total',47,'2026-05'),
('stat_camera_meter_incident','Guangzhou Incident Light Meter','Guangzhou City','secondhand',114000,'total',31,'2026-05'),('stat_camera_chart_portable','Guangzhou Portable Color Chart','Guangzhou City','secondhand',39000,'total',28,'2026-05'),
('stat_camera_battery_np','Guangzhou Mirrorless Battery Kit','Guangzhou City','secondhand',58000,'total',76,'2026-05'),('stat_camera_filter_67','Guangzhou 67mm Filter Set','Guangzhou City','secondhand',51000,'total',64,'2026-05'),
('stat_camera_macro_rail','Guangzhou Macro Rail','Guangzhou City','secondhand',62000,'total',23,'2026-06'),('stat_camera_dry_fifty','Guangzhou 50L Dry Cabinet','Guangzhou City','secondhand',78000,'total',51,'2026-06'),
('stat_camera_printer_a3','Guangzhou A3+ Photo Printer','Guangzhou City','secondhand',298000,'total',26,'2026-06'),('stat_camera_slider_manual','Guangzhou Manual Camera Slider','Guangzhou City','secondhand',94000,'total',33,'2026-06');
UPDATE _counters SET value=23 WHERE key='listing_seq'; UPDATE _counters SET value=20 WHERE key='contact_seq';
COMMIT;
