-- bali_22d_jun maps env
-- Places, roads, and road/transit events for the Bali 22-day trip.
-- Schema matches servers/maps_mock exactly.

BEGIN TRANSACTION;

-- ========== places ==========
-- Columns: place_id, name, category, lat, lng, country, city, rating, price_level, hours_json, phone, website, formatted
INSERT INTO places (place_id, name, category, lat, lng, country, city, rating, price_level, hours_json, phone, website, formatted) VALUES ('pl_dps_airport', 'Ngurah Rai International Airport (DPS)', 'airport', -8.7482, 115.1672, 'ID', 'Bali', 4.2, NULL, '{"open_24h": true}', '+62361936111', NULL, 'Jl. Raya Gusti Ngurah Rai, Tuban, Kuta');
INSERT INTO places (place_id, name, category, lat, lng, country, city, rating, price_level, hours_json, phone, website, formatted) VALUES ('pl_pvg_airport', 'Shanghai Pudong International Airport (PVG)', 'airport', 31.1443, 121.8083, 'CN', 'Shanghai', 4.0, NULL, '{"open_24h": true}', '+862196990990', NULL, 'Pudong New Area, Shanghai');
INSERT INTO places (place_id, name, category, lat, lng, country, city, rating, price_level, hours_json, phone, website, formatted) VALUES ('pl_bimc_kuta', 'BIMC Hospital Kuta', 'hospital', -8.7231, 115.1767, 'ID', 'Bali', 4.5, 3, '{"mon_fri": "00:00-24:00", "sat_sun": "00:00-24:00"}', '+62361761263', 'https://bimcbali.com', 'Jl. Bypass Ngurah Rai No.100X, Kuta. 24-hour emergency department, obstetrics/gynecology coverage, and an English-speaking international patient desk.');
INSERT INTO places (place_id, name, category, lat, lng, country, city, rating, price_level, hours_json, phone, website, formatted) VALUES ('pl_siloam_bali', 'Siloam Hospitals Bali', 'hospital', -8.6812, 115.2148, 'ID', 'Bali', 4.3, 3, '{"mon_fri": "00:00-24:00", "sat_sun": "00:00-24:00"}', '+62361779900', 'https://siloamhospitals.com', 'Jl. Sunset Road No.818, Kuta. Emergency and obstetrics services operate around the clock; English interpretation is available through the international desk.');
INSERT INTO places (place_id, name, category, lat, lng, country, city, rating, price_level, hours_json, phone, website, formatted) VALUES ('pl_kasih_ibu_ubud', 'Kasih Ibu Hospital Ubud', 'hospital', -8.5058, 115.2645, 'ID', 'Bali', 4.0, 2, '{"mon_fri": "00:00-24:00", "sat_sun": "00:00-24:00"}', '+62361978978', NULL, 'Jl. Raya Ubud, Ubud. General emergency care is available 24 hours; obstetric coverage is on call and English support should be confirmed by phone.');
INSERT INTO places (place_id, name, category, lat, lng, country, city, rating, price_level, hours_json, phone, website, formatted) VALUES ('pl_tanah_lot', 'Tanah Lot Temple', 'temple', -8.6212, 115.0868, 'ID', 'Bali', 4.6, 1, '{"daily": "07:00-19:00"}', NULL, NULL, 'Beraban, Kediri, Tabanan');
INSERT INTO places (place_id, name, category, lat, lng, country, city, rating, price_level, hours_json, phone, website, formatted) VALUES ('pl_uluwatu', 'Uluwatu Temple', 'temple', -8.8292, 115.0849, 'ID', 'Bali', 4.7, 1, '{"daily": "07:00-19:00"}', NULL, NULL, 'Pecatu, South Kuta. The cliff route to the temple includes more than 250 steep stone stairs.');
INSERT INTO places (place_id, name, category, lat, lng, country, city, rating, price_level, hours_json, phone, website, formatted) VALUES ('pl_tirta_empul', 'Tirta Empul Temple', 'temple', -8.4153, 115.3154, 'ID', 'Bali', 4.5, 1, '{"daily": "08:00-18:00"}', NULL, NULL, 'Tampaksiring, Gianyar');
INSERT INTO places (place_id, name, category, lat, lng, country, city, rating, price_level, hours_json, phone, website, formatted) VALUES ('pl_besakih', 'Besakih Temple (Mother Temple)', 'temple', -8.3745, 115.4531, 'ID', 'Bali', 4.4, 1, '{"daily": "08:00-17:00"}', NULL, NULL, 'Besakih, Rendang, Karangasem. Near Mt Agung.');
INSERT INTO places (place_id, name, category, lat, lng, country, city, rating, price_level, hours_json, phone, website, formatted) VALUES ('pl_taman_ayun', 'Taman Ayun Temple', 'temple', -8.5416, 115.1729, 'ID', 'Bali', 4.3, 1, '{"daily": "08:00-17:00"}', NULL, NULL, 'Mengwi, Badung. Flat ground, accessible.');
INSERT INTO places (place_id, name, category, lat, lng, country, city, rating, price_level, hours_json, phone, website, formatted) VALUES ('pl_tegallalang', 'Tegallalang Rice Terrace', 'nature', -8.4312, 115.2789, 'ID', 'Bali', 4.5, 1, '{"daily": "06:00-18:00"}', NULL, NULL, 'Tegallalang, Gianyar. 200+ uneven stone steps. 2.5km walking on slopes.');
INSERT INTO places (place_id, name, category, lat, lng, country, city, rating, price_level, hours_json, phone, website, formatted) VALUES ('pl_ceking_terrace', 'Ceking Rice Terrace (Flat Viewpoint)', 'nature', -8.4289, 115.2801, 'ID', 'Bali', 4.2, 1, '{"daily": "06:00-18:00"}', NULL, NULL, 'Ceking, Tegallalang. The viewpoint has a 0.4 km mostly level paved path and a curb-free entrance.');
INSERT INTO places (place_id, name, category, lat, lng, country, city, rating, price_level, hours_json, phone, website, formatted) VALUES ('pl_jatiluwih', 'Jatiluwih Rice Terraces (UNESCO)', 'nature', -8.3692, 115.1308, 'ID', 'Bali', 4.6, 1, '{"daily": "08:00-17:00"}', NULL, NULL, 'Jatiluwih, Penebel, Tabanan. Mostly flat walking paths.');
INSERT INTO places (place_id, name, category, lat, lng, country, city, rating, price_level, hours_json, phone, website, formatted) VALUES ('pl_kintamani_view', 'Kintamani Viewpoint (Mt Batur)', 'viewpoint', -8.2439, 115.3604, 'ID', 'Bali', 4.4, 1, '{"daily": "06:00-18:00"}', NULL, NULL, 'Kintamani, Bangli. 12km from Agung crater. CLOSED when volcano Level 3.');
INSERT INTO places (place_id, name, category, lat, lng, country, city, rating, price_level, hours_json, phone, website, formatted) VALUES ('pl_ubud_palace', 'Ubud Royal Palace', 'attraction', -8.5063, 115.2624, 'ID', 'Bali', 4.3, 1, '{"daily": "08:00-19:00"}', NULL, NULL, 'Jl. Raya Ubud, Ubud');
INSERT INTO places (place_id, name, category, lat, lng, country, city, rating, price_level, hours_json, phone, website, formatted) VALUES ('pl_ubud_market', 'Ubud Art Market', 'shopping', -8.5061, 115.2629, 'ID', 'Bali', 4.2, 1, '{"daily": "06:00-18:00"}', NULL, NULL, 'Jl. Raya Ubud, Ubud');
INSERT INTO places (place_id, name, category, lat, lng, country, city, rating, price_level, hours_json, phone, website, formatted) VALUES ('pl_monkey_forest', 'Sacred Monkey Forest Sanctuary', 'nature', -8.5183, 115.2588, 'ID', 'Bali', 4.5, 1, '{"daily": "08:30-18:00"}', NULL, NULL, 'Jl. Monkey Forest, Ubud. Paved paths, mostly flat.');
INSERT INTO places (place_id, name, category, lat, lng, country, city, rating, price_level, hours_json, phone, website, formatted) VALUES ('pl_campuhan_ridge', 'Campuhan Ridge Walk', 'nature', -8.5025, 115.2517, 'ID', 'Bali', 4.6, 0, '{"daily": "06:00-18:00"}', NULL, NULL, 'Ubud. Gentle paved path 2km. Flat, suitable for all.');
INSERT INTO places (place_id, name, category, lat, lng, country, city, rating, price_level, hours_json, phone, website, formatted) VALUES ('pl_seminyak_beach', 'Seminyak Beach', 'beach', -8.6863, 115.1567, 'ID', 'Bali', 4.4, 0, '{"daily": "00:00-24:00"}', NULL, NULL, 'Seminyak, Kuta Utara. Flat sand walking.');
INSERT INTO places (place_id, name, category, lat, lng, country, city, rating, price_level, hours_json, phone, website, formatted) VALUES ('pl_nusa_dua_beach', 'Nusa Dua Beach', 'beach', -8.8028, 115.2341, 'ID', 'Bali', 4.5, 0, '{"daily": "00:00-24:00"}', NULL, NULL, 'Nusa Dua. Calm waters, flat access.');
INSERT INTO places (place_id, name, category, lat, lng, country, city, rating, price_level, hours_json, phone, website, formatted) VALUES ('pl_sanur_beach', 'Sanur Beach', 'beach', -8.6932, 115.2621, 'ID', 'Bali', 4.3, 0, '{"daily": "00:00-24:00"}', NULL, NULL, 'Sanur. Calm, shallow, good for non-swimmers.');
INSERT INTO places (place_id, name, category, lat, lng, country, city, rating, price_level, hours_json, phone, website, formatted) VALUES ('pl_waterbom', 'Waterbom Bali', 'attraction', -8.7264, 115.1694, 'ID', 'Bali', 4.6, 2, '{"daily": "09:00-18:00"}', '+62361755676', 'https://waterbom-bali.com', 'Jl. Kartika Plaza, Kuta');
INSERT INTO places (place_id, name, category, lat, lng, country, city, rating, price_level, hours_json, phone, website, formatted) VALUES ('pl_bali_safari', 'Bali Safari and Marine Park', 'attraction', -8.5917, 115.3381, 'ID', 'Bali', 4.3, 2, '{"daily": "09:00-17:00"}', '+62361950000', NULL, 'Jl. Bypass Prof. Dr. Ida Bagus Mantra, Gianyar');
INSERT INTO places (place_id, name, category, lat, lng, country, city, rating, price_level, hours_json, phone, website, formatted) VALUES ('pl_sekumpul_waterfall', 'Sekumpul Waterfall', 'nature', -8.1756, 115.3823, 'ID', 'Bali', 4.7, 1, '{"daily": "07:00-17:00"}', NULL, NULL, 'Sekumpul, Sawan, Buleleng. 400+ stairs down and up. Very strenuous.');
INSERT INTO places (place_id, name, category, lat, lng, country, city, rating, price_level, hours_json, phone, website, formatted) VALUES ('pl_tegenungan_waterfall', 'Tegenungan Waterfall', 'nature', -8.5753, 115.2893, 'ID', 'Bali', 4.3, 1, '{"daily": "06:30-18:30"}', NULL, NULL, 'Kemenuh, Sukawati, Gianyar. ~100 stairs.');
INSERT INTO places (place_id, name, category, lat, lng, country, city, rating, price_level, hours_json, phone, website, formatted) VALUES ('pl_warung_babi_guling', 'Warung Babi Guling Ibu Oka', 'restaurant', -8.5048, 115.2631, 'ID', 'Bali', 4.4, 1, '{"daily": "11:00-15:00"}', NULL, NULL, 'Jl. Tegal Sari No.2, Ubud. NO seafood, pork-based.');
INSERT INTO places (place_id, name, category, lat, lng, country, city, rating, price_level, hours_json, phone, website, formatted) VALUES ('pl_locavore', 'Locavore Restaurant', 'restaurant', -8.5023, 115.2609, 'ID', 'Bali', 4.7, 3, '{"tue_sat": "12:00-14:30, 18:00-22:00"}', '+62361977733', NULL, 'Jl. Dewi Sita, Ubud. Fine dining, accommodates allergies on request.');
INSERT INTO places (place_id, name, category, lat, lng, country, city, rating, price_level, hours_json, phone, website, formatted) VALUES ('pl_naughty_nuri', 'Naughty Nuris Warung', 'restaurant', -8.5058, 115.2573, 'ID', 'Bali', 4.3, 2, '{"daily": "11:00-22:00"}', NULL, NULL, 'Jl. Raya Sanggingan, Ubud. BBQ ribs, no seafood.');
INSERT INTO places (place_id, name, category, lat, lng, country, city, rating, price_level, hours_json, phone, website, formatted) VALUES ('pl_sardine_seminyak', 'Sardine Restaurant', 'restaurant', -8.6789, 115.1612, 'ID', 'Bali', 4.5, 3, '{"daily": "11:30-23:00"}', '+62361738202', NULL, 'Jl. Petitenget No.21, Seminyak. The menu is seafood-focused and shellfish is handled on shared preparation surfaces.');
INSERT INTO places (place_id, name, category, lat, lng, country, city, rating, price_level, hours_json, phone, website, formatted) VALUES ('pl_swept_away', 'Swept Away at The Samaya', 'restaurant', -8.6842, 115.1588, 'ID', 'Bali', 4.6, 3, '{"daily": "07:00-23:00"}', '+62361731149', NULL, 'Jl. Laksmana, Seminyak. International menu, allergen-friendly.');
INSERT INTO places (place_id, name, category, lat, lng, country, city, rating, price_level, hours_json, phone, website, formatted) VALUES ('pl_cafe_pomegranate', 'Cafe Pomegranate', 'restaurant', -8.5071, 115.2589, 'ID', 'Bali', 4.2, 1, '{"daily": "08:00-21:00"}', NULL, NULL, 'Ubud. Vegetarian and vegan kitchen with no seafood dishes; staff can provide an ingredient list on request.');
INSERT INTO places (place_id, name, category, lat, lng, country, city, rating, price_level, hours_json, phone, website, formatted) VALUES ('pl_warung_made', 'Warung Made Seminyak', 'restaurant', -8.6901, 115.1623, 'ID', 'Bali', 4.1, 1, '{"daily": "08:00-23:00"}', NULL, NULL, 'Jl. Raya Seminyak. Balinese cuisine, clearly labeled allergens.');
INSERT INTO places (place_id, name, category, lat, lng, country, city, rating, price_level, hours_json, phone, website, formatted) VALUES ('pl_jimbaran_bay_seafood', 'Jimbaran Bay Seafood', 'restaurant', -8.7654, 115.1612, 'ID', 'Bali', 4.4, 2, '{"daily": "16:00-22:00"}', NULL, NULL, 'Jimbaran Beach. Fish and shellfish dominate the menu, and multiple vendors use shared charcoal grills.');
INSERT INTO places (place_id, name, category, lat, lng, country, city, rating, price_level, hours_json, phone, website, formatted) VALUES ('pl_ku_de_ta', 'Ku De Ta', 'restaurant', -8.6884, 115.1567, 'ID', 'Bali', 4.3, 3, '{"daily": "08:00-01:00"}', '+62361736969', NULL, 'Jl. Kayu Aya No.9, Seminyak. Beach club + restaurant.');
INSERT INTO places (place_id, name, category, lat, lng, country, city, rating, price_level, hours_json, phone, website, formatted) VALUES ('pl_ubud_yoga_barn', 'The Yoga Barn', 'wellness', -8.5112, 115.2623, 'ID', 'Bali', 4.5, 2, '{"daily": "07:00-21:00"}', '+62361971236', 'https://theyogabarn.com', 'Jl. Hanoman, Ubud. Prenatal yoga classes available.');
INSERT INTO places (place_id, name, category, lat, lng, country, city, rating, price_level, hours_json, phone, website, formatted) VALUES ('pl_como_shambhala', 'COMO Shambhala Wellness Retreat', 'wellness', -8.4967, 115.2401, 'ID', 'Bali', 4.8, 3, '{"daily": "08:00-20:00"}', NULL, NULL, 'Banjar Begawan, Ubud. Pregnancy-safe spa treatments available.');
INSERT INTO places (place_id, name, category, lat, lng, country, city, rating, price_level, hours_json, phone, website, formatted) VALUES ('pl_spring_spa', 'Spring Spa Seminyak', 'wellness', -8.6892, 115.1634, 'ID', 'Bali', 4.3, 2, '{"daily": "09:00-21:00"}', NULL, NULL, 'Seminyak. Prenatal massage available.');
INSERT INTO places (place_id, name, category, lat, lng, country, city, rating, price_level, hours_json, phone, website, formatted) VALUES ('pl_goa_gajah', 'Goa Gajah (Elephant Cave)', 'temple', -8.5242, 115.2876, 'ID', 'Bali', 4.2, 1, '{"daily": "08:00-16:00"}', NULL, NULL, 'Bedulu, Blahbatuh, Gianyar. Some stairs but short.');
INSERT INTO places (place_id, name, category, lat, lng, country, city, rating, price_level, hours_json, phone, website, formatted) VALUES ('pl_lempuyang', 'Lempuyang Temple (Gates of Heaven)', 'temple', -8.3908, 115.6312, 'ID', 'Bali', 4.5, 1, '{"daily": "07:00-17:00"}', NULL, NULL, 'Karangasem. The upper complex is reached by more than 1,700 steps and there is no lift.');

-- ========== roads ==========
-- Columns: road_id, name, city, geom_json
INSERT INTO roads (road_id, name, city, geom_json) VALUES ('rd_airport_seminyak', 'DPS Airport to Seminyak', 'Bali', '{"distance_km": 12, "typical_min": 25}');
INSERT INTO roads (road_id, name, city, geom_json) VALUES ('rd_seminyak_ubud', 'Seminyak to Ubud', 'Bali', '{"distance_km": 35, "typical_min": 75}');
INSERT INTO roads (road_id, name, city, geom_json) VALUES ('rd_ubud_kintamani', 'Ubud to Kintamani', 'Bali', '{"distance_km": 33, "typical_min": 65}');
INSERT INTO roads (road_id, name, city, geom_json) VALUES ('rd_seminyak_nusa_dua', 'Seminyak to Nusa Dua', 'Bali', '{"distance_km": 22, "typical_min": 40}');
INSERT INTO roads (road_id, name, city, geom_json) VALUES ('rd_ubud_sanur', 'Ubud to Sanur', 'Bali', '{"distance_km": 25, "typical_min": 50}');
INSERT INTO roads (road_id, name, city, geom_json) VALUES ('rd_airport_ubud', 'DPS Airport to Ubud', 'Bali', '{"distance_km": 38, "typical_min": 80}');
INSERT INTO roads (road_id, name, city, geom_json) VALUES ('rd_bypass_ngurah_rai', 'Ngurah Rai Bypass', 'Bali', '{"distance_km": 15, "typical_min": 20}');
INSERT INTO roads (road_id, name, city, geom_json) VALUES ('rd_ubud_tegallalang', 'Ubud to Tegallalang', 'Bali', '{"distance_km": 9, "typical_min": 20}');

-- ========== road_events (pre-seeded inactive) ==========
-- Columns: event_id, road_id, start_dt, end_dt, kind, magnitude, note, active
INSERT INTO road_events (event_id, road_id, start_dt, end_dt, kind, magnitude, note, active) VALUES ('evt_ubud_flood_20260620', 'rd_seminyak_ubud', '2026-06-20T04:00:00+08:00', '2026-06-22T18:00:00+08:00', 'closure', NULL, 'Heavy flooding on Ubud approach roads due to monsoon-tail storms', 0);
INSERT INTO road_events (event_id, road_id, start_dt, end_dt, kind, magnitude, note, active) VALUES ('evt_ubud_flood2_20260620', 'rd_ubud_kintamani', '2026-06-20T04:00:00+08:00', '2026-06-22T18:00:00+08:00', 'closure', NULL, 'Ubud-Kintamani road flooded and mudslide risk', 0);
INSERT INTO road_events (event_id, road_id, start_dt, end_dt, kind, magnitude, note, active) VALUES ('evt_kintamani_volcano_closure', 'rd_ubud_kintamani', '2026-06-22T05:00:00+08:00', '2026-07-15T00:00:00+08:00', 'closure', NULL, 'Road closed due to Mt Agung Level 3 volcanic activity - 6km exclusion zone', 0);
INSERT INTO road_events (event_id, road_id, start_dt, end_dt, kind, magnitude, note, active) VALUES ('evt_ceremony_delay', 'rd_seminyak_ubud', '2026-06-15T08:00:00+08:00', '2026-06-15T12:00:00+08:00', 'heavy_traffic', 0.6, 'Galungan ceremony processions causing delays on Seminyak-Ubud corridor', 0);

-- ========== transit_lines (Bali has no rail - road-based only) ==========
-- Columns: line_id, name, mode, operator, segment_minutes_json
INSERT INTO transit_lines (line_id, name, mode, operator, segment_minutes_json) VALUES ('ln_kura_kura_seminyak', 'Kura-Kura Bus Seminyak Line', 'bus', 'Kura-Kura Bus', '{"seminyak_to_kuta": 20, "kuta_to_airport": 15}');
INSERT INTO transit_lines (line_id, name, mode, operator, segment_minutes_json) VALUES ('ln_kura_kura_ubud', 'Kura-Kura Bus Ubud Line', 'bus', 'Kura-Kura Bus', '{"ubud_to_sanur": 45, "sanur_to_kuta": 30}');
INSERT INTO transit_lines (line_id, name, mode, operator, segment_minutes_json) VALUES ('ln_perama_shuttle', 'Perama Tourist Shuttle', 'bus', 'Perama Tour', '{"kuta_to_ubud": 60, "ubud_to_sanur": 40, "sanur_to_nusa_dua": 35}');

COMMIT;
