-- email environment for a four-person East Asia travel workspace.
-- Records combine relevant options with historical and near-match business context.
-- Later scenario incidents are released only by event mutations, not by this initial state.

PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;

-- account_config: 1 rows
INSERT INTO "account_config" ("id", "email", "name", "created_at") VALUES (1, 'user@mock.local', 'East Asia Group Trip Assistant', '2026-01-01T00:00:00Z');

-- attachments: 4 rows
INSERT INTO "attachments" ("id", "message_id", "filename", "content_type", "size", "content_b64", "content_id") VALUES (1, 7, 'q1-archive-manifest.txt', 'text/plain', 1840, NULL, NULL);
INSERT INTO "attachments" ("id", "message_id", "filename", "content_type", "size", "content_b64", "content_id") VALUES (2, 13, 'router-invoice.pdf', 'application/pdf', 48211, NULL, NULL);
INSERT INTO "attachments" ("id", "message_id", "filename", "content_type", "size", "content_b64", "content_id") VALUES (3, 15, 'ac-cleaning-receipt.pdf', 'application/pdf', 39520, NULL, NULL);
INSERT INTO "attachments" ("id", "message_id", "filename", "content_type", "size", "content_b64", "content_id") VALUES (4, 21, 'winter-choir-program.pdf', 'application/pdf', 71642, NULL, NULL);

-- folders: 4 rows
INSERT INTO "folders" ("id", "name", "delimiter", "flags_json", "message_count", "unread_count") VALUES (1, 'INBOX', '/', '["\\Inbox"]', 6, 2);
INSERT INTO "folders" ("id", "name", "delimiter", "flags_json", "message_count", "unread_count") VALUES (2, 'Archive', '/', '["\\Archive"]', 6, 0);
INSERT INTO "folders" ("id", "name", "delimiter", "flags_json", "message_count", "unread_count") VALUES (3, 'Receipts', '/', '[]', 5, 1);
INSERT INTO "folders" ("id", "name", "delimiter", "flags_json", "message_count", "unread_count") VALUES (4, 'Community', '/', '[]', 4, 2);

-- messages: 21 rows
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (1, 1, '<stay-0422@jinghotel.ex>', '         ', 'billing@jinghotel.example.com', '["chen.yu@example.com"]', '[]', '[]', '2026-04-23T10:18:00+08:00', '   Hello，4   22       hotel       completecheck-out。        680 CNY    68 CNY，      ；     invoice，   email          。', NULL, 1, 0, 0, NULL, NULL, '{}', 289, 846, '2026-04-23T10:18:00+08:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (2, 1, '<m2-b7c1df@mail.ex>', '5      completerecord', 'service@xuhui-property.example', '["chen.yu@example.com"]', '[]', '[]', '2026-05-22T08:36:00+08:00', '2         5   21  complete  ，        WQ-260521。property service             。', NULL, 1, 0, 0, NULL, NULL, '{}', 302, 684, '2026-05-22T08:36:00+08:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (3, 1, '<m3-fe9598@mail.ex>', '       ', 'proof@hongqiao-print.example', '["chen.yu@example.com"]', '["production@studio.example"]', '[]', '2026-05-20T16:48:00+08:00', '           。     180     ，        5   18  confirm 。', NULL, 1, 1, 0, NULL, NULL, '{}', 317, 752, '2026-05-20T16:48:00+08:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (4, 1, '<m4-bfd5be@mail.ex>', '        ', 'lab@anfu-vet.example', '["chen.yu@example.com","li.ting@example.com"]', '[]', '[]', '2026-05-18T14:02:00+08:00', '             。  record  5.1   ，      CAT-60516  update。', NULL, 0, 1, 1, NULL, NULL, '{}', 329, 596, '2026-05-18T14:02:00+08:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (5, 1, '<m5-f96692@mail.ex>', '    confirm ', 'account@isp.example', '["chen.yu@example.com"]', '[]', '[]', '2026-05-12T11:24:00+08:00', '          2027   2  。monthly fee 169 CNY，           。', NULL, 1, 0, 0, NULL, NULL, '{}', 341, 511, '2026-05-12T11:24:00+08:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (6, 1, '<m6-163817@mail.ex>', '      ：      ', 'notice@library.example', '["chen.yu@example.com"]', '[]', '[]', '2026-05-09T17:50:00+08:00', '     B-77841     fen         ，    5   16    。', NULL, 0, 0, 0, NULL, NULL, '{}', 356, 472, '2026-05-09T17:50:00+08:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (7, 2, '<m7-8115ae@mail.ex>', 'Q1 retrospective    complete', 'records@studio.example', '["chen.yu@example.com"]', '["creative.director@studio.example"]', '[]', '2026-04-09T09:18:00+08:00', '    retrospective   fen     、          。           。', NULL, 1, 0, 0, NULL, NULL, '{}', 411, 805, '2026-04-09T09:18:00+08:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (8, 2, '<m8-d64b05@mail.ex>', '       ', 'desk@shaanxi-cycle.example', '["chen.yu@example.com"]', '[]', '[]', '2026-03-28T11:16:00+08:00', '          ，    90 CNY，    168 CNY。        。', NULL, 1, 0, 0, NULL, NULL, '{}', 426, 588, '2026-03-28T11:16:00+08:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (9, 2, '<m9-872e6c@mail.ex>', '        ', 'facilities@office.example', '["chen.yu@example.com"]', '["floor5@office.example"]', '[]', '2026-03-12T13:45:00+08:00', '   43 people       ，      10:27 complete  。           。', NULL, 1, 0, 0, NULL, NULL, '{}', 438, 642, '2026-03-12T13:45:00+08:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (10, 2, '<m10-19a167@mail.ex>', 'repair  CAM-5517    ', 'service@luban-camera.example', '["chen.yu@example.com"]', '[]', '[]', '2025-11-16T13:05:00+08:00', '       complete 300      ，          。  amount 1,280 CNY。', NULL, 1, 0, 1, NULL, NULL, '{}', 453, 621, '2025-11-16T13:05:00+08:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (11, 2, '<m11-86268f@mail.ex>', '       ', 'host@hengshan-books.example', '["chen.yu@example.com"]', '["members@hengshan-books.example"]', '[]', '2025-10-26T10:12:00+08:00', '        21   30  。 complete            ，recordpeople   。', NULL, 1, 0, 0, NULL, NULL, '{}', 469, 734, '2025-10-26T10:12:00+08:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (12, 2, '<m12-ba69d5@mail.ex>', '      ', 'records@clinic.example', '["chen.yu@example.com"]', '[]', '[]', '2025-09-13T12:30:00+08:00', '  complete       ，      。  invoice    SH-DENT-9132。', NULL, 1, 0, 0, NULL, NULL, '{}', 482, 507, '2025-09-13T12:30:00+08:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (13, 3, '<m13-5dc194@mail.ex>', '  invoice：     ', 'invoice@digital-store.example', '["chen.yu@example.com"]', '[]', '[]', '2026-01-24T18:08:00+08:00', '   RT-260124 amount 899.00 CNY，          。invoice   Chen Yu。', NULL, 1, 0, 0, NULL, NULL, '{}', 517, 640, '2026-01-24T18:08:00+08:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (14, 3, '<m14-f9653b@mail.ex>', '         ', 'receipts@home-store.example', '["chen.yu@example.com"]', '[]', '[]', '2026-02-27T20:22:00+08:00', '         436 CNY，      equipment    WF-A219。', NULL, 1, 0, 0, NULL, NULL, '{}', 529, 456, '2026-02-27T20:22:00+08:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (15, 3, '<m15-e33fb4@mail.ex>', '        ', 'billing@cleaning.example', '["chen.yu@example.com"]', '[]', '[]', '2026-04-11T11:35:00+08:00', '           520 CNY，       1802，     bank 。', NULL, 1, 0, 0, NULL, NULL, '{}', 541, 532, '2026-04-11T11:35:00+08:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (16, 3, '<m16-dcfe7f@mail.ex>', '       ', 'statements@market.example', '["chen.yu@example.com"]', '[]', '[]', '2026-04-26T07:55:00+08:00', '   complete 7      ，   1  ，    684.30 CNY。', NULL, 1, 0, 0, NULL, NULL, '{}', 558, 498, '2026-04-26T07:55:00+08:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (17, 3, '<m17-bb0727@mail.ex>', '    fee ', 'accounts@hongqiao-print.example', '["chen.yu@example.com"]', '["production@studio.example"]', '[]', '2026-05-21T17:05:00+08:00', '             760 CNY，     PR-0521。', NULL, 0, 0, 0, NULL, NULL, '{}', 572, 509, '2026-05-21T17:05:00+08:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (18, 4, '<m18-12703e@mail.ex>', '         ', 'garden@neighborhood.example', '["chen.yu@example.com"]', '[]', '[]', '2026-05-06T09:12:00+08:00', '         。Chen Yu     date  5   10  ，           。', NULL, 1, 0, 0, NULL, NULL, '{}', 603, 577, '2026-05-06T09:12:00+08:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (19, 4, '<m19-3d455a@mail.ex>', '          ', 'programs@arts.example', '["chen.yu@example.com"]', '[]', '[]', '2026-04-15T14:30:00+08:00', '          ，   74 fen 。     fen  52:18   。', NULL, 1, 0, 0, NULL, NULL, '{}', 618, 463, '2026-04-15T14:30:00+08:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (20, 4, '<m20-0e0372@mail.ex>', '   equipment    ', 'recycle@neighborhood.example', '["chen.yu@example.com"]', '[]', '[]', '2026-03-19T18:40:00+08:00', '                     。     8.6   。', NULL, 0, 0, 0, NULL, NULL, '{}', 631, 519, '2026-03-19T18:40:00+08:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (21, 4, '<m21-2f3326@mail.ex>', '         ', 'events@community.example', '["chen.yu@example.com"]', '[]', '[]', '2025-12-11T19:05:00+08:00', '        ，            。        email。', NULL, 0, 0, 1, NULL, NULL, '{}', 647, 550, '2025-12-11T19:05:00+08:00');

COMMIT;
PRAGMA foreign_keys=ON;
