-- Generated notification_hub seed for bed_total_reno_v4_30d
BEGIN;
INSERT INTO official_accounts (account_id, name, category, description) VALUES ('oa_qbed_housing', 'renovation note', 'home_improvement', 'renovation note、 materials renovation note、renovation note protection  and renovation note environment  review renovation note');
INSERT INTO official_account_subscriptions (user_id, account_id, subscribed_at) VALUES ('usr_du_rong', 'oa_qbed_housing', '2026-05-27T02:20:00Z');
INSERT INTO official_accounts (account_id, name, category, description) VALUES ('oa_qbed_brand', ' millwork  construction  with renovation note service ', 'shopping_service', ' cabinetry  contract 、 edge sealing renovation note、 paint finish  rework  and renovation note after  evidence  explanation ');
INSERT INTO official_account_subscriptions (user_id, account_id, subscribed_at) VALUES ('usr_du_rong', 'oa_qbed_brand', '2026-05-30T08:45:00Z');
INSERT INTO official_accounts (account_id, name, category, description) VALUES ('oa_qbed_card', 'renovation note credit card ', 'finance', 'renovation note、 foreign-currency transaction  with renovation note safety  reminder ');
INSERT INTO official_account_subscriptions (user_id, account_id, subscribed_at) VALUES ('usr_du_rong', 'oa_qbed_card', '2026-06-02T01:10:00Z');
INSERT INTO official_account_posts (post_id, account_id, title, summary, url, published_at) VALUES ('post_qbed_1', 'oa_qbed_housing', ' millwork  materials renovation note with renovation note protection  reconcile renovation note', 'renovation note、 edge sealing renovation note、 hardware  and  coating  should renovation note； delivery receipt  only renovation note proof  arrival ， installation  before renovation note reconcile  batch 、renovation note and renovation note condition 。', 'https://housing.example/suzhou/woodwork-arrival', '2026-06-03');
INSERT INTO official_account_posts (post_id, account_id, title, summary, url, published_at) VALUES ('post_qbed_2', 'oa_qbed_brand', ' cabinetry  edge sealing  with  paint finish  rework  evidence  checklist ', ' edge sealing renovation note、renovation note and  paint finish renovation note should  separately  record  location 、 measurement 、 photos  time renovation note primer  topcoat  batch ，renovation note。', 'https://woodall.example/service/bedroom-evidence', '2026-06-05');
INSERT INTO official_account_posts (post_id, account_id, title, summary, url, published_at) VALUES ('post_qbed_3', 'oa_qbed_card', ' hardware merchant renovation note with renovation note transaction  reconcile ', ' overseas  hardware renovation note transfer renovation note； same amount  transaction renovation note、renovation note with  posted  status  reconcile ，renovation note in  record  cannot renovation note before renovation note reversal 。', 'https://card.example/merchant-preauth-check', '2026-06-07');
INSERT INTO official_account_posts (post_id, account_id, title, summary, url, published_at) VALUES ('post_qbed_4', 'oa_qbed_brand', ' not renovation note cabinetry  hardware  with  edge sealing  surplus materials  listing renovation note', ' listing  before renovation note hinges renovation note、 drawer slides renovation note and  edge sealing renovation note，renovation note payment  not  posted  before  must not renovation note rework  budget 。', 'https://woodall.example/service/leftover-listing', '2026-06-10');
INSERT INTO subscriptions (subscription_id, user_id, source, type, target, condition_json, status, created_at, updated_at) VALUES ('sub_qbed_log', 'usr_du_rong', 'delivery_logistics', 'keyword', 'YTOQBED5520002CN', '{"keywords": [" hinges ", " drawer slides ", " primer ", " arrival ", " batch "], "order_id": "ord_qbed_0002"}', 'active', '2026-06-14T13:15:00Z', '2026-06-14T13:15:00Z');
INSERT INTO subscriptions (subscription_id, user_id, source, type, target, condition_json, status, created_at, updated_at) VALUES ('sub_qbed_card', 'usr_du_rong', 'credit_card', 'keyword', 'card_qbed_01', '{"keywords": [" hardware merchant ", "renovation note", " same amount  transaction ", " reversal "]}', 'active', '2026-06-14T12:50:00Z', '2026-06-14T12:50:00Z');
INSERT INTO price_alerts (alert_id, user_id, item_ref, target_price_minor, currency, status, created_at) VALUES ('alr_qbed_1', 'usr_du_rong', 'prod_qbed_main', 3060000, 'CNY', 'active', '2026-06-14T11:30:00Z');
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_qbed_arrival_policy_0614', 'usr_du_rong', 'delivery_logistics', 'policy_update', 'sub_qbed_log', ' millwork  batch  arrival renovation note reminder ', 'renovation note with  hardware  arrival  after  should renovation note batch  and  delivery receipt  record ； arrival renovation note installation  or  acceptance renovation note。', '{"order_id": "ord_qbed_0002", "tracking_no": "YTOQBED5520002CN"}', '2026-06-14T04:05:00Z', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_qbed_fx_policy_0614', 'usr_du_rong', 'credit_card', 'policy_update', 'sub_qbed_card', 'renovation note hardware  transaction  posted renovation note reminder ', ' overseas  hardware merchant renovation note posted  time renovation note； please  with  order  reconcile 。', '{"card_id": "card_qbed_01", "tx_id": "tx_qbed_fx"}', '2026-06-14T03:35:00Z', 0);
INSERT INTO _counters (key,value) VALUES ('subscription_seq',2),('alert_seq',1);
COMMIT;

BEGIN;
UPDATE notifications SET title=' millwork  batch  arrival renovation note reminder ', body='renovation note with  hardware  arrival  after  should renovation note batch  and  delivery receipt  record ； arrival renovation note installation  or  acceptance renovation note。', created_at='2026-06-14T04:05:00Z' WHERE notification_id='ntf_qbed_arrival_policy_0614';
UPDATE notifications SET title='renovation note hardware  transaction  posted renovation note reminder ', body=' overseas  hardware merchant renovation note posted  time renovation note； please  with  order  reconcile 。', created_at='2026-06-14T03:35:00Z' WHERE notification_id='ntf_qbed_fx_policy_0614';
INSERT INTO notifications (notification_id,user_id,source,type,subscription_id,title,body,payload_json,created_at,read) VALUES
 ('ntf_qbed_measure_0518','usr_du_rong','calendar','policy_update',NULL,'5 month 18 day renovation note has  archive ','renovation note and renovation note M-0518  has  archive ， follow-up renovation note。','{"event_id":"evt_qbed_measure_0518","version":"M-0518"}','2026-05-18T03:00:00Z',1),
 ('ntf_qbed_quote_0512','usr_du_rong','ecommerce','price_change',NULL,'renovation note wall paneling  quote  Q-0508  has renovation note valid renovation note',' quote renovation note 28 renovation note、renovation note service renovation note and renovation note topcoat ，5  month  11  day  valid renovation note。','{"quote_no":"Q-0508","room":"living_room","status":"expired"}','2026-05-12T02:00:00Z',1),
 ('ntf_qbed_doc1','usr_du_rong','email','policy_update',NULL,' contractor  authorization letter  still renovation note signature renovation note',' contract renovation note email renovation note； complete  before renovation note verification 。','{"document":"authorization","status":"missing_page"}','2026-06-12T08:05:00Z',0),
 ('ntf_qbed_stock1','usr_du_rong','ecommerce','price_change',NULL,'renovation note edge sealing renovation note inventory renovation note',' in renovation note current  batch renovation note condition 。','{"item":"edge_band","state":"near_match"}','2026-06-14T06:15:00Z',0);
COMMIT;
