-- Generated notification_hub seed for camping_trip_procure_30d
BEGIN;
INSERT INTO official_accounts (account_id, name, category, description) VALUES ('oa_camp_customs', 'camping business detailalert', 'logistics', 'Cross-border shipping, personal declaration, and quota policy notice');
INSERT INTO official_account_subscriptions (user_id, account_id, subscribed_at) VALUES ('usr_ye_chen', 'oa_camp_customs', '2026-06-06T00:00:00Z');
INSERT INTO official_accounts (account_id, name, category, description) VALUES ('oa_camp_brand', 'officialmarketplacecamping business detail', 'shopping_service', 'Official warranty, credentials, and overseas support');
INSERT INTO official_account_subscriptions (user_id, account_id, subscribed_at) VALUES ('usr_ye_chen', 'oa_camp_brand', '2026-06-06T00:00:00Z');
INSERT INTO official_accounts (account_id, name, category, description) VALUES ('oa_camp_card', 'camping business detail', 'finance', 'Statements, FX transactions, and card safety reminders');
INSERT INTO official_account_subscriptions (user_id, account_id, subscribed_at) VALUES ('usr_ye_chen', 'oa_camp_card', '2026-06-06T00:00:00Z');
INSERT INTO official_account_posts (post_id, account_id, title, summary, url, published_at) VALUES ('post_camp_1', 'oa_camp_customs', 'camping business detail', 'Air shipment of lithium-battery items is limited by rated energy (Wh); over-limit items cannot fly, and declarations must state name and value accurately.', 'https://customs.example/li-battery-notice', '2026-06-08');
INSERT INTO official_account_posts (post_id, account_id, title, summary, url, published_at) VALUES ('post_camp_2', 'oa_camp_brand', 'Official warranty, credentials, and overseas support', 'camping business detailpleasecamping business detailproduct/SKU camping business detailverificationspecification、batchcamping business detailverification code；camping business detailplatformsame modelcamping business detail/gift/shipping feecamping business detail，camping business detail。', 'https://brand.example/notice', '2026-06-08');
INSERT INTO official_account_posts (post_id, account_id, title, summary, url, published_at) VALUES ('post_camp_3', 'oa_camp_card', 'Safety tips for foreign and FX card transactions', 'Foreign-currency posting may have exchange-rate and timing differences; verify duplicates or unfamiliar merchants and dispute when appropriate.', 'https://card.example/fx-safety', '2026-06-08');
INSERT INTO official_account_posts (post_id, account_id, title, summary, url, published_at) VALUES ('post_camp_4', 'oa_camp_brand', 'Comparison of three options', 'premium version(¥780,giftcamping business detail)；standard version(¥450,value for money)；entry version(camping business detailgiftcamping business detailmissing parts，requires an additionalcamping business detail¥600)。pleasecamping business detailbudgetcamping business detail。', 'https://brand.example/options', '2026-06-08');
INSERT INTO subscriptions (subscription_id, user_id, source, type, target, condition_json, status, created_at, updated_at) VALUES ('sub_camp_log', 'usr_ye_chen', 'delivery_logistics', 'keyword', 'YTOCAMP5520002CN', '{"keywords": ["camping business detail", "camping business detail", "camping business detail", "compliant"], "order_id": "ord_camp_0002"}', 'active', '2026-06-15T09:00:00Z', '2026-06-15T09:00:00Z');
INSERT INTO subscriptions (subscription_id, user_id, source, type, target, condition_json, status, created_at, updated_at) VALUES ('sub_camp_card', 'usr_ye_chen', 'credit_card', 'keyword', 'card_camp_01', '{"keywords": ["camping business detail", "camping business detail", "camping business detail"]}', 'active', '2026-06-15T00:00:00Z', '2026-06-15T00:00:00Z');
INSERT INTO price_alerts (alert_id, user_id, item_ref, target_price_minor, currency, status, created_at) VALUES ('alr_camp_1', 'usr_ye_chen', 'prod_camp_main', 350910, 'CNY', 'active', '2026-06-15T00:00:00Z');
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_camp_seed1', 'usr_ye_chen', 'delivery_logistics', 'policy_update', 'sub_camp_log', 'camping business detail：The same item has different prices across platforms', 'camping business detailcampingsleeping bagcamping business detailplatformcamping business detailshipping fee，place an ordercamping business detailpleasecamping business detail。', '{"order_id": "ord_camp_0002", "tracking_no": "YTOCAMP5520002CN"}', '2026-06-15T12:05:00Z', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_camp_seed2', 'usr_ye_chen', 'credit_card', 'policy_update', 'sub_camp_card', 'camping business detailalert', 'camping business detail，camping business detail，pleasecamping business detail。', '{"card_id": "card_camp_01", "tx_id": "tx_camp_fx"}', '2026-06-15T11:35:00Z', 0);
INSERT INTO _counters (key,value) VALUES ('subscription_seq',2),('alert_seq',1);
COMMIT;
