PRAGMA foreign_keys = ON;
INSERT INTO subscriptions (subscription_id, user_id, source, type, target, condition_json, status, created_at, updated_at) VALUES ('sub_gt_plan_watch', 'user_liang_weimin', 'calendar', 'keyword', 'microbreak_schedule', '{"topic":"plan_check"}', 'active', '2026-07-01T08:30:00+08:00', '2026-07-01T08:30:00+08:00');
INSERT INTO subscriptions (subscription_id, user_id, source, type, target, condition_json, status, created_at, updated_at) VALUES ('sub_gt_health_watch', 'user_liang_weimin', 'health_tracker', 'keyword', 'neck_eye_threshold', '{"topic":"health_check"}', 'active', '2026-07-01T08:30:00+08:00', '2026-07-01T08:30:00+08:00');
INSERT INTO subscriptions (subscription_id, user_id, source, type, target, condition_json, status, created_at, updated_at) VALUES ('sub_gt_email_watch', 'user_liang_weimin', 'email', 'keyword', 'academy_parent_inbox', '{"topic":"privacy_check"}', 'active', '2026-07-01T08:30:00+08:00', '2026-07-01T08:30:00+08:00');
INSERT INTO subscriptions (subscription_id, user_id, source, type, target, condition_json, status, created_at, updated_at) VALUES ('sub_gt_data_watch', 'user_liang_weimin', 'health_tracker', 'keyword', 'sync_quality', '{"topic":"data_quality"}', 'active', '2026-07-01T08:30:00+08:00', '2026-07-01T08:30:00+08:00');
INSERT INTO subscriptions (subscription_id, user_id, source, type, target, condition_json, status, created_at, updated_at) VALUES ('sub_gt_final_watch', 'user_liang_weimin', 'notion', 'keyword', 'final_review', '{"topic":"handoff"}', 'active', '2026-07-01T08:30:00+08:00', '2026-07-01T08:30:00+08:00');
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_000', 'user_liang_weimin', 'calendar', 'digest', NULL, 'ordinary personal reminder 000', 'ordinary noise notification.', '{"noise":true}', '2026-06-01T08:00:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_001', 'user_liang_weimin', 'health_tracker', 'digest', NULL, 'ordinary personal reminder 001', 'ordinary noise notification.', '{"noise":true}', '2026-06-02T08:01:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_002', 'user_liang_weimin', 'email', 'digest', NULL, 'ordinary personal reminder 002', 'ordinary noise notification.', '{"noise":true}', '2026-06-03T08:02:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_003', 'user_liang_weimin', 'notion', 'digest', NULL, 'ordinary personal reminder 003', 'ordinary noise notification.', '{"noise":true}', '2026-06-04T08:03:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_004', 'user_liang_weimin', 'calendar', 'digest', NULL, 'ordinary personal reminder 004', 'ordinary noise notification.', '{"noise":true}', '2026-06-05T08:04:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_005', 'user_liang_weimin', 'health_tracker', 'digest', NULL, 'ordinary personal reminder 005', 'ordinary noise notification.', '{"noise":true}', '2026-06-06T08:05:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_006', 'user_liang_weimin', 'email', 'digest', NULL, 'ordinary personal reminder 006', 'ordinary noise notification.', '{"noise":true}', '2026-06-07T08:06:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_007', 'user_liang_weimin', 'notion', 'digest', NULL, 'ordinary personal reminder 007', 'ordinary noise notification.', '{"noise":true}', '2026-06-08T08:07:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_008', 'user_liang_weimin', 'calendar', 'digest', NULL, 'ordinary personal reminder 008', 'ordinary noise notification.', '{"noise":true}', '2026-06-09T08:08:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_009', 'user_liang_weimin', 'health_tracker', 'digest', NULL, 'ordinary personal reminder 009', 'ordinary noise notification.', '{"noise":true}', '2026-06-10T08:09:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_010', 'user_liang_weimin', 'email', 'digest', NULL, 'ordinary personal reminder 010', 'ordinary noise notification.', '{"noise":true}', '2026-06-11T08:10:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_011', 'user_liang_weimin', 'notion', 'digest', NULL, 'ordinary personal reminder 011', 'ordinary noise notification.', '{"noise":true}', '2026-06-12T08:11:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_012', 'user_liang_weimin', 'calendar', 'digest', NULL, 'ordinary personal reminder 012', 'ordinary noise notification.', '{"noise":true}', '2026-06-13T08:12:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_013', 'user_liang_weimin', 'health_tracker', 'digest', NULL, 'ordinary personal reminder 013', 'ordinary noise notification.', '{"noise":true}', '2026-06-14T08:13:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_014', 'user_liang_weimin', 'email', 'digest', NULL, 'ordinary personal reminder 014', 'ordinary noise notification.', '{"noise":true}', '2026-06-15T08:14:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_015', 'user_liang_weimin', 'notion', 'digest', NULL, 'ordinary personal reminder 015', 'ordinary noise notification.', '{"noise":true}', '2026-06-16T08:15:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_016', 'user_liang_weimin', 'calendar', 'digest', NULL, 'ordinary personal reminder 016', 'ordinary noise notification.', '{"noise":true}', '2026-06-17T08:16:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_017', 'user_liang_weimin', 'health_tracker', 'digest', NULL, 'ordinary personal reminder 017', 'ordinary noise notification.', '{"noise":true}', '2026-06-18T08:17:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_018', 'user_liang_weimin', 'email', 'digest', NULL, 'ordinary personal reminder 018', 'ordinary noise notification.', '{"noise":true}', '2026-06-19T08:18:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_019', 'user_liang_weimin', 'notion', 'digest', NULL, 'ordinary personal reminder 019', 'ordinary noise notification.', '{"noise":true}', '2026-06-20T08:19:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_020', 'user_liang_weimin', 'calendar', 'digest', NULL, 'ordinary personal reminder 020', 'ordinary noise notification.', '{"noise":true}', '2026-06-21T08:20:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_021', 'user_liang_weimin', 'health_tracker', 'digest', NULL, 'ordinary personal reminder 021', 'ordinary noise notification.', '{"noise":true}', '2026-06-22T08:21:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_022', 'user_liang_weimin', 'email', 'digest', NULL, 'ordinary personal reminder 022', 'ordinary noise notification.', '{"noise":true}', '2026-06-23T08:22:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_023', 'user_liang_weimin', 'notion', 'digest', NULL, 'ordinary personal reminder 023', 'ordinary noise notification.', '{"noise":true}', '2026-06-24T08:23:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_024', 'user_liang_weimin', 'calendar', 'digest', NULL, 'ordinary personal reminder 024', 'ordinary noise notification.', '{"noise":true}', '2026-06-25T08:24:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_025', 'user_liang_weimin', 'health_tracker', 'digest', NULL, 'ordinary personal reminder 025', 'ordinary noise notification.', '{"noise":true}', '2026-06-26T08:25:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_026', 'user_liang_weimin', 'email', 'digest', NULL, 'ordinary personal reminder 026', 'ordinary noise notification.', '{"noise":true}', '2026-06-27T08:26:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_027', 'user_liang_weimin', 'notion', 'digest', NULL, 'ordinary personal reminder 027', 'ordinary noise notification.', '{"noise":true}', '2026-06-28T08:27:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_028', 'user_liang_weimin', 'calendar', 'digest', NULL, 'ordinary personal reminder 028', 'ordinary noise notification.', '{"noise":true}', '2026-06-29T08:28:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_029', 'user_liang_weimin', 'health_tracker', 'digest', NULL, 'ordinary personal reminder 029', 'ordinary noise notification.', '{"noise":true}', '2026-06-30T08:29:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_030', 'user_liang_weimin', 'email', 'digest', NULL, 'ordinary personal reminder 030', 'ordinary noise notification.', '{"noise":true}', '2026-07-01T08:30:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_031', 'user_liang_weimin', 'notion', 'digest', NULL, 'ordinary personal reminder 031', 'ordinary noise notification.', '{"noise":true}', '2026-07-02T08:31:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_032', 'user_liang_weimin', 'calendar', 'digest', NULL, 'ordinary personal reminder 032', 'ordinary noise notification.', '{"noise":true}', '2026-07-03T08:32:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_033', 'user_liang_weimin', 'health_tracker', 'digest', NULL, 'ordinary personal reminder 033', 'ordinary noise notification.', '{"noise":true}', '2026-07-04T08:33:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_034', 'user_liang_weimin', 'email', 'digest', NULL, 'ordinary personal reminder 034', 'ordinary noise notification.', '{"noise":true}', '2026-07-05T08:34:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_035', 'user_liang_weimin', 'notion', 'digest', NULL, 'ordinary personal reminder 035', 'ordinary noise notification.', '{"noise":true}', '2026-07-06T08:35:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_036', 'user_liang_weimin', 'calendar', 'digest', NULL, 'ordinary personal reminder 036', 'ordinary noise notification.', '{"noise":true}', '2026-07-07T08:36:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_037', 'user_liang_weimin', 'health_tracker', 'digest', NULL, 'ordinary personal reminder 037', 'ordinary noise notification.', '{"noise":true}', '2026-07-08T08:37:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_038', 'user_liang_weimin', 'email', 'digest', NULL, 'ordinary personal reminder 038', 'ordinary noise notification.', '{"noise":true}', '2026-07-09T08:38:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_039', 'user_liang_weimin', 'notion', 'digest', NULL, 'ordinary personal reminder 039', 'ordinary noise notification.', '{"noise":true}', '2026-07-10T08:39:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_040', 'user_liang_weimin', 'calendar', 'digest', NULL, 'ordinary personal reminder 040', 'ordinary noise notification.', '{"noise":true}', '2026-06-01T08:40:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_041', 'user_liang_weimin', 'health_tracker', 'digest', NULL, 'ordinary personal reminder 041', 'ordinary noise notification.', '{"noise":true}', '2026-06-02T08:41:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_042', 'user_liang_weimin', 'email', 'digest', NULL, 'ordinary personal reminder 042', 'ordinary noise notification.', '{"noise":true}', '2026-06-03T08:42:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_043', 'user_liang_weimin', 'notion', 'digest', NULL, 'ordinary personal reminder 043', 'ordinary noise notification.', '{"noise":true}', '2026-06-04T08:43:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_044', 'user_liang_weimin', 'calendar', 'digest', NULL, 'ordinary personal reminder 044', 'ordinary noise notification.', '{"noise":true}', '2026-06-05T08:44:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_045', 'user_liang_weimin', 'health_tracker', 'digest', NULL, 'ordinary personal reminder 045', 'ordinary noise notification.', '{"noise":true}', '2026-06-06T08:45:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_046', 'user_liang_weimin', 'email', 'digest', NULL, 'ordinary personal reminder 046', 'ordinary noise notification.', '{"noise":true}', '2026-06-07T08:46:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_047', 'user_liang_weimin', 'notion', 'digest', NULL, 'ordinary personal reminder 047', 'ordinary noise notification.', '{"noise":true}', '2026-06-08T08:47:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_048', 'user_liang_weimin', 'calendar', 'digest', NULL, 'ordinary personal reminder 048', 'ordinary noise notification.', '{"noise":true}', '2026-06-09T08:48:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_049', 'user_liang_weimin', 'health_tracker', 'digest', NULL, 'ordinary personal reminder 049', 'ordinary noise notification.', '{"noise":true}', '2026-06-10T08:49:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_050', 'user_liang_weimin', 'email', 'digest', NULL, 'ordinary personal reminder 050', 'ordinary noise notification.', '{"noise":true}', '2026-06-11T08:50:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_051', 'user_liang_weimin', 'notion', 'digest', NULL, 'ordinary personal reminder 051', 'ordinary noise notification.', '{"noise":true}', '2026-06-12T08:51:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_052', 'user_liang_weimin', 'calendar', 'digest', NULL, 'ordinary personal reminder 052', 'ordinary noise notification.', '{"noise":true}', '2026-06-13T08:52:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_053', 'user_liang_weimin', 'health_tracker', 'digest', NULL, 'ordinary personal reminder 053', 'ordinary noise notification.', '{"noise":true}', '2026-06-14T08:53:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_054', 'user_liang_weimin', 'email', 'digest', NULL, 'ordinary personal reminder 054', 'ordinary noise notification.', '{"noise":true}', '2026-06-15T08:54:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_055', 'user_liang_weimin', 'notion', 'digest', NULL, 'ordinary personal reminder 055', 'ordinary noise notification.', '{"noise":true}', '2026-06-16T08:55:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_056', 'user_liang_weimin', 'calendar', 'digest', NULL, 'ordinary personal reminder 056', 'ordinary noise notification.', '{"noise":true}', '2026-06-17T08:56:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_057', 'user_liang_weimin', 'health_tracker', 'digest', NULL, 'ordinary personal reminder 057', 'ordinary noise notification.', '{"noise":true}', '2026-06-18T08:57:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_058', 'user_liang_weimin', 'email', 'digest', NULL, 'ordinary personal reminder 058', 'ordinary noise notification.', '{"noise":true}', '2026-06-19T08:58:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_059', 'user_liang_weimin', 'notion', 'digest', NULL, 'ordinary personal reminder 059', 'ordinary noise notification.', '{"noise":true}', '2026-06-20T08:59:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_060', 'user_liang_weimin', 'calendar', 'digest', NULL, 'ordinary personal reminder 060', 'ordinary noise notification.', '{"noise":true}', '2026-06-21T08:00:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_061', 'user_liang_weimin', 'health_tracker', 'digest', NULL, 'ordinary personal reminder 061', 'ordinary noise notification.', '{"noise":true}', '2026-06-22T08:01:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_062', 'user_liang_weimin', 'email', 'digest', NULL, 'ordinary personal reminder 062', 'ordinary noise notification.', '{"noise":true}', '2026-06-23T08:02:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_063', 'user_liang_weimin', 'notion', 'digest', NULL, 'ordinary personal reminder 063', 'ordinary noise notification.', '{"noise":true}', '2026-06-24T08:03:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_064', 'user_liang_weimin', 'calendar', 'digest', NULL, 'ordinary personal reminder 064', 'ordinary noise notification.', '{"noise":true}', '2026-06-25T08:04:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_065', 'user_liang_weimin', 'health_tracker', 'digest', NULL, 'ordinary personal reminder 065', 'ordinary noise notification.', '{"noise":true}', '2026-06-26T08:05:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_066', 'user_liang_weimin', 'email', 'digest', NULL, 'ordinary personal reminder 066', 'ordinary noise notification.', '{"noise":true}', '2026-06-27T08:06:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_067', 'user_liang_weimin', 'notion', 'digest', NULL, 'ordinary personal reminder 067', 'ordinary noise notification.', '{"noise":true}', '2026-06-28T08:07:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_068', 'user_liang_weimin', 'calendar', 'digest', NULL, 'ordinary personal reminder 068', 'ordinary noise notification.', '{"noise":true}', '2026-06-29T08:08:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_069', 'user_liang_weimin', 'health_tracker', 'digest', NULL, 'ordinary personal reminder 069', 'ordinary noise notification.', '{"noise":true}', '2026-06-30T08:09:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_070', 'user_liang_weimin', 'email', 'digest', NULL, 'ordinary personal reminder 070', 'ordinary noise notification.', '{"noise":true}', '2026-07-01T08:10:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_071', 'user_liang_weimin', 'notion', 'digest', NULL, 'ordinary personal reminder 071', 'ordinary noise notification.', '{"noise":true}', '2026-07-02T08:11:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_072', 'user_liang_weimin', 'calendar', 'digest', NULL, 'ordinary personal reminder 072', 'ordinary noise notification.', '{"noise":true}', '2026-07-03T08:12:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_073', 'user_liang_weimin', 'health_tracker', 'digest', NULL, 'ordinary personal reminder 073', 'ordinary noise notification.', '{"noise":true}', '2026-07-04T08:13:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_074', 'user_liang_weimin', 'email', 'digest', NULL, 'ordinary personal reminder 074', 'ordinary noise notification.', '{"noise":true}', '2026-07-05T08:14:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_075', 'user_liang_weimin', 'notion', 'digest', NULL, 'ordinary personal reminder 075', 'ordinary noise notification.', '{"noise":true}', '2026-07-06T08:15:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_076', 'user_liang_weimin', 'calendar', 'digest', NULL, 'ordinary personal reminder 076', 'ordinary noise notification.', '{"noise":true}', '2026-07-07T08:16:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_077', 'user_liang_weimin', 'health_tracker', 'digest', NULL, 'ordinary personal reminder 077', 'ordinary noise notification.', '{"noise":true}', '2026-07-08T08:17:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_078', 'user_liang_weimin', 'email', 'digest', NULL, 'ordinary personal reminder 078', 'ordinary noise notification.', '{"noise":true}', '2026-07-09T08:18:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_079', 'user_liang_weimin', 'notion', 'digest', NULL, 'ordinary personal reminder 079', 'ordinary noise notification.', '{"noise":true}', '2026-07-10T08:19:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_080', 'user_liang_weimin', 'calendar', 'digest', NULL, 'ordinary personal reminder 080', 'ordinary noise notification.', '{"noise":true}', '2026-06-01T08:20:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_081', 'user_liang_weimin', 'health_tracker', 'digest', NULL, 'ordinary personal reminder 081', 'ordinary noise notification.', '{"noise":true}', '2026-06-02T08:21:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_082', 'user_liang_weimin', 'email', 'digest', NULL, 'ordinary personal reminder 082', 'ordinary noise notification.', '{"noise":true}', '2026-06-03T08:22:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_083', 'user_liang_weimin', 'notion', 'digest', NULL, 'ordinary personal reminder 083', 'ordinary noise notification.', '{"noise":true}', '2026-06-04T08:23:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_084', 'user_liang_weimin', 'calendar', 'digest', NULL, 'ordinary personal reminder 084', 'ordinary noise notification.', '{"noise":true}', '2026-06-05T08:24:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_085', 'user_liang_weimin', 'health_tracker', 'digest', NULL, 'ordinary personal reminder 085', 'ordinary noise notification.', '{"noise":true}', '2026-06-06T08:25:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_086', 'user_liang_weimin', 'email', 'digest', NULL, 'ordinary personal reminder 086', 'ordinary noise notification.', '{"noise":true}', '2026-06-07T08:26:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_087', 'user_liang_weimin', 'notion', 'digest', NULL, 'ordinary personal reminder 087', 'ordinary noise notification.', '{"noise":true}', '2026-06-08T08:27:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_088', 'user_liang_weimin', 'calendar', 'digest', NULL, 'ordinary personal reminder 088', 'ordinary noise notification.', '{"noise":true}', '2026-06-09T08:28:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_089', 'user_liang_weimin', 'health_tracker', 'digest', NULL, 'ordinary personal reminder 089', 'ordinary noise notification.', '{"noise":true}', '2026-06-10T08:29:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_090', 'user_liang_weimin', 'email', 'digest', NULL, 'ordinary personal reminder 090', 'ordinary noise notification.', '{"noise":true}', '2026-06-11T08:30:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_091', 'user_liang_weimin', 'notion', 'digest', NULL, 'ordinary personal reminder 091', 'ordinary noise notification.', '{"noise":true}', '2026-06-12T08:31:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_092', 'user_liang_weimin', 'calendar', 'digest', NULL, 'ordinary personal reminder 092', 'ordinary noise notification.', '{"noise":true}', '2026-06-13T08:32:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_093', 'user_liang_weimin', 'health_tracker', 'digest', NULL, 'ordinary personal reminder 093', 'ordinary noise notification.', '{"noise":true}', '2026-06-14T08:33:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_094', 'user_liang_weimin', 'email', 'digest', NULL, 'ordinary personal reminder 094', 'ordinary noise notification.', '{"noise":true}', '2026-06-15T08:34:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_095', 'user_liang_weimin', 'notion', 'digest', NULL, 'ordinary personal reminder 095', 'ordinary noise notification.', '{"noise":true}', '2026-06-16T08:35:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_096', 'user_liang_weimin', 'calendar', 'digest', NULL, 'ordinary personal reminder 096', 'ordinary noise notification.', '{"noise":true}', '2026-06-17T08:36:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_097', 'user_liang_weimin', 'health_tracker', 'digest', NULL, 'ordinary personal reminder 097', 'ordinary noise notification.', '{"noise":true}', '2026-06-18T08:37:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_098', 'user_liang_weimin', 'email', 'digest', NULL, 'ordinary personal reminder 098', 'ordinary noise notification.', '{"noise":true}', '2026-06-19T08:38:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_099', 'user_liang_weimin', 'notion', 'digest', NULL, 'ordinary personal reminder 099', 'ordinary noise notification.', '{"noise":true}', '2026-06-20T08:39:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_100', 'user_liang_weimin', 'calendar', 'digest', NULL, 'ordinary personal reminder 100', 'ordinary noise notification.', '{"noise":true}', '2026-06-21T08:40:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_101', 'user_liang_weimin', 'health_tracker', 'digest', NULL, 'ordinary personal reminder 101', 'ordinary noise notification.', '{"noise":true}', '2026-06-22T08:41:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_102', 'user_liang_weimin', 'email', 'digest', NULL, 'ordinary personal reminder 102', 'ordinary noise notification.', '{"noise":true}', '2026-06-23T08:42:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_103', 'user_liang_weimin', 'notion', 'digest', NULL, 'ordinary personal reminder 103', 'ordinary noise notification.', '{"noise":true}', '2026-06-24T08:43:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_104', 'user_liang_weimin', 'calendar', 'digest', NULL, 'ordinary personal reminder 104', 'ordinary noise notification.', '{"noise":true}', '2026-06-25T08:44:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_105', 'user_liang_weimin', 'health_tracker', 'digest', NULL, 'ordinary personal reminder 105', 'ordinary noise notification.', '{"noise":true}', '2026-06-26T08:45:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_106', 'user_liang_weimin', 'email', 'digest', NULL, 'ordinary personal reminder 106', 'ordinary noise notification.', '{"noise":true}', '2026-06-27T08:46:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_107', 'user_liang_weimin', 'notion', 'digest', NULL, 'ordinary personal reminder 107', 'ordinary noise notification.', '{"noise":true}', '2026-06-28T08:47:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_108', 'user_liang_weimin', 'calendar', 'digest', NULL, 'ordinary personal reminder 108', 'ordinary noise notification.', '{"noise":true}', '2026-06-29T08:48:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_109', 'user_liang_weimin', 'health_tracker', 'digest', NULL, 'ordinary personal reminder 109', 'ordinary noise notification.', '{"noise":true}', '2026-06-30T08:49:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_110', 'user_liang_weimin', 'email', 'digest', NULL, 'ordinary personal reminder 110', 'ordinary noise notification.', '{"noise":true}', '2026-07-01T08:50:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_111', 'user_liang_weimin', 'notion', 'digest', NULL, 'ordinary personal reminder 111', 'ordinary noise notification.', '{"noise":true}', '2026-07-02T08:51:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_112', 'user_liang_weimin', 'calendar', 'digest', NULL, 'ordinary personal reminder 112', 'ordinary noise notification.', '{"noise":true}', '2026-07-03T08:52:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_113', 'user_liang_weimin', 'health_tracker', 'digest', NULL, 'ordinary personal reminder 113', 'ordinary noise notification.', '{"noise":true}', '2026-07-04T08:53:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_114', 'user_liang_weimin', 'email', 'digest', NULL, 'ordinary personal reminder 114', 'ordinary noise notification.', '{"noise":true}', '2026-07-05T08:54:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_115', 'user_liang_weimin', 'notion', 'digest', NULL, 'ordinary personal reminder 115', 'ordinary noise notification.', '{"noise":true}', '2026-07-06T08:55:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_116', 'user_liang_weimin', 'calendar', 'digest', NULL, 'ordinary personal reminder 116', 'ordinary noise notification.', '{"noise":true}', '2026-07-07T08:56:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_117', 'user_liang_weimin', 'health_tracker', 'digest', NULL, 'ordinary personal reminder 117', 'ordinary noise notification.', '{"noise":true}', '2026-07-08T08:57:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_118', 'user_liang_weimin', 'email', 'digest', NULL, 'ordinary personal reminder 118', 'ordinary noise notification.', '{"noise":true}', '2026-07-09T08:58:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_119', 'user_liang_weimin', 'notion', 'digest', NULL, 'ordinary personal reminder 119', 'ordinary noise notification.', '{"noise":true}', '2026-07-10T08:59:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_120', 'user_liang_weimin', 'calendar', 'digest', NULL, 'ordinary personal reminder 120', 'ordinary noise notification.', '{"noise":true}', '2026-06-01T08:00:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_121', 'user_liang_weimin', 'health_tracker', 'digest', NULL, 'ordinary personal reminder 121', 'ordinary noise notification.', '{"noise":true}', '2026-06-02T08:01:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_122', 'user_liang_weimin', 'email', 'digest', NULL, 'ordinary personal reminder 122', 'ordinary noise notification.', '{"noise":true}', '2026-06-03T08:02:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_123', 'user_liang_weimin', 'notion', 'digest', NULL, 'ordinary personal reminder 123', 'ordinary noise notification.', '{"noise":true}', '2026-06-04T08:03:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_124', 'user_liang_weimin', 'calendar', 'digest', NULL, 'ordinary personal reminder 124', 'ordinary noise notification.', '{"noise":true}', '2026-06-05T08:04:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_125', 'user_liang_weimin', 'health_tracker', 'digest', NULL, 'ordinary personal reminder 125', 'ordinary noise notification.', '{"noise":true}', '2026-06-06T08:05:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_126', 'user_liang_weimin', 'email', 'digest', NULL, 'ordinary personal reminder 126', 'ordinary noise notification.', '{"noise":true}', '2026-06-07T08:06:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_127', 'user_liang_weimin', 'notion', 'digest', NULL, 'ordinary personal reminder 127', 'ordinary noise notification.', '{"noise":true}', '2026-06-08T08:07:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_128', 'user_liang_weimin', 'calendar', 'digest', NULL, 'ordinary personal reminder 128', 'ordinary noise notification.', '{"noise":true}', '2026-06-09T08:08:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_129', 'user_liang_weimin', 'health_tracker', 'digest', NULL, 'ordinary personal reminder 129', 'ordinary noise notification.', '{"noise":true}', '2026-06-10T08:09:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_130', 'user_liang_weimin', 'email', 'digest', NULL, 'ordinary personal reminder 130', 'ordinary noise notification.', '{"noise":true}', '2026-06-11T08:10:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_131', 'user_liang_weimin', 'notion', 'digest', NULL, 'ordinary personal reminder 131', 'ordinary noise notification.', '{"noise":true}', '2026-06-12T08:11:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_132', 'user_liang_weimin', 'calendar', 'digest', NULL, 'ordinary personal reminder 132', 'ordinary noise notification.', '{"noise":true}', '2026-06-13T08:12:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_133', 'user_liang_weimin', 'health_tracker', 'digest', NULL, 'ordinary personal reminder 133', 'ordinary noise notification.', '{"noise":true}', '2026-06-14T08:13:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_134', 'user_liang_weimin', 'email', 'digest', NULL, 'ordinary personal reminder 134', 'ordinary noise notification.', '{"noise":true}', '2026-06-15T08:14:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_135', 'user_liang_weimin', 'notion', 'digest', NULL, 'ordinary personal reminder 135', 'ordinary noise notification.', '{"noise":true}', '2026-06-16T08:15:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_136', 'user_liang_weimin', 'calendar', 'digest', NULL, 'ordinary personal reminder 136', 'ordinary noise notification.', '{"noise":true}', '2026-06-17T08:16:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_137', 'user_liang_weimin', 'health_tracker', 'digest', NULL, 'ordinary personal reminder 137', 'ordinary noise notification.', '{"noise":true}', '2026-06-18T08:17:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_138', 'user_liang_weimin', 'email', 'digest', NULL, 'ordinary personal reminder 138', 'ordinary noise notification.', '{"noise":true}', '2026-06-19T08:18:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_139', 'user_liang_weimin', 'notion', 'digest', NULL, 'ordinary personal reminder 139', 'ordinary noise notification.', '{"noise":true}', '2026-06-20T08:19:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_140', 'user_liang_weimin', 'calendar', 'digest', NULL, 'ordinary personal reminder 140', 'ordinary noise notification.', '{"noise":true}', '2026-06-21T08:20:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_141', 'user_liang_weimin', 'health_tracker', 'digest', NULL, 'ordinary personal reminder 141', 'ordinary noise notification.', '{"noise":true}', '2026-06-22T08:21:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_142', 'user_liang_weimin', 'email', 'digest', NULL, 'ordinary personal reminder 142', 'ordinary noise notification.', '{"noise":true}', '2026-06-23T08:22:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_143', 'user_liang_weimin', 'notion', 'digest', NULL, 'ordinary personal reminder 143', 'ordinary noise notification.', '{"noise":true}', '2026-06-24T08:23:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_144', 'user_liang_weimin', 'calendar', 'digest', NULL, 'ordinary personal reminder 144', 'ordinary noise notification.', '{"noise":true}', '2026-06-25T08:24:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_145', 'user_liang_weimin', 'health_tracker', 'digest', NULL, 'ordinary personal reminder 145', 'ordinary noise notification.', '{"noise":true}', '2026-06-26T08:25:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_146', 'user_liang_weimin', 'email', 'digest', NULL, 'ordinary personal reminder 146', 'ordinary noise notification.', '{"noise":true}', '2026-06-27T08:26:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_147', 'user_liang_weimin', 'notion', 'digest', NULL, 'ordinary personal reminder 147', 'ordinary noise notification.', '{"noise":true}', '2026-06-28T08:27:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_148', 'user_liang_weimin', 'calendar', 'digest', NULL, 'ordinary personal reminder 148', 'ordinary noise notification.', '{"noise":true}', '2026-06-29T08:28:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_149', 'user_liang_weimin', 'health_tracker', 'digest', NULL, 'ordinary personal reminder 149', 'ordinary noise notification.', '{"noise":true}', '2026-06-30T08:29:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_150', 'user_liang_weimin', 'email', 'digest', NULL, 'ordinary personal reminder 150', 'ordinary noise notification.', '{"noise":true}', '2026-07-01T08:30:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_151', 'user_liang_weimin', 'notion', 'digest', NULL, 'ordinary personal reminder 151', 'ordinary noise notification.', '{"noise":true}', '2026-07-02T08:31:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_152', 'user_liang_weimin', 'calendar', 'digest', NULL, 'ordinary personal reminder 152', 'ordinary noise notification.', '{"noise":true}', '2026-07-03T08:32:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_153', 'user_liang_weimin', 'health_tracker', 'digest', NULL, 'ordinary personal reminder 153', 'ordinary noise notification.', '{"noise":true}', '2026-07-04T08:33:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_154', 'user_liang_weimin', 'email', 'digest', NULL, 'ordinary personal reminder 154', 'ordinary noise notification.', '{"noise":true}', '2026-07-05T08:34:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_155', 'user_liang_weimin', 'notion', 'digest', NULL, 'ordinary personal reminder 155', 'ordinary noise notification.', '{"noise":true}', '2026-07-06T08:35:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_156', 'user_liang_weimin', 'calendar', 'digest', NULL, 'ordinary personal reminder 156', 'ordinary noise notification.', '{"noise":true}', '2026-07-07T08:36:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_157', 'user_liang_weimin', 'health_tracker', 'digest', NULL, 'ordinary personal reminder 157', 'ordinary noise notification.', '{"noise":true}', '2026-07-08T08:37:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_158', 'user_liang_weimin', 'email', 'digest', NULL, 'ordinary personal reminder 158', 'ordinary noise notification.', '{"noise":true}', '2026-07-09T08:38:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_159', 'user_liang_weimin', 'notion', 'digest', NULL, 'ordinary personal reminder 159', 'ordinary noise notification.', '{"noise":true}', '2026-07-10T08:39:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_160', 'user_liang_weimin', 'calendar', 'digest', NULL, 'ordinary personal reminder 160', 'ordinary noise notification.', '{"noise":true}', '2026-06-01T08:40:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_161', 'user_liang_weimin', 'health_tracker', 'digest', NULL, 'ordinary personal reminder 161', 'ordinary noise notification.', '{"noise":true}', '2026-06-02T08:41:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_162', 'user_liang_weimin', 'email', 'digest', NULL, 'ordinary personal reminder 162', 'ordinary noise notification.', '{"noise":true}', '2026-06-03T08:42:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_163', 'user_liang_weimin', 'notion', 'digest', NULL, 'ordinary personal reminder 163', 'ordinary noise notification.', '{"noise":true}', '2026-06-04T08:43:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_164', 'user_liang_weimin', 'calendar', 'digest', NULL, 'ordinary personal reminder 164', 'ordinary noise notification.', '{"noise":true}', '2026-06-05T08:44:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_165', 'user_liang_weimin', 'health_tracker', 'digest', NULL, 'ordinary personal reminder 165', 'ordinary noise notification.', '{"noise":true}', '2026-06-06T08:45:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_166', 'user_liang_weimin', 'email', 'digest', NULL, 'ordinary personal reminder 166', 'ordinary noise notification.', '{"noise":true}', '2026-06-07T08:46:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_167', 'user_liang_weimin', 'notion', 'digest', NULL, 'ordinary personal reminder 167', 'ordinary noise notification.', '{"noise":true}', '2026-06-08T08:47:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_168', 'user_liang_weimin', 'calendar', 'digest', NULL, 'ordinary personal reminder 168', 'ordinary noise notification.', '{"noise":true}', '2026-06-09T08:48:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_169', 'user_liang_weimin', 'health_tracker', 'digest', NULL, 'ordinary personal reminder 169', 'ordinary noise notification.', '{"noise":true}', '2026-06-10T08:49:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_170', 'user_liang_weimin', 'email', 'digest', NULL, 'ordinary personal reminder 170', 'ordinary noise notification.', '{"noise":true}', '2026-06-11T08:50:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_171', 'user_liang_weimin', 'notion', 'digest', NULL, 'ordinary personal reminder 171', 'ordinary noise notification.', '{"noise":true}', '2026-06-12T08:51:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_172', 'user_liang_weimin', 'calendar', 'digest', NULL, 'ordinary personal reminder 172', 'ordinary noise notification.', '{"noise":true}', '2026-06-13T08:52:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_173', 'user_liang_weimin', 'health_tracker', 'digest', NULL, 'ordinary personal reminder 173', 'ordinary noise notification.', '{"noise":true}', '2026-06-14T08:53:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_174', 'user_liang_weimin', 'email', 'digest', NULL, 'ordinary personal reminder 174', 'ordinary noise notification.', '{"noise":true}', '2026-06-15T08:54:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_175', 'user_liang_weimin', 'notion', 'digest', NULL, 'ordinary personal reminder 175', 'ordinary noise notification.', '{"noise":true}', '2026-06-16T08:55:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_176', 'user_liang_weimin', 'calendar', 'digest', NULL, 'ordinary personal reminder 176', 'ordinary noise notification.', '{"noise":true}', '2026-06-17T08:56:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_177', 'user_liang_weimin', 'health_tracker', 'digest', NULL, 'ordinary personal reminder 177', 'ordinary noise notification.', '{"noise":true}', '2026-06-18T08:57:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_178', 'user_liang_weimin', 'email', 'digest', NULL, 'ordinary personal reminder 178', 'ordinary noise notification.', '{"noise":true}', '2026-06-19T08:58:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_179', 'user_liang_weimin', 'notion', 'digest', NULL, 'ordinary personal reminder 179', 'ordinary noise notification.', '{"noise":true}', '2026-06-20T08:59:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_180', 'user_liang_weimin', 'calendar', 'digest', NULL, 'ordinary personal reminder 180', 'ordinary noise notification.', '{"noise":true}', '2026-06-21T09:00:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_181', 'user_liang_weimin', 'health_tracker', 'digest', NULL, 'ordinary personal reminder 181', 'ordinary noise notification.', '{"noise":true}', '2026-06-22T09:01:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_182', 'user_liang_weimin', 'email', 'digest', NULL, 'ordinary personal reminder 182', 'ordinary noise notification.', '{"noise":true}', '2026-06-23T09:02:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_183', 'user_liang_weimin', 'notion', 'digest', NULL, 'ordinary personal reminder 183', 'ordinary noise notification.', '{"noise":true}', '2026-06-24T09:03:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_184', 'user_liang_weimin', 'calendar', 'digest', NULL, 'ordinary personal reminder 184', 'ordinary noise notification.', '{"noise":true}', '2026-06-25T09:04:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_185', 'user_liang_weimin', 'health_tracker', 'digest', NULL, 'ordinary personal reminder 185', 'ordinary noise notification.', '{"noise":true}', '2026-06-26T09:05:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_186', 'user_liang_weimin', 'email', 'digest', NULL, 'ordinary personal reminder 186', 'ordinary noise notification.', '{"noise":true}', '2026-06-27T09:06:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_187', 'user_liang_weimin', 'notion', 'digest', NULL, 'ordinary personal reminder 187', 'ordinary noise notification.', '{"noise":true}', '2026-06-28T09:07:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_188', 'user_liang_weimin', 'calendar', 'digest', NULL, 'ordinary personal reminder 188', 'ordinary noise notification.', '{"noise":true}', '2026-06-29T09:08:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_189', 'user_liang_weimin', 'health_tracker', 'digest', NULL, 'ordinary personal reminder 189', 'ordinary noise notification.', '{"noise":true}', '2026-06-30T09:09:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_190', 'user_liang_weimin', 'email', 'digest', NULL, 'ordinary personal reminder 190', 'ordinary noise notification.', '{"noise":true}', '2026-07-01T09:10:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_191', 'user_liang_weimin', 'notion', 'digest', NULL, 'ordinary personal reminder 191', 'ordinary noise notification.', '{"noise":true}', '2026-07-02T09:11:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_192', 'user_liang_weimin', 'calendar', 'digest', NULL, 'ordinary personal reminder 192', 'ordinary noise notification.', '{"noise":true}', '2026-07-03T09:12:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_193', 'user_liang_weimin', 'health_tracker', 'digest', NULL, 'ordinary personal reminder 193', 'ordinary noise notification.', '{"noise":true}', '2026-07-04T09:13:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_194', 'user_liang_weimin', 'email', 'digest', NULL, 'ordinary personal reminder 194', 'ordinary noise notification.', '{"noise":true}', '2026-07-05T09:14:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_195', 'user_liang_weimin', 'notion', 'digest', NULL, 'ordinary personal reminder 195', 'ordinary noise notification.', '{"noise":true}', '2026-07-06T09:15:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_196', 'user_liang_weimin', 'calendar', 'digest', NULL, 'ordinary personal reminder 196', 'ordinary noise notification.', '{"noise":true}', '2026-07-07T09:16:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_197', 'user_liang_weimin', 'health_tracker', 'digest', NULL, 'ordinary personal reminder 197', 'ordinary noise notification.', '{"noise":true}', '2026-07-08T09:17:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_198', 'user_liang_weimin', 'email', 'digest', NULL, 'ordinary personal reminder 198', 'ordinary noise notification.', '{"noise":true}', '2026-07-09T09:18:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_199', 'user_liang_weimin', 'notion', 'digest', NULL, 'ordinary personal reminder 199', 'ordinary noise notification.', '{"noise":true}', '2026-07-10T09:19:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_200', 'user_liang_weimin', 'calendar', 'digest', NULL, 'ordinary personal reminder 200', 'ordinary noise notification.', '{"noise":true}', '2026-07-11T09:20:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_201', 'user_liang_weimin', 'health_tracker', 'digest', NULL, 'ordinary personal reminder 201', 'ordinary noise notification.', '{"noise":true}', '2026-07-12T09:21:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_202', 'user_liang_weimin', 'email', 'digest', NULL, 'ordinary personal reminder 202', 'ordinary noise notification.', '{"noise":true}', '2026-07-13T09:22:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_203', 'user_liang_weimin', 'notion', 'digest', NULL, 'ordinary personal reminder 203', 'ordinary noise notification.', '{"noise":true}', '2026-07-14T09:23:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_204', 'user_liang_weimin', 'calendar', 'digest', NULL, 'ordinary personal reminder 204', 'ordinary noise notification.', '{"noise":true}', '2026-07-15T09:24:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_205', 'user_liang_weimin', 'health_tracker', 'digest', NULL, 'ordinary personal reminder 205', 'ordinary noise notification.', '{"noise":true}', '2026-07-16T09:25:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_206', 'user_liang_weimin', 'email', 'digest', NULL, 'ordinary personal reminder 206', 'ordinary noise notification.', '{"noise":true}', '2026-07-17T09:26:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_207', 'user_liang_weimin', 'notion', 'digest', NULL, 'ordinary personal reminder 207', 'ordinary noise notification.', '{"noise":true}', '2026-07-18T09:27:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_208', 'user_liang_weimin', 'calendar', 'digest', NULL, 'ordinary personal reminder 208', 'ordinary noise notification.', '{"noise":true}', '2026-07-19T09:28:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_209', 'user_liang_weimin', 'health_tracker', 'digest', NULL, 'ordinary personal reminder 209', 'ordinary noise notification.', '{"noise":true}', '2026-07-20T09:29:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_210', 'user_liang_weimin', 'email', 'digest', NULL, 'ordinary personal reminder 210', 'ordinary noise notification.', '{"noise":true}', '2026-07-21T09:30:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_211', 'user_liang_weimin', 'notion', 'digest', NULL, 'ordinary personal reminder 211', 'ordinary noise notification.', '{"noise":true}', '2026-07-22T09:31:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_212', 'user_liang_weimin', 'calendar', 'digest', NULL, 'ordinary personal reminder 212', 'ordinary noise notification.', '{"noise":true}', '2026-07-23T09:32:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_213', 'user_liang_weimin', 'health_tracker', 'digest', NULL, 'ordinary personal reminder 213', 'ordinary noise notification.', '{"noise":true}', '2026-07-24T09:33:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_214', 'user_liang_weimin', 'email', 'digest', NULL, 'ordinary personal reminder 214', 'ordinary noise notification.', '{"noise":true}', '2026-07-25T09:34:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_215', 'user_liang_weimin', 'notion', 'digest', NULL, 'ordinary personal reminder 215', 'ordinary noise notification.', '{"noise":true}', '2026-07-26T09:35:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_216', 'user_liang_weimin', 'calendar', 'digest', NULL, 'ordinary personal reminder 216', 'ordinary noise notification.', '{"noise":true}', '2026-07-27T09:36:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_217', 'user_liang_weimin', 'health_tracker', 'digest', NULL, 'ordinary personal reminder 217', 'ordinary noise notification.', '{"noise":true}', '2026-07-28T09:37:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_218', 'user_liang_weimin', 'email', 'digest', NULL, 'ordinary personal reminder 218', 'ordinary noise notification.', '{"noise":true}', '2026-07-29T09:38:00+08:00', 1);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_gt_noise_219', 'user_liang_weimin', 'notion', 'digest', NULL, 'ordinary personal reminder 219', 'ordinary noise notification.', '{"noise":true}', '2026-07-30T09:39:00+08:00', 1);

UPDATE notifications
SET created_at = printf('2026-06-%02dT%02d:%02d:00+08:00', 1 + ((CAST(substr(notification_id, -3) AS INTEGER)) % 28), 7 + (CAST(substr(notification_id, -3) AS INTEGER) % 11), CAST(substr(notification_id, -3) AS INTEGER) % 60),
    title = CASE (CAST(substr(notification_id, -3) AS INTEGER) % 15)
      WHEN 0 THEN 'pre-class hydration personal reminder' WHEN 1 THEN 'midday short-walk prompt' WHEN 2 THEN 'game-record organization completion reminder'
      WHEN 3 THEN 'eyes-closed rest after evening class' WHEN 4 THEN 'classroomlightingreview' WHEN 5 THEN 'between-classscapular movement'
      WHEN 6 THEN 'weekendmeal window' WHEN 7 THEN 'dataupreviewoffscreenpromptshow' WHEN 8 THEN 'privatepersoncalendarconflictcheck'
      WHEN 9 THEN 'health recordmissingreview' WHEN 10 THEN 'parent-email authorization boundary' WHEN 11 THEN 'classlocationchangedataverify'
      WHEN 12 THEN 'distinguish step sources' WHEN 13 THEN 'neck stiffness self-report' ELSE 'eye fatigue self-report' END,
    body =
      CASE (CAST(substr(notification_id, -3) AS INTEGER) % 15)
        WHEN 0 THEN 'Hydrate before the next class; do not use training to crowd out meals.' WHEN 1 THEN 'ifhasthreearrivefivescoredataairarchive,candatadatadatawalking.'
        WHEN 2 THEN 'completedpaperrecordorganizeorganizeafteroffopenhead-downdatadata.' WHEN 3 THEN 'eveningclassendafterdatacloseeyeanddatadatadatadata.'
        WHEN 4 THEN 'confirmedafterarrangelightingisdatadatareview,dataneedtimedatadataplace.' WHEN 5 THEN 'between-classdatalowcandatascapularaftercompress,notforcedataneck.'
        WHEN 6 THEN 'Keep lunch during long classes; do not teach continuously to the end.' WHEN 7 THEN 'Do screen review in segments with distance gaze after each segment.'
        WHEN 8 THEN 'onlyconditionorganizepersonal reminder,notdatachangeGo Academyformalclass.' WHEN 9 THEN 'Mark missing values as missing; do not estimate completion.'
        WHEN 10 THEN 'Without user authorization, do not disclose health information to parents.' WHEN 11 THEN 'Refresh classroom and time in the calendar before execution.'
        WHEN 12 THEN 'Record work movement and intentional walking separately.' WHEN 13 THEN 'recordstiffstiffscoreandcontinuetime,no diagnosis.'
        ELSE 'recordeye fatiguescorewithscreen/Go boardexposurebackgroundcontext.' END
      || ' '
      || CASE CAST((CAST(substr(notification_id, -3) AS INTEGER)) / 15 AS INTEGER)
        WHEN 0 THEN 'status completed.' WHEN 1 THEN 'statusread.' WHEN 2 THEN 'Historically skipped once.' WHEN 3 THEN 'Historically rescheduled due to class conflict.'
        WHEN 4 THEN 'Historically changed to rest due to fatigue.' WHEN 5 THEN 'Historically device data was complete.' WHEN 6 THEN 'Historically device data was partially missing.'
        WHEN 7 THEN 'Historically recorded self-report only.' WHEN 8 THEN 'Historically consistent with the personal calendar.' WHEN 9 THEN 'Historically no external email was needed.'
        WHEN 10 THEN 'Historically no purchase was involved.' WHEN 11 THEN 'Historically no equipment was used.' WHEN 12 THEN 'Historically retained the next review.'
        WHEN 13 THEN 'Historically closed risk.' ELSE 'for natural retrieval only.' END,
    payload_json = json_object('kind','historical_personal_reminder','source_context',source,'personal_only',1)
WHERE notification_id LIKE 'ntf_gt_noise_%';

-- Persist each reminder's actual topic, time and source in structured form;
-- repeated technical payload shells do not count as separate business facts.
UPDATE notifications
SET payload_json = json_object(
      'kind','historical_personal_reminder',
      'topic',title,
      'source_context',source,
      'recorded_at',created_at,
      'personal_only',1,
      'completion_context',body)
WHERE notification_id LIKE 'ntf_gt_noise_%';

UPDATE notifications
SET notification_id = replace(notification_id, 'ntf_gt_noise_', 'ntf_gt_archive_')
WHERE notification_id LIKE 'ntf_gt_noise_%';
