-- Curated Stage-0 seed for career_background_check_consent / job_board.

BEGIN;

INSERT INTO companies (company_id, name, industry, size, stage, city, intro, rating) VALUES
  ('comp_meituan', 'Meituan', 'local services/internet', '10000translated text', 'public', 'Shanghai', 'local servicestransaction、fulfillmenttranslated textplatformtranslated text。', 4.1),
  ('comp_xiaohongshu', 'translated text', 'internet/communitye-commerce', '5000-10000translated text', 'Dtranslated text', 'Shanghai', 'community、e-commercetranslated textinternetcompany。', 4.3),
  ('comp_zhipu', 'translated textAI', 'artificial intelligence', '500-1000translated text', 'Ctranslated text', 'Shanghai', 'translated textplatform、translated textservicetranslated text。', 4.2),
  ('comp_bilibili', 'translated text', 'internet/translated textcommunity', '5000-10000translated text', 'public', 'Shanghai', 'translated text、translated text、communitytranslated textcontenttranslated textplatform。', 4.1),
  ('comp_borchina', 'translated text', 'IToutsourced role', '1000-5000translated text', 'private', 'Shanghai', 'translated textoutsourced roletranslated textstaffing-agency roleservicetranslated text，translated textinternettranslated text。', 3.1),
  ('comp_ruijietech', 'translated text', 'ITtranslated textoutsourced role', '1000-5000translated text', 'private', 'Shanghai', 'translated textstaffing-agency roleservice。', 3.0),
  ('comp_dewu', 'Dewu', 'e-commerce/translated text', '5000-10000translated text', 'private', 'Shanghai', 'translated texte-commerce、transactionfulfillmenttranslated textdo notserviceplatform。', 3.9),
  ('comp_pinduoduo', 'translated text', 'internet/e-commerce', '10000translated text', 'public', 'Shanghai', 'e-commercetransaction、translated textplatform。', 4.0),
  ('comp_cainiao', 'translated text', 'logisticstranslated text', '10000translated text', 'private', 'Shanghai', 'logisticstranslated text、translated textplatform。', 3.9),
  ('comp_ctrip', 'translated text', 'translated text', '10000translated text', 'public', 'Shanghai', 'translated text、translated textserviceplatform。', 4.0),
  ('comp_huolala', 'translated text', 'logisticsinternet', '5000-10000translated text', 'Dtranslated text', 'Shanghai', 'translated texttransaction、translated textserviceplatform。', 3.8),
  ('comp_qiniu', 'translated text', 'translated textcalculate', '1000-5000translated text', 'Dtranslated text', 'Shanghai', 'translated text、translated textcalculateservicetranslated text。', 4.0),
  ('comp_pingan', 'translated text', 'fintech', '10000translated text', 'translated text', 'Shanghai', 'translated textsystem、datatranslated textplatform。', 3.8),
  ('comp_unionpay', 'translated textdata', 'paymenttranslated text', '5000-10000translated text', 'translated text', 'Shanghai', 'translated textpayment、translated textdataservice。', 4.0),
  ('comp_lufax', 'translated text', 'fintech', '5000-10000translated text', 'public', 'Shanghai', 'translated text、translated textplatform。', 3.7),
  ('comp_transsion', 'translated text', 'translated text', '10000translated text', 'public', 'Shanghai', 'translated text、translated textservicetranslated textplatform。', 3.9),
  ('comp_saic', 'translated text', 'translated text', '10000translated text', 'translated text', 'Shanghai', 'translated text、translated textservicetranslated textplatform。', 4.0),
  ('comp_ximalaya', 'translated text', 'internet/translated text', '1000-5000translated text', 'private', 'Shanghai', 'translated textcontent、translated text、translated textserviceplatform。', 3.8),
  ('comp_zhongtong', 'translated text', 'logisticstranslated text', '5000-10000translated text', 'public', 'Shanghai', 'translated text、translated textplatform。', 3.8),
  ('comp_hellobike', 'translated text', 'translated text', '5000-10000translated text', 'Dtranslated text', 'Shanghai', 'translated text、local servicestranslated textserviceplatform。', 3.9),
  ('comp_ubicloud', 'translated text', 'translated textcalculate', '1000-5000translated text', 'public', 'Shanghai', 'translated text、translated textservicetranslated text。', 3.8),
  ('comp_sensetime', 'translated text', 'artificial intelligence', '5000-10000translated text', 'public', 'Shanghai', 'artificial intelligenceplatform、translated text AI translated text。', 3.9),
  ('comp_yitu', 'translated text', 'artificial intelligence', '1000-5000translated text', 'Dtranslated text', 'Shanghai', 'translated text、healthcaretranslated textcalculateplatform。', 3.7),
  ('comp_honeycomb', 'translated text', 'translated text', '5000-10000translated text', 'translated text', 'Shanghai', 'translated text、translated textplatform。', 3.8),
  ('comp_fosun', 'translated text', 'translated text', '1000-5000translated text', 'translated text', 'Shanghai', 'translated textdata、translated text。', 3.8),
  ('comp_springair', 'translated text', 'translated text', '1000-5000translated text', 'public', 'Shanghai', 'translated text、translated textservicesystem。', 4.0),
  ('comp_baosight', 'translated text', 'translated textinternet', '5000-10000translated text', 'public', 'Shanghai', 'translated text、translated textinternettranslated textplatform。', 4.1),
  ('comp_mihoyo', 'translated text', 'translated text', '5000-10000translated text', 'private', 'Shanghai', 'translated text、translated textservice。', 4.4),
  ('comp_lilith', 'translated text', 'translated text', '1000-5000translated text', 'private', 'Shanghai', 'translated text、translated textdataplatform。', 4.2),
  ('comp_epicmed', 'translated text', 'healthcaretranslated text', '1000-5000translated text', 'Ctranslated text', 'Shanghai', 'healthcaretranslated textartificial intelligencetranslated textplatform。', 4.0);

INSERT INTO jobs (job_id, company_id, title, city, category, salary_min_minor, salary_max_minor, salary_months, experience, education, jd, requirements, tags, status, posted_at) VALUES
  ('jb-dqs7vegrnhjsx', 'comp_meituan', 'senior backend engineer (transaction platform)', 'Shanghai', 'backend', 4500000, 7000000, 16, '5-10', 'master', 'Responsible for transaction fulfillment services; sharding, configuration, governance, distributed tracing, transaction integrity, and concurrency.', 'Proficient in Java and Spring Cloud; experience with sharding, configuration, governance, tracing, transactions, and concurrency.', 'Java,transaction,sharding,configuration,governance', 'open', '2026-05-02T08:37:00Z'),
  ('jb-ie3wkxyoibmzx', 'comp_xiaohongshu', 'backend development engineer (e-commerce)', 'Shanghai', 'backend', 4000000, 6500000, 16, '3-5', 'bachelor', 'Build e-commerce retrieval and feed services with consistency guarantees.', 'Familiar with Java and Go; experience in retrieval, feed, and consistency.', 'Go,e-commerce,retrieval,feed,consistency', 'open', '2026-05-03T09:12:00Z'),
  ('jb-torw2k5f73wax', 'comp_zhipu', 'platform development engineer (inference platform)', 'Shanghai', 'backend', 5000000, 8000000, 15, '5-10', 'master', 'Develop GPU scheduling and inference services with optimization.', 'Familiar with Go/C++ and Kubernetes; GPU scheduling, inference, and optimization experience.', 'Go,AI platform,GPU scheduling,inference,optimization', 'open', '2026-05-04T10:26:00Z'),
  ('jb-auul27fld7udx', 'comp_bilibili', 'service development engineer (danmaku)', 'Shanghai', 'backend', 3800000, 6000000, 15, '3-5', 'bachelor', 'Build high-volume connections and broadcast services with backpressure.', 'Familiar with Go, Java, and Netty; experience with connections, broadcast, and backpressure.', 'Go,connections,broadcast,backpressure', 'open', '2026-05-05T13:48:00Z'),
  ('jb-mpjdmhfipkmux', 'comp_borchina', 'seniorbackenddevelopmentengineer（translated text）', 'Shanghai', 'backend', 5500000, 8500000, 14, '5-10', 'master', 'translated textroletranslated textoutsourced role/dispatched-employment roletranslated text，translated textsigntranslated textinternettranslated text，translated text，translated textdirect-hiretranslated text。', 'Java/Go；translated textaccepttranslated text；translated text。', 'Java,translated text,translated text', 'open', '2026-05-06T15:05:00Z'),
  ('jb-4mkqknf63eipx', 'comp_ruijietech', 'platformbackendengineer（translated text）', 'Shanghai', 'backend', 5204500, 8004500, 14, '3-5', 'bachelor', 'translated textpassedtranslated textstaffing-agency roletranslated text，translated text，translated textplatformtranslated text，translated textsign。', 'Java；acceptstaffing-agency role/outsourced role；translated textplatformdevelopmentexperience。', 'Java,platform,translated text', 'open', '2026-05-07T16:42:00Z'),
  ('jb-zssclqhtxvygx', 'comp_dewu', 'senior backend engineer (transaction)', 'Shanghai', 'backend', 4804500, 7204500, 16, '5-10', 'master', 'E-commerce transaction role with a two years noncompete; no compensation is stated for the noncompete.', 'Proficient in Java transaction systems; review the two years noncompete and uncompensated noncompete risk before acceptance.', 'Java,transaction,noncompete,two years,no compensation', 'open', '2026-05-08T11:18:00Z'),
  ('jb-fvdivc37hwtjx', 'comp_pinduoduo', 'translated textseniorengineer', 'Shanghai', 'backend', 4600000, 7200000, 16, '5-10', 'bachelor', 'responsible fortranslated text、translated text，translated text。', 'translated textexperience，familiar with MySQL、Kafka、translated text。', 'translated text,translated text,Kafka', 'open', '2026-05-09T14:33:00Z'),
  ('jb-zbqia2h3kyghx', 'comp_pinduoduo', 'translated textplatformbackendengineer', 'Shanghai', 'backend', 4000000, 6200000, 16, '3-5', 'bachelor', 'translated text、translated textreviewtranslated textservice，translated textdatatranslated text。', 'familiar with Java、SQL translated text，translated text。', 'translated textplatform,Java,data', 'open', '2026-05-10T17:06:00Z'),
  ('jb-2jnd3nmudetux', 'comp_cainiao', 'logisticstranslated textplatformengineer', 'Shanghai', 'backend', 3900000, 6100000, 15, '5-10', 'bachelor', 'translated textcalculate、translated textservice，translated textstabletranslated text。', 'translated text Java、translated text，translated textsystemtranslated textexperience。', 'logistics,translated text,translated text', 'open', '2026-05-11T09:54:00Z'),
  ('jb-v4zyg3fdllhox', 'comp_cainiao', 'translated textbackendengineer', 'Shanghai', 'backend', 3500000, 5600000, 15, '3-5', 'bachelor', 'responsible fortranslated text、translated textplatform，translated text。', 'translated text，familiar withdatatranslated text、translated text。', 'translated text,translated text,translated text', 'open', '2026-05-12T10:41:00Z'),
  ('jb-e3ttx57kcfqwx', 'comp_ctrip', 'translated texttransactionbackendresponsible fortranslated text', 'Shanghai', 'backend', 4300000, 6800000, 15, '5-10', 'bachelor', 'responsible forsearchtranslated text，translated text。', 'translated texttransactiontranslated textexperience，familiar with Java、RPC translated text、translated text。', 'translated text,transaction,stabletranslated text', 'open', '2026-05-13T12:16:00Z'),
  ('jb-ksh2fqsbinayx', 'comp_ctrip', 'translated textplatformengineer', 'Shanghai', 'backend', 3400000, 5300000, 14, '3-5', 'bachelor', 'translated text、translated textaccounttranslated textservice，translated text。', 'familiar withtranslated text、worktranslated text，translated text。', 'translated text,worktranslated text,translated text', 'open', '2026-05-14T15:27:00Z'),
  ('jb-w737rf7qobiex', 'comp_huolala', 'translated textbackendengineer', 'Shanghai', 'backend', 3800000, 6000000, 15, '3-5', 'bachelor', 'translated text、translated textservice，translated textcalculate。', 'familiar with Go/Java、Redis、translated textservice，translated textexperience。', 'translated text,translated text,Go', 'open', '2026-05-15T18:03:00Z'),
  ('jb-jp35xfqbog46x', 'comp_huolala', 'translated textplatformengineer', 'Shanghai', 'backend', 3300000, 5000000, 14, '3-5', 'bachelor', 'translated text、translated textplatform，translated text。', 'translated textbackendservicedevelopment、translated textdatatranslated text，translated textcompliancetranslated text。', 'translated text,translated text,translated text', 'open', '2026-05-16T08:52:00Z'),
  ('jb-6tqcyhy73bnjx', 'comp_qiniu', 'translated textengineer', 'Shanghai', 'backend', 3900000, 5900000, 15, '5-10', 'bachelor', 'developmenttranslated text、translated text、translated textweektranslated textservice，translated textdatatranslated text。', 'proficient in Go，familiar withtranslated text、translated textdatatranslated text API translated text。', 'translated text,Go,translated text', 'open', '2026-05-17T11:47:00Z'),
  ('jb-yivchzgf5q6hx', 'comp_qiniu', 'translated textplatformengineer', 'Shanghai', 'backend', 3400000, 5400000, 14, '3-5', 'bachelor', 'translated text、translated textnoticetranslated text，translated text。', 'familiar with Go/Java、translated text，understandtranslated text。', 'translated text,translated text,translated text', 'open', '2026-05-18T13:21:00Z'),
  ('jb-dj7srw6deblax', 'comp_pingan', 'translated textplatformengineer', 'Shanghai', 'backend', 4000000, 6200000, 15, '5-10', 'bachelor', 'translated text、translated textreviewtranslated textplatform，translated text。', 'familiar with Java、translated text、translated textservicetranslated text，translated textsystemexperience。', 'translated text,translated text,translated text', 'open', '2026-05-19T16:08:00Z'),
  ('jb-xiybied3uenex', 'comp_pingan', 'translated textservicetranslated textengineer', 'Shanghai', 'backend', 3700000, 5800000, 15, '5-10', 'bachelor', 'translated text、translated text，translated textstabletranslated text。', 'translated textservicetranslated text、Kubernetes、translated textretrospectivetranslated text。', 'translated text,servicetranslated text,SRE', 'open', '2026-05-20T17:39:00Z'),
  ('jb-faq2amiec7igx', 'comp_unionpay', 'paymenttranslated textbackendengineer', 'Shanghai', 'backend', 3600000, 5400000, 14, '5-10', 'bachelor', 'translated textpaymenttranslated text、translated textsystem，translated textdatatranslated text。', 'familiar with Java、datatranslated text、translated textpaymentsecuritytranslated text，worktranslated textstable。', 'payment,translated text,translated text', 'open', '2026-05-21T09:28:00Z'),
  ('jb-6gkko6bjykjnx', 'comp_unionpay', 'translated textplatform API engineer', 'Shanghai', 'backend', 3200000, 4900000, 14, '3-5', 'bachelor', 'translated text、translated text、signtranslated textsigntranslated textservice，translated textdevelopmenttranslated text。', 'translated text API translated text、OAuth、translated text，translated textplatformtranslated text。', 'translated textplatform,API,security', 'open', '2026-05-22T10:07:00Z'),
  ('jb-sbwfgxwmpqtnx', 'comp_lufax', 'translated textaccountplatformengineer', 'Shanghai', 'backend', 3600000, 5600000, 15, '5-10', 'bachelor', 'responsible fortranslated textaccount、translated texttransactiontranslated text，translated textdatatranslated text。', 'familiar with Java、translated text，translated textdatatranslated text。', 'translated text,account,data', 'open', '2026-05-23T14:02:00Z'),
  ('jb-jcounzre5jdwx', 'comp_lufax', 'translated textcalculateengineer', 'Shanghai', 'backend', 3800000, 5900000, 15, '3-5', 'master', 'developmenttranslated text、translated text，translated text。', 'familiar with Flink、Kafka、Java translated text，translated text。', 'translated text,Flink,translated textcalculate', 'open', '2026-05-24T15:51:00Z'),
  ('jb-kr65shdc44cqx', 'comp_transsion', 'translated textplatformengineer', 'Shanghai', 'backend', 3500000, 5400000, 14, '5-10', 'bachelor', 'translated text、translated textservice，translated textcompliancetranslated text。', 'familiar with Java/Go、translated textservice、privacycompliancetranslated text。', 'translated text,translated text,compliance', 'open', '2026-05-25T17:14:00Z'),
  ('jb-hs7hhqpfgohbx', 'comp_transsion', 'translated textbackendengineer', 'Shanghai', 'backend', 3200000, 5000000, 14, '3-5', 'bachelor', 'responsible fortranslated textreview、translated textservice，translated text。', 'translated textbackenddevelopment、translated textcontentreviewprocess，translated text。', 'translated text,translated text,translated text', 'open', '2026-05-26T08:44:00Z'),
  ('jb-5rzry777wt2ax', 'comp_saic', 'translated textplatformseniorengineer', 'Shanghai', 'backend', 3800000, 5800000, 15, '5-10', 'bachelor', 'translated text、translated textplatform，translated textsecuritytranslated text。', 'familiar with Java/Go、MQTT、translated textidentitytranslated text，translated text IoT experience。', 'translated text,IoT,translated text', 'open', '2026-05-27T11:03:00Z'),
  ('jb-umw7tqz2hyamx', 'comp_saic', 'translated textservicetranslated textengineer', 'Shanghai', 'backend', 3100000, 4800000, 14, '3-5', 'bachelor', 'translated text、translated textfulfillmenttranslated textservicetranslated textsystem，translated textdata。', 'familiar withtranslated text、worktranslated text，translated text。', 'translated text,translated text,translated textdata', 'open', '2026-05-01T13:57:00Z'),
  ('jb-otf4r7qcdwjwx', 'comp_ximalaya', 'translated textbackendengineer', 'Shanghai', 'backend', 3400000, 5200000, 15, '3-5', 'bachelor', 'responsible fortranslated text、translated textservice，translated textseveranceprocess。', 'translated text Java、paymenttranslated text、translated text，translated textexperience。', 'translated text,translated text,payment', 'open', '2026-05-02T16:25:00Z'),
  ('jb-c4ryggp6afu2x', 'comp_ximalaya', 'contenttranslated textplatformengineer', 'Shanghai', 'backend', 3300000, 5100000, 14, '3-5', 'bachelor', 'translated textcontenttranslated text、reviewtranslated textservice，translated text。', 'familiar with Go/Java、searchtranslated text，translated textcontenttranslated textweektranslated text。', 'contenttranslated text,search,translated text', 'open', '2026-05-03T18:11:00Z'),
  ('jb-dqcbu35mly7ix', 'comp_zhongtong', 'translated textplatformengineer', 'Shanghai', 'backend', 3300000, 5100000, 14, '3-5', 'bachelor', 'translated text、translated textsigntranslated text，translated textquerytranslated text。', 'familiar withtranslated text、translated textdatatranslated text，translated textlogisticstranslated textexperience。', 'translated text,translated text,translated text', 'open', '2026-05-04T09:39:00Z'),
  ('jb-ovsjgs75lvbxx', 'comp_zhongtong', 'translated textbackendengineer', 'Shanghai', 'backend', 3500000, 5400000, 14, '3-5', 'bachelor', 'translated text、translated textsystem，translated textstabletranslated text。', 'translated text Java/Go、translated text，translated text。', 'translated text,translated text,translated text', 'open', '2026-05-05T10:53:00Z'),
  ('jb-e6urpxmzcry6x', 'comp_hellobike', 'translated textplatformengineer', 'Shanghai', 'backend', 3500000, 5400000, 15, '3-5', 'bachelor', 'translated text、translated text，translated text。', 'familiar with Go/Java、translated text、translated text，translated textexperiencetranslated textfirst。', 'translated text,translated text,IoT', 'open', '2026-05-06T12:42:00Z'),
  ('jb-qfwyg6cmyzlmx', 'comp_hellobike', 'local servicesfulfillmentengineer', 'Shanghai', 'backend', 3400000, 5200000, 14, '3-5', 'bachelor', 'translated text、translated textfulfillmentnoticeservice，translated textseverance。', 'translated textservice、datatranslated textsystemtranslated text，translated textdatareconcile。', 'local services,fulfillment,translated text', 'open', '2026-05-07T14:19:00Z'),
  ('jb-xyhjxazfnmxfx', 'comp_ubicloud', 'translated textengineer', 'Shanghai', 'backend', 3700000, 5700000, 15, '5-10', 'bachelor', 'responsible fortranslated textweektranslated text、translated text、translated text，translated text。', 'proficient in Go/Python，translated textcalculatetranslated text、translated text。', 'translated text,translated text,Go', 'open', '2026-05-08T15:36:00Z'),
  ('jb-vz2b6nhzfrl7x', 'comp_ubicloud', 'translated textplatformengineer', 'Shanghai', 'backend', 3300000, 5000000, 14, '3-5', 'bachelor', 'translated text、translated textservice，translated text。', 'familiar withdatatranslated text、translated text，translated text。', 'translated text,translated text,translated text', 'open', '2026-05-09T17:52:00Z'),
  ('jb-4ptyit57yydmx', 'comp_sensetime', 'translated textserviceplatformengineer', 'Shanghai', 'backend', 4200000, 6600000, 15, '5-10', 'master', 'translated text、translated text、translated textplatform，translated text。', 'familiar with Go/Python、Kubernetes、GPU worktranslated text API translated text。', 'translated textservice,Kubernetes,GPU', 'open', '2026-05-10T08:29:00Z'),
  ('jb-sohth6y3o4oux', 'comp_sensetime', 'dataplatformbackendengineer', 'Shanghai', 'backend', 3600000, 5600000, 15, '3-5', 'bachelor', 'developmentdatatranslated text、translated textservice，guaranteetranslated textdatatranslated text。', 'translated textbackenddevelopment、translated text、worktranslated text。', 'dataplatform,translated text,worktranslated text', 'open', '2026-05-11T11:34:00Z'),
  ('jb-dvahbslm373ax', 'comp_yitu', 'healthcaretranslated textplatformengineer', 'Shanghai', 'backend', 3900000, 6000000, 15, '5-10', 'master', 'responsible fortranslated text、translated text、translated textplatform，translated text。', 'familiar with Java/Go、DICOM translated text、datatranslated text。', 'healthcaretranslated text,translated text,translated text', 'open', '2026-05-12T13:08:00Z'),
  ('jb-2eotdx4rs2wax', 'comp_yitu', 'translated textcalculateplatformengineer', 'Shanghai', 'backend', 3500000, 5400000, 14, '3-5', 'bachelor', 'translated text、translated textservice，translated text。', 'familiar withtranslated text、translated text、GIS datatranslated text。', 'translated textcalculate,translated text,translated text', 'open', '2026-05-13T16:56:00Z'),
  ('jb-f3yqxdp33bklx', 'comp_honeycomb', 'translated textsystemengineer', 'Shanghai', 'backend', 3200000, 4900000, 14, '3-5', 'bachelor', 'translated text、translated textservice，translated textdata。', 'familiar with Java、translated textdatatranslated text、translated text，translated text。', 'MES,translated text,translated text', 'open', '2026-05-14T18:24:00Z'),
  ('jb-iym5pouxu5dpx', 'comp_honeycomb', 'translated textplatformengineer', 'Shanghai', 'backend', 3300000, 5100000, 14, '3-5', 'bachelor', 'translated text、translated textplatform，translated textdatatranslated text。', 'translated text、translated textdatatranslated text，translated textexperience。', 'translated text,translated text,data', 'open', '2026-05-15T09:06:00Z'),
  ('jb-ipagnlldxwsfx', 'comp_fosun', 'translated textdataplatformengineer', 'Shanghai', 'backend', 3300000, 5000000, 14, '5-10', 'bachelor', 'translated text、translated textdata，translated text、translated text。', 'familiar with Java、datatranslated text、worktranslated textdatatranslated text，translated text。', 'translated textdata,worktranslated text,translated text', 'open', '2026-05-16T10:32:00Z'),
  ('jb-xsl7vrni6i5ux', 'comp_fosun', 'translated textidentityplatformengineer', 'Shanghai', 'backend', 3500000, 5300000, 14, '3-5', 'bachelor', 'translated textweektranslated text、translated textservice，translated text。', 'translated text OAuth/OIDC、RBAC、translated textsecuritytranslated text，translated text IAM experience。', 'IAM,translated text,security', 'open', '2026-05-17T12:58:00Z'),
  ('jb-lilxomkx7ukgx', 'comp_springair', 'translated textsystemengineer', 'Shanghai', 'backend', 3500000, 5300000, 14, '5-10', 'bachelor', 'translated text、translated textplatform，translated textdaytranslated text。', 'familiar with Java、translated textsystemtranslated text，translated textconfirm。', 'translated text,translated textsystem,translated text', 'open', '2026-05-18T14:47:00Z'),
  ('jb-htlsq7s2v5p3x', 'comp_springair', 'translated textbackendengineer', 'Shanghai', 'backend', 3300000, 5000000, 14, '3-5', 'master', 'translated text、translated textrequirementstranslated textservice，translated text。', 'familiar with Python/Java、translated textservicetranslated textdatatranslated text，translated text。', 'translated text,translated text,data', 'open', '2026-05-19T15:18:00Z'),
  ('jb-kpp47k3jdrryx', 'comp_baosight', 'translated textinternetplatformengineer', 'Shanghai', 'backend', 3400000, 5200000, 14, '5-10', 'bachelor', 'translated text、translated text，translated text。', 'familiar with Java/Go、translated textdata、translated textplatformtranslated text。', 'translated textinternet,translated text,translated text', 'open', '2026-05-20T17:31:00Z'),
  ('jb-mct2yociyy6zx', 'comp_baosight', 'translated textdevelopmentengineer', 'Shanghai', 'backend', 3200000, 4900000, 14, '3-5', 'bachelor', 'translated text、translated text，translated text。', 'translated text Python/Go、Kubernetes、translated text。', 'DevOps,Kubernetes,translated text', 'open', '2026-05-21T08:58:00Z'),
  ('jb-mlrl6nol2ybgx', 'comp_mihoyo', 'translated textplatformengineer', 'Shanghai', 'backend', 4200000, 6500000, 16, '5-10', 'bachelor', 'responsible fortranslated text、translated textservice，translated textstable。', 'familiar with Go/Java、translated text、translated textsecuritytranslated text。', 'translated text,translated text,translated text', 'open', '2026-05-22T11:52:00Z'),
  ('jb-dwptove7ubffx', 'comp_lilith', 'translated textpaymentplatformengineer', 'Shanghai', 'backend', 3900000, 6100000, 15, '5-10', 'bachelor', 'translated textpaymenttranslated text、translated text，translated text。', 'translated textpaymentsystemexperience，familiar with Java/Go、translated text。', 'translated textpayment,translated text,translated text', 'open', '2026-05-23T13:36:00Z'),
  ('jb-ebxclewip6skx', 'comp_epicmed', 'healthcaredataplatformengineer', 'Shanghai', 'backend', 3700000, 5700000, 15, '5-10', 'master', 'translated textdatatranslated text、translated textauthorizationtranslated textplatform，retaintranslated textrecord。', 'familiar with Java/Go、datatranslated textprivacytranslated text，translated texthealthcaretranslated text。', 'healthcaredata,privacy,translated text', 'open', '2026-05-24T16:14:00Z');

INSERT INTO resumes (resume_id, user_id, name, headline, years_exp, education, skills, summary, updated_at) VALUES
  ('resume_sang_wu', 'usr_sang_wu', 'Sang Wu', 'seniorbackendengineer（8translated text / Java / Go / translated texttransaction）', 8, 'master', 'Java,Go,Spring Cloud,Kafka,Redis,MySQL,translated textservicetranslated text,translated text,translated textretrospective', 'translated textinternetbackendexperience，responsible fortranslated texttransactiontranslated textfulfillmentsystemtranslated text；translated textfirstShanghaidirect-hire、stableplatformtranslated text。', '2026-06-08T01:00:00Z');






INSERT INTO _counters (key, value) VALUES
  ('application_seq', 0),
  ('chat_seq', 0),
  ('message_seq', 0),
  ('alert_seq', 0);

COMMIT;
