-- High-rise handover email seed: all Stage 0 messages predate the 2026-06-15 09:00 kickoff.
BEGIN;
INSERT INTO account_config (id, email, name, created_at) VALUES (1, 'chu.nuo.hd@gmail.com', '褚诺', '2021-09-01T00:00:00Z');
INSERT INTO folders (id,name) VALUES (1,'INBOX'),(2,'Sent'),(3,'Drafts'),(4,'Trash'),(5,'Spam');
INSERT INTO messages (id, folder_id, message_id, subject, from_addr, to_addr_json, date, body_text, is_read, is_important, headers_json, size, created_at) VALUES (1,1,'<handover-index@builder.example>','交付资料目录与缺页说明','澄湾置业交付组 <handover@builder.example>','["chu.nuo.hd@gmail.com"]','2026-06-10T09:15:00Z','现提供交付通知、住宅质量保证书目录、使用说明书目录和户内设备清单。竣工资料索引第 7 页仍待归档，补齐前请勿把目录写成资料已完整移交。',1,1,'{"x-project":"tower-b"}',438,'2026-06-10T09:15:00Z');
INSERT INTO messages (id, folder_id, message_id, subject, from_addr, to_addr_json, date, body_text, is_read, is_important, headers_json, size, created_at) VALUES (2,1,'<inspection-roster@property.example>','6 月 17 日分户查验人员与进场要求','澄湾物业验收台 <acceptance@property.example>','["chu.nuo.hd@gmail.com"]','2026-06-11T03:20:00Z','查验安排为 10:00 入户，参与人包括业主、开发商工程师、物业和独立验房师。大型检测设备需提前登记；消防通道与电梯前室不得堆放材料。',1,1,'{"x-channel":"property"}',410,'2026-06-11T03:20:00Z');
INSERT INTO messages (id, folder_id, message_id, subject, from_addr, to_addr_json, date, body_text, is_read, is_important, headers_json, size, created_at) VALUES (3,1,'<public-rule-digest@service.example>','交付核验公开规则摘录（请结合合同原件）','住居事务资料服务 <digest@service.example>','["chu.nuo.hd@gmail.com"]','2026-06-12T02:00:00Z','公开规则核对摘要：商品房交付应符合法定和约定条件；房地产开发企业应承担保修责任。摘要只用于建立核验清单，具体权利义务仍以有效法规正文、合同和实际证据为准。',1,0,'{"source_id":"mohurd-commercial-housing-sales-measures"}',492,'2026-06-12T02:00:00Z');
INSERT INTO messages (id, folder_id, message_id, subject, from_addr, to_addr_json, date, body_text, is_read, is_important, headers_json, size, created_at) VALUES (4,1,'<inspection-quote@testlab.example>','验房设备校准与现场服务委托单','筑衡检测 <billing@testlab.example>','["chu.nuo.hd@gmail.com"]','2026-06-13T08:30:00Z','委托单包含激光测距仪和门窗水密观察设备的校准服务。卡片端可能先显示预授权，正式入账前应核对商户名、币种、委托编号和是否发生重复收费。',1,0,'{"engagement":"BH-260613"}',421,'2026-06-13T08:30:00Z');
INSERT INTO messages (id, folder_id, message_id, subject, from_addr, to_addr_json, date, body_text, is_read, is_important, headers_json, size, created_at) VALUES (5,1,'<lift-protection@property.example>','交付期电梯保护与材料运输窗口','澄湾物业工程部 <engineering@property.example>','["chu.nuo.hd@gmail.com"]','2026-06-14T06:40:00Z','电梯保护预计 6 月 25 日拆除。此后携带大型检测设备须重新预约货梯；外窗复验若与拆除时间冲突，应在日历中保留改期原因和参与人确认。',0,0,'{"x-channel":"property-engineering"}',386,'2026-06-14T06:40:00Z');
UPDATE folders SET message_count=(SELECT COUNT(*) FROM messages WHERE messages.folder_id=folders.id), unread_count=(SELECT COUNT(*) FROM messages WHERE messages.folder_id=folders.id AND messages.is_read=0);
INSERT INTO _counters (key,value) VALUES ('msg_seq',5);
COMMIT;
