PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
DELETE FROM "viewings";
DELETE FROM "saved_listings";
DELETE FROM "contacts";
DELETE FROM "listings";
DELETE FROM "search_subscriptions";
DELETE FROM "market_stats";
DELETE FROM "agents";
INSERT INTO "agents" ("agent_id","name","agency","phone","rating","deals_count","service_area") VALUES ('ag_njr_zhoumin','Zhou Min','Irental recordIrental record·Jiangbei New Arearental record','025-58864018',4.8,142,'Jiangbei New Area/Pukou');
INSERT INTO "agents" ("agent_id","name","agency","phone","rating","deals_count","service_area") VALUES ('ag_njr_sunlei','Sun Lei','rental record·rental recordMingfarental record','025-58815126',4.6,98,'Jiangbei New Area');
INSERT INTO "agents" ("agent_id","name","agency","phone","rating","deals_count","service_area") VALUES ('ag_njr_wuting','rental record','rental record·rental record','025-58876340',4.6,110,'Jiangbei New Area/rental record');
INSERT INTO "agents" ("agent_id","name","agency","phone","rating","deals_count","service_area") VALUES ('ag_njr_liqiang','Li Qiang','inrental record·rental record','025-58843961',4.5,76,'Jiangbei New Area');
INSERT INTO "agents" ("agent_id","name","agency","phone","rating","deals_count","service_area") VALUES ('ag_njr_zhenghao','Zheng Hao','rental record·rental record','025-58822775',4.6,64,'Jiangbei New Area/Pukou');
INSERT INTO "agents" ("agent_id","name","agency","phone","rating","deals_count","service_area") VALUES ('ag_njr_fengjie','rental record','Irental recordIrental record·daysrental record','025-58867758',4.6,88,'Jiangbei New Area');
INSERT INTO "agents" ("agent_id","name","agency","phone","rating","deals_count","service_area") VALUES ('ag_njr_xujun','rental record','rental record·rental recorddayrental record','025-58834806',4.7,70,'Jiangbei New Area');
INSERT INTO "agents" ("agent_id","name","agency","phone","rating","deals_count","service_area") VALUES ('ag_njr_hemin','rental record','rental record·Venice Water Cityrental record','025-58878297',4.6,120,'Jiangbei New Area');
INSERT INTO "agents" ("agent_id","name","agency","phone","rating","deals_count","service_area") VALUES ('ag_njr_luogang','rental recordjust','inrental record·rental record','025-58825828',4.6,58,'Jiangbei New Area/rental record');
INSERT INTO "agents" ("agent_id","name","agency","phone","rating","deals_count","service_area") VALUES ('ag_njr_gaoxiang','rental record','rental record·rental record','025-58839114',3.9,27,'Jiangbei New Area');
INSERT INTO "market_stats" ("stat_id","area","city","category","avg_price_minor","unit","sample_size","period") VALUES ('ms_08','Mingfa Riverside New City','Nanjing','rent',390000,'per_month',48,'2026-05');
INSERT INTO "market_stats" ("stat_id","area","city","category","avg_price_minor","unit","sample_size","period") VALUES ('ms_09','Riverside Homes','Nanjing','rent',440000,'per_month',49,'2026-05');
INSERT INTO "market_stats" ("stat_id","area","city","category","avg_price_minor","unit","sample_size","period") VALUES ('ms_02','Qiaobei Waterfront','Nanjing','rent',405000,'per_month',42,'2026-05');
INSERT INTO "market_stats" ("stat_id","area","city","category","avg_price_minor","unit","sample_size","period") VALUES ('ms_07','Hongyang Plaza Apartments','Nanjing','rent',410000,'per_month',47,'2026-05');
INSERT INTO "market_stats" ("stat_id","area","city","category","avg_price_minor","unit","sample_size","period") VALUES ('ms_10','Pujiang Yayan','Nanjing','rent',400000,'per_month',50,'2026-05');
INSERT INTO "market_stats" ("stat_id","area","city","category","avg_price_minor","unit","sample_size","period") VALUES ('ms_06','Tianrun City Block 10','Nanjing','rent',405000,'per_month',46,'2026-05');
INSERT INTO "market_stats" ("stat_id","area","city","category","avg_price_minor","unit","sample_size","period") VALUES ('ms_11','Xuri Shangcheng','Nanjing','rent',300000,'per_month',51,'2026-05');
INSERT INTO "market_stats" ("stat_id","area","city","category","avg_price_minor","unit","sample_size","period") VALUES ('ms_12','Venice Water City','Nanjing','rent',398000,'per_month',52,'2026-05');
INSERT INTO "market_stats" ("stat_id","area","city","category","avg_price_minor","unit","sample_size","period") VALUES ('ms_04','Qiaolin New Estate','Nanjing','rent',395000,'per_month',44,'2026-05');
INSERT INTO "listings" ("listing_id","category","title","city","district","community","price_minor","area_sqm","rooms","metro","attrs_json","description","photos_json","agent_id","owner_user_id","status","listed_at") VALUES ('lst_njr_0500','rent','Mingfa Riverside New City 2 room1 living room 78sqm entire-unit rental','Nanjing','Jiangbei New Area','Mingfa Riverside New City',388000,78.0,2,'S8 Line·rental recordnewrental record Station 420m','{"layout": "2 room1 living room", "area": 78.0, "orientation": "southeast", "floor": "8/18", "finish": "2023yearrenovated", "elevator": "tworental record", "property owner name": "Gu Jianguo", "property certificate number": "rental record(2020)rental recordnotrental recordNo.235633number", "agency fee": 388000, "agency fee note": "agency fee=1rental recordmonthly rentrental record", "before viewingdeposit": 0, "rental recordpayrental record": "one-month deposit, three-month rent", "payee name": "Gu Jianguo", "amenities": "southeastrental recordtwo-bedroom，videocanrental recordutility metersanddoor lock；workdaymorning peaktransferabout25minutestoSoftware Avenue。"}','southeastrental recordtwo-bedroom，videocanrental recordutility metersanddoor lock；workdaymorning peaktransferabout25minutestoSoftware Avenue。','["rental recordliving room", "rental record", "kitchenrental record"]','ag_njr_zhoumin',NULL,'active','2026-06-24T09:15:00Z');
INSERT INTO "listings" ("listing_id","category","title","city","district","community","price_minor","area_sqm","rooms","metro","attrs_json","description","photos_json","agent_id","owner_user_id","status","listed_at") VALUES ('lst_njr_0511','rent','Riverside Homes 2 room1 living room 86sqm entire-unit rental','Nanjing','Jiangbei New Area','Riverside Homes',455000,86.0,2,'S8 Line·rental recordnewrental record Station 760m','{"layout": "2 room1 living room", "area": 86.0, "orientation": "southwest", "floor": "16/26", "finish": "2019yeardelivery", "elevator": "three", "property owner name": "rental record", "property certificate number": "rental record(2020)rental recordnotrental recordNo.700819number", "agency fee": 455000, "agency fee note": "agency fee=1rental recordmonthly rentrental record", "before viewingdeposit": 0, "rental recordpayrental record": "one-month deposit, three-month rent", "payee name": "rental record", "amenities": "rental recordfloorcanrental record，rental record；monthly rentrental recordcurrentlimit。"}','rental recordfloorcanrental record，rental record；monthly rentrental recordcurrentlimit。','["rental recordliving room", "timerental record", "elevator living room"]','ag_njr_sunlei',NULL,'active','2026-06-23T11:20:00Z');
INSERT INTO "listings" ("listing_id","category","title","city","district","community","price_minor","area_sqm","rooms","metro","attrs_json","description","photos_json","agent_id","owner_user_id","status","listed_at") VALUES ('lst_njr_0512','rent','Qiaobei Waterfront 2 room1 living room 80sqm entire-unit rental','Nanjing','Jiangbei New Area','Qiaobei Waterfront',405000,80.0,2,'S8 Line·rental record Station 530m','{"layout": "2 room1 living room", "area": 80.0, "orientation": "north-south", "floor": "5/11", "finish": "rental record", "elevator": "one", "property owner name": "rental record", "property certificate number": "rental record(2020)rental recordnotrental recordNo.320965number", "agency fee": 405000, "agency fee note": "agency fee=1rental recordmonthly rentrental record", "before viewingdeposit": 0, "rental recordpayrental record": "one-month deposit, three-month rent", "payee name": "rental record", "amenities": "north-southcommunicaterental record，rental recordunderrental recordpersonrental record，steprental recordto Stationaboutrental recordminutes。"}','north-southcommunicaterental record，rental recordunderrental recordpersonrental record，steprental recordto Stationaboutrental recordminutes。','["living roomdaylight", "bedroomrental record", "communityrental record"]','ag_njr_wuting',NULL,'active','2026-06-25T08:40:00Z');
INSERT INTO "listings" ("listing_id","category","title","city","district","community","price_minor","area_sqm","rooms","metro","attrs_json","description","photos_json","agent_id","owner_user_id","status","listed_at") VALUES ('lst_njr_0513','rent','Hongyang Plaza Apartments 2 room1 living room 82sqm entire-unit rental','Nanjing','Jiangbei New Area','Hongyang Plaza Apartments',408000,82.0,2,'S8 Line·rental recordnewrental record Station 680m','{"layout": "2 room1 living room", "area": 82.0, "orientation": "rental record", "floor": "12/22", "finish": "rental recordfinish", "elevator": "four", "property owner name": "rental record", "property certificate number": "rental record(2020)rental recordnotrental recordNo.626081number", "agency fee": 408000, "agency fee note": "agency fee=1rental recordmonthly rentrental record", "before viewingdeposit": 0, "rental recordpayrental record": "rental recordpayrental record", "payee name": "rental record", "amenities": "rental record，rental recordbetweenrental recordandweekrental record，rental recordcontract。"}','rental record，rental recordbetweenrental recordandweekrental record，rental recordcontract。','["rental recordliving room", "kitchenrental record", "rental recordoutsiderental record"]','ag_njr_liqiang',NULL,'active','2026-06-22T14:10:00Z');
INSERT INTO "listings" ("listing_id","category","title","city","district","community","price_minor","area_sqm","rooms","metro","attrs_json","description","photos_json","agent_id","owner_user_id","status","listed_at") VALUES ('lst_njr_0514','rent','Pujiang Yayan 2 room1 living room 80sqm entire-unit rental','Nanjing','Jiangbei New Area','Pujiang Yayan',400000,80.0,2,'Metro10 Line·Nanjingrental record Station 940m','{"layout": "2 room1 living room", "area": 80.0, "orientation": "north-south", "floor": "3/18", "finish": "2021yearrenovated", "elevator": "two", "property owner name": "Zheng Guohua", "property certificate number": "rental record(2020)rental recordnotrental recordNo.293924number", "agency fee": 800000, "agency fee note": "agency fee=2rental recordmonthly rentrental record", "before viewingdeposit": 100000, "rental recordpayrental record": "one-month deposit, three-month rent", "payee name": "Zheng Guohua", "amenities": "two-bedroomrental recordmessagerental recordbalcony；rental recordrequestbefore viewingrental recordpayrental record，contractservice feerental recordmonthly rentrental record。"}','two-bedroomrental recordmessagerental recordbalcony；rental recordrequestbefore viewingrental recordpayrental record，contractservice feerental recordmonthly rentrental record。','["living roomrental record", "bedroomrental record", "kitchenrental record"]','ag_njr_zhenghao',NULL,'active','2026-06-28T09:00:00Z');
INSERT INTO "listings" ("listing_id","category","title","city","district","community","price_minor","area_sqm","rooms","metro","attrs_json","description","photos_json","agent_id","owner_user_id","status","listed_at") VALUES ('lst_njr_0515','rent','Tianrun City Block 10 2 room1 living room 81sqm entire-unit rental','Nanjing','Jiangbei New Area','Tianrun City Block 10',402000,81.0,2,'S8 Line·daysrental record Station 350m','{"layout": "2 room1 living room", "area": 81.0, "orientation": "rental record", "floor": "21/33", "finish": "rental recordrenovated", "elevator": "three", "property owner name": "rental record", "property certificate number": "rental record(2020)rental recordnotrental recordNo.426564number", "agency fee": 402000, "agency fee note": "agency fee=1rental recordmonthly rentrental record", "before viewingdeposit": 50000, "rental recordpayrental record": "one-month deposit, one-month rent", "payee name": "rental record", "amenities": "rental recordcommunityhigh floor，rental record；viewingrental recordanddepositrequestneedrental recordverify。"}','rental recordcommunityhigh floor，rental record；viewingrental recordanddepositrequestneedrental recordverify。','["rental record living room", "rental recordbetween", "Metrosteprental record"]','ag_njr_fengjie',NULL,'active','2026-06-26T10:05:00Z');
INSERT INTO "listings" ("listing_id","category","title","city","district","community","price_minor","area_sqm","rooms","metro","attrs_json","description","photos_json","agent_id","owner_user_id","status","listed_at") VALUES ('lst_njr_0516','rent','Xuri Shangcheng 2 room1 living room 79sqm entire-unit rental','Nanjing','Jiangbei New Area','Xuri Shangcheng',418000,79.0,2,'S8 Line·rental recordnewrental record Station 610m','{"layout": "2 room1 living room", "area": 79.0, "orientation": "north-south", "floor": "10/24", "finish": "furnishedrental recordgood", "elevator": "rental record", "property owner name": "rental record", "property certificate number": "rental record(2020)rental recordnotrental recordNo.360455number", "agency fee": 418000, "agency fee note": "agency fee=1rental recordmonthly rentrental record", "before viewingdeposit": 0, "rental recordpayrental record": "one-month deposit, three-month rent", "payee name": "rental record", "amenities": "unitrental recordmaintainrental recordgood，rental record，rental recordlatestrental recordbudgetonrental record。"}','unitrental recordmaintainrental recordgood，rental record，rental recordlatestrental recordbudgetonrental record。','["rental recordbalcony", "rental record", "communityrental record"]','ag_njr_xujun',NULL,'active','2026-06-21T16:30:00Z');
INSERT INTO "listings" ("listing_id","category","title","city","district","community","price_minor","area_sqm","rooms","metro","attrs_json","description","photos_json","agent_id","owner_user_id","status","listed_at") VALUES ('lst_njr_0518','rent','Venice Water City 2 room1 living room 83sqm entire-unit rental','Nanjing','Jiangbei New Area','Venice Water City',396000,83.0,2,'S8 Line·rental record Station 890m','{"layout": "2 room1 living room", "area": 83.0, "orientation": "southeast", "floor": "24/32", "finish": "2018yearfurnished", "elevator": "three", "property owner name": "rental record", "property certificate number": "rental record(2020)rental recordnotrental recordNo.265585number", "agency fee": 396000, "agency fee note": "agency fee=1rental recordmonthly rentrental record", "before viewingdeposit": 0, "rental recordpayrental record": "rental recordpayrental record", "payee name": "Li Wei", "amenities": "rental recordcommunityhigh floor，rental recordamenitiesrental record；contractrental recordproperty ownerandcollectionaccountnamedifferent。"}','rental recordcommunityhigh floor，rental recordamenitiesrental record；contractrental recordproperty ownerandcollectionaccountnamedifferent。','["living room", "timerental record", "communityrental record"]','ag_njr_hemin',NULL,'active','2026-06-25T13:25:00Z');
INSERT INTO "listings" ("listing_id","category","title","city","district","community","price_minor","area_sqm","rooms","metro","attrs_json","description","photos_json","agent_id","owner_user_id","status","listed_at") VALUES ('lst_njr_0519','rent','Qiaolin New Estate 2 room1 living room 77sqm entire-unit rental','Nanjing','Jiangbei New Area','Qiaolin New Estate',393000,77.0,2,'Metro10 Line·rental record Station 1250m','{"layout": "2 room1 living room", "area": 77.0, "orientation": "rental record", "floor": "4/6", "finish": "standard finish", "elevator": "none", "property owner name": "Liu Jianhua (刘建华)", "property certificate number": "rental record(2020)rental recordnotrental recordNo.182253number", "agency fee": 393000, "agency fee note": "agency fee=1rental recordmonthly rentrental record", "before viewingdeposit": 0, "rental recordpayrental record": "one-month deposit, one-month rent", "payee name": "Liu Jianhua (刘建桦)", "amenities": "rental record、rental record，steprental recordtoMetrorental record；property ownerandpayee namerental recordatrental recorddifferentrental record。"}','rental record、rental record，steprental recordtoMetrorental record；property ownerandpayee namerental recordatrental recorddifferentrental record。','["living roomrental record", "kitchen", "rental record"]','ag_njr_luogang',NULL,'active','2026-06-20T15:45:00Z');
COMMIT;
UPDATE listings SET listed_at = '2026-06-27T23:00:00Z'
WHERE listed_at > '2026-06-28T01:00:00Z';
PRAGMA foreign_keys=ON;

BEGIN TRANSACTION;
INSERT INTO agents(agent_id,name,agency,phone,rating,deals_count,service_area) VALUES
('ag_njr_tangyu','rental record','rental record·rental record','025-8312-2041',4.4,81,'rental record/rental record'),
('ag_njr_qianwei','rental record','Pukouunitrental record','025-8312-2076',4.1,49,'Pukourental record'),
('ag_njr_songlan','rental record','rental record·rental recordnewrental record','025-8312-2118',4.7,133,'rental record/rental record'),
('ag_njr_huangbo','rental record','rental record·rental record','025-8312-2159',4.3,92,'rental record'),
('ag_njr_yujie','rental record','Irental recordIrental record·rental record','025-8312-2194',4.6,118,'rental record/rental record'),
('ag_njr_caixia','rental record','rental record','025-8312-2235',3.8,35,'rental record/rental recordnew'),
('ag_njr_mengfan','rental record','rental record·rental record','025-8312-2271',4.5,104,'rental record/rental record'),
('ag_njr_dingrui','rental record','Nanjingrental recordrentrental record','025-8312-2308',4.2,57,'Jiangbei New Area');
INSERT INTO market_stats(stat_id,area,city,category,avg_price_minor,unit,sample_size,period) VALUES
('ms_dingshan_apr','Top-of-the-Hill Street Xinyuan','Nanjing','rent',372000,'per_month',37,'2026-04'),
('ms_dingshan_may','Top-of-the-Hill Street Xinyuan','Nanjing','rent',381000,'per_month',41,'2026-05'),
('ms_taishan_apr','rental recordnewrental record','Nanjing','rent',346000,'per_month',56,'2026-04'),
('ms_taishan_may','rental recordnewrental record','Nanjing','rent',352000,'per_month',61,'2026-05'),
('ms_liuzhou_apr','rental record','Nanjing','rent',425000,'per_month',43,'2026-04'),
('ms_liuzhou_may','rental record','Nanjing','rent',432000,'per_month',48,'2026-05'),
('ms_getang_apr','rental record','Nanjing','rent',318000,'per_month',32,'2026-04'),
('ms_getang_may','rental record','Nanjing','rent',326000,'per_month',36,'2026-05'),
('ms_yanchuang_apr','rental record','Nanjing','rent',458000,'per_month',29,'2026-04'),
('ms_yanchuang_may','rental record','Nanjing','rent',465000,'per_month',34,'2026-05'),
('ms_longhua_apr','rental record','Nanjing','rent',398000,'per_month',45,'2026-04'),
('ms_longhua_may','rental record','Nanjing','rent',404000,'per_month',50,'2026-05');
INSERT INTO listings(listing_id,category,title,city,district,community,price_minor,area_sqm,rooms,metro,attrs_json,description,photos_json,agent_id,owner_user_id,status,listed_at) VALUES
('lst_njr_riverstone_one','rent','rental recordone-bedroomrental recordbalcony','Nanjing','Jiangbei New Area','rental record',298000,48.0,1,'S8 Line·rental recordnewrental record Station 760m','{"property owner name":"rental recordwillrental record","payee name":"rental recordwillrental record","rental recordpayrental record":"one-month deposit, one-month rent","elevator":"have","canmove-indate":"2026-06-30"}','one-bedroomarearental record，balconyrental record。','["rental recordbalcony","rental recordkitchen"]','ag_njr_songlan',NULL,'active','2026-05-18T09:25:00Z'),
('lst_njr_dingshan_three','rent','Top-of-the-Hill Street Xinyuanrental recordthree-bedroom','Nanjing','Jiangbei New Area','Top-of-the-Hill Street Xinyuan',420000,86.0,3,'Metro10 Line·Nanjingrental record Station 1320m','{"property owner name":"rental record","payee name":"rental record","rental recordpayrental record":"one-month deposit, three-month rent","elevator":"have","canmove-indate":"2026-07-05"}','rental recordbetweenbedroomrental recordhaverental record，living roomdaylightrental record。','["rental recordbetweenbedroom","rental record"]','ag_njr_tangyu',NULL,'active','2026-05-20T14:10:00Z'),
('lst_njr_jingxin_two','rent','rental recordnewrental recordnorth-southtwo-bedroom','Nanjing','Jiangbei New Area','rental recordnewrental record',365000,72.0,2,'S8 Line·informationrental record Station 980m','{"property owner name":"rental record","payee name":"rental record","rental recordpayrental record":"one-month deposit, three-month rent","elevator":"none","floor":"5/6"}','steprental record，rental recordunderhaverental recordbetweenrental record。','["living room","steprental record","rental record"]','ag_njr_yujie',NULL,'active','2026-05-22T08:55:00Z'),
('lst_njr_yulan_studio','rent','rental recordbetween','Nanjing','Jiangbei New Area','rental record',255000,42.0,1,'Metro10 Line·rental record Station 410m','{"property owner name":"rental record","payee name":"rental record","rental recordpayrental record":"one-month deposit, one-month rent","elevator":"have","rental record":"liverental record"}','rental recordbetweennonerental recordunit，rental record。','["rental recordbetweenrental record","utility meters"]','ag_njr_mengfan',NULL,'active','2026-05-25T17:30:00Z'),
('lst_njr_ginkgo_three','rent','rental recordthree-bedroomshared rentalrental recordentire-unit rental','Nanjing','Jiangbei New Area','rental record',390000,92.0,3,'S8 Line·rental record Station 650m','{"property owner name":"rental record","payee name":"rental record","rental recordpayrental record":"one-month deposit, three-month rent","elevator":"have","rental recordlease":"2026-06-25torental record"}','rental recordshared rentalrental recordreserve，rental recordunitbetweenrental record。','["rental recordbedroom","rental recordbedroom","rental recordliving room"]','ag_njr_yujie',NULL,'active','2026-05-27T10:18:00Z'),
('lst_njr_lanting_two','rent','rental recordtwo-bedroomlow floor','Nanjing','Jiangbei New Area','rental record',348000,68.0,2,'S8 Line·rental record Station 1180m','{"property owner name":"rental record","payee name":"rental record","rental recordpayrental record":"one-month deposit, three-month rent","elevator":"have","floor":"2/18"}','rental recordcommunityrental record，rental recordbetweenhavepersonrental record。','["timerental record","rental record","elevator living room"]','ag_njr_yujie',NULL,'active','2026-05-29T12:40:00Z'),
('lst_njr_smart_one','rent','rental recordpersonrental recordone-bedroom','Nanjing','Jiangbei New Area','rental recordpersonrental record',330000,50.0,1,'Metro10 Line·rental record Station 880m','{"property owner name":"rental recordrentrental recordcompany","payee name":"Nanjingrental recordliveunitrental recordhaverental recordcompany","rental recordpayrental record":"one-month deposit, one-month rent","elevator":"have","rentrental recordunderrental record":"12rental recordmonth"}','rental recordlisting，rentrental recordunderrental recordyear。','["rental record living room","bedroom","rental record"]','ag_njr_caixia',NULL,'active','2026-06-01T09:45:00Z'),
('lst_njr_yangtze_three','rent','rental recordhourrental recordthree-bedroom','Nanjing','Jiangbei New Area','rental recordhourrental record',510000,108.0,3,'Metro10 Line·Pukouten-thousandrental record Station 520m','{"property owner name":"rental recordnew","payee name":"rental recordnew","rental recordpayrental record":"one-month deposit, three-month rent","elevator":"have","rental record_minor":28000}','arearental record，monthly rentrental recordcurrentbudget。','["rental record living room","rental record","communityinrental record"]','ag_njr_mengfan',NULL,'active','2026-06-03T15:05:00Z'),
('lst_njr_hongyang_two','rent','rental recorddayrental recordonrental recordtwo-bedroom','Nanjing','Jiangbei New Area','rental recorddayrental recordonrental record',399000,76.0,2,'S8 Line·rental record Station 690m','{"property owner name":"rental record","payee name":"rental record","rental recordpayrental record":"one-month deposit, three-month rent","elevator":"have","before viewingdeposit":0}','rental record，kitchenuserental record。','["kitchenrental record","rental record"]','ag_njr_huangbo',NULL,'active','2026-06-05T11:22:00Z'),
('lst_njr_bridge_one','rent','rental recordyearrental recordone-bedroom','Nanjing','Jiangbei New Area','rental recordyearrental record',268000,45.0,1,'S8 Line·rental recordnewrental record Station 340m','{"property owner name":"Nanjingrental recordhaverental recordcompany","payee name":"Nanjingrental recordhaverental recordcompany","rental recordpayrental record":"one-month deposit, one-month rent","elevator":"have","rental record":true}','commutefacilitate，rental record。','["rental record living room","bedroom","rental record"]','ag_njr_qianwei',NULL,'active','2026-06-08T08:35:00Z'),
('lst_njr_jinling_three','rent','rental recordnewrental recordthree-bedroom','Nanjing','Jiangbei New Area','rental recordnewrental record',360000,94.0,3,'S8 Line·rental recordnewrental recordsendrental record Station 1450m','{"property owner name":"rental record","payee name":"rental record","rental recordpayrental record":"one-month deposit, three-month rent","elevator":"none","floor":"4/6"}','three-bedroomrental record，rental recordbetweennonerental recordcentsrental record。','["rental recordbetween","living room","rental record"]','ag_njr_caixia',NULL,'delisted','2026-05-11T16:42:00Z'),
('lst_njr_longhua_two','rent','rental recordMetrorental recordtwo-bedroom','Nanjing','Jiangbei New Area','rental recordcommunity',438000,74.0,2,'Metro10 Line·rental record Station 180m','{"property owner name":"rental record","payee name":"rental record","rental recordpayrental record":"one-month deposit, three-month rent","elevator":"have","rental record":true}','Metrorental record，rental recordoutsideisrental record。','["rental record","Metrorental record"]','ag_njr_mengfan',NULL,'active','2026-06-10T13:58:00Z'),
('lst_njr_getang_one','rent','rental recordnewrental recordone-bedroom','Nanjing','Jiangbei New Area','rental recordnewrental record',245000,46.0,1,'S8 Line·rental record Station 920m','{"property owner name":"rental record","payee name":"rental record","rental recordpayrental record":"one-month deposit, one-month rent","elevator":"have","canmove-indate":"2026-06-28"}','pricerental record，rental recordSoftware Avenuetransferrental record。','["living room"," Stationrental recordsteprental record"]','ag_njr_yujie',NULL,'active','2026-06-12T10:06:00Z'),
('lst_njr_riverside_three','rent','rental recordandrental recordthree-bedroominrental record','Nanjing','Jiangbei New Area','rental recordandrental record',475000,101.0,3,'Metro10 Line·rental record Station 1100m','{"property owner name":"rental record","payee name":"rental record","rental recordpayrental record":"one-month deposit, three-month rent","elevator":"have","rental record_minor":22000}','inrental recordthree-bedroom，contractrental recordpay。','["living room","rental recordbetweenbedroom","rental record"]','ag_njr_tangyu',NULL,'active','2026-06-15T09:17:00Z'),
('lst_njr_taishan_two','rent','rental recordnewrental recordrenovatedtwo-bedroom','Nanjing','Jiangbei New Area','rental recordnewrental record',382000,70.0,2,'S8 Line·rental recordnewrental record Station 540m','{"property owner name":"rental record","payee name":"rental record","rental recordpayrental record":"one-month deposit, three-month rent","elevator":"none","finishtime":"2026-05"}','rental recordmonthrenovated，rental record。','["newrental record","rental record","kitchen"]','ag_njr_songlan',NULL,'delisted','2026-06-17T18:25:00Z');
INSERT INTO saved_listings(user_id,listing_id,saved_at) VALUES
('u_lp_N7m4Qx8K','lst_njr_riverstone_one','2026-05-18T12:20:00Z'),
('u_lp_N7m4Qx8K','lst_njr_jingxin_two','2026-05-23T07:45:00Z'),
('u_lp_N7m4Qx8K','lst_njr_yulan_studio','2026-05-26T09:08:00Z'),
('u_lp_N7m4Qx8K','lst_njr_jinling_three','2026-05-12T18:30:00Z'),
('u_lp_N7m4Qx8K','lst_njr_taishan_two','2026-06-18T08:15:00Z');
COMMIT;

BEGIN TRANSACTION;
INSERT INTO agents(agent_id,name,agency,phone,rating,deals_count,service_area) VALUES
('ag_njr_gaoxin','weekrental record','rental record','025-58874126',4.6,132,'rental recordnewrental recordsendrental record/rental record'),
('ag_njr_qiaolin','rental record','Pukourental record','025-58130984',4.3,76,'rental record/rental record'),
('ag_njr_taishan','rental record','rental record','025-58460217',4.5,164,'rental recordnewrental record/rental record');
INSERT INTO listings(listing_id,category,title,city,district,community,price_minor,area_sqm,rooms,metro,attrs_json,description,photos_json,agent_id,owner_user_id,status,listed_at) VALUES
('lst_njr_yanchuang_one','rent','rental recordpersonrental recordone-bedroom','Nanjing','Jiangbei New Area','rental recordpersonrental record',335000,52.0,1,'Metro10 Line·rental record Station 1150m','{"property owner name":"Nanjingrental recordassetrental recordhaverental recordcompany","payee name":"Nanjingrental recordassetrental recordhaverental recordcompany","rental recordpayrental record":"one-month deposit, three-month rent","elevator":"have","rental recordrentrental record":"12rental recordmonth"}','rental recordworkdayrental record，contractnotacceptrental recordmonthrental recordrent。','["rental record Station","one-bedroomliving room","rental record living room"]','ag_njr_gaoxin',NULL,'active','2026-05-29T08:42:00Z'),
('lst_njr_qiaolin_two','rent','rental recordnewrental recordtwo-bedroom','Nanjing','Pukou District','rental record',278000,74.0,2,'MetroS3 Line·rental record Station 890m','{"property owner name":"rental record","payee name":"rental record","rental recordpayrental record":"one-month deposit, one-month rent","elevator":"have","rental record":"notrental record"}','rental recordhaverental recordandrental record，kitchennotrental record。','["rental recordliving room","kitchenrental record","Metrorental record"]','ag_njr_qiaolin',NULL,'delisted','2026-05-16T13:27:00Z'),
('lst_njr_taishan_old_two','rent','rental recordnewrental recordcommunitytwo-bedroom','Nanjing','Jiangbei New Area','rental recordnewrental record',318000,66.0,2,'MetroS8 Line·rental recordnewrental record Station 520m','{"property owner name":"rental record","payee name":"rental record","rental recordpayrental record":"one-month deposit, three-month rent","elevator":"none","floor":"3/6","rental record":"rental record"}','rental recordsteprental record，rental recordbedroomrental recordcommunityrental record，rental recordafterrental record。','["steprental record","rental recordbedroom","rental record"]','ag_njr_taishan',NULL,'active','2026-06-04T10:18:00Z'),
('lst_njr_longhua_loft','rent','rental recordliverental record','Nanjing','Pukou District','rental record',305000,45.0,1,'Metro10 Line·rental record Station 260m','{"property owner name":"Nanjingrental recordhaverental recordcompany","payee name":"Nanjingrental recordhaverental recordcompany","rental recordpayrental record":"one-month deposit, three-month rent","rental record":"office","rental record":"rental record"}','unitthisrental recordoffice，rental record，rental recordnotrental record。','["rental recordliving room","rental record","rental record"]','ag_njr_gaoxin',NULL,'active','2026-06-15T17:06:00Z');
INSERT INTO market_stats(stat_id,area,city,category,avg_price_minor,unit,sample_size,period) VALUES
('ms_yanchuang_talent_may','rental recordpersonrental record','Nanjing','rent',342000,'per_month',38,'2026-05'),
('ms_qiaolin_may','rental recordnewrental recordtwo-bedroom','Nanjing','rent',286000,'per_month',31,'2026-05'),
('ms_taishan_old_apr','rental recordnewrental recordno elevatortwo-bedroom','Nanjing','rent',326000,'per_month',44,'2026-04');
COMMIT;
UPDATE listings SET listed_at = '2026-06-27T23:00:00Z'
WHERE listed_at > '2026-06-28T01:00:00Z';
