-- HAND-REVIEWED MATERIALIZED ENVIRONMENT (2026-08-02)
-- Each loaded business row is retained; template values were replaced one-for-one.
PRAGMA foreign_keys = OFF;
BEGIN TRANSACTION;
-- _counters: 2 rows
INSERT INTO "_counters" ("key", "value") VALUES ('msg_seq', 9000);
INSERT INTO "_counters" ("key", "value") VALUES ('draft_seq', 9000);
-- account_config: 1 rows
INSERT INTO "account_config" ("id", "email", "name", "created_at") VALUES (1, 'maya.chen@example.com', 'Maya Chen', '2024-01-08T09:15:00-05:00');
-- folders: 5 rows
INSERT INTO "folders" ("id", "name", "delimiter", "flags_json", "message_count", "unread_count") VALUES (1, 'INBOX', '/', '["\\Inbox"]', 17, 5);
INSERT INTO "folders" ("id", "name", "delimiter", "flags_json", "message_count", "unread_count") VALUES (2, 'Sent', '/', '["\\Sent"]', 0, 0);
INSERT INTO "folders" ("id", "name", "delimiter", "flags_json", "message_count", "unread_count") VALUES (3, 'Drafts', '/', '["\\Drafts"]', 0, 0);
INSERT INTO "folders" ("id", "name", "delimiter", "flags_json", "message_count", "unread_count") VALUES (4, 'Trash', '/', '["\\Trash"]', 0, 0);
INSERT INTO "folders" ("id", "name", "delimiter", "flags_json", "message_count", "unread_count") VALUES (5, 'Spam', '/', '["\\Junk"]', 0, 0);
-- messages: 17 rows
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (210, 1, '<boston-wedding-thanks-20260518@nora.example>', 'Thank you for coming to our Boston wedding', 'nora@example.com', '["maya.chen@example.com"]', '[]', '[]', '2026-05-18T14:22:00-04:00', 'Thank you for joining us in Cambridge. The photo gallery will remain available through June, and this thread belongs to the completed Boston weekend rather than the Italy trip.', NULL, 1, 0, 0, NULL, NULL, '{"category":"historical_wedding"}', 5210, 163, '2026-05-18T14:22:00-04:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (237, 1, '<card-statement-20260731@bank.example>', 'July travel-card statement ready', 'statements@bank.example', '["maya.chen@example.com"]', '[]', '[]', '2026-08-01T07:18:00-04:00', 'Your July statement is ready in the secure portal. Review merchant names and pending holds there because this email does not contain a full card number.', NULL, 1, 1, 0, NULL, NULL, '{"category":"banking"}', 5237, 139, '2026-08-01T07:18:00-04:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (264, 1, '<travel-insurance-intake-20260804@broker.example>', 'Information needed for travel coverage comparison', 'service@insurance-broker.example', '["maya.chen@example.com"]', '[]', '[]', '2026-08-04T10:36:00-04:00', 'Please provide destination countries, approximate dates, trip cost range, and existing card benefits. We will compare written cancellation, delay, medical, and baggage terms.', NULL, 1, 0, 1, NULL, NULL, '{"category":"insurance"}', 5264, 165, '2026-08-04T10:36:00-04:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (291, 1, '<suitcase-repair-20260815@repair.example>', 'Suitcase repair completion estimate', 'service@luggage-repair.example', '["maya.chen@example.com"]', '[]', '[]', '2026-08-15T11:41:00-04:00', 'The replacement wheel is installed. Pickup is available Monday after 16:00, and the telescoping handle should be inspected before leaving the shop.', NULL, 0, 0, 0, NULL, NULL, '{"category":"personal"}', 5291, 134, '2026-08-15T11:41:00-04:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (318, 1, '<client-handoff-20260817@studio.example>', 'Coverage for September client work', 'amelia@studio.example', '["maya.chen@example.com"]', '[]', '[]', '2026-08-17T09:28:00-04:00', 'I can cover the Northstar review while you are away. Please leave the current decision, owner, due date, and escalation path in the project workspace.', NULL, 1, 0, 1, NULL, NULL, '{"category":"work"}', 5318, 146, '2026-08-17T09:28:00-04:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (346, 1, '<pet-sitter-followup-20260813@care.example>', 'Pet care follow-up questions', 'jordan@petcare.example', '["maya.chen@example.com"]', '[]', '[]', '2026-08-13T08:52:00-04:00', 'Please confirm feeding times, the veterinary practice, and an emergency contact. Send building access instructions through the secure app rather than email.', NULL, 1, 0, 0, NULL, NULL, '{"category":"home"}', 5346, 140, '2026-08-13T08:52:00-04:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (373, 1, '<allergy-translation-20260822@language.example>', 'Italian allergy-card wording', 'translator@language.example', '["maya.chen@example.com"]', '[]', '[]', '2026-08-22T14:17:00-04:00', 'The draft explains a severe pine-nut allergy and asks about shared utensils and preparation surfaces. A restaurant still needs to confirm its own controls.', NULL, 0, 1, 1, NULL, NULL, '{"category":"allergy"}', 5373, 147, '2026-08-22T14:17:00-04:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (401, 1, '<airline-general-watch-20260820@fare.example>', 'General Europe fare watch', 'alerts@fare-watch.example', '["maya.chen@example.com"]', '[]', '[]', '2026-08-20T06:45:00-04:00', 'Several transatlantic fares changed this week. This alert is a market summary rather than a live quote for a specific itinerary, so retrieve current fare rules before acting.', NULL, 1, 0, 0, NULL, NULL, '{"category":"market_watch"}', 5401, 151, '2026-08-20T06:45:00-04:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (428, 1, '<rome-hotel-newsletter-20260810@hotel.example.it>', 'September Rome city-break newsletter', 'news@hotel-example.it', '["maya.chen@example.com"]', '[]', '[]', '2026-08-10T12:08:00+02:00', 'Our September newsletter lists public rates and museum packages. It is not a reservation and does not guarantee availability for Maya’s travel dates.', NULL, 1, 0, 0, NULL, NULL, '{"category":"marketing"}', 5428, 139, '2026-08-10T12:08:00+02:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (455, 1, '<rail-account-security-20260808@rail.example>', 'Rail account sign-in alert', 'security@rail.example', '["maya.chen@example.com"]', '[]', '[]', '2026-08-08T19:22:00-04:00', 'A sign-in from New York was recognized on your rail account. No ticket was purchased. Review account activity in the official app if this was not you.', NULL, 1, 1, 0, NULL, NULL, '{"category":"security"}', 5455, 143, '2026-08-08T19:22:00-04:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (482, 1, '<restaurant-newsletter-20260806@dining.example.it>', 'Florence summer dining newsletter', 'newsletter@dining.example.it', '["maya.chen@example.com"]', '[]', '[]', '2026-08-06T16:35:00+02:00', 'This newsletter highlights seasonal menus around Florence. General cuisine labels do not establish protection from pine-nut cross-contact.', NULL, 1, 0, 0, NULL, NULL, '{"category":"marketing"}', 5482, 126, '2026-08-06T16:35:00+02:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (509, 1, '<project-kickoff-20260804@studio.example>', 'Autumn campaign kickoff date', 'producer@studio.example', '["maya.chen@example.com"]', '[]', '[]', '2026-08-04T12:24:00-04:00', 'The autumn campaign kickoff is scheduled for October 2. September travel should not change the approved client-review calendar without owner confirmation.', NULL, 1, 0, 0, NULL, NULL, '{"category":"work"}', 5509, 143, '2026-08-04T12:24:00-04:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (536, 1, '<vaccination-record-portal-20260718@clinic.example>', 'Clinic portal document available', 'portal@clinic.example', '["maya.chen@example.com"]', '[]', '[]', '2026-07-18T09:11:00-04:00', 'A routine immunization summary is available in the clinic portal. Download health documents only if needed and do not forward them through ordinary travel email.', NULL, 1, 0, 0, NULL, NULL, '{"category":"health"}', 5536, 150, '2026-07-18T09:11:00-04:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (563, 1, '<bank-travel-alerts-20260819@bank.example>', 'Travel alerts and merchant controls', 'security@bank.example', '["maya.chen@example.com"]', '[]', '[]', '2026-08-19T13:04:00-04:00', 'You can enable purchase alerts and review foreign transactions in the secure portal. Support will never ask for the full card number by email.', NULL, 0, 1, 0, NULL, NULL, '{"category":"banking"}', 5563, 139, '2026-08-19T13:04:00-04:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (590, 1, '<museum-reservation-20260811@tickets.example.it>', 'Uffizi reservation reminder for a friend', 'tickets@museum.example.it', '["maya.chen@example.com"]', '[]', '[]', '2026-08-11T09:40:00+02:00', 'This reminder is for an older reservation made for Priya and does not belong to Maya’s current trip. The booking reference is stored in Priya’s thread.', NULL, 1, 0, 0, NULL, NULL, '{"category":"historical"}', 5590, 140, '2026-08-11T09:40:00+02:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (617, 1, '<budget-template-20260823@maya.example>', 'Italy planning budget categories', 'maya.chen@example.com', '["maya.chen@example.com"]', '[]', '[]', '2026-08-23T21:07:00-04:00', 'Personal note: track flights, hotels, rail, meals, local transport, card holds, refunds, and authorization status separately. Do not treat estimates as settled charges.', NULL, 0, 1, 1, NULL, NULL, '{"category":"self_note"}', 5617, 153, '2026-08-23T21:07:00-04:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (644, 1, '<weather-subscription-20260824@weather.example>', 'Italy city weather subscription active', 'notices@weather.example', '["maya.chen@example.com"]', '[]', '[]', '2026-08-24T08:38:00-04:00', 'Milan, Florence, and Rome are saved for forecast review. This subscription confirmation contains no forecast and should not be read as a future weather outcome.', NULL, 0, 0, 0, NULL, NULL, '{"category":"weather"}', 5644, 151, '2026-08-24T08:38:00-04:00');
COMMIT;
PRAGMA foreign_keys = ON;
