-- Time-isolated email seed for central_ac_install_30d
BEGIN;
INSERT INTO account_config (id, email, name, created_at) VALUES (1, 'luo.wei.install@gmail.com', 'Luo Wei', '2021-09-01T00:00:00Z');
INSERT INTO folders (id,name) VALUES (1,'INBOX'),(2,'Sent'),(3,'Drafts'),(4,'Trash'),(5,'Spam');
INSERT INTO messages (id, folder_id, message_id, subject, from_addr, to_addr_json, cc_addr_json, bcc_addr_json, date, body_text, body_html, is_read, is_important, is_flagged, in_reply_to, references_header, headers_json, uid, size, created_at) VALUES (1, 1, '<iscac-o1@mall.cn>', 'order confirmation：CoolMax three-bedroom central air conditioner', 'official marketplace <order@mall.cn>', '["luo.wei.install@gmail.com"]', '[]', '[]', '2026-06-12T03:25:00Z', 'main-unit order ord_iscac_0001 paid,order details include model and purchase proof。', NULL, 1, 0, 0, NULL, NULL, '{}', 1001, 240, '2026-06-12T03:25:00Z');
INSERT INTO messages (id, folder_id, message_id, subject, from_addr, to_addr_json, cc_addr_json, bcc_addr_json, date, body_text, body_html, is_read, is_important, is_flagged, in_reply_to, references_header, headers_json, uid, size, created_at) VALUES (2, 1, '<iscac-o2@mall.cn>', 'installation service order confirmation', 'official marketplace <order@mall.cn>', '["luo.wei.install@gmail.com"]', '[]', '[]', '2026-06-12T04:10:00Z', 'installation service order ord_iscac_0002 paid,fees include primary installation, floor/materials, and second home-visit items.', NULL, 1, 0, 0, NULL, NULL, '{}', 1002, 260, '2026-06-12T04:10:00Z');
INSERT INTO messages (id, folder_id, message_id, subject, from_addr, to_addr_json, cc_addr_json, bcc_addr_json, date, body_text, body_html, is_read, is_important, is_flagged, in_reply_to, references_header, headers_json, uid, size, created_at) VALUES (3, 1, '<iscac-service@coolmax.example>', 'CoolMax home-visit installation service record', 'CoolMax service center <service@coolmax.example>', '["luo.wei.install@gmail.com"]', '[]', '[]', '2026-06-14T00:20:00Z', 'The home-visit service code is CMX-SVC-2074，use the marketplace order and official service record for installer credentials and fee items.', NULL, 0, 1, 0, NULL, NULL, '{}', 1003, 260, '2026-06-14T00:20:00Z');
UPDATE folders SET message_count=(SELECT COUNT(*) FROM messages WHERE messages.folder_id=folders.id), unread_count=(SELECT COUNT(*) FROM messages WHERE messages.folder_id=folders.id AND messages.is_read=0);
INSERT INTO _counters (key,value) VALUES ('msg_seq',3);
COMMIT;
