-- Curated Stage-0 seed for campus_ai_infra_offer_deadline_tradeoff / notification_hub.

BEGIN;

INSERT INTO subscriptions (subscription_id, user_id, source, type, target, condition_json, status, created_at, updated_at) VALUES
  ('sub_gpu_scheduler_2026', 'usr_lin_che', 'job_board', 'keyword', 'Beijing GPU scheduling position', '{"cities": ["Beijing"], "keywords": ["GPU scheduler", "Kubernetes device plugin"]}', 'active', '2026-05-02T07:40:00Z', '2026-05-02T07:40:00Z'),
  ('sub_offer_mail_watch', 'usr_lin_che', 'email', 'keyword', 'Recruitment email follow-up', '{"senders": ["hr-starridge-chen@example.com"], "keywords": ["technical interview", "follow-up"]}', 'active', '2026-05-04T07:35:00Z', '2026-05-04T07:35:00Z');

INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES
  ('ntf_aiinfra_001', 'usr_lin_che', 'job_board', 'update', NULL, 'Position update', 'Shanghai has added a backend role for a model gateway, with a direction leaning toward service governance rather than CUDA kernels.', '{"category": "job_board", "sequence": 1}', '2026-05-01T08:00:00Z', 1),
  ('ntf_aiinfra_002', 'usr_lin_che', 'job_board', 'update', 'sub_gpu_scheduler_2026', 'Position update', 'Beijing has added a GPU scheduling engineer position, requiring Kubernetes device plugin experience.', '{"category": "job_board", "sequence": 2}', '2026-05-02T08:01:00Z', 1),
  ('ntf_aiinfra_003', 'usr_lin_che', 'job_board', 'update', NULL, 'Position status', 'A training platform position collected in 2025 has been closed, and the page retains the closing date and original city.', '{"category": "job_board", "sequence": 3}', '2026-05-03T08:02:00Z', 1),
  ('ntf_mail_001', 'usr_lin_che', 'email', 'update', 'sub_offer_mail_watch', 'Unread email', 'The follow-up email after the StarRidge technical interview has not been read, and there is currently no written offer.', '{"category": "email", "sequence": 4}', '2026-05-04T08:03:00Z', 1),
  ('ntf_mail_002', 'usr_lin_che', 'email', 'update', NULL, 'Resume version', 'The public resume has completed one self-review, and the research experience and performance data are still based on content that can be verified by the individual.', '{"category": "email", "sequence": 5}', '2026-05-05T08:04:00Z', 1),
  ('ntf_calendar_001', 'usr_lin_che', 'calendar', 'update', NULL, 'Schedule reminder', 'The research group weekly meeting is scheduled for the morning of May 13, at Room 402 of the System Institute.', '{"category": "calendar", "sequence": 6}', '2026-05-06T08:05:00Z', 1),
  ('ntf_calendar_002', 'usr_lin_che', 'calendar', 'update', NULL, 'Schedule reminder', 'The mentor group meeting on the afternoon of May 19 has been confirmed in the calendar.', '{"category": "calendar", "sequence": 7}', '2026-05-07T08:06:00Z', 1),
  ('ntf_thesis_001', 'usr_lin_che', 'school', 'update', NULL, 'Paper reminder', 'The paper figures need supplemental hardware configuration, concurrency, and error explanations.', '{"category": "school", "sequence": 8}', '2026-05-08T08:07:00Z', 1),
  ('ntf_thesis_002', 'usr_lin_che', 'school', 'update', NULL, 'Graduation reminder', 'The college is collecting preferences for the defense time; the official date has not yet been announced.', '{"category": "school", "sequence": 9}', '2026-05-09T08:08:00Z', 1),
  ('ntf_security_001', 'usr_lin_che', 'campus_it', 'update', NULL, 'Account security', 'The password for the campus unified identity authentication system is about to expire; please update it on the official portal.', '{"category": "campus_it", "sequence": 10}', '2026-05-10T08:09:00Z', 1),
  ('ntf_library_001', 'usr_lin_che', 'library', 'update', NULL, 'Borrowing reminder', 'Two system-oriented textbooks will be due on May 14.', '{"category": "library", "sequence": 11}', '2026-05-11T08:10:00Z', 1),
  ('ntf_cluster_001', 'usr_lin_che', 'lab', 'update', NULL, 'Cluster Notice', 'A800 queue maintenance is complete, and personal experiment logs need to be backed up within the retention period.', '{"category": "lab", "sequence": 12}', '2026-05-12T08:11:00Z', 1),
  ('ntf_content_001', 'usr_lin_che', 'content_platform', 'update', NULL, 'Content subscription', 'A new article discusses the throughput and fairness trade-offs of continuous batching.', '{"category": "content_platform", "sequence": 13}', '2026-05-01T08:12:00Z', 1),
  ('ntf_content_002', 'usr_lin_che', 'content_platform', 'update', NULL, 'Content subscription', 'A new article reminds readers to distinguish verbal intent, referral status, and written offer.', '{"category": "content_platform", "sequence": 14}', '2026-05-02T08:13:00Z', 1),
  ('ntf_content_003', 'usr_lin_che', 'content_platform', 'update', NULL, 'Privacy Notice', 'Job search material minimization topic update: transcripts and ID cards should not be sent to unfamiliar advisors.', '{"category": "content_platform", "sequence": 15}', '2026-05-03T08:14:00Z', 1),
  ('ntf_job_004', 'usr_lin_che', 'job_board', 'update', NULL, 'Saved jobs', 'The PineVector retrieval kernel role has updated its database experience requirements.', '{"category": "job_board", "sequence": 16}', '2026-05-04T08:15:00Z', 1),
  ('ntf_job_005', 'usr_lin_che', 'job_board', 'update', NULL, 'Saved jobs', 'The Moonshot Ops performance tools role is offering an online technical sharing session, which does not mean entry into the recruitment process.', '{"category": "job_board", "sequence": 17}', '2026-05-05T08:16:00Z', 1),
  ('ntf_job_006', 'usr_lin_che', 'job_board', 'update', NULL, 'Position comparison', 'An edge deployment position notes that support at the client site is required for 8 to 10 days per month.', '{"category": "job_board", "sequence": 18}', '2026-05-06T08:17:00Z', 1),
  ('ntf_mail_003', 'usr_lin_che', 'email', 'update', NULL, 'Campus services', 'The graduation photo gathering time has been sent to email.', '{"category": "email", "sequence": 19}', '2026-05-07T08:18:00Z', 1),
  ('ntf_mail_004', 'usr_lin_che', 'email', 'update', NULL, 'Account reminder', 'The bank document validity reminder comes from the official App; there is no need to reply by email with the document.', '{"category": "email", "sequence": 20}', '2026-05-08T08:19:00Z', 1),
  ('ntf_calendar_003', 'usr_lin_che', 'calendar', 'update', NULL, 'Two schedules on the same morning', 'The May 20 08:30 graduation photo assembly and the 09:00 equipment loan registration are still kept at the same time.', '{"category": "calendar", "sequence": 21}', '2026-05-09T08:20:00Z', 1),
  ('ntf_calendar_004', 'usr_lin_che', 'calendar', 'update', NULL, 'Weekend venue status', 'Saturday afternoon lab badminton is still tentative; two of the six registered people have not replied yet.', '{"category": "calendar", "sequence": 22}', '2026-05-10T08:21:00Z', 1),
  ('ntf_lab_002', 'usr_lin_che', 'lab', 'update', NULL, 'Data compliance', 'Graduation thesis examples must not contain real user identifiers or laboratory internal addresses.', '{"category": "lab", "sequence": 23}', '2026-05-11T08:22:00Z', 0),
  ('ntf_git_001', 'usr_lin_che', 'developer', 'update', NULL, 'Dependency update', 'The personal experimental repository has a security update dependency, and the benchmark needs to be rerun before merging.', '{"category": "developer", "sequence": 24}', '2026-05-12T08:23:00Z', 0),
  ('ntf_cloud_001', 'usr_lin_che', 'cloud', 'update', NULL, 'Education quota period', 'The student cloud trial quota is valid until June 30, and the remaining quota is 168 yuan.', '{"category": "cloud", "sequence": 25}', '2026-05-01T08:24:00Z', 0),
  ('ntf_systems_001', 'usr_lin_che', 'research', 'update', NULL, 'Paper subscription', 'This week''s serving paper list has added topics on memory management and request scheduling.', '{"category": "research", "sequence": 26}', '2026-05-02T08:25:00Z', 0),
  ('ntf_course_001', 'usr_lin_che', 'school', 'update', NULL, 'Course feedback', 'The CUDA assignment needs additional analysis of memory coalescing and stream synchronization.
', '{"category": "school", "sequence": 27}', '2026-05-03T08:26:00Z', 0),
  ('ntf_dorm_001', 'usr_lin_che', 'campus', 'update', NULL, 'Dormitory notice', 'Dormitory safety inspection will take place on the morning of May 27.', '{"category": "campus", "sequence": 28}', '2026-05-04T08:27:00Z', 0),
  ('ntf_transport_001', 'usr_lin_che', 'travel', 'update', NULL, 'Waitlist status', 'The train ticket for the graduation trip is still on the waitlist, and no charge has been deducted at present.', '{"category": "travel", "sequence": 29}', '2026-05-05T08:28:00Z', 0),
  ('ntf_phone_001', 'usr_lin_che', 'mobile', 'update', NULL, 'Data usage balance', 'This month''s general data usage has 1.8 GB remaining, and the dormitory campus network online rate over the past seven days is 99.2%.', '{"category": "mobile", "sequence": 30}', '2026-05-06T08:29:00Z', 0),
  ('ntf_backup_001', 'usr_lin_che', 'storage', 'update', NULL, 'Backup completed', 'The paper source files, raw experimental logs, and public resume directories have all been backed up overnight.', '{"category": "storage", "sequence": 31}', '2026-05-07T08:30:00Z', 0),
  ('ntf_offer_math_001', 'usr_lin_che', 'content_platform', 'update', NULL, 'Compensation article', 'The new article explains how to separate fixed cash, target bonuses, and long-term incentives.', '{"category": "content_platform", "sequence": 32}', '2026-05-08T08:31:00Z', 0),
  ('ntf_recruit_001', 'usr_lin_che', 'career_center', 'update', NULL, 'Process Q&A open', 'On May 25, the college career center will open consultation for tripartite materials; on site, only a materials checklist and system entry instructions will be provided.', '{"category": "career_center", "sequence": 33}', '2026-05-09T08:32:00Z', 0),
  ('ntf_profile_001', 'usr_lin_che', 'content_platform', 'update', NULL, 'Project Homepage Update', 'The public project page has added a scheduler course project description and two performance curves.', '{"category": "content_platform", "sequence": 34}', '2026-05-10T08:33:00Z', 0),
  ('ntf_followup_001', 'usr_lin_che', 'job_board', 'update', NULL, 'Saved job update time', 'The latest update times of the two saved positions were May 7 and May 8 respectively.', '{"category": "job_board", "sequence": 35}', '2026-05-11T08:34:00Z', 0),
  ('ntf_decision_001', 'usr_lin_che', 'notion', 'update', NULL, 'Recent edits on the profile page', 'The study and graduation materials page was last edited on May 1, and the current directory contains three types of pages: courses, thesis, and leaving-school procedures.', '{"category": "notion", "sequence": 36}', '2026-05-12T08:35:00Z', 0);

INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES
  ('ntf_card_migration_receipt', 'usr_lin_che', 'campus_card', 'receipt', NULL, 'Campus card balance migration completed', 'The 83.40 yuan balance from the old card has been transferred to the new card ending in 4821.', '{"receipt": "C4821", "amount_minor": 8340}', '2026-01-24T03:08:00Z', 1),
  ('ntf_library_hold_window', 'usr_lin_che', 'library', 'availability', NULL, 'Reserved book has arrived at the library', 'The English edition of the distributed data systems textbook will remain available until the library closes on January 25.', '{"branch": "east-2f", "hold_until": "2026-01-25T21:30:00+08:00"}', '2026-01-23T05:50:00Z', 1),
  ('ntf_cloud_invoice_zero_due', 'usr_lin_che', 'cloud_billing', 'invoice', NULL, 'The January bill was offset by the education credit', 'Object storage and CPU instances total 31.8 yuan, and the amount payable for this billing period is 0.', '{"period": "2026-01", "gross_minor": 3180, "due_minor": 0}', '2026-02-02T11:09:00Z', 1),
  ('ntf_rocm_ci_green', 'usr_lin_che', 'developer', 'build', NULL, 'ROCm compatibility patch passed CI', 'Both gfx90a and gfx942 builds passed, and issue #1847 has been closed.', '{"issue": 1847, "architectures": ["gfx90a", "gfx942"]}', '2026-02-08T13:25:00Z', 1),
  ('ntf_dorm_repair_closed', 'usr_lin_che', 'housing', 'work_order', NULL, 'Dormitory repair work order closed', 'Work order H-60318 replaced the inlet valve, and a half-hour retest showed no leakage.', '{"work_order": "H-60318", "building": "7"}', '2026-03-05T08:55:00Z', 1),
  ('ntf_scholarship_publication', 'usr_lin_che', 'student_office', 'notice', NULL, 'Public notice of the university-level scholarship list', 'Six people in Lin Che''s major were included in the three-day public notice list.', '{"notice": "scholarship-2026", "duration_days": 3}', '2026-03-12T03:34:00Z', 0),
  ('ntf_cluster_job_retryable', 'usr_lin_che', 'cluster', 'job_status', NULL, 'Experiment assignment can be re-queued', 'After the gpu-a17 driver was reset, run-8831 was marked as retryable.', '{"node": "gpu-a17", "job": "run-8831", "status": "retryable"}', '2026-03-30T12:06:00Z', 0),
  ('ntf_alumni_alias_reserved', 'usr_lin_che', 'identity', 'account', NULL, 'Alumni email alias reserved', 'The alias linche26 will be enabled after the academic status departure synchronization.', '{"alias": "linche26", "state": "reserved"}', '2026-04-06T02:01:00Z', 1),
  ('ntf_proof_asset_received', 'usr_lin_che', 'publication', 'asset', NULL, 'Figure 4 replacement file has been received', 'The manuscript number registered by the editorial department is SYS-2025-118, and the author affiliation has not changed.', '{"manuscript": "SYS-2025-118", "asset": "figure4-proof.png"}', '2026-04-14T10:33:00Z', 1),
  ('ntf_gym_refund', 'usr_lin_che', 'campus_wallet', 'refund', NULL, 'Badminton court refund received', 'The fees after the cancellation of Court 3 on April 23 were refunded to the campus wallet.', '{"booking": "GYM-423-3", "status": "refunded"}', '2026-04-22T04:16:00Z', 1),
  ('ntf_dorm_network_metrics', 'usr_lin_che', 'campus_network', 'maintenance', NULL, 'Network maintenance in Building 7 completed', 'Packet loss during the evening peak dropped from 6.2% to 0.4%, and the authentication method did not change.', '{"building": "7", "packet_loss_before": 6.2, "packet_loss_after": 0.4}', '2026-04-29T09:41:00Z', 0),
  ('ntf_storage_quota_1380', 'usr_lin_che', 'storage', 'quota', NULL, 'The experiment directory has used 1.38 TB', 'Raw traces account for about 64%, and 92 GB were added in the past seven days.', '{"used_tb": 1.38, "weekly_growth_gb": 92}', '2026-05-02T02:31:00Z', 0),
  ('ntf_bike_tag_active', 'usr_lin_che', 'campus_security', 'registration', NULL, 'Bicycle electronic tag activated', 'The blue commuter shuttle tag B7-194 is valid until June 30.', '{"tag": "B7-194", "valid_until": "2026-06-30"}', '2026-05-05T06:22:00Z', 1),
  ('ntf_travel_reimbursement', 'usr_lin_che', 'campus_finance', 'deposit', NULL, 'Travel reimbursement received', 'Nanjing conference reimbursement of 1,268 yuan, voucher number F2026050817.', '{"voucher": "F2026050817", "amount_minor": 126800}', '2026-05-08T03:49:00Z', 0),
  ('ntf_lab_key_inventory', 'usr_lin_che', 'lab', 'inventory', NULL, 'Laboratory key inventory update', 'The two keys for the workstation drawer and equipment cabinet 4B are still registered under Lin Che''s name.', '{"inventory": "LAB-KEY-0510", "outstanding": 2}', '2026-05-10T11:37:00Z', 0),
  ('ntf_transit_refund_receipt', 'usr_lin_che', 'campus_transit', 'refund', NULL, 'Campus bus card refund completed', 'The deposit and remaining 23.5 yuan have been refunded to Alipay, and the electronic receipt can be viewed on the transportation service page.', '{"balance_minor": 2350, "channel": "alipay"}', '2026-04-19T04:20:00Z', 1);

INSERT INTO official_accounts (account_id, name, category, description) VALUES
  ('oa_career_center', 'College career center', 'Campus', 'Publish information about graduation destinations, three-party agreements, and recruitment activities.'),
  ('oa_systems_digest', 'System research weekly report', 'Technology', 'Compile public papers and activities on systems and basic software.');

INSERT INTO official_account_subscriptions (user_id, account_id, subscribed_at) VALUES
  ('usr_lin_che', 'oa_career_center', '2025-09-01T00:00:00Z'),
  ('usr_lin_che', 'oa_systems_digest', '2025-10-01T00:00:00Z');

INSERT INTO official_account_posts (post_id, account_id, title, summary, url, published_at) VALUES
  ('oa_post_resume_clinic', 'oa_career_center', 'May resume clinic and three-party consultation schedule', 'Announce consultation hours and emphasize that the formal materials are to be checked by the graduate.', 'https://career.example.edu.cn/posts/may-clinic', '2026-05-06T08:00:00Z'),
  ('oa_post_systems_weekly', 'oa_systems_digest', 'This week''s system papers: Serving, Memory, and Scheduling', 'Organize the publicly shareable paper titles and conference links, excluding recruitment conclusions.', 'https://systems.example.org/digest/2026-w19', '2026-05-08T08:00:00Z');

COMMIT;
