-- Generated email seed for garden_total_reno_v4_30d
BEGIN;
INSERT INTO account_config (id, email, name, created_at) VALUES (1, 'yong.wei.reno4@gmail.com', 'Evan Young', '2021-09-01T00:00:00Z');
INSERT INTO folders (id,name) VALUES (1,'INBOX'),(2,'Sent'),(3,'Drafts'),(4,'Trash'),(5,'Spam');
INSERT INTO messages (id, folder_id, message_id, subject, from_addr, to_addr_json, date, body_text, is_read, is_important, headers_json, size, created_at) VALUES (1, 1, '<qgrd-contract@mall.cn>', 'Signing receipt: courtyard drainage and paving master order', 'Official Mall <order@mall.cn>', '["yong.wei.reno4@gmail.com"]', '2026-06-13T01:25:00Z', 'ord_qgrd_0001 signing receipt generated; the contracting entity, drainage construction, paving, and maintenance responsibilities still require separate verification.', 1, 0, '{}', 220, '2026-06-13T01:25:00Z');
INSERT INTO messages (id, folder_id, message_id, subject, from_addr, to_addr_json, date, body_text, is_read, is_important, headers_json, size, created_at) VALUES (2, 1, '<qgrd-measure@mall.cn>', 'Initial site measurement: elevations, drains, and paving scope', 'Official Mall <order@mall.cn>', '["yong.wei.reno4@gmail.com"]', '2026-06-13T05:10:00Z', 'ord_qgrd_0002 initial measurement record includes benchmarks, drains, and paving scope; initial measurement does not equal a rain test or concealed-work acceptance.', 1, 0, '{}', 220, '2026-06-13T05:10:00Z');
INSERT INTO messages (id, folder_id, message_id, subject, from_addr, to_addr_json, date, body_text, is_read, is_important, headers_json, size, created_at) VALUES (3, 1, '<qgrd-batch@garden.example>', 'Arrival listing for drainage channels, paving, and nursery stock batches', 'Project Warehouse <warehouse@garden.example>', '["yong.wei.reno4@gmail.com"]', '2026-06-14T02:00:00Z', 'Drainage channels, drain covers, paving stone, and nursery stock arrived by batch; the arrival listing cannot replace grading, drainage-channel connection, a rain test, or establishment acceptance.', 0, 1, '{}', 220, '2026-06-14T02:00:00Z');
INSERT INTO messages (id, folder_id, message_id, subject, from_addr, to_addr_json, date, body_text, is_read, is_important, headers_json, size, created_at) VALUES (4, 1, '<20260522-security@mall.example>', 'Historical security reminder: corrective-work refunds verified only on the platform', 'Mall Security Center <security@mall.example>', '["yong.wei.reno4@gmail.com"]', '2026-05-22T02:00:00Z', 'Historical reminder: do not enter bank card details or pay authentication fees through short links in email; corrective work and retention-payment adjustments must be verified only through official orders and card transactions.', 0, 0, '{"campaign":"security-20260522"}', 220, '2026-05-22T02:00:00Z');
UPDATE folders SET message_count=(SELECT COUNT(*) FROM messages WHERE messages.folder_id=folders.id), unread_count=(SELECT COUNT(*) FROM messages WHERE messages.folder_id=folders.id AND messages.is_read=0);
INSERT INTO _counters (key,value) VALUES ('msg_seq',4);
COMMIT;
-- 2026-07-29 handbook remediation: pre-kickoff mailbox for courtyard drainage.
BEGIN;
UPDATE messages SET subject='Signing receipt: courtyard drainage and paving master order', body_text='ord_qgrd_0001 signing receipt generated; the contracting entity, drainage construction, paving, and maintenance responsibilities still require separate verification.', date='2026-06-13T01:25:00Z', created_at='2026-06-13T01:25:00Z' WHERE id=1;
UPDATE messages SET subject='Initial site measurement: elevations, drains, and paving scope', body_text='ord_qgrd_0002 initial measurement record includes benchmarks, drains, and paving scope; initial measurement does not equal a rain test or concealed-work acceptance.', date='2026-06-13T05:10:00Z', created_at='2026-06-13T05:10:00Z' WHERE id=2;
UPDATE messages SET subject='Arrival listing for drainage channels, paving, and nursery stock batches', from_addr='Project Warehouse <warehouse@garden.example>', body_text='Drainage channels, drain covers, paving stone, and nursery stock arrived by batch; the arrival listing cannot replace grading, drainage-channel connection, a rain test, or establishment acceptance.', date='2026-06-14T02:00:00Z', created_at='2026-06-14T02:00:00Z' WHERE id=3;
UPDATE messages SET subject='Historical security reminder: corrective-work refunds verified only on the platform', from_addr='Mall Security Center <security@mall.example>', body_text='Historical reminder: do not enter bank card details or pay authentication fees through short links in email; corrective work and retention-payment adjustments must be verified only through official orders and card transactions.', date='2026-05-22T02:00:00Z', created_at='2026-05-22T02:00:00Z', headers_json='{"campaign":"security-20260522"}' WHERE id=4;
INSERT INTO messages (folder_id,message_id,subject,from_addr,to_addr_json,date,body_text,is_read,is_important,headers_json,size,created_at) VALUES
 (1,'<20260310.patio-close.4c72@garden.example>','Qinglong Temple East Courtyard terrace drainage reinspection closeout','Project Archives <archive@garden.example>','["yong.wei.reno4@gmail.com"]','2026-03-10T06:20:00Z','The south-facing terrace in the east courtyard of Qinglong Temple has completed three sections of flow-through testing, actual-rain observation, and drainage records; project closeout was processed on March 10.',1,0,'{"project":"patio-2025-closeout"}',168,'2026-03-10T06:20:00Z'),
 (1,'<20260506.roof-drain-quote.91b2@garden.example>','Roof rainwater inlets and downpipes modification quote','Quotation Center <quote@garden.example>','["yong.wei.reno4@gmail.com"]','2026-05-06T01:15:00Z','The quotation covers roof rainwater inlets, downpipes, and eaves-gutter connections, excluding pavement base course, permeable pavement, planting area, and courtyard overflow structures.',1,0,'{"comparison":"roof_scope_mismatch"}',182,'2026-05-06T01:15:00Z'),
 (1,'<qgrd-auth@contract.example>','Supplementary documents for courtyard contracting-entity authorization','Contract Review <review@contract.example>','["yong.wei.reno4@gmail.com"]','2026-06-12T06:00:00Z','The authorization letter must correspond to the contracting entity, site lead, and drainage and paving scope; the responsible-person signature page is currently missing.',0,1,'{"document":"authorization"}',176,'2026-06-12T06:00:00Z'),
 (1,'<qgrd-drain-batch@garden.example>','Drainage-channel and drain-cover batch checklist','Materials Supply <batch@garden.example>','["yong.wei.reno4@gmail.com"]','2026-06-12T08:30:00Z','Drainage channels, corner fittings, and drain covers belong to different batches; each component must be linked to a specific location and drainage-channel connection record.',1,0,'{"document":"drain_batch"}',170,'2026-06-12T08:30:00Z'),
 (1,'<qgrd-rain-protocol@survey.example>','Method for recording post-rain drainage observations','Surveying Firm <service@survey.example>','["yong.wei.reno4@gmail.com"]','2026-06-11T03:20:00Z','The observation must record the rainfall period, ponding boundary, measuring scale, drain status, and drainage time; a single completion photo cannot replace it.',1,0,'{"document":"rain_observation"}',166,'2026-06-11T03:20:00Z'),
 (1,'<20260614.paver-stock.2f83@supply.example>','Similar-color permeable paver stock reminder','Paving Supply <stock@supply.example>','["yong.wei.reno4@gmail.com"]','2026-06-14T04:10:00Z','Similar-color permeable pavers are in stock, but their dimensions do not match the current approved sample and they cannot be substituted without confirmation.',0,0,'{"state":"dimension_mismatch"}',174,'2026-06-14T04:10:00Z');
UPDATE folders SET message_count=(SELECT COUNT(*) FROM messages WHERE folder_id=folders.id), unread_count=(SELECT COUNT(*) FROM messages WHERE folder_id=folders.id AND is_read=0);
COMMIT;
-- 2026-07-30 cross-service richness remediation: individually reviewed pre-kickoff courtyard correspondence.
BEGIN;
INSERT INTO messages (folder_id,message_id,subject,from_addr,to_addr_json,date,body_text,is_read,is_important,headers_json,size,created_at) VALUES
 (1,'<garden-level-grid@landscape.example>','Initial courtyard elevation-grid sketch','Landscape Design Development <design@landscape.example>','["yong.wei.reno4@gmail.com"]','2026-01-07T03:08:00Z','The initial version uses the entrance threshold as the relative benchmark and marks nine measurement points and drain directions; the drawing still awaits site remeasurement and cannot prove that grading is complete.',1,0,'{"document":"level_grid_v1"}',180,'2026-01-07T03:08:00Z'),
 (1,'<property-outdoor-workhours@gaoxin.example>','Courtyard noise and earthwork removal hours','Gaoxin Property Management <service@gaoxin.example>','["yong.wei.reno4@gmail.com"]','2026-01-14T07:17:00Z','Cutting and earthwork hauling are limited to 09:00 to 12:00 and 14:00 to 18:00 on weekdays; vehicles entering the site must be registered in advance.',1,0,'{"topic":"outdoor_work_hours"}',164,'2026-01-14T07:17:00Z'),
 (1,'<old-sprinkler-return@irrigation.example>','Return of old-model irrigation controller sample','Irrigation Sample Room <samples@irrigation.example>','["yong.wei.reno4@gmail.com"]','2026-01-25T09:22:00Z','The four-zone controller from the previous terrace project has been returned and the sample-loan form closed; it is unrelated to the courtyard drip-irrigation plan.',1,0,'{"sample":"sprinkler_controller_closed"}',166,'2026-01-25T09:22:00Z'),
 (1,'<paver-color-warmgray@paverlab.example>','Warm-gray permeable paver color-board observation record','Paving Sample Room <lab@paverlab.example>','["yong.wei.reno4@gmail.com"]','2026-02-03T02:31:00Z','The warm-gray sample appears darker on cloudy days; Evan Young requested a side-by-side comparison with the exterior-wall stone. The model, batch, and quantity have not yet been confirmed.',1,0,'{"sample":"warm_gray_paver"}',168,'2026-02-03T02:31:00Z'),
 (1,'<invoice-balcony-planter@mall.cn>','Historical balcony planter invoice archived','Official Mall <invoice@mall.cn>','["yong.wei.reno4@gmail.com"]','2026-02-09T01:18:00Z','An invoice for CNY 4,860 was issued for the balcony aluminum planter order and after-sales service was closed; it is outside the courtyard drainage or nursery-stock contract.',1,0,'{"order_scope":"balcony_planter_closed"}',168,'2026-02-09T01:18:00Z'),
 (1,'<tree-pruning-service@arbor.example>','Existing crabapple winter-pruning record','Tree Care <service@arbor.example>','["yong.wei.reno4@gmail.com"]','2026-02-20T10:14:00Z','The maintenance staff removed dead branches and retained photos of three old wounds; this is the pre-construction baseline for tree condition and does not represent subsequent nursery-stock responsibility.',1,0,'{"plant":"existing_crabapple"}',176,'2026-02-20T10:14:00Z'),
 (1,'<drain-grate-loadtest@drain.example>','Linear drainage-channel cover sample materials','Drainage Technical Services <quality@drain.example>','["yong.wei.reno4@gmail.com"]','2026-03-02T04:19:00Z','The sample materials list the material, joint width, and test load, and the report concerns the showroom sample; the drainage channel delivered to the site still requires batch and connection-fitting verification.',1,1,'{"sample":"linear_drain_grate"}',178,'2026-03-02T04:19:00Z'),
 (1,'<gate-protection-deposit@gaoxin.example>','Receipt for courtyard material-entry protection deposit','Gaoxin Property Finance <finance@gaoxin.example>','["yong.wei.reno4@gmail.com"]','2026-03-10T08:25:00Z','Property management received a CNY 3,000 protection deposit for the residential road and gatehouse, to be returned after the exit inspection; it cannot be included in project payment or a refund.',1,0,'{"receipt":"road_protection"}',172,'2026-03-10T08:25:00Z'),
 (1,'<laser-level-calibration@inspect.example>','Laser level calibration certificate','Third-Party Surveying <equipment@inspect.example>','["yong.wei.reno4@gmail.com"]','2026-03-19T02:34:00Z','The laser level was calibrated on March 13 and is valid through September; an equipment certificate does not mean the site benchmark elevation data is correct.',1,1,'{"instrument":"laser_level"}',171,'2026-03-19T02:34:00Z'),
 (1,'<neighbor-wall-repair@gaoxin.example>','Notice of adjacent boundary-wall repair','Gaoxin Property Engineering <engineering@gaoxin.example>','["yong.wei.reno4@gmail.com"]','2026-03-27T11:06:00Z','The neighboring household to the west will repair the boundary-wall plaster on March 29. Property management requires both sides to protect their plants separately; this work is separate from the courtyard drainage contract.',1,0,'{"topic":"neighbor_wall"}',173,'2026-03-27T11:06:00Z'),
 (1,'<outdoor-step-trim-quote@stone.example>','Separate quote for entrance-step side-edge repair','Stone Finishing <quote@stone.example>','["yong.wei.reno4@gmail.com"]','2026-03-31T06:39:00Z','The quote for repairing chipped step edges is CNY 1,160 and excludes the main courtyard paving, drainage channels, and light fixtures; it has not yet been confirmed.',0,0,'{"quote_minor":116000,"scope":"step_edge"}',169,'2026-03-31T06:39:00Z'),
 (1,'<soil-moisture-probe@arbor.example>','Scope of use for soil-moisture meter','Nursery-Stock Maintenance <equipment@arbor.example>','["yong.wei.reno4@gmail.com"]','2026-04-08T01:49:00Z','The maintenance provider explains that soil-moisture readings are used to determine irrigation and cannot be used to infer pavement base-course drainage or drainage-channel connection quality.',1,1,'{"instrument":"soil_moisture"}',168,'2026-04-08T01:49:00Z'),
 (1,'<garden-light-cable-measure@electric.example>','Remeasurement of outdoor-light cable route','Electrical Measurement <measure@electric.example>','["yong.wei.reno4@gmail.com"]','2026-04-15T09:16:00Z','The remeasurement records 18.6 meters of concealed wall-side light-cable routing, with two tree pits requiring clearance; no outdoor-light change order has yet been created.',1,0,'{"scope":"outdoor_cable_route"}',168,'2026-04-15T09:16:00Z'),
 (1,'<paver-delivery-slot-cancel@landscape.example>','First permeable-paver delivery window canceled','Project Coordination <coordination@landscape.example>','["yong.wei.reno4@gmail.com"]','2026-04-21T03:12:00Z','The permeable-paver delivery scheduled for April 25 was canceled because of gate-road construction; no receipt or paving occurred.',1,0,'{"event":"cancelled_paver_delivery"}',160,'2026-04-21T03:12:00Z'),
 (1,'<sponge-facility-consult@drain.example>','Consultation on combining a sunken planting area with drainage channels','Drainage Technical Services <consult@drain.example>','["yong.wei.reno4@gmail.com"]','2026-04-26T08:27:00Z','The technician explained that planting-area detention, overflow, and linear drainage-channel connections must be evaluated together with site elevations; the consultation does not mean the current plan has passed.',1,0,'{"topic":"drainage_combination"}',173,'2026-04-26T08:27:00Z'),
 (1,'<benchmark-precheck@inspect.example>','Pre-construction check of benchmarks and threshold elevation','Third-Party Surveying <field@inspect.example>','["yong.wei.reno4@gmail.com"]','2026-04-30T02:06:00Z','Pre-construction verification points were established at the entrance threshold, rainwater inlet, and southeast corner; the data serves only as a baseline for subsequent differences.',0,1,'{"phase":"pregrade","points":3}',162,'2026-04-30T02:06:00Z'),
 (1,'<outdoor-light-circuit@electric.example>','Briefing on dedicated outdoor-light circuit','Electrical Coordination <site@electric.example>','["yong.wei.reno4@gmail.com"]','2026-05-04T07:11:00Z','The wall lights and ground outlets are powered by a dedicated circuit with leakage protection; connections must be inspected while de-energized. This is not evidence for drainage acceptance.',1,0,'{"circuit":"outdoor_lighting"}',174,'2026-05-04T07:11:00Z'),
 (1,'<garden-waste-sort@recycle.example>','Sorting instructions for stone packaging and garden waste','Community Waste Removal <service@recycle.example>','["yong.wei.reno4@gmail.com"]','2026-05-09T05:18:00Z','Paver pallets, woven bags, pruning branches, and reusable stone offcuts must be separated; unopened full packages of pavers must not be treated as construction waste.',1,0,'{"topic":"garden_waste_sort"}',171,'2026-05-09T05:18:00Z'),
 (1,'<basement-damp-history@gaoxin.example>','Historical service ticket: basement garage seepage closed','Gaoxin Property Customer Service <tickets@gaoxin.example>','["yong.wei.reno4@gmail.com"]','2026-05-13T09:41:00Z','The garage seepage on May 9 was investigated and attributed to drainage from fire-pipe maintenance, and the ticket was closed; it has no direct connection to responsibility for ponding in the first-floor courtyard.',1,0,'{"ticket":"garage_water_closed"}',172,'2026-05-13T09:41:00Z'),
 (1,'<paver-layout-options@design.example>','Permeable-paver running-bond and basket-weave layouts on hold','Landscape Design Development <design@landscape.example>','["yong.wei.reno4@gmail.com"]','2026-05-17T03:09:00Z','Evan Young retained two layout options, running bond for the main passage and basket weave for the seating area, and requested confirmation of grading and waste factors first.',1,0,'{"decision":"paver_layout_pending"}',166,'2026-05-17T03:09:00Z'),
 (1,'<tree-transit-insurance@carrier.example>','Coverage of nursery-stock transport insurance','Carrier Protection <claims@carrier.example>','["yong.wei.reno4@gmail.com"]','2026-05-20T01:26:00Z','Transport insurance covers broken branches and root-ball splitting while nursery stock is in transit, with coverage of CNY 42,000; post-planting maintenance responsibility will be determined separately.',1,0,'{"coverage":"plant_transit","insured_minor":4200000}',169,'2026-05-20T01:26:00Z'),
 (1,'<mud-control-patrol@gaoxin.example>','Pre-earthwork road mud-control inspection','Gaoxin Property Engineering <engineering@gaoxin.example>','["yong.wei.reno4@gmail.com"]','2026-05-22T08:03:00Z','Property management confirmed that wheel-wash mats, road protection, and rainwater-grate covers were in place; it did not evaluate the courtyard pavement base course or drainage.',1,0,'{"inspection":"mud_control"}',168,'2026-05-22T08:03:00Z'),
 (1,'<plant-protection-estimate@arbor.example>','Estimate for nursery-stock protection during construction','Nursery-Stock Maintenance <estimate@arbor.example>','["yong.wei.reno4@gmail.com"]','2026-05-26T10:22:00Z','The estimate for crabapple support, root-zone covering, and relocation protection for two shrubs is CNY 1,920; it has not yet been purchased or authorized.',1,0,'{"estimate_minor":192000,"scope":"plant_protection"}',165,'2026-05-26T10:22:00Z'),
 (1,'<account-login-xian@mall.cn>','Official Mall Xi''an new-device login confirmation','Official Mall Security Center <security@mall.cn>','["yong.wei.reno4@gmail.com"]','2026-05-28T02:38:00Z','Evan Young confirmed that the Gaoxin District login on May 27 was from his phone; the order and payment details were unchanged.',1,1,'{"security_case":"new_phone_verified"}',163,'2026-05-28T02:38:00Z'),
 (1,'<paver-tone-review@paverlab.example>','Second review of warm-gray and light sand-gray samples','Paving Sample Room <lab@paverlab.example>','["yong.wei.reno4@gmail.com"]','2026-05-30T04:04:00Z','In evening light, light sand-gray is closer to the exterior wall; Evan Young still requested a decision only after comparing the samples in wet site conditions.',1,0,'{"sample":"paver_tone_compare"}',163,'2026-05-30T04:04:00Z'),
 (1,'<drain-cleanout-clearance@drain.example>','Verification of drainage-channel cleanout access space','Drainage Design <design@drain.example>','["yong.wei.reno4@gmail.com"]','2026-06-01T08:13:00Z','The plan retains 280 millimeters of operating space above the cleanout; the data comes from the drawings and still requires field measurement after construction.',0,1,'{"check":"cleanout_clearance"}',165,'2026-06-01T08:13:00Z'),
 (1,'<geotextile-certificate@materials.example>','Geotextile batch documents received','Materials Quality Control <quality@materials.example>','["yong.wei.reno4@gmail.com"]','2026-06-03T01:08:00Z','A summary of the basis weight and width for geotextile batch GT-8H was sent, covering 12 rolls; the documents do not cover field overlaps.',1,0,'{"batch":"GT-8H","rolls":12}',163,'2026-06-03T01:08:00Z'),
 (1,'<drain-grate-color@drain.example>','Drainage-channel cover color awaiting side-by-side sample comparison','Drainage Supply <stock@drain.example>','["yong.wei.reno4@gmail.com"]','2026-06-04T06:17:00Z','The dark-gray cover is bluer than the paving sample; the supplier recommends observing both wet and dry conditions before installation.',0,1,'{"state":"awaiting_wet_dry_compare"}',166,'2026-06-04T06:17:00Z'),
 (1,'<garden-access-card@gaoxin.example>','Construction gate access-card issuance record','Gaoxin Property Customer Service <access@gaoxin.example>','["yong.wei.reno4@gmail.com"]','2026-06-05T02:01:00Z','The site lead collected one temporary access card, scheduled for return on July 16; this does not constitute acceptance or payment authorization.',1,0,'{"asset":"garden_access_card"}',165,'2026-06-05T02:01:00Z'),
 (1,'<tree-root-zones@design.example>','Briefing on protecting existing tree root zones','Landscape Design Development <design@landscape.example>','["yong.wei.reno4@gmail.com"]','2026-06-06T07:18:00Z','No-storage zones were marked around the crabapple and sweet osmanthus root zones; grading and light-cable work must route around them and does not directly increase the order.',1,0,'{"scope":"tree_root_zones"}',166,'2026-06-06T07:18:00Z'),
 (1,'<joint-sand-storage@materials.example>','Moisture-protection inspection for temporarily stored joint sand','Materials Quality Control <quality@materials.example>','["yong.wei.reno4@gmail.com"]','2026-06-07T03:09:00Z','A warehouse spot check found intact package seals, pallets elevated off the ground, and no storage mixed with wet soil; this only proves the pre-arrival storage conditions.',1,0,'{"storage":"joint_sand"}',162,'2026-06-07T03:09:00Z'),
 (1,'<plant-handover-draft@arbor.example>','Draft handover of nursery-stock protection responsibility','Nursery-Stock Maintenance <site@arbor.example>','["yong.wei.reno4@gmail.com"]','2026-06-08T09:37:00Z','The construction team and maintenance provider plan to complete the handover based on full-tree views, root zones, and support conditions, with actual photo timestamps controlling.',1,0,'{"handover":"plant_protection"}',166,'2026-06-08T09:37:00Z'),
 (1,'<authorization-license-name@contract.example>','Correction to contracting-entity license name awaiting seal','Contract Review <review@contract.example>','["yong.wei.reno4@gmail.com"]','2026-06-09T01:12:00Z','The company abbreviation on the authorization letter does not match the full name on the business license; the review requires a stamped correction page and the site lead''s signature.',0,1,'{"document":"entity_name_correction"}',169,'2026-06-09T01:12:00Z'),
 (1,'<paver-label-retake@landscape.example>','Additional photos required for permeable-paver pallet labels','Project Warehouse <warehouse@landscape.example>','["yong.wei.reno4@gmail.com"]','2026-06-09T10:25:00Z','The labels on two paver pallets are obscured by reflective wrapping; the model, color code, and batch cannot be identified in the same frame. Additional photos are required before the wrapping is removed.',0,1,'{"evidence":"paver_label_retake"}',166,'2026-06-09T10:25:00Z'),
 (1,'<tree-crate-arrival@carrier.example>','Advance notice of nursery-stock root-ball crate receipt','Carrier Customer Service <service@carrier.example>','["yong.wei.reno4@gmail.com"]','2026-06-10T02:18:00Z','The carrier states that the crate straps are intact; upon receipt, the root balls, branch securing, and leaf dehydration must still be checked.',0,0,'{"shipment_scope":"tree_crates"}',165,'2026-06-10T02:18:00Z'),
 (1,'<evidence-separation-garden@inspect.example>','Benchmark elevation, equivalent hose test, and actual-rain observation must be separate','Third-Party Surveying <field@inspect.example>','["yong.wei.reno4@gmail.com"]','2026-06-10T06:31:00Z','The surveyor requires the benchmarks, equivalent hose test, actual-rain ponding boundary, and drainage time to be recorded separately; they cannot substitute for one another.',1,1,'{"guidance":"drainage_evidence_layers"}',171,'2026-06-10T06:31:00Z'),
 (1,'<outdoor-light-count@landscape.example>','Outdoor-light arrival quantity awaiting recount','Project Warehouse <warehouse@landscape.example>','["yong.wei.reno4@gmail.com"]','2026-06-11T00:28:00Z','The delivery note lists six wall lights and four ground outlets; the warehouse initially counted five wall lights, and another small box has not yet been opened.',0,1,'{"wall_lights_expected":6,"wall_lights_first":5}',171,'2026-06-11T00:28:00Z'),
 (1,'<freight-window-pavers@gaoxin.example>','June 14 permeable-paver unloading period','Gaoxin Property Engineering <engineering@gaoxin.example>','["yong.wei.reno4@gmail.com"]','2026-06-12T09:12:00Z','Property management confirmed that unloading at the west gate is permitted from 13:30 to 15:30 on June 14 and requires road protection to be laid before the pallets are placed on the ground.',1,0,'{"event":"paver_unloading_slot"}',166,'2026-06-12T09:12:00Z'),
 (1,'<arrival-groups-garden@landscape.example>','Photo directory for the first batch of courtyard materials','Project Coordination <coordination@landscape.example>','["yong.wei.reno4@gmail.com"]','2026-06-14T08:44:00Z','Arrival photos are divided into seven groups: permeable pavers, channel bodies, connection fittings, geotextile, jointing material, nursery stock, and light fixtures; the directory does not equal acceptance.',0,1,'{"evidence":"garden_arrival_groups"}',171,'2026-06-14T08:44:00Z'),
 (1,'<prestart-baseline-garden@inspect.example>','Pre-start baseline: threshold, rainwater inlet, and tree pits','Third-Party Surveying <field@inspect.example>','["yong.wei.reno4@gmail.com"]','2026-06-14T11:29:00Z','The survey records the original conditions of the threshold, rainwater inlet, southeast corner, and two tree pits; subsequent changes will be assessed by point and time.',0,1,'{"phase":"prestart","scope":"threshold_drain_treepit"}',174,'2026-06-14T11:29:00Z');
UPDATE folders SET message_count=(SELECT COUNT(*) FROM messages WHERE folder_id=folders.id), unread_count=(SELECT COUNT(*) FROM messages WHERE folder_id=folders.id AND is_read=0);
UPDATE _counters SET value=50 WHERE key='msg_seq';
COMMIT;
