"""Scenario constants (generated). Only this file varies by scenario; scoring logic is in checks.py."""
from __future__ import annotations

STAGE_COUNT = 24
ALL_SERVERS = ('ecommerce', 'delivery_logistics', 'credit_card', 'email', 'calendar', 'notification_hub', 'listing_platform', 'weather')
OUTPUT_PATHS = ('/workspace/gear_plan.md', '/workspace/budget.md', '/workspace/decision_log.md', '/workspace/risk_register.md', '/workspace/order_tracker.md', '/workspace/evidence_log.md', '/workspace/final_summary.md', '/workspace/HEARTBEAT.md')
THREAD_IDS = ['ord_homtg_0001', 'ord_homtg_0002', 'lst_homtg_0001']
THREAD_LABELS = {'ord_homtg_0001': ['ord_homtg_0001', 'thread 1', 'thread 1', 'thread 1', 'thread one', 'Product and Group Leader Verification'], 'ord_homtg_0002': ['ord_homtg_0002', 'thread 2', 'thread 2', 'thread 2', 'thread two', 'group-formation thread', 'delivery thread'], 'lst_homtg_0001': ['lst_homtg_0001', 'thread 3', 'thread 3', 'thread 3', 'thread three', 'tiered-price thread', 'funds thread']}
THREAD_TERMS = {'ord_homtg_0001': ['personal care', 'lot', 'anti-counterfeit', 'verification code', 'CleanHome', 'group-purchase product'], 'ord_homtg_0002': ['join group', 'group formation', 'pickup point', 'group leader', 'refund', 'collection', 'group purchase', 'verification code', 'group-formation rate', 'evidence'], 'lst_homtg_0001': ['tiered group-purchase rebate', 'tiered price', 'rebate', 'recruit participants', 'group formation', 'group purchase', 'difference', 'return', 'received', 'funds']}
THREAD_EVIDENCE = {'ord_homtg_0001': ['product name', 'lot', 'proof of purchase', 'anti-counterfeit', 'invoice', 'verification code'], 'ord_homtg_0002': ['group-order number', 'group-formation progress', 'pickup point', 'pickup verification code', 'refund evidence', 'group leader'], 'lst_homtg_0001': ['group-order number', 'tiered price', 'rebate amount', 'rebate reference', 'difference', 'received']}
STAGE_EXPECTED_SERVERS = {0: ['ecommerce', 'delivery_logistics', 'credit_card'], 1: ['ecommerce', 'delivery_logistics', 'credit_card', 'listing_platform'], 2: ['ecommerce', 'notification_hub'], 3: ['ecommerce', 'notification_hub'], 4: ['ecommerce'], 6: ['delivery_logistics'], 7: ['email', 'ecommerce'], 9: ['ecommerce', 'delivery_logistics'], 10: ['credit_card'], 12: ['email'], 14: ['credit_card'], 15: ['delivery_logistics', 'weather'], 18: ['credit_card'], 20: ['credit_card']}
