BEGIN TRANSACTION;
INSERT INTO account_config (email, name, created_at) VALUES ('chen_yu@owner.example.com', 'Chen Yu', '2026-01-01T00:00:00+08:00');
INSERT OR IGNORE INTO folders (id, name, delimiter, flags_json, message_count, unread_count) VALUES (1, 'INBOX', '/', '[]', 8, 8);
INSERT INTO messages (folder_id, message_id, subject, from_addr, to_addr_json, cc_addr_json, bcc_addr_json, date, body_text, body_html, is_read, is_important, is_flagged, in_reply_to, references_header, headers_json, uid, size, created_at) VALUES (1, '<apt-renov-steady-quote-20260602@owner.example>', '【ShanghaiSteadyHome Renovation】Pudongrenovation details 68㎡ renovationrenovation details v1', 'ShanghaiSteadyHome Renovation projectrenovation details <contact@steady-renov.example.com>', '["chen_yu@owner.example.com"]', '[]', '[]', '2026-06-02T10:00:00+08:00', 'Chen Yurenovation details，

renovation detailsPudongrenovation details 68㎡ renovation details v1，renovation detailsprimary materials+renovation details+renovation details，renovation details ¥168,000（renovation detailschange orderrenovation details）。renovation detailsvalidrenovation details 2026-06-12。

renovation details，renovation details。

ShanghaiSteadyHome Renovation projectrenovation details renovation details / 138-0000-0001', NULL, 0, 1, 0, NULL, NULL, '{"X-Renov-Document-Type":"contractor_quote","X-Renov-Provider-Id":"provider_ca5a1f8412f2","X-Renov-Quote-Total":"168000","X-Renov-Valid-Until":"2026-06-12"}', NULL, 280, '2026-06-02T10:00:00+08:00');
INSERT INTO messages (folder_id, message_id, subject, from_addr, to_addr_json, cc_addr_json, bcc_addr_json, date, body_text, body_html, is_read, is_important, is_flagged, in_reply_to, references_header, headers_json, uid, size, created_at) VALUES (1, '<apt-renov-zhicheng-quote-20260603@owner.example>', '【Zhicheng Renovationrenovation details】Pudongrenovation details 68㎡ renovationrenovation details v1', 'Zhicheng Renovationrenovation details renovation details <info@zhicheng-zs.example.com>', '["chen_yu@owner.example.com"]', '[]', '[]', '2026-06-03T11:30:00+08:00', 'Chen Yurenovation details，

renovation details，renovation detailsPudongrenovation details 68㎡ renovation details v1，renovation details ¥139,800（renovation detailsprimary materials+renovation details+renovation details，renovation detailschange orderrenovation details）。renovation detailsvalidrenovation details 2026-06-13。

renovation details，renovation details。renovation details，renovation details。

Zhicheng Renovationrenovation details / renovation details renovation details / 138-0000-0003', NULL, 0, 1, 0, NULL, NULL, '{"X-Renov-Document-Type":"contractor_quote","X-Renov-Provider-Id":"provider_ff96cabffad8","X-Renov-Quote-Total":"139800","X-Renov-Valid-Until":"2026-06-13"}', NULL, 320, '2026-06-03T11:30:00+08:00');
INSERT INTO messages (folder_id, message_id, subject, from_addr, to_addr_json, cc_addr_json, bcc_addr_json, date, body_text, body_html, is_read, is_important, is_flagged, in_reply_to, references_header, headers_json, uid, size, created_at) VALUES (1, '<apt-renov-kuaijie-quote-20260603@owner.example>', '【renovation detailsrenovationrenovation details】Pudongrenovation details 68㎡ renovationrenovation details v1', 'renovation detailsrenovationrenovation details renovation details <quote@kuaijie-zx.example.com>', '["chen_yu@owner.example.com"]', '[]', '[]', '2026-06-03T15:45:00+08:00', 'Chen Yurenovation details，

renovation detailsPudongrenovation details 68㎡ renovation details v1，renovation details ¥118,500（renovation detailschange orderrenovation details，renovation details）。renovation detailsvalidrenovation details 2026-06-15。

renovation details 6 renovation details，renovation details 50 renovation details。renovation details。

renovation detailsrenovationrenovation details / renovation details / 138-0000-0008', NULL, 0, 0, 0, NULL, NULL, '{"X-Renov-Document-Type":"contractor_quote","X-Renov-Provider-Id":"provider_72db3d0f0914","X-Renov-Quote-Total":"118500","X-Renov-Valid-Until":"2026-06-15"}', NULL, 250, '2026-06-03T15:45:00+08:00');
INSERT INTO messages (folder_id, message_id, subject, from_addr, to_addr_json, cc_addr_json, bcc_addr_json, date, body_text, body_html, is_read, is_important, is_flagged, in_reply_to, references_header, headers_json, uid, size, created_at) VALUES (1, '<apt-renov-property-deposit-20260604@owner.example>', '【Huamu Gardenproperty management】renovationrenovation details/renovation details', 'Huamu Gardenproperty managementrenovation details <property@huamu-jiayuan.example.com>', '["chen_yu@owner.example.com"]', '[]', '[]', '2026-06-04T09:10:00+08:00', 'Chen Yurenovation details：

renovation details 18-2-1203 renovation detailsrenovationfilingrenovation detailsrenovationrenovation details ¥3,000（renovation details）renovation detailsfilingrenovation details ¥500。renovation details 2026-06-12 renovation detailsproperty managementrenovation details。

Huamu Gardenproperty management', NULL, 0, 1, 0, NULL, NULL, '{"X-Renov-Document-Type":"property_deposit_terms","X-Renov-Linked-Rule":"rule_88988b405ebb"}', NULL, 200, '2026-06-04T09:10:00+08:00');
INSERT INTO messages (folder_id, message_id, subject, from_addr, to_addr_json, cc_addr_json, bcc_addr_json, date, body_text, body_html, is_read, is_important, is_flagged, in_reply_to, references_header, headers_json, uid, size, created_at) VALUES (1, '<apt-renov-property-noise-reminder-20260606@owner.example>', '【Huamu Gardenproperty management】renovation detailsrenovationrenovation detailstimerenovation details', 'Huamu Gardenproperty managementrenovation details <property@huamu-jiayuan.example.com>', '["chen_yu@owner.example.com"]', '[]', '[]', '2026-06-06T11:45:00+08:00', 'Chen Yurenovation details：

renovation details《Shanghairenovation detailsproperty managementrenovation details》renovation details《renovationrenovation details》，renovation details 18:00-renovation details 08:00、renovation detailsnoiserenovation detailsrenovationrenovation details（renovation details、renovation details、renovation details）。renovation detailscontractorrenovation details。

renovation detailsnoiserenovation details，property managementrenovation detailsconstruction paused。

Huamu Gardenproperty managementrenovation details', NULL, 0, 0, 0, NULL, NULL, '{"X-Renov-Document-Type":"property_noise_rules","X-Renov-Linked-Rule":"rule_8a73ec5482a7,rule_09c615815311,rule_7eacedcab6bb"}', NULL, 260, '2026-06-06T11:45:00+08:00');
INSERT INTO messages (folder_id, message_id, subject, from_addr, to_addr_json, cc_addr_json, bcc_addr_json, date, body_text, body_html, is_read, is_important, is_flagged, in_reply_to, references_header, headers_json, uid, size, created_at) VALUES (1, '<apt-renov-supplier-cabinet-leadtime-20260612@owner.example>', '【Moduluxrenovation detailscabinet】renovation detailscabinetrenovation details', 'Moduluxrenovation detailscabinet renovation details <order@modulux-cab.example.com>', '["chen_yu@owner.example.com"]', '[]', '[]', '2026-06-12T15:00:00+08:00', 'Chen Yurenovation details：

renovation details RedApple renovation detailscabinet（renovation details mat_cab_004）renovation details，renovation detailssubstitutionrenovation details mat_cab_001 / mat_cab_002。renovation details，renovation details。

currentrenovation details 42 renovation details（renovation detailsinstallation）。

Modulux renovation details / 138-0000-0301', NULL, 0, 0, 0, NULL, NULL, '{"X-Renov-Document-Type":"material_stock_update","X-Renov-Linked-Material":"mat_cab_004","X-Renov-Substitute-Materials":"mat_cab_001,mat_cab_002"}', NULL, 240, '2026-06-12T15:00:00+08:00');
INSERT INTO messages (folder_id, message_id, subject, from_addr, to_addr_json, cc_addr_json, bcc_addr_json, date, body_text, body_html, is_read, is_important, is_flagged, in_reply_to, references_header, headers_json, uid, size, created_at) VALUES (1, '<apt-renov-supplier-tile-availability-20260609@owner.example>', '【renovation details】6 renovation details', 'renovation details renovation details <sales@taoyuan-tile.example.com>', '["chen_yu@owner.example.com"]', '[]', '[]', '2026-06-09T14:20:00+08:00', 'Chen Yurenovation details：

renovation details 6 renovation details 750x1500 / 800x800 / 900x1800 renovation details，deliveryrenovation details 7-10 renovation details。renovation details 138-0000-0501 renovation details。

renovation details renovation details', NULL, 0, 0, 0, NULL, NULL, '{"X-Renov-Document-Type":"material_price_notice","X-Renov-Linked-Provider":"provider_2a13da3f218b"}', NULL, 220, '2026-06-09T14:20:00+08:00');
INSERT INTO messages (folder_id, message_id, subject, from_addr, to_addr_json, cc_addr_json, bcc_addr_json, date, body_text, body_html, is_read, is_important, is_flagged, in_reply_to, references_header, headers_json, uid, size, created_at) VALUES (1, '<apt-renov-neighbor-forwarded-20260605@owner.example>', '【Huamu Gardenproperty managementrenovation details】renovation details', 'Huamu Gardenproperty managementrenovation details <property@huamu-jiayuan.example.com>', '["chen_yu@owner.example.com"]', '[]', '[]', '2026-06-05T17:30:00+08:00', 'Chen Yurenovation details：

renovation detailsrenovation，renovation details。renovation detailsrenovationrenovation details 24h renovation detailsproperty managementrenovation details（rule_87816f661958）。renovation details 4h，renovation details。

Huamu Gardenproperty management', NULL, 0, 0, 0, NULL, NULL, '{"X-Renov-Document-Type":"property_access_requirements","X-Renov-Linked-Rule":"rule_87816f661958"}', NULL, 240, '2026-06-05T17:30:00+08:00');
INSERT OR IGNORE INTO folders (id, name, delimiter, flags_json, message_count, unread_count) VALUES (2, 'Sent', '/', '["\\Sent"]', 0, 0);
INSERT OR IGNORE INTO folders (id, name, delimiter, flags_json, message_count, unread_count) VALUES (3, 'Drafts', '/', '["\\Drafts"]', 0, 0);

-- HANDBOOK_REMEDIATION_V113_email
DELETE FROM messages;
INSERT INTO messages(id,folder_id,message_id,subject,from_addr,to_addr_json,cc_addr_json,bcc_addr_json,date,body_text,body_html,is_read,is_important,is_flagged,in_reply_to,references_header,headers_json,uid,size,created_at) VALUES
 (1,1,'<msg-8205e4d74cc9@property.example>','renovationfilingmaterialsrenovation details（2026 renovation details）','Huamu Gardenproperty management <service@property.example>','["chen_yu@owner.example.com"]','[]','[]','2026-05-06T09:00:00+08:00','filingrenovation detailscontractorrenovation details、renovation details、electrical and plumbingrenovation details、noiserenovation detailsdebris removalrenovation details；renovation detailspassedrenovation details。',NULL,1,1,0,NULL,NULL,'{"topic":"filing"}',1,330,'2026-05-06T09:00:00+08:00'),
 (2,1,'<msg-c879d7f42693@steady.example>','68 renovation details','ShanghaiSteadyHome Renovation <contact@steady-renov.example.com>','["chen_yu@owner.example.com"]','[]','[]','2026-05-08T10:20:00+08:00','renovation details；renovation detailsmaterialsrenovation details，renovation detailsproperty managementrenovation details。',NULL,1,0,0,NULL,NULL,'{"provider":"provider_ca5a1f8412f2"}',2,310,'2026-05-08T10:20:00+08:00'),
 (3,1,'<msg-aac5b60fa22a@zhicheng.example>','renovation details：schedulerenovation details','Zhicheng Renovation <info@zhicheng-zs.example.com>','["chen_yu@owner.example.com"]','[]','[]','2026-05-09T14:10:00+08:00','renovation detailswindow；electrical and plumbingrenovation details、waterproofingrenovation details，renovation detailscontractrenovation detailsacceptance inspectionrecordrenovation details。',NULL,1,0,0,NULL,NULL,'{"provider":"provider_ff96cabffad8"}',3,300,'2026-05-09T14:10:00+08:00'),
 (4,1,'<msg-b8fa52c14fcc@hushang.example>','renovation details','renovation details <hello@hushang-jz.example.com>','["chen_yu@owner.example.com"]','[]','[]','2026-05-10T11:30:00+08:00','renovation details、projectrenovation details；renovation details，renovation detailsnoiserenovation details。',NULL,1,0,0,NULL,NULL,'{"provider":"provider_4782f62d7207"}',4,300,'2026-05-10T11:30:00+08:00'),
 (5,1,'<msg-aa15cb4be79d@cabinet.example>','U renovation detailscabinetrenovation details','Modulux renovation detailscabinet <design@modulux.example.com>','["chen_yu@owner.example.com"]','[]','[]','2026-05-12T09:40:00+08:00','renovation details、renovation details、renovation details；hardwarerenovation details。',NULL,1,0,0,NULL,NULL,'{"topic":"cabinet"}',5,310,'2026-05-12T09:40:00+08:00'),
 (6,1,'<msg-232ba2eca9c9@paint.example>','renovation details VOC renovation details','renovation details <service@yixi-paint.example.com>','["chen_yu@owner.example.com"]','[]','[]','2026-05-13T15:05:00+08:00','renovation details VOC renovation details；renovation details、renovation detailsventilationrenovation details。',NULL,1,0,0,NULL,NULL,'{"topic":"paint"}',6,320,'2026-05-13T15:05:00+08:00'),
 (7,1,'<msg-626477b1d346@tile.example>','renovation details','renovation details <showroom@taoyuan-tile.example.com>','["chen_yu@owner.example.com"]','[]','[]','2026-05-14T13:20:00+08:00','750×1500 renovation details，tile installationrenovation details、renovation details、renovation details。',NULL,1,0,0,NULL,NULL,'{"topic":"tile"}',7,300,'2026-05-14T13:20:00+08:00'),
 (8,1,'<msg-6b92d940f4bb@inspect.example>','renovation detailsrenovationrenovation detailsacceptance inspectionrenovation details','renovation details <advice@yanjing-inspect.example.com>','["chen_yu@owner.example.com"]','[]','[]','2026-05-15T10:00:00+08:00','renovation details、electrical and plumbingrenovation details、water-retentionrenovation details 48 renovation details、tile installationrenovation detailsacceptance inspection。',NULL,1,1,0,NULL,NULL,'{"topic":"inspection"}',8,340,'2026-05-15T10:00:00+08:00'),
 (9,1,'<msg-4f9893949d9b@property.example>','renovation detailsnoiserenovation details','Huamu Gardenproperty management <service@property.example>','["chen_yu@owner.example.com"]','[]','[]','2026-05-16T09:10:00+08:00','renovation details 09:00-12:00、14:00-18:00 renovation detailsnoiserenovation details；renovation details。',NULL,1,1,0,NULL,NULL,'{"rule":"noise"}',9,290,'2026-05-16T09:10:00+08:00'),
 (10,1,'<msg-5af8311cd562@waste.example>','renovationdebris removalrenovation details','renovation detailsdebris removal <quote@qingfeng-waste.example.com>','["chen_yu@owner.example.com"]','[]','[]','2026-05-18T08:50:00+08:00','renovation details，property managementrenovation details。',NULL,1,0,0,NULL,NULL,'{"topic":"waste"}',10,260,'2026-05-18T08:50:00+08:00'),
 (11,1,'<msg-222651ce6f49@floor.example>','renovation detailsinstallationrenovation details','Greenwood renovation details <tech@greenwood.example.com>','["chen_yu@owner.example.com"]','[]','[]','2026-05-19T16:00:00+08:00','renovation details，renovation detailsinstallation。',NULL,1,0,0,NULL,NULL,'{"topic":"floor"}',11,250,'2026-05-19T16:00:00+08:00'),
 (12,1,'<msg-36777a9c28fa@electric.example>','renovation detailselectrical and plumbingrenovation details','renovation detailselectrical and plumbing <service@lutong.example.com>','["chen_yu@owner.example.com"]','[]','[]','2026-05-21T11:15:00+08:00','renovation details、residual-current protection、renovation details、renovation details；renovation details。',NULL,1,1,0,NULL,NULL,'{"topic":"electrical"}',12,330,'2026-05-21T11:15:00+08:00'),
 (13,1,'<msg-a0153269d91f@waterproof.example>','water-retentionrenovation details','renovation detailswaterproofingrenovation details <service@shuimi.example.com>','["chen_yu@owner.example.com"]','[]','[]','2026-05-22T14:40:00+08:00','renovation detailswater-retention 48 renovation details，renovation detailsproperty managementrenovation details；renovation details。',NULL,1,1,0,NULL,NULL,'{"topic":"waterproof"}',13,330,'2026-05-22T14:40:00+08:00'),
 (14,1,'<msg-5e0f9e58a3f2@lighting.example>','lightingrenovation details','renovation details <design@light.example.com>','["chen_yu@owner.example.com"]','[]','[]','2026-05-24T10:30:00+08:00','renovation details、renovation details、renovation details，installationrenovation details。',NULL,1,0,0,NULL,NULL,'{"topic":"lighting"}',14,260,'2026-05-24T10:30:00+08:00'),
 (15,1,'<msg-ec10c18458e2@community.example>','renovation detailsmaterialsrenovation details','Huamu Gardenproperty management <service@property.example>','["chen_yu@owner.example.com"]','[]','[]','2026-05-26T09:25:00+08:00','renovation detailsmaterialsrenovation details，renovation detailsacceptance inspectionrenovation details。',NULL,1,0,0,NULL,NULL,'{"rule":"elevator"}',15,260,'2026-05-26T09:25:00+08:00'),
 (16,1,'<msg-9e003904ebb5@clean.example>','renovation detailscleaningscoperenovation details','renovation details <service@clean.example.com>','["chen_yu@owner.example.com"]','[]','[]','2026-05-27T13:10:00+08:00','renovation detailscleaningrenovation details，renovation detailsinstallationrenovation detailscorrective workrenovation details。',NULL,1,0,0,NULL,NULL,'{"topic":"cleaning"}',16,280,'2026-05-27T13:10:00+08:00'),
 (17,1,'<msg-6730a1690db8@iaq.example>','renovation details','renovation details <booking@iaq.example.com>','["chen_yu@owner.example.com"]','[]','[]','2026-05-29T10:00:00+08:00','renovation detailsrequirementrenovation details；renovation details TVOC，renovation detailsvalidrenovation detailswindow。',NULL,1,1,0,NULL,NULL,'{"topic":"iaq"}',17,310,'2026-05-29T10:00:00+08:00'),
 (18,1,'<msg-99a739308bc0@family.example>','renovation detailsdaterenovation details','renovation details <family@owner.example.com>','["chen_yu@owner.example.com"]','[]','[]','2026-05-31T18:00:00+08:00','renovation details 8 renovation details 8 renovation detailswindow，renovation detailsacceptance inspection、ventilationrenovation detailscorrective workrenovation details。',NULL,1,1,0,NULL,NULL,'{"topic":"movein"}',18,280,'2026-05-31T18:00:00+08:00');
UPDATE folders SET message_count=(SELECT COUNT(*) FROM messages WHERE folder_id=folders.id), unread_count=(SELECT COUNT(*) FROM messages WHERE folder_id=folders.id AND is_read=0);

COMMIT;
