-- Generated delivery_logistics seed for floor_total_reno_v4_30d
BEGIN;
INSERT INTO shipments (shipment_id, user_id, tracking_no, carrier, service_level, status, sender_json, recipient_json, weight_kg, dimensions_json, declared_value_minor, fee_minor, created_at, eta_date, scheduled_pickup_at, updated_at, cancel_reason) VALUES ('shp_qflr_0001', 'usr_lai_xu', 'SF7584520001CN', 'translated business text', 'express', 'delivered', '{"recipient": "Chengduunderfloor heatingflooringtranslated business textwarehouse", "phone": "4008100001", "province": "translated business text", "city": "Chengdu", "district": "translated business text", "detail": "translated business text 12 translated business text"}', '{"recipient": "Lai Xu", "phone": "13900000000", "province": "translated business text", "city": "Chengdu", "district": "translated business text", "detail": "translated business text 2000 translated business text 2207", "postal_code": "610213"}', 612.0, '{"length_cm": 120, "width_cm": 80, "height_cm": 110}', 3900000, 0, '2026-06-11T09:00:00+08:00', '2026-06-14', NULL, '2026-06-14T15:50:00+08:00', NULL);
INSERT INTO shipments (shipment_id, user_id, tracking_no, carrier, service_level, status, sender_json, recipient_json, weight_kg, dimensions_json, declared_value_minor, fee_minor, created_at, eta_date, scheduled_pickup_at, updated_at, cancel_reason) VALUES ('shp_qflr_0002', 'usr_lai_xu', 'YTOQFLR5520002CN', 'translated business text', 'standard', 'in_transit', '{"recipient": "Chengduunderfloor heatingdetectdocumentscenter", "phone": "4008100002", "province": "translated business text", "city": "Chengdu", "district": "translated business text", "detail": "translated business textdetecttranslated business text 5 translated business text"}', '{"recipient": "Lai Xu", "phone": "13900000000", "province": "translated business text", "city": "Chengdu", "district": "translated business text", "detail": "translated business text 2000 translated business text 2207", "postal_code": "610213"}', 32.4, '{"length_cm": 76, "width_cm": 48, "height_cm": 31}', 99600, 800, '2026-06-12T08:40:00+08:00', '2026-06-16', NULL, '2026-06-14T19:20:00+08:00', NULL);
INSERT INTO shipment_events (event_id, shipment_id, at, location, status_code, description) VALUES ('evt_qflr_d1', 'shp_qflr_0001', '2026-06-14T15:50:00+08:00', 'Chengdutranslated business text', 'delivered', 'coil、levelingtranslated business textandflooringtranslated business textreachprojectaddress，Lai Xusigntranslated business text；deliverytranslated business textequalspressure testorflooring installationacceptance');
INSERT INTO shipment_events (event_id, shipment_id, at, location, status_code, description) VALUES ('evt_qflr_d2', 'shp_qflr_0002', '2026-06-14T19:20:00+08:00', 'Chengdutranslated business text', 'in_transit', 'thermostattranslated business text、measurementtoolandreinspectiondocumentsalreadysendtranslated business textprojectaddress');
INSERT INTO address_book (address_id, user_id, label, recipient, phone, province, city, district, detail, postal_code, is_default) VALUES ('abk_qflr_1', 'usr_lai_xu', 'translated business textunderfloor heatingmaterialstranslated business text', 'Lai Xu（constructionmaterialssigntranslated business text）', '02863072416', 'translated business text', 'Chengdu', 'translated business text', 'translated business text 2000 translated business textnexttranslated business text', '610213', 1);
INSERT INTO status_subscriptions (subscription_id, shipment_id, channel, target, active, created_at) VALUES ('sublog_qflr_1', 'shp_qflr_0002', 'email', 'lai.xu.reno4@gmail.com', 1, '2026-06-14T20:05:00+08:00');
INSERT INTO _counters (key,value) VALUES ('shipment_seq',2),('event_seq',2),('pickup_seq',0),('ticket_seq',0),('subscription_seq',1);
COMMIT;

BEGIN;
UPDATE shipments SET created_at='2026-06-11T09:00:00+08:00',updated_at='2026-06-14T15:50:00+08:00',eta_date='2026-06-14' WHERE shipment_id='shp_qflr_0001';
UPDATE shipments SET created_at='2026-06-12T08:40:00+08:00',updated_at='2026-06-14T19:20:00+08:00',eta_date='2026-06-14' WHERE shipment_id='shp_qflr_0002';
UPDATE shipment_events SET at='2026-06-14T15:50:00+08:00',description='coil、manifoldandlevelingmaterialstranslated business textnumbersigntranslated business text；not yetcompletepressure test、moisture contentorflooring installationacceptance' WHERE event_id='evt_qflr_d1';
UPDATE shipment_events SET at='2026-06-14T19:20:00+08:00',location='Chengdutranslated business text',description='thermostattranslated business text、flooringtranslated business textandtwo-meter straightedgereinspectiondocumentscompleteintranslated business text，pendingtranslated business text' WHERE event_id='evt_qflr_d2';
COMMIT;

-- 2026-07-30 cross-service richness remediation: reviewed material and instrument logistics history.
BEGIN;
INSERT INTO shipments (shipment_id,user_id,tracking_no,carrier,service_level,status,sender_json,recipient_json,weight_kg,dimensions_json,declared_value_minor,fee_minor,created_at,eta_date,scheduled_pickup_at,updated_at,cancel_reason) VALUES
 ('shp_qflr_oak_swatches','usr_lai_xu','JDCD02861594CN','translated business text','standard','delivered','{"recipient":"Chengduflooringtranslated business text","phone":"4008281530","province":"translated business text","city":"Chengdu","district":"translated business text","detail":"translated business text 3 translated business text"}','{"recipient":"Lai Xu","phone":"13900000000","province":"translated business text","city":"Chengdu","district":"translated business text","detail":"translated business text 2000 translated business textbeforetranslated business text","postal_code":"610213"}',4.1,'{"length_cm":48,"width_cm":34,"height_cm":11}',22800,1000,'2026-02-02T10:08:00+08:00','2026-02-04',NULL,'2026-02-04T14:02:00+08:00',NULL),
 ('shp_qflr_return_controller','usr_lai_xu','ZTO8P4R731605CN','intranslated business textcourier','standard','returned','{"recipient":"Lai Xu","phone":"13900000000","province":"translated business text","city":"Chengdu","district":"translated business text","detail":"translated business text 2000 translated business text"}','{"recipient":"Chengdutranslated business text","phone":"4008124678","province":"translated business text","city":"Chengdu","district":"translated business text","detail":"translated business text 62 translated business text","postal_code":"610041"}',1.9,'{"length_cm":31,"width_cm":23,"height_cm":15}',12600,1100,'2026-01-24T09:30:00+08:00','2026-01-26','2026-01-24T14:40:00+08:00','2026-01-26T16:32:00+08:00',NULL),
 ('shp_qflr_pressure_case','usr_lai_xu','EMS2076138495CN','intranslated business text EMS','express','delivered','{"recipient":"Chengdutranslated business textdetectcenter","phone":"4008139952","province":"translated business text","city":"Chengdu","district":"translated business text","detail":"translated business textintranslated business text 18 translated business text"}','{"recipient":"Lai Xu","phone":"13900000000","province":"translated business text","city":"Chengdu","district":"translated business text","detail":"translated business text 2000 translated business textbeforetranslated business text","postal_code":"610213"}',3.6,'{"length_cm":42,"width_cm":29,"height_cm":19}',156000,1600,'2026-03-17T11:16:00+08:00','2026-03-19',NULL,'2026-03-19T10:26:00+08:00',NULL),
 ('shp_qflr_skirting_samples','usr_lai_xu','YDKC580271946CN','translated business textreachcourier','standard','delivered','{"recipient":"translated business textconvergematerialstranslated business text","phone":"4008291642","province":"translated business text","city":"translated business text","district":"translated business text","detail":"translated business textmaterialstranslated business text 5 translated business text"}','{"recipient":"Lai Xu","phone":"13900000000","province":"translated business text","city":"Chengdu","district":"translated business text","detail":"translated business text 2000 translated business text","postal_code":"610213"}',5.3,'{"length_cm":72,"width_cm":24,"height_cm":17}',29400,900,'2026-04-13T16:22:00+08:00','2026-04-16',NULL,'2026-04-16T12:35:00+08:00',NULL),
 ('shp_qflr_insulation_docs','usr_lai_xu','SFCQ731962084CN','translated business text','express','delivered','{"recipient":"translated business textmaterialsdetecttranslated business text","phone":"4008165407","province":"translated business text","city":"translated business text","district":"translated business text","detail":"translated business text 12 translated business text"}','{"recipient":"Lai Xu","phone":"13900000000","province":"translated business text","city":"Chengdu","district":"translated business text","detail":"translated business text 2000 translated business text 2207","postal_code":"610213"}',0.9,'{"length_cm":33,"width_cm":25,"height_cm":6}',1800,1400,'2026-06-01T08:42:00+08:00','2026-06-03',NULL,'2026-06-03T09:48:00+08:00',NULL),
 ('shp_qflr_threshold_strip','usr_lai_xu','DBCD401758296CN','translated business textcourier','in_home','exception','{"recipient":"Chengdutranslated business textconvergewarehouse","phone":"4008179023","province":"translated business text","city":"Chengdu","district":"translated business text","detail":"translated business text 11 translated business text"}','{"recipient":"Lai Xu","phone":"13900000000","province":"translated business text","city":"Chengdu","district":"translated business text","detail":"translated business text 2000 translated business textmaterialstranslated business text","postal_code":"610213"}',9.8,'{"length_cm":210,"width_cm":16,"height_cm":14}',26800,2200,'2026-06-03T13:05:00+08:00','2026-06-05',NULL,'2026-06-05T11:34:00+08:00',NULL),
 ('shp_qflr_controller_transformer','usr_lai_xu','JDCF620374815CN','translated business text','standard','delivered','{"recipient":"translated business textwarehouse","phone":"4008241956","province":"translated business text","city":"Chengdu","district":"translated business text","detail":"translated business text 7 translated business text"}','{"recipient":"Lai Xu","phone":"13900000000","province":"translated business text","city":"Chengdu","district":"translated business text","detail":"translated business text 2000 translated business text 2207","postal_code":"610213"}',3.4,'{"length_cm":41,"width_cm":28,"height_cm":15}',51200,0,'2026-06-04T17:28:00+08:00','2026-06-06',NULL,'2026-06-06T13:19:00+08:00',NULL),
 ('shp_qflr_floor_protection','usr_lai_xu','STOC792641053CN','translated business textcourier','standard','delivered','{"recipient":"Chengdutranslated business textmaterialstranslated business text","phone":"4008195302","province":"translated business text","city":"Chengdu","district":"translated business text","detail":"translated business textmaterialstranslated business text 8 translated business text"}','{"recipient":"Lai Xu","phone":"13900000000","province":"translated business text","city":"Chengdu","district":"translated business text","detail":"translated business text 2000 translated business text","postal_code":"610213"}',14.2,'{"length_cm":79,"width_cm":42,"height_cm":31}',34600,800,'2026-06-06T09:06:00+08:00','2026-06-08',NULL,'2026-06-08T17:22:00+08:00',NULL),
 ('shp_qflr_label_lamp','usr_lai_xu','YZPD471825306CN','translated business text','economy','in_transit','{"recipient":"translated business textproject warehousetranslated business text","phone":"4008134069","province":"translated business text","city":"Chengdu","district":"translated business text","detail":"translated business text 12 translated business text"}','{"recipient":"Lai Xu","phone":"13900000000","province":"translated business text","city":"Chengdu","district":"translated business text","detail":"translated business text 2000 translated business textmaterialstranslated business text","postal_code":"610213"}',2.0,'{"length_cm":35,"width_cm":24,"height_cm":12}',9200,600,'2026-06-10T12:31:00+08:00','2026-06-15',NULL,'2026-06-14T07:12:00+08:00',NULL),
 ('shp_qflr_flooring_pallet','usr_lai_xu','KYCD681935247CN','translated business text','express','out_for_delivery','{"recipient":"translated business textwood flooringtranslated business textwarehouse","phone":"4008256031","province":"translated business text","city":"translated business text","district":"translated business text","detail":"translated business text 4 translated business text"}','{"recipient":"Lai Xu","phone":"13900000000","province":"translated business text","city":"Chengdu","district":"translated business text","detail":"translated business text 2000 translated business text","postal_code":"610213"}',524.0,'{"length_cm":190,"width_cm":115,"height_cm":128}',428000,6200,'2026-06-11T07:16:00+08:00','2026-06-14',NULL,'2026-06-14T10:03:00+08:00',NULL);
INSERT INTO shipment_events (event_id,shipment_id,at,location,status_code,description) VALUES
 ('evt_qflr_swatches_pickup','shp_qflr_oak_swatches','2026-02-02T13:18:00+08:00','Chengdutranslated business text','picked_up','translated business textoak、translated business textandtranslated business text，outsidetranslated business textmust nottranslated business textconfirmbatch'),
 ('evt_qflr_swatches_delivered','shp_qflr_oak_swatches','2026-02-04T14:02:00+08:00','Chengdutranslated business text','delivered','translated business textbeforetranslated business text，Lai Xutranslated business text；translated business textsigntranslated business textequalsflooring installationtranslated business textcomplete'),
 ('evt_qflr_controller_collected','shp_qflr_return_controller','2026-01-24T14:52:00+08:00','Chengdutranslated business text','picked_up','previoustranslated business textprojecttranslated business textcompletetranslated business text，andtranslated business textthermostattranslated business textseparaterecord'),
 ('evt_qflr_controller_returned','shp_qflr_return_controller','2026-01-26T16:32:00+08:00','translated business text','returned','translated business textsigntranslated business textandtranslated business text，not yettranslated business textthisprojectorderorfunds'),
 ('evt_qflr_gauge_departed','shp_qflr_pressure_case','2026-03-17T16:48:00+08:00','Chengdutranslated business text','in_transit','translated business textthentranslated business textnumberpressuretranslated business texttable、translated business textandcredentialtranslated business text'),
 ('evt_qflr_gauge_delivered','shp_qflr_pressure_case','2026-03-19T10:26:00+08:00','translated business textbeforetranslated business text','delivered','equipmenttranslated business textroundtranslated business textdetecttranslated business text，translated business textresulttranslated business textanypressure holdconclusion'),
 ('evt_qflr_skirting_sort','shp_qflr_skirting_samples','2026-04-14T08:04:00+08:00','translated business text','in_transit','baseboard、doorwaytrim stripandtranslated business textcompletetranslated business text，not yettranslated business textwood flooringtranslated business textmaterials'),
 ('evt_qflr_skirting_delivered','shp_qflr_skirting_samples','2026-04-16T12:35:00+08:00','translated business text','delivered','convergetranslated business text，Lai Xusigntranslated business text；quantitytranslated business textandtranslated business text'),
 ('evt_qflr_docs_collected','shp_qflr_insulation_docs','2026-06-01T15:22:00+08:00','translated business text','picked_up','BW-6F translated business textdetecttranslated business textandtranslated business textbatchdocumentstranslated business text'),
 ('evt_qflr_docs_delivered','shp_qflr_insulation_docs','2026-06-03T09:48:00+08:00','Chengdutranslated business text','delivered','filetranslated business textdeliverythistranslated business text，documentscomplete；does not replaceon-sitetranslated business textcheck'),
 ('evt_qflr_strip_exception','shp_qflr_threshold_strip','2026-06-05T08:06:00+08:00','Chengdutranslated business textintranslated business text','exception','translated business textitemsoutsidetranslated business text，translated business textandtranslated business textchecktranslated business texttabletranslated business text'),
 ('evt_qflr_strip_held','shp_qflr_threshold_strip','2026-06-05T11:34:00+08:00','Chengdutranslated business text','exception','trim striptranslated business text，not yetsigntranslated business textnot yetconfirmtranslated business text'),
 ('evt_qflr_transformer_sort','shp_qflr_controller_transformer','2026-06-05T08:42:00+08:00','Chengdutranslated business text','in_transit','thermostattranslated business textchunkandtranslated business textcompletetranslated business text，translated business textwithouttranslated business text'),
 ('evt_qflr_transformer_delivered','shp_qflr_controller_transformer','2026-06-06T13:19:00+08:00','translated business text','delivered','translated business text，not yettranslated business textpressure testrecord'),
 ('evt_qflr_protection_pickup','shp_qflr_floor_protection','2026-06-06T16:26:00+08:00','Chengdutranslated business text','picked_up','translated business text、translated business textandtranslated business text'),
 ('evt_qflr_protection_delivered','shp_qflr_floor_protection','2026-06-08T17:22:00+08:00','translated business text','delivered','translated business textmaterialstranslated business textthentranslated business text，constructiontranslated business textpendingtranslated business textarea'),
 ('evt_qflr_lamp_departed','shp_qflr_label_lamp','2026-06-11T08:02:00+08:00','Chengdutranslated business text','in_transit','translated business textcoillabeltranslated business textandtranslated business textproject warehousetranslated business text'),
 ('evt_qflr_lamp_hub','shp_qflr_label_lamp','2026-06-14T07:12:00+08:00','Chengdutranslated business text','in_transit','translated business textreachtranslated business text，expectednextitemstranslated business text，currentnot yettranslated business text'),
 ('evt_qflr_pallet_departed','shp_qflr_flooring_pallet','2026-06-11T13:44:00+08:00','translated business text','picked_up','wood flooringtranslated business text、translated business textandtranslated business textcheckthentranslated business text'),
 ('evt_qflr_pallet_out','shp_qflr_flooring_pallet','2026-06-14T10:03:00+08:00','Chengdutranslated business text','out_for_delivery','translated business textwaittranslated business textwindow，translated business textnot yettranslated business textorreconcilebatch');
INSERT INTO address_book (address_id,user_id,label,recipient,phone,province,city,district,detail,postal_code,is_default) VALUES
 ('abk_qflr_controller_room','usr_lai_xu','Chengdutranslated business text','translated business text','02861472830','translated business text','Chengdu','translated business text','translated business text 62 translated business text','610041',0),
 ('abk_qflr_meter_center','usr_lai_xu','pressuretranslated business texttabletranslated business textcenter','translated business text','02862051974','translated business text','Chengdu','translated business text','translated business textintranslated business text 18 translated business textinstrumentwindow','610072',0),
 ('abk_qflr_floor_lab','usr_lai_xu','wood flooringtranslated business text','translated business text','02861830625','translated business text','Chengdu','translated business text','translated business text 3 translated business text','611730',0),
 ('abk_qflr_recycle','usr_lai_xu','translated business text','translated business text','02861589720','translated business text','Chengdu','translated business text','translated business textcategorytranslated business text','610213',0),
 ('abk_qflr_bigcargo','usr_lai_xu','translated business text','translated business textmaterialstranslated business text','02862341059','translated business text','Chengdu','translated business text','translated business text 2000 translated business text','610213',0);
INSERT INTO issue_tickets (ticket_id,shipment_id,issue_type,description,status,opened_at,expected_response_date,resolved_at) VALUES
 ('tkt_qflr_strip_bend','shp_qflr_threshold_strip','damaged','translated business texttrim stripoutsidetranslated business text，translated business textconfirmtabletranslated business textandtranslated business text。','in_review','2026-06-05T11:48:00+08:00','2026-06-07',NULL),
 ('tkt_qflr_pallet_slot','shp_qflr_flooring_pallet','delivery_failed','translated business textinitialtranslated business textreachtranslated business textstilltranslated business text，waitmaterialstranslated business textconfirmtranslated business text。','open','2026-06-14T10:11:00+08:00','2026-06-15',NULL),
 ('tkt_qflr_swatches_locker','shp_qflr_oak_swatches','wrong_address','translated business textthentranslated business textbeforetranslated business text，andtranslated business textLai Xusigntranslated business text。','resolved','2026-02-04T11:20:00+08:00','2026-02-05','2026-02-04T14:02:00+08:00'),
 ('tkt_qflr_transformer_terminal','shp_qflr_controller_transformer','missing_item','translated business textsendtranslated business textpressuretranslated business textnot yettranslated business text，translated business textwarehousetranslated business text；alreadydeliverytranslated business textchunkkeepnot yettranslated business text。','closed','2026-06-06T14:24:00+08:00','2026-06-08','2026-06-08T09:18:00+08:00');
INSERT INTO status_subscriptions (subscription_id,shipment_id,channel,target,active,created_at) VALUES
 ('sublog_qflr_pallet','shp_qflr_flooring_pallet','sms','13900000000',1,'2026-06-11T07:23:00+08:00'),
 ('sublog_qflr_strip','shp_qflr_threshold_strip','email','lai.xu.reno4@gmail.com',1,'2026-06-03T13:12:00+08:00'),
 ('sublog_qflr_gauge','shp_qflr_pressure_case','email','lai.xu.reno4@gmail.com',0,'2026-03-17T11:22:00+08:00'),
 ('sublog_qflr_lamp','shp_qflr_label_lamp','webhook','https://project.example/hooks/floor-label-lamp',1,'2026-06-10T12:39:00+08:00'),
 ('sublog_qflr_protection','shp_qflr_floor_protection','sms','13900000000',0,'2026-06-06T09:14:00+08:00');
UPDATE _counters SET value=12 WHERE key='shipment_seq';
UPDATE _counters SET value=22 WHERE key='event_seq';
UPDATE _counters SET value=6 WHERE key='subscription_seq';
UPDATE _counters SET value=4 WHERE key='ticket_seq';
COMMIT;

-- Recipient records use the checkout address; handoff locations remain shipment-event facts.
BEGIN;
UPDATE shipments SET recipient_json='{"recipient":"Lai Xu","phone":"13900000000","province":"translated business text","city":"Chengdu","district":"translated business text","detail":"translated business text 2000 translated business text 2207","postal_code":"610213"}' WHERE shipment_id='shp_qflr_oak_swatches';
UPDATE shipments SET recipient_json='{"recipient":"Lai Xu","phone":"13900000000","province":"translated business text","city":"Chengdu","district":"translated business text","detail":"translated business text 2000 translated business text 2207","postal_code":"610213"}' WHERE shipment_id='shp_qflr_return_controller';
UPDATE shipments SET recipient_json='{"recipient":"Lai Xu","phone":"13900000000","province":"translated business text","city":"Chengdu","district":"translated business text","detail":"translated business text 2000 translated business text 2207","postal_code":"610213"}' WHERE shipment_id='shp_qflr_pressure_case';
UPDATE shipments SET recipient_json='{"recipient":"Lai Xu","phone":"13900000000","province":"translated business text","city":"Chengdu","district":"translated business text","detail":"translated business text 2000 translated business text 2207","postal_code":"610213"}' WHERE shipment_id='shp_qflr_skirting_samples';
UPDATE shipments SET recipient_json='{"recipient":"Lai Xu","phone":"13900000000","province":"translated business text","city":"Chengdu","district":"translated business text","detail":"translated business text 2000 translated business text 2207","postal_code":"610213"}' WHERE shipment_id='shp_qflr_insulation_docs';
UPDATE shipments SET recipient_json='{"recipient":"Lai Xu","phone":"13900000000","province":"translated business text","city":"Chengdu","district":"translated business text","detail":"translated business text 2000 translated business text 2207","postal_code":"610213"}' WHERE shipment_id='shp_qflr_threshold_strip';
UPDATE shipments SET recipient_json='{"recipient":"Lai Xu","phone":"13900000000","province":"translated business text","city":"Chengdu","district":"translated business text","detail":"translated business text 2000 translated business text 2207","postal_code":"610213"}' WHERE shipment_id='shp_qflr_controller_transformer';
UPDATE shipments SET recipient_json='{"recipient":"Lai Xu","phone":"13900000000","province":"translated business text","city":"Chengdu","district":"translated business text","detail":"translated business text 2000 translated business text 2207","postal_code":"610213"}' WHERE shipment_id='shp_qflr_floor_protection';
UPDATE shipments SET recipient_json='{"recipient":"Lai Xu","phone":"13900000000","province":"translated business text","city":"Chengdu","district":"translated business text","detail":"translated business text 2000 translated business text 2207","postal_code":"610213"}' WHERE shipment_id='shp_qflr_label_lamp';
UPDATE shipments SET recipient_json='{"recipient":"Lai Xu","phone":"13900000000","province":"translated business text","city":"Chengdu","district":"translated business text","detail":"translated business text 2000 translated business text 2207","postal_code":"610213"}' WHERE shipment_id='shp_qflr_flooring_pallet';
COMMIT;
