-- Generated email seed for community_household_groupbuy_30d
BEGIN;
INSERT INTO account_config (id, email, name, created_at) VALUES (1, 'xie.lin.home@gmail.com', 'Evelyn Xie', '2021-09-01T00:00:00Z');
INSERT INTO folders (id,name) VALUES (1,'INBOX'),(2,'Sent'),(3,'Drafts'),(4,'Trash'),(5,'Spam');
INSERT INTO messages (id, folder_id, message_id, subject, from_addr, to_addr_json, date, body_text, is_read, is_important, headers_json, size, created_at) VALUES (1, 1, '<homtg-o1@mall.cn>', 'Order confirmation：CleanHomebusiness labelset(group purchasebusiness label)', 'official mall <order@mall.cn>', '["xie.lin.home@gmail.com"]', '2026-06-15T11:25:00Z', 'Your order ord_homtg_0001 payment succeeded。retain the authentication number and receipt for verification。', 1, 0, '{}', 220, '2026-06-15T11:25:00Z');
INSERT INTO messages (id, folder_id, message_id, subject, from_addr, to_addr_json, date, body_text, is_read, is_important, headers_json, size, created_at) VALUES (2, 1, '<homtg-o2@mall.cn>', 'Order confirmation：community household-goods group delivery line', 'official mall <order@mall.cn>', '["xie.lin.home@gmail.com"]', '2026-06-15T02:10:00Z', 'Your order ord_homtg_0002 payment succeeded，will ship to your designated forwarding warehouse。', 1, 0, '{}', 220, '2026-06-15T02:10:00Z');
INSERT INTO messages (id, folder_id, message_id, subject, from_addr, to_addr_json, date, body_text, is_read, is_important, headers_json, size, created_at) VALUES (3, 1, '<homtg-fwd@forward.com>', '【Jiying forwarding warehouse】business labelparcel arrived at warehouse，confirm shipping method', 'forwarding warehouse <service@forward.com>', '["xie.lin.home@gmail.com"]', '2026-06-15T12:00:00Z', 'Dear XL2099 member：your parcel will arrive at the warehouse。Notice：contains regulated/shipping method for powered items is restricted by policy，confirm declaration details and shipping method before dispatch。', 0, 1, '{}', 220, '2026-06-15T12:00:00Z');
INSERT INTO messages (id, folder_id, message_id, subject, from_addr, to_addr_json, date, body_text, is_read, is_important, headers_json, size, created_at) VALUES (4, 1, '<20260618-tax@cn-home-refund.com>', '【Urgent】community spending rebatepending claim，business label48hours click to verify your bank card', 'community spending rebate center <noreply@cn-home-refund.com>', '["xie.lin.home@gmail.com"]', '2026-06-18T15:40:00Z', 'business labelcommunity spending rebate ¥200 pending claim。Please within 48 business labelcardbusiness label，and pay ¥15 processing feebusiness label，expires if late。
http://cn-home-refund.com/claim?id=XL9472', 0, 0, '{"x-warning": "suspicious-domain"}', 220, '2026-06-18T15:40:00Z');
UPDATE folders SET message_count=(SELECT COUNT(*) FROM messages WHERE messages.folder_id=folders.id), unread_count=(SELECT COUNT(*) FROM messages WHERE messages.folder_id=folders.id AND messages.is_read=0);
INSERT INTO _counters (key,value) VALUES ('msg_seq',4);
COMMIT;
