-- Generated notification_hub seed for central_ac_install_30d
BEGIN;
INSERT INTO official_accounts (account_id, name, category, description) VALUES ('oa_iscac_customs', 'appliance delivery and installation rules', 'service', 'large-appliance delivery, installation, and on-site acceptance rules');
INSERT INTO official_account_subscriptions (user_id, account_id, subscribed_at) VALUES ('usr_luo_wei', 'oa_iscac_customs', '2026-06-06T00:00:00Z');
INSERT INTO official_accounts (account_id, name, category, description) VALUES ('oa_iscac_brand', 'official delivery, installation, and after-sales service', 'shopping_service', 'official warranty, credentials, and overseas after-sales notes');
INSERT INTO official_account_subscriptions (user_id, account_id, subscribed_at) VALUES ('usr_luo_wei', 'oa_iscac_brand', '2026-06-06T00:00:00Z');
INSERT INTO official_accounts (account_id, name, category, description) VALUES ('oa_iscac_card', 'CMB credit card', 'finance', 'statement, foreign-currency transaction, and card-safety alerts');
INSERT INTO official_account_subscriptions (user_id, account_id, subscribed_at) VALUES ('usr_luo_wei', 'oa_iscac_card', '2026-06-06T00:00:00Z');
INSERT INTO official_account_posts (post_id, account_id, title, summary, url, published_at) VALUES ('post_iscac_1', 'oa_iscac_customs', 'large-appliance delivery acceptance and rescheduling rules', 'reschedule a home visit for severe weather or unsuitable site conditions；service records retain the original case number and appointment history。', 'https://service.example/delivery-installation', '2026-06-08');
INSERT INTO official_account_posts (post_id, account_id, title, summary, url, published_at) VALUES ('post_iscac_2', 'oa_iscac_brand', 'official warranty, credentials, and overseas after-sales notes', 'official installation records include the compatible model, installer credentials, home-visit code, and published fees；installation acceptance records support later after-sales claims。', 'https://brand.example/notice', '2026-06-08');
INSERT INTO official_account_posts (post_id, account_id, title, summary, url, published_at) VALUES ('post_iscac_3', 'oa_iscac_card', 'overseas and foreign-currency card safety tips', 'foreign-currency postings may have exchange-rate and timing differences；check promptly and open a dispute for duplicate charges or unfamiliar merchants。', 'https://card.example/fx-safety', '2026-06-08');
INSERT INTO official_account_posts (post_id, account_id, title, summary, url, published_at) VALUES ('post_iscac_4', 'oa_iscac_brand', 'comparison of three handling options', 'official rework requires an additional payment ¥780；rescheduling licensed third-party installation is expected to require an additional payment ¥450；self-remediation can be submitted for reimbursement，materials are estimated at ¥600 and valid receipts are required。', 'https://brand.example/options', '2026-06-08');
INSERT INTO subscriptions (subscription_id, user_id, source, type, target, condition_json, status, created_at, updated_at) VALUES ('sub_iscac_log', 'usr_luo_wei', 'delivery_logistics', 'keyword', 'YTOSCAC5520002CN', '{"keywords": ["delivery and installation", "on-site", "installation", "acceptance"], "order_id": "ord_iscac_0002"}', 'active', '2026-06-14T00:30:00Z', '2026-06-14T00:30:00Z');
INSERT INTO subscriptions (subscription_id, user_id, source, type, target, condition_json, status, created_at, updated_at) VALUES ('sub_iscac_card', 'usr_luo_wei', 'credit_card', 'keyword', 'card_iscac_01', '{"keywords": ["foreign currency", "duplicate charge", "dispute"]}', 'active', '2026-06-15T00:00:00Z', '2026-06-15T00:00:00Z');
INSERT INTO price_alerts (alert_id, user_id, item_ref, target_price_minor, currency, status, created_at) VALUES ('alr_iscac_1', 'usr_luo_wei', 'prod_iscac_main', 1709910, 'CNY', 'active', '2026-06-15T00:00:00Z');
INSERT INTO _counters (key,value) VALUES ('subscription_seq',2),('alert_seq',1);
COMMIT;
