PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
DELETE FROM "reservations";
DELETE FROM "saved_merchants";
DELETE FROM "reviews";
DELETE FROM "merchant_qa";
DELETE FROM "deals";
DELETE FROM "merchants";
INSERT INTO "merchants" ("merchant_id","name","category","city","area","address","phone","rating_tenths","review_count","avg_price_minor","price_band","hours","tags","has_private_room","max_party_size") VALUES ('mer_njr_zhoumin','Irental recordIrental recordJiangbei New Arearental record·Zhou Minrental record','home_service','Nanjing','Jiangbei New Area','Pukou Districtrental record1numberMingfarental recordA-18','025-58864926',47,286,398000,'$$$','08:45-20:30','platform verified,rental record,rental record,remotevideorental record',0,0);
INSERT INTO "merchants" ("merchant_id","name","category","city","area","address","phone","rating_tenths","review_count","avg_price_minor","price_band","hours","tags","has_private_room","max_party_size") VALUES ('mer_njr_sunlei','rental recordMingfarental record·Sun Lei','home_service','Nanjing','Jiangbei New Area','Pukou Districtrental recordMingfarental recordB-07','025-58815282',46,119,365000,'$$','09:30-21:00','platform verified,unitrental record, Stationoutsiderental recordcommunicaterental record',0,0);
INSERT INTO "merchants" ("merchant_id","name","category","city","area","address","phone","rating_tenths","review_count","avg_price_minor","price_band","hours","tags","has_private_room","max_party_size") VALUES ('mer_njr_wuting','rental record·rental record','home_service','Nanjing','Jiangbei New Area','Pukou Districtrental record48numberrental record','025-58876839',46,173,402000,'$$$','09:00-19:30','platform verified,rental recordrentrental record,contractrental record',0,0);
INSERT INTO "merchants" ("merchant_id","name","category","city","area","address","phone","rating_tenths","review_count","avg_price_minor","price_band","hours","tags","has_private_room","max_party_size") VALUES ('mer_njr_liqiang','inrental record·Li Qiang','home_service','Nanjing','Jiangbei New Area','Pukou Districtrental record6numberrental recordnumberArental record','025-58843956',44,64,376000,'$$','10:00-18:30','platform verified,unitrental record,rental record',0,0);
INSERT INTO "merchants" ("merchant_id","name","category","city","area","address","phone","rating_tenths","review_count","avg_price_minor","price_band","hours","tags","has_private_room","max_party_size") VALUES ('mer_njr_zhenghao','rental record·Zheng Hao','home_service','Nanjing','Jiangbei New Area','Pukou Districtrental record12numberPujiang Yayanrental record','025-58822771',46,92,388000,'$$','08:30-20:00','platform verified,entire-unit rental,rental recordrecord',0,0);
INSERT INTO "merchants" ("merchant_id","name","category","city","area","address","phone","rating_tenths","review_count","avg_price_minor","price_band","hours","tags","has_private_room","max_party_size") VALUES ('mer_njr_fengjie','Irental recordIrental recorddaysrental record·rental record','home_service','Nanjing','Jiangbei New Area','Pukou Districtrental recorddaysrental recordNo.rental record','025-58867754',46,207,401000,'$$$','09:00-20:30','platform verified,daysrental record,rental record',0,0);
INSERT INTO "merchants" ("merchant_id","name","category","city","area","address","phone","rating_tenths","review_count","avg_price_minor","price_band","hours","tags","has_private_room","max_party_size") VALUES ('mer_njr_xujun','rental recordXuri Shangchengrental record·rental record','home_service','Nanjing','Jiangbei New Area','Pukou Districtrental recordXuri Shangchengrental record11rental record','025-58834802',47,151,418000,'$$$','09:15-19:45','platform verified,high floorliverental record,remotelease signingmaterials',0,0);
INSERT INTO "merchants" ("merchant_id","name","category","city","area","address","phone","rating_tenths","review_count","avg_price_minor","price_band","hours","tags","has_private_room","max_party_size") VALUES ('mer_njr_qianyu','rental record·rental record','home_service','Nanjing','Jiangbei New Area','Pukou Districtrental record12number','025-58856381',40,37,332000,'$','11:00-18:00','unitrental record,rental recordcommunity,rental record',0,0);
INSERT INTO "merchants" ("merchant_id","name","category","city","area","address","phone","rating_tenths","review_count","avg_price_minor","price_band","hours","tags","has_private_room","max_party_size") VALUES ('mer_njr_hemin','rental recordVenice Water Cityrental record·rental record','home_service','Nanjing','Jiangbei New Area','Pukou Districtrental recordVenice Water Cityrental record','025-58878293',46,244,396000,'$$','08:45-20:15','platform verified,rental recordcommunity,rental recordlandlordcollectionrental record',0,0);
INSERT INTO "merchants" ("merchant_id","name","category","city","area","address","phone","rating_tenths","review_count","avg_price_minor","price_band","hours","tags","has_private_room","max_party_size") VALUES ('mer_njr_luogang','inrental record·rental recordjust','home_service','Nanjing','Jiangbei New Area','Pukou Districtrental record26number','025-58825823',46,83,353000,'$$','09:30-18:30','platform verified,rental recordnewrental record,rental recordmaterialsverification',0,0);
INSERT INTO "reviews" ("review_id","merchant_id","user_id","rating","body","image_captions","created_at") VALUES ('rev_7Kq3mP9V','mer_njr_fengjie','u_8Kq3mV7P',4,'rental recorddaysrental record，cannoteelevatorandrental recordstatus。','{}','2026-05-06T10:00:00Z');
INSERT INTO "reviews" ("review_id","merchant_id","user_id","rating","body","image_captions","created_at") VALUES ('review-20260407-A8xM','mer_njr_fengjie','member-4Tn9Qx',5,'rental recordcommunicaterental record，nonerental recordplatformrental recordpayment。','{}','2026-04-07T10:00:00Z');
INSERT INTO "reviews" ("review_id","merchant_id","user_id","rating","body","image_captions","created_at") VALUES ('rvw_HM_4Tn7Q','mer_njr_hemin','usr_A7m2Kp8V',2,'listingrental record，rental recordcollectionaccountrental recordInotrental record。','{}','2026-05-08T10:00:00Z');
INSERT INTO "reviews" ("review_id","merchant_id","user_id","rating","body","image_captions","created_at") VALUES ('dianping_9Pc2Lm','mer_njr_hemin','uid_9Pc4Lw6M',4,'communityamenitiesrental record，lease signingrental recordneedverification。','{}','2026-04-09T10:00:00Z');
INSERT INTO "reviews" ("review_id","merchant_id","user_id","rating","body","image_captions","created_at") VALUES ('rev-LQ-6vK4','mer_njr_liqiang','u-N5q8Rk3T',3,'beforerental recordveryrental record，rental recordservice feerental recordexplainbeforeafternotmatch，needmyselfleaverental recordplatformrecord。','{}','2026-05-10T10:00:00Z');
INSERT INTO "reviews" ("review_id","merchant_id","user_id","rating","body","image_captions","created_at") VALUES ('review_20260411_Q7mR','mer_njr_liqiang','member_7Vx2Mp9Q',3,'rental recordafterfrequentrental recordchoose，rental recordmaterialsrental record。','{}','2026-04-11T10:00:00Z');
INSERT INTO "reviews" ("review_id","merchant_id","user_id","rating","body","image_captions","created_at") VALUES ('rvw_LG_3Xk8P','mer_njr_luogang','usr_K4m8Tn6P',3,'rental recordcontractrental recordveryrental record，notrental recordproperty owner namerental recordpayee namehaveonerental record。','{}','2026-05-12T10:00:00Z');
INSERT INTO "reviews" ("review_id","merchant_id","user_id","rating","body","image_captions","created_at") VALUES ('dp_5Nq2Vt9M','mer_njr_luogang','uid-3Qp7Vx9L',3,'remoterental recordneedunitbetween，onlinetransferrental record。','{}','2026-04-13T10:00:00Z');
INSERT INTO "reviews" ("review_id","merchant_id","user_id","rating","body","image_captions","created_at") VALUES ('rev_QY_8Lm4C','mer_njr_qianyu','u_6Rm2Kw8T',3,'canrental recordlistingnotrental record，rental record。','{}','2026-05-14T10:00:00Z');
INSERT INTO "reviews" ("review_id","merchant_id","user_id","rating","body","image_captions","created_at") VALUES ('review-4Pz7Kq','mer_njr_qianyu','member-P9x4Nq',3,'canrental recordbudgetrental record，rental recordmaterialsnotrental record。','{}','2026-04-15T10:00:00Z');
INSERT INTO "reviews" ("review_id","merchant_id","user_id","rating","body","image_captions","created_at") VALUES ('rvw_SL_9Tn3W','mer_njr_sunlei','usr_5Tn8Lm2V',3,'listinginformationupdatedrental record，rental recordtimerental recordtoWeChatrental recordcommunicate，platformleaverental recordnotrental record。','{}','2026-05-16T10:00:00Z');
INSERT INTO "reviews" ("review_id","merchant_id","user_id","rating","body","image_captions","created_at") VALUES ('dp_6Kx8Mr2Q','mer_njr_sunlei','uid_7Kp3Qx9R',3,'rental record，rental recordcopyrental recordfinalrental record。','{}','2026-04-17T10:00:00Z');
INSERT INTO "reviews" ("review_id","merchant_id","user_id","rating","body","image_captions","created_at") VALUES ('rev_WT_3qP7V','mer_njr_wuting','u-W4m6Pv8N',4,'videorental recordkitchenandrental record，routenoterental recordneedrental recordmeasured。','{}','2026-05-18T10:00:00Z');
INSERT INTO "reviews" ("review_id","merchant_id","user_id","rating","body","image_captions","created_at") VALUES ('review_20260419_M8cL','mer_njr_wuting','member_2Qx9Tk5L',5,'schedulerental recordhour，rental recordpayrental record。','{}','2026-04-19T10:00:00Z');
INSERT INTO "reviews" ("review_id","merchant_id","user_id","rating","body","image_captions","created_at") VALUES ('rvw_HB_5Vn2K','mer_njr_xujun','usr_M8v3Kp7R',5,'rental recordcommunityrecentrentedrental recordexplainrental record，canrental recordplatformnumber。','{}','2026-05-20T10:00:00Z');
INSERT INTO "reviews" ("review_id","merchant_id","user_id","rating","body","image_captions","created_at") VALUES ('dp_7Qm4Xt9P','mer_njr_xujun','uid-6Pn4Xq9T',4,'videoviewingrental recordnumbersafechoose，rental recordhaverental record。','{}','2026-04-21T10:00:00Z');
INSERT INTO "reviews" ("review_id","merchant_id","user_id","rating","body","image_captions","created_at") VALUES ('rev_TY_2Kp8R','mer_njr_zhenghao','u_9Kx2Lm7V',3,'before viewingrental recordtorental record，rental recordconditionssayrental recordnotrental record。','{}','2026-05-22T10:00:00Z');
INSERT INTO "reviews" ("review_id","merchant_id","user_id","rating","body","image_captions","created_at") VALUES ('review-9Lm3Vq','mer_njr_zhenghao','member_5Qp8Rv3N',4,'photoupdatedrental recordhour，service feeandrental recordatcontractattachitemincentsrental record。','{}','2026-04-23T10:00:00Z');
INSERT INTO "reviews" ("review_id","merchant_id","user_id","rating","body","image_captions","created_at") VALUES ('rvw_QW_6Xn4T','mer_njr_zhoumin','usr-T7m4Kx9P',5,'rental recordproperty certificaterental recorditemafterrental recordcontractrental record，videoviewingrecordalsoorganizerental record。','{}','2026-05-24T10:00:00Z');
INSERT INTO "reviews" ("review_id","merchant_id","user_id","rating","body","image_captions","created_at") VALUES ('dp_4Rk7Mp2V','mer_njr_zhoumin','uid_3Vq6Np8M',5,'contractinofpayee nameandproperty ownereachitemexplain，nonepressingfirstrental recordviewingdeposit。','{}','2026-04-25T10:00:00Z');
COMMIT;
PRAGMA foreign_keys=ON;

BEGIN TRANSACTION;
INSERT INTO merchants(merchant_id,name,category,city,area,address,phone,rating_tenths,review_count,avg_price_minor,price_band,hours,tags,has_private_room,max_party_size) VALUES
('mer_njr_tangyu','rental record','home_service','Nanjing','Jiangbei New Area','rental record88number','025-83122041',44,96,360000,'$$','09:00-19:00','rental recordrent,rental record,videorental record',0,0),
('mer_njr_qianwei','Pukouunitrental record','home_service','Nanjing','Pukou District','rental record41number','025-83122076',41,73,320000,'$$','08:30-18:30','rental recordcommunity,steprental recordunit,rentrental record',0,0),
('mer_njr_songlan','rental recordnewrental record','home_service','Nanjing','Jiangbei New Area','rental record16number','025-83122118',47,214,390000,'$$','09:00-20:00','Metrounit,platformlease signing,rental record',0,0),
('mer_njr_huangbo','rental record','home_service','Nanjing','Jiangbei New Area','rental record189number','025-83122159',43,181,430000,'$$$','09:00-20:30','rental record,contractrental record,onlineviewing',0,0),
('mer_njr_yujie','Irental recordIrental record','home_service','Nanjing','Jiangbei New Area','rental record322number','025-83122194',46,168,310000,'$$','08:30-19:30','rental record,rental record,entire-unit rental',0,0),
('mer_njr_caixia','rental record','home_service','Nanjing','Jiangbei New Area','rental record99number','025-83122235',38,51,460000,'$$$','09:30-18:00','personrental record,rental recordunit,rental recordrentrental record',0,0),
('mer_njr_mengfan','rental record','home_service','Nanjing','Pukou District','rental recordMetrorental record2number','025-83122271',45,193,410000,'$$','09:00-20:00','rental record,rental record,Metrorental record',0,0),
('mer_njr_dingrui','Nanjingrental recordrentrental record','home_service','Nanjing','Jiangbei New Area','rental recordnewrental record28numberrental recordofficerental record','025-83122308',42,88,350000,'$','10:00-18:00','landlordrental recordrent,rental recordcontract,remotehandoff',0,0);
INSERT INTO reviews(review_id,merchant_id,user_id,rating,body,image_captions,created_at) VALUES
('rv_njr_tang_video','mer_njr_tangyu','tenant_song',4,'videofromrental recordtorental record，rental record。','{"photos":["videoscreenshot"]}','2026-03-08T12:40:00Z'),
('rv_njr_tang_key','mer_njr_tangyu','tenant_chen',3,'rental record，weekdaynotrental record。','{}','2026-05-21T09:18:00Z'),
('rv_njr_qian_stairs','mer_njr_qianwei','tenant_lai',4,'brokerrental recordbeforenoterental recordhas elevator。','{"photos":["rental record"]}','2026-02-17T18:22:00Z'),
('rv_njr_qian_meter','mer_njr_qianwei','tenant_pan',3,'handoffrental record，timedayrental recordon。','{}','2026-06-02T10:35:00Z'),
('rv_njr_song_contract','mer_njr_songlan','tenant_fan',5,'contractversioncanatplatformunderrental record，rental record。','{"photos":["rental record"]}','2026-01-26T15:12:00Z'),
('rv_njr_song_commute','mer_njr_songlan','tenant_wen',4,'rental recordmeasuredtoMetrorental recordminutes。','{}','2026-04-15T08:50:00Z'),
('rv_njr_huang_inventory','mer_njr_huangbo','tenant_rao',4,'rental recordeachitemrental recordfollow，handoffrental record。','{"photos":["rental recordnumber"]}','2026-03-19T17:46:00Z'),
('rv_njr_huang_fee','mer_njr_huangbo','tenant_xiong',3,'service feerental recorddaysrental record，amountrental record。','{}','2026-05-28T20:08:00Z'),
('rv_njr_yu_factory','mer_njr_yujie','tenant_mo',3,'unitrental record，rental recordbetweenrental record。','{"photos":["rental recordbetweenrental record"]}','2026-04-04T21:16:00Z'),
('rv_njr_yu_repair','mer_njr_yujie','tenant_he',5,'move-inbeforerental recordofkitchenrental record。','{}','2026-06-10T13:30:00Z'),
('rv_njr_cai_company','mer_njr_caixia','tenant_gan',4,'rental recordlistingsendrental recordandpayment recipientrental recordmatch。','{"photos":["rental recordsendrental record"]}','2026-02-23T11:05:00Z'),
('rv_njr_cai_term','mer_njr_caixia','tenant_jiang',2,'rental recordacceptrental recordyearrentrental record，rental recordbeforerental recordrentrental recordaboutrental record。','{}','2026-05-09T16:24:00Z'),
('rv_njr_meng_road','mer_njr_mengfan','tenant_lu',3,'rental recordbranchlistingrental record，rental recordunitrental record。','{}','2026-03-31T19:50:00Z'),
('rv_njr_meng_owner','mer_njr_mengfan','tenant_bai',5,'landlordidentity cardandproperty deedon-siteverificationrental record。','{"photos":["verificationrental record"]}','2026-06-17T14:42:00Z'),
('rv_njr_ding_remote','mer_njr_dingrui','tenant_wei',4,'rental recordhandoffcontainsutility metersphotoanddoor lockrental record。','{"photos":["handoffrental record"]}','2026-04-27T10:33:00Z'),
('rv_njr_ding_response','mer_njr_dingrui','tenant_hou',3,'workdayrental recordbetweenrental recordcommunicaterental recordNo.rental recorddaysrental record。','{}','2026-06-20T09:14:00Z');
INSERT INTO deals(deal_id,merchant_id,title,description,price_minor,list_price_minor,serves,valid_until,status) VALUES
('deal_njr_tang_video','mer_njr_tangyu','rental recordminutesvideorental record','rental record、utility metersandrental recordoutsiderental record。',9900,15000,1,'2026-05-31','expired'),
('deal_njr_qian_inventory','mer_njr_qianwei','rental recordunitrental record','rental recordphotoandnumberrental record。',12800,18000,1,'2026-06-15','expired'),
('deal_njr_song_contract','mer_njr_songlan','rentrental recordcontractrental record','platformrental recordmarkedrental recordneedrental recorditemrental record。',19900,26000,1,'2026-04-30','expired'),
('deal_njr_huang_handover','mer_njr_huangbo','remotehandoffrental record','videohandoffrental recordutility metersphoto。',23800,32000,1,'2026-06-20','sold_out'),
('deal_njr_yu_clean','mer_njr_yujie','rental recordunitrental record','two-bedroom roomrental recordandkitchenrental record。',26000,34000,1,'2026-05-20','expired'),
('deal_njr_cai_invoice','mer_njr_caixia','rental recordrentrental recordmaterialsrental record','rental recordcontract、sendrental recordandpaymentnote。',15000,22000,1,'2026-06-18','expired'),
('deal_njr_meng_route','mer_njr_mengfan','morning peakrouterental record','rental recordtimeMetroandsteprental recordrouterental record。',16800,24000,1,'2026-05-12','expired'),
('deal_njr_ding_lock','mer_njr_dingrui','rental recorddoor lockhandoff','recordrental recordhourrental recordandrental recordtime。',12000,16000,1,'2026-06-25','expired');
INSERT INTO merchant_qa(qa_id,merchant_id,user_id,question,answer,answered_by,created_at) VALUES
('qa_njr_tang_weekend','mer_njr_tangyu','user_tao','weekdaycanrental recordofrental recordunitrental record？','rental recordweekdayrental record。','branchbroker','2026-05-18T08:42:00Z'),
('qa_njr_qian_invoice','mer_njr_qianwei','user_shao','service feecanrental recordsendrental record？','branchcanrental recordvaluerental recordstandardrental recordsendrental record。','financialrental record','2026-03-11T10:20:00Z'),
('qa_njr_song_video','mer_njr_songlan','user_ke','videorental recordwillrental record？','rental recordprocesscontainsrental record、rental record、rental record。','branchrental record','2026-04-06T15:36:00Z'),
('qa_njr_huang_keys','mer_njr_huangbo','user_xu','rental recordunitrental recordatrental recordin？','rental recordcentsatbranch，rental recordcentsrental record。','valuerental recordbroker','2026-02-28T12:08:00Z'),
('qa_njr_yu_pets','mer_njr_yujie','user_deng','rental recordlistingrental recordacceptrental record？','isrental recordacceptrental recordlandlordrental recordwritecontract。','rentrental record','2026-05-25T09:50:00Z'),
('qa_njr_cai_term','mer_njr_caixia','user_zhu','personrental recordhaverental recordyearrentrental record？','currentrental recordcontractrental recordmonth。','rental record','2026-06-03T13:17:00Z'),
('qa_njr_meng_receipt','mer_njr_mengfan','user_huang','rental recordservice feehaverental record？','branchnotrental record，onlinepaymentautomaticallyrental record。','rental record','2026-04-18T18:44:00Z'),
('qa_njr_ding_sign','mer_njr_dingrui','user_qin','rental recordcontractuserental recordname？','platformrental recordverificationandrental recordnamerental record。','lease signingrental record','2026-06-12T11:25:00Z');
COMMIT;

BEGIN TRANSACTION;
INSERT INTO merchants(merchant_id,name,category,city,area,address,phone,rating_tenths,review_count,avg_price_minor,price_band,hours,tags,has_private_room,max_party_size) VALUES
('mer_njr_remote_inspect','rental recordremoterental recordunitwork room','home_service','Nanjing','Jiangbei New Area','rental record92number','025-58832914',46,214,26800,'$$','09:00-19:00','videorental recordunit,utility meters,door lockrental record',0,0),
('mer_njr_cowork_cafe','rental recordworkrental record','restaurant','Nanjing','Jiangbei New Area','rental record99numberBrental record','025-58874563',43,187,5200,'$','07:30-20:30','rental record,rental record,workdayunitrental record',0,16);
INSERT INTO reviews(review_id,merchant_id,user_id,rating,body,image_captions,created_at) VALUES
('rv_njr_remote_bathroom','mer_njr_remote_inspect','user_njr_liao',5,'rental recordtorental recordandrental record，rental recordvideorental recorddayssendtorental recordmailbox。','{"captions":["rental recordscreenshot"]}','2026-05-12T12:34:00Z'),
('rv_njr_remote_signal','mer_njr_remote_inspect','user_njr_shen',4,'rental recordunderrental recordnumberrental record，rental recordunitrental recordandelevator living room。','{"captions":["elevator living room"]}','2026-06-02T09:51:00Z'),
('rv_njr_cowork_breakfast','mer_njr_cowork_cafe','user_njr_yan',4,'rental recordhaverental record，rental recordsheetrental recordhourexcerptrental record。','{"captions":["rental record"]}','2026-04-23T08:16:00Z');
INSERT INTO deals(deal_id,merchant_id,title,description,price_minor,list_price_minor,serves,valid_until,status) VALUES
('deal_njr_remote_meter_pack','mer_njr_remote_inspect','rental recordremoterental record','containsrental recordnumber、readrental recordandrental recordofrental recordvideo。',21800,28000,1,'2026-06-10','expired'),
('deal_njr_cowork_weekcard','mer_njr_cowork_cafe','rental recordworkdayweekrental record','rental recordworkdayonrental recordandrental recordbetweenrental record。',23800,31000,1,'2026-05-31','sold_out');
COMMIT;
