-- Generated notification_hub seed for community_household_groupbuy_30d
BEGIN;
INSERT INTO official_accounts (account_id, name, category, description) VALUES ('oa_homtg_customs', 'Customs cross-border alert', 'logistics', 'cross-border shipping、personal-item declaration and limits policy');
INSERT INTO official_account_subscriptions (user_id, account_id, subscribed_at) VALUES ('usr_xie_lin', 'oa_homtg_customs', '2026-06-06T00:00:00Z');
INSERT INTO official_accounts (account_id, name, category, description) VALUES ('oa_homtg_brand', 'community group purchasebusiness label', 'shopping_service', 'official warranty/qualification and overseas after-sales information');
INSERT INTO official_account_subscriptions (user_id, account_id, subscribed_at) VALUES ('usr_xie_lin', 'oa_homtg_brand', '2026-06-06T00:00:00Z');
INSERT INTO official_accounts (account_id, name, category, description) VALUES ('oa_homtg_card', 'CMBbusiness labelcard', 'finance', 'statement、foreign-currency transaction and card safety reminder');
INSERT INTO official_account_subscriptions (user_id, account_id, subscribed_at) VALUES ('usr_xie_lin', 'oa_homtg_card', '2026-06-06T00:00:00Z');
INSERT INTO official_account_posts (post_id, account_id, title, summary, url, published_at) VALUES ('post_homtg_1', 'oa_homtg_customs', 'Personal lithium-battery shipping and declaration notice', 'business label(Wh)restriction，business label；business label。', 'https://customs.example/li-battery-notice', '2026-06-08');
INSERT INTO official_account_posts (post_id, account_id, title, summary, url, published_at) VALUES ('post_homtg_2', 'oa_homtg_brand', 'official warranty/qualification and overseas after-sales information', 'before opening the group, use the product/SKU details to verify group leader qualification、product lot and verification code；if group formation fails, change pickup point or request refund，pickup requires the pickup verification code。', 'https://brand.example/notice', '2026-06-08');
INSERT INTO official_account_posts (post_id, account_id, title, summary, url, published_at) VALUES ('post_homtg_3', 'oa_homtg_card', 'business labelforeign currencybusiness labelcardbusiness labelNotice', 'foreign-currency posting may have exchange-rate and timing differences；if duplicate charges or an unfamiliar merchant appear，verify promptly and open a dispute if needed。', 'https://card.example/fx-safety', '2026-06-08');
INSERT INTO official_account_posts (post_id, account_id, title, summary, url, published_at) VALUES ('post_homtg_4', 'oa_homtg_brand', 'Comparison of three handling options', 'official self-operated group(¥780,most reliable)；community leader group(¥450,business labelgroup formation)；pickup-point individual group(free but requires self-verification, about¥600)。weigh delivered cost and reliability。', 'https://brand.example/options', '2026-06-08');
INSERT INTO subscriptions (subscription_id, user_id, source, type, target, condition_json, status, created_at, updated_at) VALUES ('sub_homtg_log', 'usr_xie_lin', 'delivery_logistics', 'keyword', 'YTOOMTG5520002CN', '{"keywords": ["forwarding", "dispatch", "business label", "compliance"], "order_id": "ord_homtg_0002"}', 'active', '2026-06-15T09:00:00Z', '2026-06-15T09:00:00Z');
INSERT INTO subscriptions (subscription_id, user_id, source, type, target, condition_json, status, created_at, updated_at) VALUES ('sub_homtg_card', 'usr_xie_lin', 'credit_card', 'keyword', 'card_homtg_01', '{"keywords": ["foreign currency", "duplicate charge", "dispute"]}', 'active', '2026-06-15T00:00:00Z', '2026-06-15T00:00:00Z');
INSERT INTO price_alerts (alert_id, user_id, item_ref, target_price_minor, currency, status, created_at) VALUES ('alr_homtg_1', 'usr_xie_lin', 'prod_homtg_main', 20610, 'CNY', 'active', '2026-06-15T00:00:00Z');
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_homtg_seed1', 'usr_xie_lin', 'delivery_logistics', 'policy_update', 'sub_homtg_log', 'Group-purchase notice：group-formation progress pending confirmation', 'business labelcommunity household-goods groupbusiness labelgroup-formation progress pending confirmation，pickup requires the pickup-point verification code。', '{"order_id": "ord_homtg_0002", "tracking_no": "YTOOMTG5520002CN"}', '2026-06-15T12:05:00Z', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_homtg_seed2', 'usr_xie_lin', 'credit_card', 'policy_update', 'sub_homtg_card', 'foreign currencybusiness label', 'your card has a new foreign-currency transaction，business label，watch subsequent reconciliation。', '{"card_id": "card_homtg_01", "tx_id": "tx_homtg_fx"}', '2026-06-15T11:35:00Z', 0);
INSERT INTO _counters (key,value) VALUES ('subscription_seq',2),('alert_seq',1);
COMMIT;
