-- Generated notification_hub seed for floor_total_reno_v4_30d
BEGIN;
INSERT INTO official_accounts (account_id, name, category, description) VALUES ('oa_qflr_housing', 'Chengduunderfloor heatingtranslated business text', 'home_improvement', 'underfloor-heating work、base layertranslated business text、wood flooringflooring installationwindowandmaterialsbatchreminder');
INSERT INTO official_account_subscriptions (user_id, account_id, subscribed_at) VALUES ('usr_lai_xu', 'oa_qflr_housing', '2026-05-24T07:35:00Z');
INSERT INTO official_accounts (account_id, name, category, description) VALUES ('oa_qflr_brand', 'underfloor heatingflooringconstruction service', 'shopping_service', 'coilpressure test、levelingreinspection、moisture contentandflooringwarrantydescription');
INSERT INTO official_account_subscriptions (user_id, account_id, subscribed_at) VALUES ('usr_lai_xu', 'oa_qflr_brand', '2026-05-29T03:10:00Z');
INSERT INTO official_accounts (account_id, name, category, description) VALUES ('oa_qflr_card', 'translated business textcredit card', 'finance', 'bill、foreign-currency transactionandtranslated business textsecurity reminder');
INSERT INTO official_account_subscriptions (user_id, account_id, subscribed_at) VALUES ('usr_lai_xu', 'oa_qflr_card', '2026-06-01T06:25:00Z');
INSERT INTO official_account_posts (post_id, account_id, title, summary, url, published_at) VALUES ('post_qflr_1', 'oa_qflr_housing', 'coil、levelingtranslated business textandflooringtranslated business textverify', 'coilbatch、manifoldmodel、levelingtranslated business textdateandflooringmoisture stateshouldrespectivelytranslated business text；materialsarrivalmust notreplacepressure testorbase layerreinspection。', 'https://housing.example/chengdu/floor-heating-arrival', '2026-06-02');
INSERT INTO official_account_posts (post_id, account_id, title, summary, url, published_at) VALUES ('post_qflr_2', 'oa_qflr_brand', 'pressure test、moisture contentandflatnessrecordboundary', 'pressuretranslated business textpressure hold、base layermoisture contentandtwo-meter straightedgereadingtranslated business textdifferentevidence，thentranslated business textflooring installationwork sequencemust notautomaticcoverbeforetranslated business textmissingrecord。', 'https://warmall.example/service/measurement-boundaries', '2026-06-04');
INSERT INTO official_account_posts (post_id, account_id, title, summary, url, published_at) VALUES ('post_qflr_3', 'oa_qflr_card', 'thermostatmerchantsame-amount transactionreconciletranslated business text', 'pre-authorized、formal postingandreversalshouldaccording tocardstatuslist separately；sendtranslated business textsame-amount transactiontranslated business textfirstreconcile the orderandmerchant，translated business textunder investigationstatustranslated business textrefund。', 'https://card.example/controller-transaction-check', '2026-06-06');
INSERT INTO official_account_posts (post_id, account_id, title, summary, url, published_at) VALUES ('post_qflr_4', 'oa_qflr_brand', 'flooringandconvergematerialsremaining stocktranslated business text', 'surplus materialslistingshouldmarkflooringbatch、baseboardtranslated business text、trim striptranslated business textandmoisture-barrier underlaymentarea，platformtranslated business textnot yetsettlementbeforetranslated business textchangefunds。', 'https://warmall.example/service/flooring-leftovers', '2026-06-11');
INSERT INTO subscriptions (subscription_id, user_id, source, type, target, condition_json, status, created_at, updated_at) VALUES ('sub_qflr_log', 'usr_lai_xu', 'delivery_logistics', 'keyword', 'YTOQFLR5520002CN', '{"keywords": ["coil", "thermostat", "flooringtranslated business text", "arrival", "reinspectiondocuments"], "order_id": "ord_qflr_0002"}', 'active', '2026-06-14T12:05:00Z', '2026-06-14T12:05:00Z');
INSERT INTO subscriptions (subscription_id, user_id, source, type, target, condition_json, status, created_at, updated_at) VALUES ('sub_qflr_card', 'usr_lai_xu', 'credit_card', 'keyword', 'card_qflr_01', '{"keywords": ["thermostatmerchant", "same-amount transaction", "under investigation", "reversal"]}', 'active', '2026-06-14T11:45:00Z', '2026-06-14T11:45:00Z');
INSERT INTO price_alerts (alert_id, user_id, item_ref, target_price_minor, currency, status, created_at) VALUES ('alr_qflr_1', 'usr_lai_xu', 'prod_qflr_main', 3510000, 'CNY', 'active', '2026-06-14T10:20:00Z');
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_qflr_0614_arrival', 'usr_lai_xu', 'delivery_logistics', 'policy_update', 'sub_qflr_log', 'historicalarrivalreminder：floormaterialsbatchretain', 'coil、levelingmaterialsandflooringarrivalthenshouldtranslated business textretain；arrivaldoes not meanpressure testorflooring installationpass。', '{"order_id": "ord_qflr_0002", "tracking_no": "YTOQFLR5520002CN"}', '2026-06-14T03:05:00Z', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_qflr_0614_fx', 'usr_lai_xu', 'credit_card', 'policy_update', 'sub_qflr_card', 'historicalforeign currencypre-authorizedreminder', 'translated business textoutsidethermostatmerchantpre-authorizedcancantranslated business texttimetranslated business text；pleaseandorderreconcile。', '{"card_id": "card_qflr_01", "tx_id": "tx_qflr_fx"}', '2026-06-14T02:35:00Z', 0);
INSERT INTO _counters (key,value) VALUES ('subscription_seq',2),('alert_seq',1);
COMMIT;

BEGIN;
UPDATE notifications SET title='historicalarrivalreminder：floormaterialsbatchretain', body='coil、levelingmaterialsandflooringarrivalthenshouldtranslated business textretain；arrivaldoes not meanpressure testorflooring installationpass。', created_at='2026-06-14T03:05:00Z' WHERE notification_id='ntf_qflr_0614_arrival';
UPDATE notifications SET title='historicalforeign currencypre-authorizedreminder', body='translated business textoutsidethermostatmerchantpre-authorizedcancantranslated business texttimetranslated business text；pleaseandorderreconcile。', created_at='2026-06-14T02:35:00Z' WHERE notification_id='ntf_qflr_0614_fx';
INSERT INTO notifications (notification_id,user_id,source,type,subscription_id,title,body,payload_json,created_at,read) VALUES
 ('ntf_qflr_0516_loop','usr_lai_xu','calendar','policy_update',NULL,'historicaltranslated business textcircuitrecordalreadyarchive','historicalobjecttranslated business textandcurrentprojectacceptance。','{"event_id":"evt_qflr_0516_pressure_review"}','2026-05-16T03:00:00Z',1),
 ('ntf_qflr_near1','usr_lai_xu','ecommerce','price_change',NULL,'translated business textbatchcancheckbuttranslated business textmatch','translated business textbatchandcurrenttranslated business textdifferent，must notdirectlyreplace。','{"state":"near_match"}','2026-06-14T05:15:00Z',0),
 ('ntf_qflr_doc1','usr_lai_xu','email','policy_update',NULL,'contractorauthorizationtranslated business textstill missingsigntranslated business text','completebeforetranslated business textpending verificationtranslated business text。','{"document":"authorization","status":"missing_page"}','2026-06-12T07:05:00Z',0),
 ('ntf_qflr_test1','usr_lai_xu','calendar','policy_update',NULL,'pressuretranslated business text、moisture contentandflatnesstranslated business textindependentrecord','thentranslated business textwork sequencemust notautomaticcoverbeforetranslated business textmissingtranslated business text。','{"matrix":"pressure_moisture_flatness"}','2026-06-14T06:00:00Z',1);
COMMIT;
