PRAGMA foreign_keys = ON;
BEGIN TRANSACTION;

INSERT INTO "account_config" ("id", "email", "name", "created_at") VALUES (1, 'li.cheng.family@example.cn', 'Li Chengfamilytravelfamily travel detail', '2026-09-01T00:00:00Z');

INSERT INTO "folders" ("id", "name", "delimiter", "flags_json", "message_count", "unread_count") VALUES (1, 'INBOX', '/', '["\\Inbox"]', 26, 8);
INSERT INTO "folders" ("id", "name", "delimiter", "flags_json", "message_count", "unread_count") VALUES (2, 'Sent', '/', '["\\Sent"]', 0, 0);
INSERT INTO "folders" ("id", "name", "delimiter", "flags_json", "message_count", "unread_count") VALUES (3, 'Drafts', '/', '["\\Drafts"]', 0, 0);

INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (1, 1, '<family-mail-01-20260105@example>', 'springfamily travel detailpickupfamily travel detail', 'kindergarten@littleacorn.example.cn', '["li.cheng.family@example.cn"]', '[]', '[]', '2026-01-05T09:00:00+08:00', 'new termpickupfamily travel detail。parentfamily travel detailnap、family travel detailemergency contactfamily travel detail。', NULL, 1, 0, 0, NULL, NULL, '{"thread":"family-01","source":"external"}', 1001, 90, '2026-01-05T09:00:00+08:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (2, 1, '<family-mail-02-20260122@example>', 'four-year-oldroutinecheckupfamily travel detail', 'clinic@pudong-childcare.example.cn', '["li.cheng.family@example.cn"]', '[]', '[]', '2026-01-22T09:00:00+08:00', 'checkuptimefamily travel detail 2 family travel detail 17 family travel detail；family travel detail，family travel detail。', NULL, 1, 1, 0, NULL, NULL, '{"thread":"family-02","source":"external"}', 1002, 109, '2026-01-22T09:00:00+08:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (3, 1, '<family-mail-03-20260203@example>', 'childfamily travel detail', 'swim@riversideclub.example.cn', '["li.cheng.family@example.cn"]', '[]', '[]', '2026-02-03T09:00:00+08:00', 'family travel detail，family travel detail，parentfamily travel detail。', NULL, 0, 0, 0, NULL, NULL, '{"thread":"family-03","source":"external"}', 1003, 87, '2026-02-03T09:00:00+08:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (4, 1, '<family-mail-04-20260226@example>', 'Shanghaifamilyoutdoorfamily travel detail', 'tickets@outdoorshow.example.cn', '["li.cheng.family@example.cn"]', '[]', '[]', '2026-02-26T09:00:00+08:00', 'family travel detailvisitfamily travel detail，childfamily travel detail。', NULL, 1, 0, 0, NULL, NULL, '{"thread":"family-04","source":"external"}', 1004, 75, '2026-02-26T09:00:00+08:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (5, 1, '<family-mail-05-20260311@example>', 'vehiclefamily travel detail', 'service@jinqiao-auto.example.cn', '["li.cheng.family@example.cn"]', '[]', '[]', '2026-03-11T09:00:00+08:00', 'family travel detailInspecttires、family travel detailchildrestraintanchor points，family travel detail。', NULL, 1, 0, 0, NULL, NULL, '{"thread":"family-05","source":"external"}', 1005, 87, '2026-03-11T09:00:00+08:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (6, 1, '<family-mail-06-20260329@example>', 'family travel detail', 'books@cloudreading.example.cn', '["li.cheng.family@example.cn"]', '[]', '[]', '2026-03-29T09:00:00+08:00', 'family travel detailchildfamily travel detail，family travel detailcollect。', NULL, 0, 0, 0, NULL, NULL, '{"thread":"family-06","source":"external"}', 1006, 84, '2026-03-29T09:00:00+08:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (7, 1, '<family-mail-07-20260408@example>', 'family travel detail', 'support@petcare-pudong.example.cn', '["li.cheng.family@example.cn"]', '[]', '[]', '2026-04-08T09:00:00+08:00', 'family travel detail；family travel detailrecord。', NULL, 1, 0, 0, NULL, NULL, '{"thread":"family-07","source":"external"}', 1007, 78, '2026-04-08T09:00:00+08:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (8, 1, '<family-mail-08-20260421@example>', 'family travel detail', 'museum@shscitech.example.cn', '["li.cheng.family@example.cn"]', '[]', '[]', '2026-04-21T09:00:00+08:00', 'family travel detailschedulefamily travel detail，family travel detail。', NULL, 1, 0, 0, NULL, NULL, '{"thread":"family-08","source":"external"}', 1008, 69, '2026-04-21T09:00:00+08:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (9, 1, '<family-mail-09-20260506@example>', 'family travel detailmaterials', 'travelclub@company.example.cn', '["li.cheng.family@example.cn"]', '[]', '[]', '2026-05-06T09:00:00+08:00', 'family travel detail、family travel detail，family travel detail。', NULL, 0, 0, 0, NULL, NULL, '{"thread":"family-09","source":"external"}', 1009, 102, '2026-05-06T09:00:00+08:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (10, 1, '<family-mail-10-20260518@example>', 'familyfamily travel detail', 'billing@shanghai-telecom.example.cn', '["li.cheng.family@example.cn"]', '[]', '[]', '2026-05-18T09:00:00+08:00', 'family travel detail，family travel detail。', NULL, 1, 0, 0, NULL, NULL, '{"thread":"family-10","source":"external"}', 1010, 72, '2026-05-18T09:00:00+08:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (11, 1, '<family-mail-11-20260527@example>', 'family travel detailschedule', 'teacher.liu@littleacorn.example.cn', '["li.cheng.family@example.cn"]', '[]', '[]', '2026-05-27T09:00:00+08:00', 'family travel detail，family travel detail。', NULL, 1, 0, 0, NULL, NULL, '{"thread":"family-11","source":"external"}', 1011, 72, '2026-05-27T09:00:00+08:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (12, 1, '<family-mail-12-20260602@example>', 'familyfamily travel detailsummary', 'insurance@harbourmutual.example.cn', '["li.cheng.family@example.cn"]', '[]', '[]', '2026-06-02T09:00:00+08:00', 'family travel detailsummaryfamily travel detail；family travel detailvehiclefamily travel detail。', NULL, 0, 1, 0, NULL, NULL, '{"thread":"family-12","source":"external"}', 1012, 93, '2026-06-02T09:00:00+08:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (13, 1, '<family-mail-13-20260610@example>', 'right-hand drivingonlinefamily travel detail', 'events@drivesafe.example.au', '["li.cheng.family@example.cn"]', '[]', '[]', '2026-06-10T09:00:00+08:00', 'family travel detail、roundabout priority、family travel detail，family travel detailretainfamily travel detail。', NULL, 1, 0, 0, NULL, NULL, '{"thread":"family-13","source":"external"}', 1013, 96, '2026-06-10T09:00:00+08:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (14, 1, '<family-mail-14-20260616@example>', 'family travel detailconsultationfamily travel detail', 'appointments@translationdesk.example.cn', '["li.cheng.family@example.cn"]', '[]', '[]', '2026-06-16T09:00:00+08:00', 'consultationfamily travel detail，family travel detailtravelfamily travel detail。', NULL, 1, 1, 1, NULL, NULL, '{"thread":"family-14","source":"external"}', 1014, 105, '2026-06-16T09:00:00+08:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (15, 1, '<family-mail-15-20260628@example>', 'family travel detailcampsitefamily travel detail', 'camp@chongming-east.example.cn', '["li.cheng.family@example.cn"]', '[]', '[]', '2026-06-28T09:00:00+08:00', 'cancelledfamily travel detail，campsitefamily travel detailstatusfamily travel detail closed。', NULL, 0, 0, 0, NULL, NULL, '{"thread":"family-15","source":"external"}', 1015, 58, '2026-06-28T09:00:00+08:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (16, 1, '<family-mail-16-20260704@example>', 'familybudgetfamily travel detail', 'support@familybudget.example.cn', '["li.cheng.family@example.cn"]', '[]', '[]', '2026-07-04T09:00:00+08:00', 'family travel detail，family travel detailpre-authorizationfamily travel detail。', NULL, 1, 0, 0, NULL, NULL, '{"thread":"family-16","source":"external"}', 1016, 93, '2026-07-04T09:00:00+08:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (17, 1, '<family-mail-17-20260712@example>', 'family travel detailspringfamily travel detail', 'newsletter@parks-victoria.example.au', '["li.cheng.family@example.cn"]', '[]', '[]', '2026-07-12T09:00:00+08:00', 'family travel detail，family travel detail。', NULL, 1, 0, 0, NULL, NULL, '{"thread":"family-17","source":"external"}', 1017, 87, '2026-07-12T09:00:00+08:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (18, 1, '<family-mail-18-20260719@example>', 'motorhomefamily travel detail', 'service@rvassociation.example.au', '["li.cheng.family@example.cn"]', '[]', '[]', '2026-07-19T09:00:00+08:00', 'materialsfamily travel detail、family travel detail、family travel detail powered site family travel detail。', NULL, 0, 0, 0, NULL, NULL, '{"thread":"family-18","source":"external"}', 1018, 86, '2026-07-19T09:00:00+08:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (19, 1, '<family-mail-19-20260727@example>', 'Septemberfamily travel detail', 'kindergarten@littleacorn.example.cn', '["li.cheng.family@example.cn"]', '[]', '[]', '2026-07-27T09:00:00+08:00', 'family travel detailparentfamily travel detail，return to kindergartenfamily travel detail。', NULL, 1, 1, 1, NULL, NULL, '{"thread":"family-19","source":"external"}', 1019, 87, '2026-07-27T09:00:00+08:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (20, 1, '<family-mail-20-20260802@example>', 'Septemberfamily travel detail', 'teamlead@company.example.cn', '["li.cheng.family@example.cn"]', '[]', '[]', '2026-08-02T09:00:00+08:00', 'family travel detail，family travel detail。', NULL, 1, 0, 0, NULL, NULL, '{"thread":"family-20","source":"external"}', 1020, 66, '2026-08-02T09:00:00+08:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (21, 1, '<family-mail-21-20260806@example>', 'airportfamily travel detail', 'parking@pudong-airport.example.cn', '["li.cheng.family@example.cn"]', '[]', '[]', '2026-08-06T09:00:00+08:00', 'family travel detailhistoryfamily travel detail，family travel detail。', NULL, 0, 0, 0, NULL, NULL, '{"thread":"family-21","source":"external"}', 1021, 78, '2026-08-06T09:00:00+08:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (22, 1, '<family-mail-22-20260811@example>', 'childfamily travel detail', 'help@airline-family.example.cn', '["li.cheng.family@example.cn"]', '[]', '[]', '2026-08-11T09:00:00+08:00', 'family travel detailchildfamily travel detail、family travel detail。', NULL, 1, 0, 0, NULL, NULL, '{"thread":"family-22","source":"external"}', 1022, 81, '2026-08-11T09:00:00+08:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (23, 1, '<family-mail-23-20260815@example>', 'travel medicinesconsultationfamily travel detail', 'clinic@pudong-childcare.example.cn', '["li.cheng.family@example.cn"]', '[]', '[]', '2026-08-15T09:00:00+08:00', 'family travel detail；family travel detail。', NULL, 1, 1, 0, NULL, NULL, '{"thread":"family-23","source":"external"}', 1023, 93, '2026-08-15T09:00:00+08:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (24, 1, '<family-mail-24-20260820@example>', 'Septemberfamily travel detailstatus', 'support@petcare-pudong.example.cn', '["li.cheng.family@example.cn"]', '[]', '[]', '2026-08-20T09:00:00+08:00', 'familyfamily travel detail，family travel detail。', NULL, 0, 0, 0, NULL, NULL, '{"thread":"family-24","source":"external"}', 1024, 87, '2026-08-20T09:00:00+08:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (25, 1, '<family-mail-25-20260824@example>', 'family travel detailparentfamily travel detail', 'teacher.liu@littleacorn.example.cn', '["li.cheng.family@example.cn"]', '[]', '[]', '2026-08-24T09:00:00+08:00', 'family travel detailpickuptime、napfamily travel detail，emergency contactfamily travel detailrecord。', NULL, 1, 0, 0, NULL, NULL, '{"thread":"family-25","source":"external"}', 1025, 96, '2026-08-24T09:00:00+08:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (26, 1, '<family-mail-26-20260828@example>', 'family travel detail', 'security@residence.example.cn', '["li.cheng.family@example.cn"]', '[]', '[]', '2026-08-28T09:00:00+08:00', 'family travel detailemergency contactfamily travel detail，family travel detail。', NULL, 1, 0, 0, NULL, NULL, '{"thread":"family-26","source":"external"}', 1026, 87, '2026-08-28T09:00:00+08:00');

INSERT INTO "_counters" ("key", "value") VALUES ('msg_seq', 500);
INSERT INTO "_counters" ("key", "value") VALUES ('draft_seq', 200);

COMMIT;
