PRAGMA foreign_keys = ON;
BEGIN TRANSACTION;

INSERT INTO "account_config" ("id", "email", "name", "created_at") VALUES (1, 'li.cheng.family@example.cn', 'Li Cheng family travel assistant', '2026-09-01T00:00:00Z');

INSERT INTO "folders" ("id", "name", "delimiter", "flags_json", "message_count", "unread_count") VALUES (1, 'INBOX', '/', '["\\Inbox"]', 26, 8);
INSERT INTO "folders" ("id", "name", "delimiter", "flags_json", "message_count", "unread_count") VALUES (2, 'Sent', '/', '["\\Sent"]', 0, 0);
INSERT INTO "folders" ("id", "name", "delimiter", "flags_json", "message_count", "unread_count") VALUES (3, 'Drafts', '/', '["\\Drafts"]', 0, 0);

INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (1, 1, '<family-mail-01-20260105@example>', 'Spring term pickup card update', 'kindergarten@littleacorn.example.cn', '["li.cheng.family@example.cn"]', '[]', '[]', '2026-01-05T09:00:00+08:00', 'The new term pickup cards are ready. The parent meeting will explain the nap, leave, and emergency contact processes.', NULL, 1, 0, 0, NULL, NULL, '{"thread":"family-01","source":"external"}', 1001, 90, '2026-01-05T09:00:00+08:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (2, 1, '<family-mail-02-20260122@example>', 'Four-year-old routine checkup appointment confirmed', 'clinic@pudong-childcare.example.cn', '["li.cheng.family@example.cn"]', '[]', '[]', '2026-01-22T09:00:00+08:00', 'The checkup is on the morning of 17 February; on-site registration only verifies the appointment name and does not collect document numbers by email.', NULL, 1, 1, 0, NULL, NULL, '{"thread":"family-02","source":"external"}', 1002, 109, '2026-01-22T09:00:00+08:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (3, 1, '<family-mail-03-20260203@example>', 'Child swim class transfer result', 'swim@riversideclub.example.cn', '["li.cheng.family@example.cn"]', '[]', '[]', '2026-02-03T09:00:00+08:00', 'The Saturday morning class has a vacancy; the course starts with shallow-water acclimation and parents must wait by the pool.', NULL, 0, 0, 0, NULL, NULL, '{"thread":"family-03","source":"external"}', 1003, 87, '2026-02-03T09:00:00+08:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (4, 1, '<family-mail-04-20260226@example>', 'Shanghai family outdoor show e-tickets', 'tickets@outdoorshow.example.cn', '["li.cheng.family@example.cn"]', '[]', '[]', '2026-02-26T09:00:00+08:00', 'The QR codes for three visitors have been generated; the child gear experience area is in Hall 2.', NULL, 1, 0, 0, NULL, NULL, '{"thread":"family-04","source":"external"}', 1004, 75, '2026-02-26T09:00:00+08:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (5, 1, '<family-mail-05-20260311@example>', 'Vehicle service work order scheduled', 'service@jinqiao-auto.example.cn', '["li.cheng.family@example.cn"]', '[]', '[]', '2026-03-11T09:00:00+08:00', 'The technician will check the tyres, brakes, and the rear child restraint anchor points; it is expected to take three hours.', NULL, 1, 0, 0, NULL, NULL, '{"thread":"family-05","source":"external"}', 1005, 87, '2026-03-11T09:00:00+08:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (6, 1, '<family-mail-06-20260329@example>', 'Travel atlas arrival notice', 'books@cloudreading.example.cn', '["li.cheng.family@example.cn"]', '[]', '[]', '2026-03-29T09:00:00+08:00', 'The Australia road map and the child nature observation book have arrived; they can be collected within seven days.', NULL, 0, 0, 0, NULL, NULL, '{"thread":"family-06","source":"external"}', 1006, 84, '2026-03-29T09:00:00+08:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (7, 1, '<family-mail-07-20260408@example>', 'Pet boarding trial stay feedback', 'support@petcare-pudong.example.cn', '["li.cheng.family@example.cn"]', '[]', '[]', '2026-04-08T09:00:00+08:00', 'Eating and activity were normal during the trial stay; formal boarding is logged twice a day, morning and evening.', NULL, 1, 0, 0, NULL, NULL, '{"thread":"family-07","source":"external"}', 1007, 78, '2026-04-08T09:00:00+08:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (8, 1, '<family-mail-08-20260421@example>', 'Parent-child activity registration confirmed', 'museum@shscitech.example.cn', '["li.cheng.family@example.cn"]', '[]', '[]', '2026-04-21T09:00:00+08:00', 'The aviation-themed workshop is scheduled for 10 a.m.; materials are provided by the venue.', NULL, 1, 0, 0, NULL, NULL, '{"thread":"family-08","source":"external"}', 1008, 69, '2026-04-21T09:00:00+08:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (9, 1, '<family-mail-09-20260506@example>', 'Company travel sharing session materials', 'travelclub@company.example.cn', '["li.cheng.family@example.cn"]', '[]', '[]', '2026-05-06T09:00:00+08:00', 'A colleague shared experience with fuel, parking, and roadside assistance on a New Zealand self-drive trip; no specific orders were involved.', NULL, 0, 0, 0, NULL, NULL, '{"thread":"family-09","source":"external"}', 1009, 102, '2026-05-06T09:00:00+08:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (10, 1, '<family-mail-10-20260518@example>', 'Home broadband bill issued', 'billing@shanghai-telecom.example.cn', '["li.cheng.family@example.cn"]', '[]', '[]', '2026-05-18T09:00:00+08:00', 'The bill for this month matches the plan; the automatic payment date is 25 May.', NULL, 1, 0, 0, NULL, NULL, '{"thread":"family-10","source":"external"}', 1010, 72, '2026-05-18T09:00:00+08:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (11, 1, '<family-mail-11-20260527@example>', 'June parent-child day arrangements', 'teacher.liu@littleacorn.example.cn', '["li.cheng.family@example.cn"]', '[]', '[]', '2026-05-27T09:00:00+08:00', 'The parent-child day includes sports at the kindergarten and lunch; the activity ends before 4 p.m.', NULL, 1, 0, 0, NULL, NULL, '{"thread":"family-11","source":"external"}', 1011, 72, '2026-05-27T09:00:00+08:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (12, 1, '<family-mail-12-20260602@example>', 'Family accident insurance annual summary', 'insurance@harbourmutual.example.cn', '["li.cheng.family@example.cn"]', '[]', '[]', '2026-06-02T09:00:00+08:00', 'The renewal summary lists the medical and emergency assistance limits; rental vehicle cover is not included in this policy.', NULL, 0, 1, 0, NULL, NULL, '{"thread":"family-12","source":"external"}', 1012, 93, '2026-06-02T09:00:00+08:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (13, 1, '<family-mail-13-20260610@example>', 'Right-hand-drive driving webinar registration', 'events@drivesafe.example.au', '["li.cheng.family@example.cn"]', '[]', '[]', '2026-06-10T09:00:00+08:00', 'The webinar covers driving on the left, roundabout priority, mirror judgement, and fatigue management; the recording is kept for 14 days.', NULL, 1, 0, 0, NULL, NULL, '{"thread":"family-13","source":"external"}', 1013, 96, '2026-06-10T09:00:00+08:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (14, 1, '<family-mail-14-20260616@example>', 'Licence translation consultation receipt', 'appointments@translationdesk.example.cn', '["li.cheng.family@example.cn"]', '[]', '[]', '2026-06-16T09:00:00+08:00', 'The adviser will explain the certified translation format and processing time; the exact state rules depend on the official information at travel time.', NULL, 1, 1, 1, NULL, NULL, '{"thread":"family-14","source":"external"}', 1014, 105, '2026-06-16T09:00:00+08:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (15, 1, '<family-mail-15-20260628@example>', 'Chongming campsite refund completed', 'camp@chongming-east.example.cn', '["li.cheng.family@example.cn"]', '[]', '[]', '2026-06-28T09:00:00+08:00', 'The cancellation refund has been returned to the original payment method and the campsite order status is closed.', NULL, 0, 0, 0, NULL, NULL, '{"thread":"family-15","source":"external"}', 1015, 58, '2026-06-28T09:00:00+08:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (16, 1, '<family-mail-16-20260704@example>', 'Family budget category adjustment', 'support@familybudget.example.cn', '["li.cheng.family@example.cn"]', '[]', '[]', '2026-07-04T09:00:00+08:00', 'The travel and education categories now display separately; a card pre-authorization is not automatically marked as actual spending.', NULL, 1, 0, 0, NULL, NULL, '{"thread":"family-16","source":"external"}', 1016, 93, '2026-07-04T09:00:00+08:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (17, 1, '<family-mail-17-20260712@example>', 'Victoria spring parks newsletter', 'newsletter@parks-victoria.example.au', '["li.cheng.family@example.cn"]', '[]', '[]', '2026-07-12T09:00:00+08:00', 'The newsletter covers trail maintenance and campsite opening seasons; all information is general announcement only.', NULL, 1, 0, 0, NULL, NULL, '{"thread":"family-17","source":"external"}', 1017, 87, '2026-07-12T09:00:00+08:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (18, 1, '<family-mail-18-20260719@example>', 'Motorhome dimension terminology note', 'service@rvassociation.example.au', '["li.cheng.family@example.cn"]', '[]', '[]', '2026-07-19T09:00:00+08:00', 'The material explains common terms such as vehicle height, wheelbase, gross mass, and campsite powered site.', NULL, 0, 0, 0, NULL, NULL, '{"thread":"family-18","source":"external"}', 1018, 86, '2026-07-19T09:00:00+08:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (19, 1, '<family-mail-19-20260727@example>', 'September leave process', 'kindergarten@littleacorn.example.cn', '["li.cheng.family@example.cn"]', '[]', '[]', '2026-07-27T09:00:00+08:00', 'Leave longer than three consecutive days can be logged in the parent portal; just update it if the return date changes.', NULL, 1, 1, 1, NULL, NULL, '{"thread":"family-19","source":"external"}', 1019, 87, '2026-07-27T09:00:00+08:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (20, 1, '<family-mail-20-20260802@example>', 'September project deputy draft', 'teamlead@company.example.cn', '["li.cheng.family@example.cn"]', '[]', '[]', '2026-08-02T09:00:00+08:00', 'The work deputy scope is listed; the formal duty roster will be confirmed at the end of the month.', NULL, 1, 0, 0, NULL, NULL, '{"thread":"family-20","source":"external"}', 1020, 66, '2026-08-02T09:00:00+08:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (21, 1, '<family-mail-21-20260806@example>', 'Airport parking membership monthly report', 'parking@pudong-airport.example.cn', '["li.cheng.family@example.cn"]', '[]', '[]', '2026-08-06T09:00:00+08:00', 'The monthly report shows historical parking duration and the points balance; it does not include future space reservations.', NULL, 0, 0, 0, NULL, NULL, '{"thread":"family-21","source":"external"}', 1021, 78, '2026-08-06T09:00:00+08:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (22, 1, '<family-mail-22-20260811@example>', 'Common questions about children on long-haul flights', 'help@airline-family.example.cn', '["li.cheng.family@example.cn"]', '[]', '[]', '2026-08-11T09:00:00+08:00', 'The airline explains the general process for child meals, stroller check-in, and adjacent seat requests.', NULL, 1, 0, 0, NULL, NULL, '{"thread":"family-22","source":"external"}', 1022, 81, '2026-08-11T09:00:00+08:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (23, 1, '<family-mail-23-20260815@example>', 'Travel medication consultation appointment', 'clinic@pudong-childcare.example.cn', '["li.cheng.family@example.cn"]', '[]', '[]', '2026-08-15T09:00:00+08:00', 'The clinic only discusses carrying common medication and jet-lag routines; medical records and prescriptions remain in the hospital system.', NULL, 1, 1, 0, NULL, NULL, '{"thread":"family-23","source":"external"}', 1023, 93, '2026-08-15T09:00:00+08:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (24, 1, '<family-mail-24-20260820@example>', 'September boarding waitlist status', 'support@petcare-pudong.example.cn', '["li.cheng.family@example.cn"]', '[]', '[]', '2026-08-20T09:00:00+08:00', 'The family pet boarding application is still waitlisted; staff will make contact separately when a space opens.', NULL, 0, 0, 0, NULL, NULL, '{"thread":"family-24","source":"external"}', 1024, 87, '2026-08-20T09:00:00+08:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (25, 1, '<family-mail-25-20260824@example>', 'Autumn parent meeting minutes', 'teacher.liu@littleacorn.example.cn', '["li.cheng.family@example.cn"]', '[]', '[]', '2026-08-24T09:00:00+08:00', 'The minutes include pickup times, the nap window, and the leave entry point; the emergency contact follows the record from last term.', NULL, 1, 0, 0, NULL, NULL, '{"thread":"family-25","source":"external"}', 1025, 96, '2026-08-24T09:00:00+08:00');
INSERT INTO "messages" ("id", "folder_id", "message_id", "subject", "from_addr", "to_addr_json", "cc_addr_json", "bcc_addr_json", "date", "body_text", "body_html", "is_read", "is_important", "is_flagged", "in_reply_to", "references_header", "headers_json", "uid", "size", "created_at") VALUES (26, 1, '<family-mail-26-20260828@example>', 'Property management departure registration note', 'security@residence.example.cn', '["li.cheng.family@example.cn"]', '[]', '[]', '2026-08-28T09:00:00+08:00', 'The property office can register an emergency contact and the expected away period; the system does not store door access codes.', NULL, 1, 0, 0, NULL, NULL, '{"thread":"family-26","source":"external"}', 1026, 87, '2026-08-28T09:00:00+08:00');

INSERT INTO "_counters" ("key", "value") VALUES ('msg_seq', 500);
INSERT INTO "_counters" ("key", "value") VALUES ('draft_seq', 200);

COMMIT;
