PRAGMA foreign_keys = ON;
BEGIN TRANSACTION;

INSERT INTO "entry_requirements" ("origin_nationality", "destination", "purpose", "visa_required", "allowed_stay_days", "passport_validity_months", "docs_needed_json", "notes", "updated_at") VALUES ('CN', 'AU', 'tourism_family_rv_trial', 1, 90, 6, '["passport","family relationship proof","trip statement","funds evidence"]', 'Chinese passport holders require an appropriate Australian visa before travel. A passport bio page, family relationship evidence for a minor, trip outline and financial evidence may be requested.', '2026-08-20T09:00:00+10:00');

INSERT INTO "visa_products" ("product_id", "destination", "nationality", "name", "processing_time_days", "fee_amount", "fee_currency", "delivery", "form_schema_json") VALUES ('AU_VISITOR_600_FAMILY', 'AU', 'CN', 'Australia Visitor visa (subclass 600) — family stream', 12, 190, 'AUD', 'online', '{"required_docs":["passport_bio","family_relationship","trip_statement"],"fields":[{"name":"arrival_date","required":true},{"name":"minor_child","required":true}]}');
INSERT INTO "visa_products" ("product_id", "destination", "nationality", "name", "processing_time_days", "fee_amount", "fee_currency", "delivery", "form_schema_json") VALUES ('AU_EVISITOR_651_EU', 'AU', 'DE', 'Australia eVisitor (subclass 651)', 3, 0, 'AUD', 'online', '{"required_docs":["passport_bio"],"fields":[{"name":"travel_purpose","required":true}]}');
INSERT INTO "visa_products" ("product_id", "destination", "nationality", "name", "processing_time_days", "fee_amount", "fee_currency", "delivery", "form_schema_json") VALUES ('AU_ETA_601_SG', 'AU', 'SG', 'Australian Electronic Travel Authority (subclass 601)', 1, 20, 'AUD', 'mobile', '{"required_docs":["passport_bio","photo"],"fields":[{"name":"contact_address","required":true}]}');
INSERT INTO "visa_products" ("product_id", "destination", "nationality", "name", "processing_time_days", "fee_amount", "fee_currency", "delivery", "form_schema_json") VALUES ('AU_STUDENT_500_CN', 'AU', 'CN', 'Australia Student visa (subclass 500)', 35, 710, 'AUD', 'online', '{"required_docs":["coe","passport_bio","financial_capacity"],"fields":[{"name":"course_provider","required":true}]}');
INSERT INTO "visa_products" ("product_id", "destination", "nationality", "name", "processing_time_days", "fee_amount", "fee_currency", "delivery", "form_schema_json") VALUES ('AU_TRANSIT_771_CN', 'AU', 'CN', 'Australia Transit visa (subclass 771)', 8, 0, 'AUD', 'online', '{"required_docs":["passport_bio","onward_ticket"],"fields":[{"name":"transit_hours","required":true}]}');
INSERT INTO "visa_products" ("product_id", "destination", "nationality", "name", "processing_time_days", "fee_amount", "fee_currency", "delivery", "form_schema_json") VALUES ('NZ_VISITOR_CN', 'NZ', 'CN', 'New Zealand Visitor Visa', 18, 246, 'NZD', 'online', '{"required_docs":["passport_bio","funds","itinerary"],"fields":[{"name":"stay_length","required":true}]}');
INSERT INTO "visa_products" ("product_id", "destination", "nationality", "name", "processing_time_days", "fee_amount", "fee_currency", "delivery", "form_schema_json") VALUES ('NZ_NZETA_US', 'NZ', 'US', 'New Zealand Electronic Travel Authority', 2, 23, 'NZD', 'mobile', '{"required_docs":["passport_bio"],"fields":[{"name":"arrival_mode","required":true}]}');
INSERT INTO "visa_products" ("product_id", "destination", "nationality", "name", "processing_time_days", "fee_amount", "fee_currency", "delivery", "form_schema_json") VALUES ('UK_STANDARD_CN', 'GB', 'CN', 'UK Standard Visitor visa', 21, 115, 'GBP', 'online', '{"required_docs":["passport_bio","funds","purpose"],"fields":[{"name":"planned_stay","required":true}]}');
INSERT INTO "visa_products" ("product_id", "destination", "nationality", "name", "processing_time_days", "fee_amount", "fee_currency", "delivery", "form_schema_json") VALUES ('CA_VISITOR_CN', 'CA', 'CN', 'Canada Temporary Resident Visa', 28, 100, 'CAD', 'online', '{"required_docs":["passport_bio","funds","travel_history"],"fields":[{"name":"host","required":false}]}');
INSERT INTO "visa_products" ("product_id", "destination", "nationality", "name", "processing_time_days", "fee_amount", "fee_currency", "delivery", "form_schema_json") VALUES ('CA_ETA_AU', 'CA', 'AU', 'Canada Electronic Travel Authorization', 1, 7, 'CAD', 'online', '{"required_docs":["passport_bio"],"fields":[{"name":"employment","required":true}]}');
INSERT INTO "visa_products" ("product_id", "destination", "nationality", "name", "processing_time_days", "fee_amount", "fee_currency", "delivery", "form_schema_json") VALUES ('JP_SINGLE_CN', 'JP', 'CN', 'Japan single-entry short-stay visa', 7, 200, 'CNY', 'consular', '{"required_docs":["passport_bio","itinerary","employment"],"fields":[{"name":"guarantor","required":false}]}');
INSERT INTO "visa_products" ("product_id", "destination", "nationality", "name", "processing_time_days", "fee_amount", "fee_currency", "delivery", "form_schema_json") VALUES ('JP_MULTIPLE_CN', 'JP', 'CN', 'Japan multiple-entry visitor visa', 11, 400, 'CNY', 'consular', '{"required_docs":["passport_bio","financial_capacity"],"fields":[{"name":"prior_visits","required":true}]}');
INSERT INTO "visa_products" ("product_id", "destination", "nationality", "name", "processing_time_days", "fee_amount", "fee_currency", "delivery", "form_schema_json") VALUES ('KR_KETA_US', 'KR', 'US', 'Korea Electronic Travel Authorization', 2, 10000, 'KRW', 'online', '{"required_docs":["passport_bio","photo"],"fields":[{"name":"address_in_korea","required":true}]}');
INSERT INTO "visa_products" ("product_id", "destination", "nationality", "name", "processing_time_days", "fee_amount", "fee_currency", "delivery", "form_schema_json") VALUES ('SG_EVISA_CN', 'SG', 'CN', 'Singapore entry visa', 5, 30, 'SGD', 'online', '{"required_docs":["passport_bio","photo","form14a"],"fields":[{"name":"local_contact","required":false}]}');
INSERT INTO "visa_products" ("product_id", "destination", "nationality", "name", "processing_time_days", "fee_amount", "fee_currency", "delivery", "form_schema_json") VALUES ('TH_EVISA_CN', 'TH', 'CN', 'Thailand tourist eVisa', 9, 240, 'CNY', 'online', '{"required_docs":["passport_bio","hotel","ticket"],"fields":[{"name":"arrival_port","required":true}]}');
INSERT INTO "visa_products" ("product_id", "destination", "nationality", "name", "processing_time_days", "fee_amount", "fee_currency", "delivery", "form_schema_json") VALUES ('MY_Evisa_CN', 'MY', 'CN', 'Malaysia tourist eVisa', 4, 160, 'CNY', 'online', '{"required_docs":["passport_bio","photo","ticket"],"fields":[{"name":"stay_address","required":true}]}');
INSERT INTO "visa_products" ("product_id", "destination", "nationality", "name", "processing_time_days", "fee_amount", "fee_currency", "delivery", "form_schema_json") VALUES ('US_B1B2_CN', 'US', 'CN', 'United States B1/B2 visitor visa', 45, 185, 'USD', 'consular', '{"required_docs":["passport_bio","ds160"],"fields":[{"name":"interview_location","required":true}]}');
INSERT INTO "visa_products" ("product_id", "destination", "nationality", "name", "processing_time_days", "fee_amount", "fee_currency", "delivery", "form_schema_json") VALUES ('EU_SCHENGEN_CN', 'FR', 'CN', 'Schengen short-stay visitor visa', 15, 90, 'EUR', 'consular', '{"required_docs":["passport_bio","insurance","itinerary"],"fields":[{"name":"main_destination","required":true}]}');
INSERT INTO "visa_products" ("product_id", "destination", "nationality", "name", "processing_time_days", "fee_amount", "fee_currency", "delivery", "form_schema_json") VALUES ('IE_SHORT_CN', 'IE', 'CN', 'Ireland short-stay visit visa', 26, 60, 'EUR', 'online', '{"required_docs":["passport_bio","funds","purpose"],"fields":[{"name":"sponsor","required":false}]}');
INSERT INTO "visa_products" ("product_id", "destination", "nationality", "name", "processing_time_days", "fee_amount", "fee_currency", "delivery", "form_schema_json") VALUES ('ZA_VISITOR_CN', 'ZA', 'CN', 'South Africa visitor visa', 14, 425, 'CNY', 'consular', '{"required_docs":["passport_bio","funds","hotel"],"fields":[{"name":"arrival_date","required":true}]}');
INSERT INTO "visa_products" ("product_id", "destination", "nationality", "name", "processing_time_days", "fee_amount", "fee_currency", "delivery", "form_schema_json") VALUES ('AE_TOURIST_CN', 'AE', 'CN', 'UAE tourist entry permit', 4, 370, 'AED', 'online', '{"required_docs":["passport_bio","photo"],"fields":[{"name":"sponsor_airline","required":false}]}');
INSERT INTO "visa_products" ("product_id", "destination", "nationality", "name", "processing_time_days", "fee_amount", "fee_currency", "delivery", "form_schema_json") VALUES ('ID_EVOA_CN', 'ID', 'CN', 'Indonesia electronic visa on arrival', 1, 500000, 'IDR', 'online', '{"required_docs":["passport_bio","onward_ticket"],"fields":[{"name":"arrival_airport","required":true}]}');
INSERT INTO "visa_products" ("product_id", "destination", "nationality", "name", "processing_time_days", "fee_amount", "fee_currency", "delivery", "form_schema_json") VALUES ('VN_EVISA_CN', 'VN', 'CN', 'Vietnam electronic visa', 3, 25, 'USD', 'online', '{"required_docs":["passport_bio","photo"],"fields":[{"name":"entry_port","required":true}]}');
INSERT INTO "visa_products" ("product_id", "destination", "nationality", "name", "processing_time_days", "fee_amount", "fee_currency", "delivery", "form_schema_json") VALUES ('LK_ETA_CN', 'LK', 'CN', 'Sri Lanka tourist ETA', 2, 50, 'USD', 'online', '{"required_docs":["passport_bio"],"fields":[{"name":"address_in_country","required":true}]}');
INSERT INTO "visa_products" ("product_id", "destination", "nationality", "name", "processing_time_days", "fee_amount", "fee_currency", "delivery", "form_schema_json") VALUES ('TR_EVISA_CN', 'TR', 'CN', 'Türkiye tourist eVisa', 1, 60, 'USD', 'online', '{"required_docs":["passport_bio","supporting_visa"],"fields":[{"name":"arrival_date","required":true}]}');
INSERT INTO "visa_products" ("product_id", "destination", "nationality", "name", "processing_time_days", "fee_amount", "fee_currency", "delivery", "form_schema_json") VALUES ('MX_VISITOR_CN', 'MX', 'CN', 'Mexico visitor visa', 10, 53, 'USD', 'consular', '{"required_docs":["passport_bio","funds"],"fields":[{"name":"appointment_city","required":true}]}');

INSERT INTO "visa_applications" ("application_id", "user_id", "product_id", "status", "applicant_json", "answers_json", "decision_day", "decision_note", "evisa_doc_ref", "history_json", "created_at", "updated_at") VALUES ('VAC_LC_2026_09_AU', 'user_li_cheng', 'AU_VISITOR_600_FAMILY', 'submitted', '{"family":["Li Cheng","Zhou Ran","Li Mi"],"minor_child":true}', '{"purpose":"family motorhome trial","arrival":"2026-09-13"}', NULL, 'Application submitted; assessment has not started.', NULL, '[{"at":"2026-09-01T12:00:00+08:00","event":"submitted"}]', '2026-09-01T12:00:00+08:00', '2026-09-01T12:00:00+08:00');

INSERT INTO "advisories" ("country_code", "level", "text", "updated_at") VALUES ('AU', 1, 'Exercise normal safety precautions. Long-distance drivers should monitor bushfire, flood and severe-weather notices by state.', '2026-08-28T10:00:00+10:00');

INSERT INTO "_counters" ("name", "value") VALUES ('application_seq', 300);
INSERT INTO "_counters" ("name", "value") VALUES ('doc_seq', 300);
INSERT INTO "_counters" ("name", "value") VALUES ('sub_seq', 50);

COMMIT;
