-- Generated notification_hub seed for garden_total_reno_v4_30d
BEGIN;
INSERT INTO official_accounts (account_id, name, category, description) VALUES ('oa_qgrd_drainage', 'Xi''an Garden Drainage and Maintenance Tips', 'home_improvement', 'Reminders on garden grading, drainage-channel connections, permeable pavement, nursery-stock maintenance, and actual-rain observation');
INSERT INTO official_account_subscriptions (user_id, account_id, subscribed_at) VALUES ('usr_yong_wei', 'oa_qgrd_drainage', '2026-05-21T04:50:00Z');
INSERT INTO official_accounts (account_id, name, category, description) VALUES ('oa_qgrd_brand', 'Garden Hardscape and Landscape Services', 'shopping_service', 'Guidance on drainage components, paving stone, nursery-stock handover, and outdoor-light waterproofing');
INSERT INTO official_account_subscriptions (user_id, account_id, subscribed_at) VALUES ('usr_yong_wei', 'oa_qgrd_brand', '2026-05-26T09:15:00Z');
INSERT INTO official_accounts (account_id, name, category, description) VALUES ('oa_qgrd_card', 'China Merchants Bank Credit Card', 'finance', 'Reminders about statements, foreign-currency transactions, and card security');
INSERT INTO official_account_subscriptions (user_id, account_id, subscribed_at) VALUES ('usr_yong_wei', 'oa_qgrd_card', '2026-05-31T02:40:00Z');
INSERT INTO official_account_posts (post_id, account_id, title, summary, url, published_at) VALUES ('post_qgrd_1', 'oa_qgrd_drainage', 'Verification of Garden Drainage Components and Nursery Stock on Arrival', 'Drainage channels, manhole covers, paving accessories, and nursery stock should be checked by batch against their locations and maintenance conditions; arrival sign-off cannot prove grading, drainage-channel connection, or survival acceptance.', 'https://landscape.example/xian/material-arrival', '2026-06-01');
INSERT INTO official_account_posts (post_id, account_id, title, summary, url, published_at) VALUES ('post_qgrd_2', 'oa_qgrd_brand', 'How to Itemize Grading, Connection Elevation Difference, and Rain-Test Evidence', 'The benchmark, slope direction, drainage-channel connection elevation, and drainage time after rain should each be documented separately; a single fair-weather observation cannot replace ponding verification after effective rainfall.', 'https://greenall.example/service/drainage-evidence', '2026-06-05');
INSERT INTO official_account_posts (post_id, account_id, title, summary, url, published_at) VALUES ('post_qgrd_3', 'oa_qgrd_card', 'Preauthorization and Reversal Status for Drainage-Accessory Merchants', 'Accessory preauthorization, duplicate-charge investigation, and final reversal are three separate statuses; the budget should retain the normal amount due until the card shows a clear negative entry.', 'https://card.example/drainage-transaction-status', '2026-06-08');
INSERT INTO official_account_posts (post_id, account_id, title, summary, url, published_at) VALUES ('post_qgrd_4', 'oa_qgrd_brand', 'Key Points for Listing Garden Stone, Manhole Covers, and Surplus Nursery Stock', 'Describe stone by batch and size, manhole covers by material and load rating, and nursery stock by specifications and maintenance status; funds on the platform do not count as surplus-material proceeds until they are settled.', 'https://greenall.example/service/garden-leftovers', '2026-06-12');
INSERT INTO subscriptions (subscription_id, user_id, source, type, target, condition_json, status, created_at, updated_at) VALUES ('sub_qgrd_log', 'usr_yong_wei', 'delivery_logistics', 'keyword', 'YTOQGRD5520002CN', '{"keywords": ["drainage-channel connection", "manhole cover", "paving sample", "nursery stock", "arrival"], "order_id": "ord_qgrd_0002"}', 'active', '2026-06-14T11:30:00Z', '2026-06-14T11:30:00Z');
INSERT INTO subscriptions (subscription_id, user_id, source, type, target, condition_json, status, created_at, updated_at) VALUES ('sub_qgrd_card', 'usr_yong_wei', 'credit_card', 'keyword', 'card_qgrd_01', '{"keywords": ["drainage fittings", "preauthorization", "duplicate transaction", "negative record"]}', 'active', '2026-06-14T10:55:00Z', '2026-06-14T10:55:00Z');
INSERT INTO price_alerts (alert_id, user_id, item_ref, target_price_minor, currency, status, created_at) VALUES ('alr_qgrd_1', 'usr_yong_wei', 'prod_qgrd_main', 3780000, 'CNY', 'active', '2026-06-14T09:40:00Z');
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_qgrd_arrival_0614', 'usr_yong_wei', 'delivery_logistics', 'policy_update', 'sub_qgrd_log', 'Historical arrival reminder: retention of drainage and paving batches', 'Drainage components, stone, and nursery stock should be retained by batch after arrival; arrival does not mean grading, rain test, or nursery-stock maintenance has passed.', '{"order_id": "ord_qgrd_0002", "tracking_no": "YTOQGRD5520002CN"}', '2026-06-14T02:05:00Z', 0);
INSERT INTO notifications (notification_id, user_id, source, type, subscription_id, title, body, payload_json, created_at, read) VALUES ('ntf_qgrd_card_fx_0614', 'usr_yong_wei', 'credit_card', 'policy_update', 'sub_qgrd_card', 'Historical foreign-currency preauthorization reminder', 'A preauthorization by an overseas drainage-fittings merchant may have a delay before posting; verify it against the order.', '{"card_id": "card_qgrd_01", "tx_id": "tx_qgrd_fx"}', '2026-06-14T01:35:00Z', 0);
INSERT INTO _counters (key,value) VALUES ('subscription_seq',2),('alert_seq',1);
COMMIT;
BEGIN;
UPDATE notifications SET title='Historical arrival reminder: retention of drainage and paving batches', body='Drainage components, stone, and nursery stock should be retained by batch after arrival; arrival does not mean grading, rain test, or nursery-stock maintenance has passed.', created_at='2026-06-14T02:05:00Z' WHERE notification_id='ntf_qgrd_arrival_0614';
UPDATE notifications SET title='Historical foreign-currency preauthorization reminder', body='A preauthorization by an overseas drainage-fittings merchant may have a delay before posting; verify it against the order.', created_at='2026-06-14T01:35:00Z' WHERE notification_id='ntf_qgrd_card_fx_0614';
INSERT INTO notifications (notification_id,user_id,source,type,subscription_id,title,body,payload_json,created_at,read) VALUES
 ('ntf_qgrd_terrace_0515','usr_yong_wei','calendar','policy_update',NULL,'Qinglong Temple East Courtyard terrace drainage reinspection archive','The south-facing terrace completed three-section water-flow testing, actual-rain observation, and drainage records on May 15; the project documentation has been closed out.','{"event_id":"evt_qgrd_terrace_review_0515"}','2026-05-15T03:00:00Z',1),
 ('ntf_qgrd_paver_mismatch_0614','usr_yong_wei','ecommerce','price_change',NULL,'Gray permeable paver stock specification update','The in-stock batch is 200×100×60mm, while the site sample is 230×115×60mm; the supplier is awaiting the remeasurement results.','{"state":"dimension_mismatch"}','2026-06-14T04:15:00Z',0),
 ('ntf_qgrd_doc1','usr_yong_wei','email','policy_update',NULL,'Authorization letter for the contracting entity still missing its signature page','Keep pending verification until it is completed.','{"document":"authorization","status":"missing_page"}','2026-06-12T06:05:00Z',0),
 ('ntf_qgrd_rain1','usr_yong_wei','weather','policy_update',NULL,'Historical weather can only serve as observation context','Construction conclusions still require benchmark elevation, grading, drainage-channel connection, and ponding records.','{"rule":"weather_not_acceptance"}','2026-06-14T05:00:00Z',1);
COMMIT;
